# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.CharField(max_length=50, verbose_name="CATEGORIE DE L'IMAGE")),
                ('photo', models.ImageField(upload_to='photos/')),
                ('nom_societe', models.CharField(max_length=50, verbose_name='NOM DE LA SOCIETE')),
                ('date_debut', models.CharField(max_length=50, verbose_name='DATE DEBUT')),
                ('date_fin', models.CharField(max_length=50, verbose_name='DATE FIN')),
            ],
        ),
    ]
