# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('product', '0002_auto_20171230_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandePassante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_bande_passante', models.CharField(choices=[('120GB', '120GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('1TB', '1TB')], max_length=50, verbose_name='TYPE BANDE PASSANTE')),
                ('debit_download', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('CANON', 'CANON'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY')], max_length=50, verbose_name='DEBIT DOWNLOAD')),
                ('debit_upload', models.CharField(choices=[('core i3', 'core i3'), ('core i5', 'core i5'), ('core i7', 'core i7'), ('celeron', 'celeron'), ('core duo', 'core duo')], max_length=50, verbose_name='DEBIT UPLOAD')),
                ('frais_installation', models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB')], max_length=50, verbose_name="FRAIS D'INSTALLATION")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='desktop',
            name='capacite_ram',
            field=models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('CANON', 'CANON'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='type_processeur',
            field=models.CharField(choices=[('core i3', 'core i3'), ('core i5', 'core i5'), ('core i7', 'core i7'), ('celeron', 'celeron'), ('core duo', 'core duo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('CANON', 'CANON'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('CANON', 'CANON'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memoire_ram',
            field=models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='type_processeur',
            field=models.CharField(choices=[('core i3', 'core i3'), ('core i5', 'core i5'), ('core i7', 'core i7'), ('celeron', 'celeron'), ('core duo', 'core duo')], max_length=50),
        ),
    ]
