# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180111_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandepassante',
            name='debit_download',
            field=models.CharField(choices=[('512KB', '512KBS'), ('1MB', '1MB'), ('2MB', '2MB'), ('3MB', '3MB'), ('4MB', '4MB'), ('5MB', '5MB')], max_length=50, verbose_name='DEBIT DOWNLOAD'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='debit_upload',
            field=models.CharField(choices=[('ILLIMITE', 'ILLIMITE')], max_length=50, verbose_name='DEBIT UPLOAD'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='frais_installation',
            field=models.CharField(choices=[('750$', '750$')], max_length=50, verbose_name="FRAIS D'INSTALLATION"),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='type_bande_passante',
            field=models.CharField(choices=[('DEDIE', 'DEDIE')], max_length=50, verbose_name='TYPE BANDE PASSANTE'),
        ),
    ]
