# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20180111_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocollantVinyleAdhesif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_autocollant', models.CharField(choices=[('TRANSPARENT', 'TRANSPARENT'), ('OPAQUE', 'OPAQUE')], max_length=50, verbose_name='TYPE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='BackDrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('dimension', models.CharField(choices=[('2,25x2,25', '2,25x2,25'), ('4,6x2,25', '4,6x2,25')], max_length=50, verbose_name='dimension')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationDeMasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_evenement_de_masse', models.CharField(choices=[('DISTRIBUTION DE FLYERS', 'DISTRIBUTION DE FLYERS'), ('ACTIVATION', 'ACTIVATION'), ('CARAVANE MOTORISE', 'CARAVANE MOTORISE'), ('EVENEMENT CORPORATE ', 'EVENEMENT CORPORATE '), ('EVENEMENT PREMIUM', 'EVENEMENT PREMIUM')], max_length=20, verbose_name='TYPE COMMUNICATION DE MASSE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationGraphique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_conception_graphique', models.CharField(choices=[('LOGO', 'LOGO'), ('PAPIER ENTETE ', 'PAPIER ENTETE '), ('CARTE DE VISITE', 'CARTE DE VISITE'), ('HABILLAGE DE SITE WEB  ', 'HABILLAGE DE SITE WEB'), ('CHARTE GRAPHIQUE', 'CHARTE GRAPHIQUE')], max_length=20, verbose_name='TYPE DE CONCEPTION GRAPHIQUE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='EcritureScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_minute', models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('20-40', '20-40'), ('40-80', '40-80')], max_length=20, verbose_name='ECRITURE DE SCENARIO')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='EvenementDeMasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_evenement_de_masse', models.CharField(choices=[('DISTRIBUTION DE FLYERS', 'DISTRIBUTION DE FLYERS'), ('ACTIVATION', 'ACTIVATION'), ('CARAVANE MOTORISE', 'CARAVANE MOTORISE'), ('EVENEMENT CORPORATE ', 'EVENEMENT CORPORATE '), ('EVENEMENT PREMIUM', 'EVENEMENT PREMIUM')], max_length=20, verbose_name='TYPE EVENEMENT DE MASSE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ImpressionBache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_support', models.CharField(choices=[('BACHE', 'BACHE'), ('TISSUS', 'TISSUS')], max_length=50, verbose_name='TYPE SUPPORT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Postproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_minute', models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('20-40', '20-40'), ('40-80', '40-80')], max_length=20, verbose_name='POSTPRODUCTION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTournage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_minute', models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('20-40', '20-40'), ('40-80', '40-80')], max_length=20, verbose_name='POSTPRODUCTION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='RamePapier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('format', models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='RollUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('dimension', models.CharField(choices=[('200cmX80cm', '200cmX80cm'), ('180cmX80cm', '180cmX80cm'), ('10cmX15cm', '10cmX15cm')], max_length=50, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Sachet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('quantite', models.CharField(choices=[('1-100', '1-100'), ('101-1000', '101-1000'), ('1001-10000', '1001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000')], max_length=50, verbose_name='QUANTITÉ')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='XStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_support', models.CharField(choices=[('NORMAL', 'NORMAL'), ('EN ALUMINIUM', 'EN ALUMINIUM')], max_length=50, verbose_name='TYPE SUPPORT')),
                ('dimensions', models.CharField(choices=[('200cmX80cm', '200cmX80cm'), ('180cmX80cm', '180cmX80cm'), ('10cmX15cm', '10cmX15cm')], max_length=50, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='farde',
            name='category',
        ),
        migrations.RemoveField(
            model_name='farde',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='affiche',
            name='face_impression',
        ),
        migrations.RemoveField(
            model_name='affiche',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='affiche',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='support_copie',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='support_original',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='support_souche',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='carteservice',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='cartevisite',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='cartevisite',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='casquetteblanche',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='depliant',
            name='face_impression',
        ),
        migrations.RemoveField(
            model_name='depliant',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='depliant',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='laniere',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='pins',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='porteclef',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='stylo',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='couleur_tshirt',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='taille_tshirt',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='unite_vente',
        ),
        migrations.RemoveField(
            model_name='tshirtblanc',
            name='unite_vente',
        ),
        migrations.AddField(
            model_name='stylo',
            name='type_stylo',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('1-500', '1-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-3000', '2001-3000'), ('3001-4000', '3001-4000'), ('4001-5000', '4001-5000'), ('5001-10000', '5001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='unite_prix',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='dimension_armoire',
            field=models.CharField(choices=[('01', '100X120CM'), ('02', '180X100CM'), ('03', '198X120CM'), ('04', '210X270CM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='type_armoire',
            field=models.CharField(choices=[('ARMOIRE BASSE', 'ARMOIRE BASSE'), ('ARMOIRE HAUTE', 'ARMOIRE HAUTE'), ('ARMOIRE MI-HAUTE', 'ARMOIRE MI-HAUTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='type_porte',
            field=models.CharField(choices=[('BATTANTES', 'BATTANTES'), ('RIDEAUX', 'RIDEAUX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditetcontroleinterne',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cachethumide',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetimprime',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetnumerique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetsec',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('100 <', '100 <')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='quantite',
            field=models.CharField(choices=[('100', '100')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casquetteblanche',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casquetteblanche',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursanglais',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enregistreurcamerasurveillance',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equerre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flexible',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='quantite',
            field=models.CharField(choices=[('1-500', '1-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-3000', '2001-3000'), ('3001-4000', '3001-4000'), ('4001-5000', '4001-5000'), ('5001-10000', '5001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gant',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gravure',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mechebeton',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='montecharge',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outilsjardinage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paumelle',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pins',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pins',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompeforage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-1000', '101-1000'), ('1001-10000', '1001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='redactiondesprocedures',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reductionpvc',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sechemain',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicenettoyage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicetraiteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingbag',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-1000', '101-1000'), ('1001-10000', '1001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingbag',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siegeetfauteuildebureau',
            name='revetement_siege',
            field=models.CharField(choices=[('BOIS', 'BOIS'), ('CUIR', 'CUIR'), ('METAL', 'METAL'), ('PLASTIQUE', 'PLASTIQUE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siegeetfauteuildebureau',
            name='type_siege',
            field=models.CharField(choices=[('CHAISE ACCUEIL', 'CHAISE ACCUEIL'), ('CHAISE VISITEUR', 'CHAISE VISITEUR'), ('FAUTEUIL DE DIRECTION', 'FAUTEUIL DE DIRECTION'), ('SIEGE DE REUNION', 'SIEGE DE REUNION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siegeetfauteuildebureau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siphon',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-1000', '101-1000'), ('1001-10000', '1001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='type_tshirt',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Farde',
        ),
    ]
