# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0007_auto_20180124_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_abonnement', models.CharField(choices=[('JOURNAL', 'JOURNAL')], max_length=20, verbose_name='TYPE ABONNEMENT')),
                ('periodicite_parution', models.CharField(choices=[('HEBDOMADAIRE', 'HEBDOMADAIRE')], max_length=20, verbose_name='PERIODICITÉ DE PARUTION')),
                ('duree_abonnement', models.CharField(choices=[('3 MOIS', '3 MOIS'), ('6 MOIS', '6 MOIS'), ('12 MOIS', '12 MOIS')], max_length=20, verbose_name='DURÉE ABONNEMENT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='AccueilAeroport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_personnes', models.CharField(choices=[('1', '1'), ('1<', '1<')], max_length=20, verbose_name='NOMBRE PERSONNES')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assainissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_assainissement', models.CharField(choices=[('DESINSECTISATION', 'DESINSECTISATION'), ('DERATISATION', 'DERATISATION'), ('NETTOYAGE', 'NETTOYAGE')], max_length=20, verbose_name='ASSAINISSEMENT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='AssuranceVoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('periode', models.CharField(choices=[('1-7 JOURS', '1-7 JOURS'), ('8-15 JOURS', '8-15 JOURS'), ('16-21 JOURS', '16-21 JOURS'), ('22-30 JOURS', '22-30 JOURS'), ('31-45 JOURS', '31-45 JOURS'), ('46-60 JOURS', '46-60 JOURS')], max_length=20, verbose_name='NOMBRE DES JOURS')),
                ('tranche_age', models.CharField(choices=[('0-55 ANS', '0-55 ANS'), ('55-65 ANS', '55-65 ANS'), ('65 ANS ET PLUS', '65 ANS ET PLUS')], max_length=20, verbose_name='TRANCHE AGE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Buffet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('choix_entree', models.CharField(choices=[('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name='CHOIX ENTRÉE')),
                ('choix_plats', models.CharField(choices=[('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DU PLATS')),
                ('choix_legumes', models.CharField(choices=[('2', '2')], max_length=20, verbose_name='CHOIX DE LEGUMES')),
                ('choix_accompagnement', models.CharField(choices=[('4', '4')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT')),
                ('choix_dessert', models.CharField(choices=[('1', '1')], max_length=20, verbose_name='CHOIX DESSERT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_etoile', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, verbose_name='NOMBRE ETOILE')),
                ('acces_wifi_gratuit', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='ACCES WIFI GRATUIT')),
                ('petit_dejeune_gratuit', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='PETIT DEJEUNE GRATUIT')),
                ('type_lit', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE', 'DOUBLE')], max_length=20, verbose_name='TYPE DE LIT')),
                ('avenue', models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE')),
                ('commune', models.CharField(choices=[('GOMBE', 'GOMBE'), ('KASAVUBU', 'KASAVUBU'), ('LIMETE', 'LIMETE'), ('BANDALUNGWA', 'BANDALUNGWA')], max_length=20, verbose_name='COMMUNE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cocktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('choix_amuse_gueule', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('0', '0')], max_length=20, verbose_name='CHOIX AMUSE GUEULE')),
                ('choix_boisson_froide', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20, verbose_name='CHOIX DE BOISSON FROIDE')),
                ('choix_boisson_alcoolisee', models.CharField(choices=[('0', '0')], max_length=20, verbose_name='CHOIX BOISSON ALCOOLISÉE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='EvacuationVidangePoubelles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('frequence', models.CharField(choices=[('1 FOIS / SEMAINE', '1 FOIS / SEMAINE'), ('2 FOIS / SEMAINE', '2 FOIS / SEMAINE'), ('3 FOIS / SEMAINE', '3 FOIS / SEMAINE')], max_length=20, verbose_name='FREQUENCE')),
                ('paiement', models.CharField(choices=[('MENSUEL', 'MENSUEL')], max_length=20, verbose_name='PAIEMENT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='InsertionPublicitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_insertion', models.CharField(choices=[('JOURNAL', 'JOURNAL')], max_length=20, verbose_name='TYPE INSERTION')),
                ('periodicite_parution', models.CharField(choices=[('HEBDOMADAIRE', 'HEBDOMADAIRE')], max_length=20, verbose_name='PERIODICITÉ DE PARUTION')),
                ('tirage', models.CharField(choices=[('1500', '1500')], max_length=20, verbose_name='TIRAGE')),
                ('dimension', models.CharField(choices=[('1 PAGE COULEUR', '1 PAGE COULEUR'), ('1 PAGE NB', '1 PAGE NB'), ('1/2 PAGE COULEUR', '1/2 PAGE COULEUR'), ('1/2 PAGE NB', '1/2 PAGE NB'), ('1/4 PAGE NB', '1/4 PAGE NB'), ('LA UNE', 'LA UNE'), ('PUBLI REPORTAGE', 'PUBLI REPORTAGE'), ('PUBLICATION DOCUMENT', 'PUBLICATION DOCUMENT')], max_length=20, verbose_name='DIMENSION INSERTION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='NavetteAeroport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_personnes', models.CharField(choices=[('1', '1'), ('1<', '1<')], max_length=20, verbose_name='NOMBRE PERSONNES')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PauseCafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('choix_amuse_gueule', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('0', '0')], max_length=20, verbose_name='CHOIX AMUSE GUEULE')),
                ('choix_boisson_froide', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20, verbose_name='CHOIX DE BOISSON FROIDE')),
                ('choix_boisson_chaude', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20, verbose_name='CHOIX BOISSON CHAUDE')),
                ('choix_viennoiserie', models.CharField(choices=[('2', '2'), ('3', '3')], max_length=20, verbose_name='CHOIX VIENNOISERIE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ProduitNettoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_produit', models.CharField(choices=[('EAU DE JAVEL', 'EAU DE JAVEL'), ('BACTEROL', 'BACTEROL'), ('CREOLINE', 'CREOLINE'), ('ESPRIT DE SEL', 'ESPRIT DE SEL'), ('INSECTICIDE', 'INSECTICIDE'), ('RATICIDE', 'RATICIDE')], max_length=20, verbose_name='TYPE PRODUIT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='SalleConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('superficie', models.CharField(choices=[('140 M2', '140 M2')], max_length=20, verbose_name='SUPERFICIE')),
                ('micro_gratuit', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NOM')], max_length=20, verbose_name='MICRO GRATUIT')),
                ('retro_projecteur', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NOM')], max_length=20, verbose_name='RETRO PROJECTEUR')),
                ('baffle_gratuit', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NOM')], max_length=20, verbose_name='BAFFLE GRATUIT')),
                ('avenue', models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE')),
                ('commune', models.CharField(choices=[('GOMBE', 'GOMBE'), ('KASAVUBU', 'KASAVUBU'), ('LIMETE', 'LIMETE'), ('BANDALUNGWA', 'BANDALUNGWA')], max_length=20, verbose_name='COMMUNE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalleGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('avenue', models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE')),
                ('commune', models.CharField(choices=[('GOMBE', 'GOMBE'), ('KASAVUBU', 'KASAVUBU'), ('LIMETE', 'LIMETE'), ('BANDALUNGWA', 'BANDALUNGWA')], max_length=20, verbose_name='COMMUNE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('periode_service', models.CharField(choices=[('JOUR', 'JOUR'), ('NUIT', 'NUIT')], max_length=20, verbose_name='PERIODE SERVICE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAgenceVoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_service', models.CharField(choices=[('NAVETTE AEROPORT', 'NAVETTE AEROPORT'), ('SERVICE PROTOCOL AEROPORT', 'SERVICE PROTOCOL AEROPORT'), ('ASSISTANCE OBTENTION  VISA', 'ASSISTANCE OBTENTION  VISA')], max_length=20, verbose_name='TYPE DE SERVICE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGardiennage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_gardiennage', models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES ', 'INDUSTRIES '), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('SECURITE RAPPROCHEE', 'SECURITE RAPPROCHEE')], max_length=20, verbose_name='TYPE GARDIENNAGE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_service_split', models.CharField(choices=[('INSTALLATION SPLIT', 'INSTALLATION SPLIT'), ('ENTRETIEN SPLIT', 'ENTRETIEN SPLIT')], max_length=20, verbose_name='TYPE SERVICE SPLIT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterModelOptions(
            name='coursanglais',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='interpretariat',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='servicedetraduction',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='servicenettoyage',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='servicetraiteur',
            options={'ordering': ['prix']},
        ),
        migrations.AlterField(
            model_name='coursanglais',
            name='niveau_cours',
            field=models.CharField(choices=[('AVANCÉ', 'AVANCÉ'), ('INTERMEDIAIRE', 'INTERMEDIAIRE'), ('DEBUTANT', 'DEBUTANT')], max_length=20, verbose_name='NIVEAU DE COURS'),
        ),
        migrations.AlterField(
            model_name='coursanglais',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='coursanglais',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='langue_interpretariat',
            field=models.CharField(choices=[('FRANCAIS-ANGLAIS', 'FRANCAIS-ANGLAIS'), ('FRANCAIS-LINGALA', 'FRANCAIS-LINGALA'), ('ANGLAIS-LINGALA', 'ANGLAIS-LINGALA')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='langue',
            field=models.CharField(choices=[('ANGLAIS', 'ANGLAIS'), ('FRANCAIS', 'FRANCAIS'), ('ALLEMAND', 'ALLEMAND'), ('ESPAGNOL', 'ESPAGNOL')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='type_document',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('TECHNIQUE', 'TECHNIQUE')], max_length=20, verbose_name='TYPE DE DOCUMENT'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='servicenettoyage',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='servicenettoyage',
            name='type_service_nettoyage',
            field=models.CharField(choices=[('APPARTEMENT', 'APPARTEMENT'), ('BUREAUX', 'BUREAUX'), ('BUREAUX + SANITAIRES', 'BUREAUX + SANITAIRES'), ('HOTEL', 'HOTEL'), ('NETTOYAGE APRES CHANTIER', 'NETTOYAGE APRES CHANTIER'), ('SANITAIRES', 'SANITAIRES')], max_length=20, verbose_name='TYPE DE SERVICE NETTOYAGE'),
        ),
        migrations.AlterField(
            model_name='servicenettoyage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='servicetraiteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='servicetraiteur',
            name='type_service_traiteur',
            field=models.CharField(choices=[('BUFFET', 'BUFFET'), ('COCKTAIL', 'COCKTAIL'), ('PAUSE CAFÉ', 'PAUSE CAFÉ')], max_length=20, verbose_name='TYPE DE SERVICE TRAITEUR'),
        ),
        migrations.AlterField(
            model_name='servicetraiteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
