# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180124_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartouche',
            name='couleur_cartouche',
            field=models.CharField(choices=[('COULEUR', 'COULEUR'), ('NOIR', 'NOIR'), ('CYAN', 'CYAN'), ('MAGENTA', 'MAGENTA'), ('JAUNE', 'JAUNE')], max_length=50, verbose_name='COULEUR DE CARTOUCHE'),
        ),
    ]
