# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20180124_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('variete', models.CharField(choices=[('NERICA', 'NERICA'), ('NERICA17', 'NERICA17'), ('NERICA18', 'NERICA18'), ('JANSMINE', 'JANSMINE'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=50, verbose_name='VARIETE')),
                ('type_riz', models.CharField(choices=[('DECORTIQUE', 'DECORTIQUE'), ('NON DECORTIQUE', 'NON DECORTIQUE')], max_length=50, verbose_name='TYPE RIZ')),
                ('qualite_riz', models.CharField(choices=[('BIO', 'BIO')], max_length=50, verbose_name='QUALITE RIZ')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('US$/JOUR', 'US$/JOUR'), ('US$/PAGE', 'US$/PAGE'), ('US$/M2', 'US$/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
