# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180124_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursanglais',
            name='langue_cours',
            field=models.CharField(choices=[('ANGLAIS', 'ANGLAIS')], default=1, max_length=20, verbose_name='LANGUE'),
            preserve_default=False,
        ),
    ]
