# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0019_auto_20180125_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditControleInterne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('secteur', models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], max_length=100, verbose_name='SECTEUR ')),
                ('type_intervention', models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION')),
                ('nombre_employes', models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYÉS')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='RedactionProcedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('secteur', models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], max_length=100, verbose_name='SECTEUR ')),
                ('type_intervention', models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION')),
                ('nombre_employes', models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYÉS')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='auditetcontroleinterne',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auditetcontroleinterne',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='redactiondesprocedures',
            name='category',
        ),
        migrations.RemoveField(
            model_name='redactiondesprocedures',
            name='vendeur',
        ),
        migrations.AlterModelOptions(
            name='assistancecomptable',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='assistancefiscale',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='auditfinancier',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='conseil',
            options={'ordering': ['prix']},
        ),
        migrations.AddField(
            model_name='assistancecomptable',
            name='secteur',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], default=1, max_length=20, verbose_name='SECTEUR '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancefiscale',
            name='secteur',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], default=1, max_length=100, verbose_name='SECTEUR '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditfinancier',
            name='secteur',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], default=1, max_length=100, verbose_name='SECTEUR '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conseil',
            name='secteur',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', '8BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], default=1, max_length=100, verbose_name='SECTEUR '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYES'),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION'),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYES'),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION'),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYÉS'),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION'),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('6-10', '6-10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name='NOMBRE EMPLOYES'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name='TYPE INTERVENTION'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='baffle_gratuit',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='BAFFLE GRATUIT'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='retro_projecteur',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='RETRO PROJECTEUR'),
        ),
        migrations.DeleteModel(
            name='AuditEtControleInterne',
        ),
        migrations.DeleteModel(
            name='RedactionDesProcedures',
        ),
    ]
