# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0021_auto_20180125_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onduleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('PREMAX', 'PREMAX'), ('APC', 'APC'), ('ITC', 'ITC'), ('MERCURY', 'MERCURY')], max_length=20, verbose_name='MARQUE ')),
                ('puissance', models.CharField(choices=[('200VA', '200VA'), ('600VA', '600VA'), ('650VA', '650VA'), ('750VA', '750VA'), ('900VA', '900VA'), ('1000VA', '1000VA'), ('1100VA', '1100VA'), ('1200VA', '1200VA'), ('1500VA', '1500VA')], max_length=20, verbose_name='PUISSANCE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Stabilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('PREMAX', 'PREMAX'), ('APC', 'APC'), ('ITC', 'ITC'), ('MERCURY', 'MERCURY'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE ')),
                ('puissance', models.CharField(choices=[('200VA', '200VA'), ('600VA', '600VA'), ('650VA', '650VA'), ('750VA', '750VA'), ('900VA', '900VA'), ('1000VA', '1000VA'), ('1100VA', '1100VA'), ('1200VA', '1200VA'), ('1500VA', '1500VA'), ('3000VA', '3000VA'), ('5000VA', '5000VA'), ('10000VA', '10000VA')], max_length=20, verbose_name='PUISSANCE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='assainissement',
            name='type_assainissement',
            field=models.CharField(choices=[('DESINSECTISATION', 'DESINSECTISATION'), ('DERATISATION', 'DERATISATION'), ('NETTOYAGE BUREAU', 'NETTOYAGE BUREAU'), ('NETTOYAGE APRES CHANTIER', 'NETTOYAGE APRES CHANTIER')], max_length=100, verbose_name="TYPE D'ASSAINISSEMENT"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_dessert',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=20, verbose_name='CHOIX DESSERT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name='CHOIX ENTRÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_plats',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DU PLATS'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX BOISSON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_froide',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON FROIDE'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='type_processeur',
            field=models.CharField(choices=[('CORE I3', 'CORE I3'), ('CORE I5', 'CORE I5'), ('CORE I7', 'CORE I7'), ('CELERON', 'CELERON'), ('DUAL CORE', 'DUAL CORE'), ('CORE DUO', 'CORE DUO'), ('INTEL CORE', 'INTEL CORE'), ('PENTIUM', 'PENTIUM'), ('INTEL XEON', 'INTEL XEON')], max_length=50, verbose_name='TYPE DE PROCESSEUR'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='langue_interpretariat',
            field=models.CharField(choices=[('ANGLAIS-FRANCAIS', 'ANGLAIS-FRANCAIS'), ('FRANCAIS-LINGALA', 'FRANCAIS-LINGALA'), ('ANGLAIS-LINGALA', 'ANGLAIS-LINGALA'), ('ALLEMAND-FRANCAIS', 'ALLEMAND-FRANCAIS'), ('ESPAGNOL-FRANCAIS', 'ESPAGNOL-FRANCAIS')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='type_processeur',
            field=models.CharField(choices=[('CORE I3', 'CORE I3'), ('CORE I5', 'CORE I5'), ('CORE I7', 'CORE I7'), ('CELERON', 'CELERON'), ('DUAL CORE', 'DUAL CORE'), ('CORE DUO', 'CORE DUO'), ('INTEL CORE', 'INTEL CORE'), ('PENTIUM', 'PENTIUM'), ('INTEL XEON', 'INTEL XEON')], max_length=50, verbose_name='TYPE DE PROCESSEUR'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_chaude',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX BOISSON CHAUDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_froide',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON FROIDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_viennoiserie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX VIENNOISERIE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='type_processeur',
            field=models.CharField(choices=[('CORE I3', 'CORE I3'), ('CORE I5', 'CORE I5'), ('CORE I7', 'CORE I7'), ('CELERON', 'CELERON'), ('DUAL CORE', 'DUAL CORE'), ('CORE DUO', 'CORE DUO'), ('INTEL CORE', 'INTEL CORE'), ('PENTIUM', 'PENTIUM'), ('INTEL XEON', 'INTEL XEON')], max_length=50, verbose_name='TYPE DE PROCESSEUR'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='langue',
            field=models.CharField(choices=[('ANGLAIS-FRANCAIS', 'ANGLAIS-FRANCAIS'), ('FRANCAIS-LINGALA', 'FRANCAIS-LINGALA'), ('ANGLAIS-LINGALA', 'ANGLAIS-LINGALA'), ('ALLEMAND-FRANCAIS', 'ALLEMAND-FRANCAIS'), ('ESPAGNOL-FRANCAIS', 'ESPAGNOL-FRANCAIS')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='capacite_memoire',
            field=models.CharField(choices=[('700MB', '700MB'), ('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('4,7GB', '4,7GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPAPCITE DE STOCKAGE'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='type_stockage',
            field=models.CharField(choices=[('MEMOIRE SD', 'MEMOIRE SD'), ('FLASHDISK', 'FLASHDISK'), ('DISQUE EXTERNE', 'DISQUE EXTERNE'), ('CD-RW', 'CD-RW'), ('DVD', 'DVD')], max_length=50, verbose_name='TYPE DE STOCKAGE'),
        ),
    ]
