# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_bouillie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('modele_tablette', models.CharField(choices=[('PRO 1', 'PRO 1'), ('PRO 2', 'PRO 2'), ('AIR2', 'AIR2'), ('TAB 3 ESSENTIAL', 'TAB 3 ESSENTIAL'), ('TAB S3', 'TAB S3'), ('TAB S2', 'TAB S2'), ('TAB A(6)', 'TAB A(6)'), ('TAB E', 'TAB E')], max_length=100, verbose_name='MODELE')),
                ('systeme_exploitation', models.CharField(choices=[('WIN7', 'WIN7'), ('WIN8', 'WIN8'), ('WIN10', 'WIN10'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS')], max_length=100, verbose_name="SYSTEME D'EXPLOITATION")),
                ('memoire_tablette', models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=20, verbose_name='MEMOIRE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RenameField(
            model_name='logiciel',
            old_name='type',
            new_name='type_logiciel',
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='modele',
            field=models.CharField(choices=[('LASERJET P2035', 'LASERJET P2035'), ('CANON 4870', 'CANON 4870'), ('COLOR LASERJET', 'COLOR LASERJET'), ('COLOR LASERJET PRO M176 N', 'COLOR LASERJET PRO M176 N'), ('COLOR LASERJET PRO M177 FW MFP', 'COLOR LASERJET PRO M177 FW MFP'), ('DESKJET 125A', 'DESKJET 125A'), ('DESKJET 2130', 'DESKJET 2130'), ('DESKJET 2180', 'DESKJET 2180'), ('DESKJET 3630 W', 'DESKJET 3630 W'), ('DESKJET 3632', 'DESKJET 3632'), ('DESKJET 3635 W', 'DESKJET 3635 W'), ('I-SENSYS MF41', 'I-SENSYS MF41'), ('IMAGE RUNNER 1133', 'IMAGE RUNNER 1133'), ('LASERJET  PRO MFP 177 FW', 'LASERJET  PRO MFP 177 FW'), ('LASERJET  PRO MFP 227 SDN', 'LASERJET  PRO MFP 227 SDN'), ('LASERJET  PRO MFP 277 DW', 'LASERJET  PRO MFP 277 DW'), ('LASERJET  PRO MFP 477 FDN', 'LASERJET  PRO MFP 477 FDN'), ('LASERJET  PRO MFP 477 FDW', 'LASERJET  PRO MFP 477 FDW'), ('LASERJET M 102 A', 'LASERJET M 102 A'), ('LASERJET M 102 W PO', 'LASERJET M 102 W PRO'), ('LASERJET M176N', 'LASERJET M176N'), ('LASERJET M201N', 'LASERJET M201N'), ('LASERJET M252DW', 'LASERJET M252DW'), ('LASERJET PRO 400', 'LASERJET PRO 400'), ('LASERJET PRO 400 M4280W', 'LASERJET PRO 400 M4280W'), ('LASERJET PRO CM1415FN', 'LASERJET PRO CM1415FN'), ('LASERJET PRO M102', 'LASERJET PRO M102'), ('LASERJET PRO M107', 'LASERJET PRO M107'), ('LASERJET PRO M12A', 'LASERJET PRO M12A'), ('LASERJET PRO M12W', 'LASERJET PRO M12W'), ('LASERJET PRO M402DN', 'LASERJET PRO M402DN'), ('LASERJET PRO M426', 'LASERJET PRO M426'), ('LASERJET PRO MF M130A', 'LASERJET PRO MF M130A'), ('LASERJET PRO MF M771', 'LASERJET PRO MF M771'), ('LASERJET PRO MFP M 127FW', 'LASERJET PRO MFP M 127FW'), ('LASERJET PRO MFP M 130', 'LASERJET PRO MFP M 130'), ('LASERJET PRO MFP M127 FN', 'LASERJET PRO MFP M127 FN'), ('LASERJET PRO MFP M225', 'LASERJET PRO MFP M225'), ('LASERJET PRO MFP M226', 'LASERJET PRO MFP M226'), ('LASERJET PRO MFP M25', 'LASERJET PRO MFP M25'), ('LASERJET PRO MFP M26', 'LASERJET PRO MFP M26'), ('LASERJET PRO MFP M521DN', 'LASERJET PRO MFP M521DN'), ('LASERJET PRO N20', 'LASERJET PRO N20'), ('LASERJET PRO P 1606 DN', 'LASERJET PRO P 1606 DN'), ('LBP 6030', 'LBP 6030'), ('OFFICE JET 4010', 'OFFICE JET 4010'), ('OFFICE JET 4610', 'OFFICE JET 4610'), ('XPRESS M 2835', 'XPRESS M 2835'), ('XPRESS M2020', 'XPRESS M2020')], max_length=50, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='routeur',
            name='marque',
            field=models.CharField(choices=[('D LINK', 'D LINK'), ('CISCO', 'CISCO'), ('LINKSYS', 'LINKSYS'), ('TP-LINK', 'TP-LINK')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='marque',
            field=models.CharField(choices=[('D LINK', 'D LINK'), ('CISCO', 'CISCO'), ('LINKSYS', 'LINKSYS'), ('TP-LINK', 'TP-LINK')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='videoprojecteur',
            name='puissance',
            field=models.CharField(choices=[('195W', '195W'), ('200W', '200W'), ('320W', '320KVA')], max_length=50, verbose_name='PUISSANCE DU RETOPROJECTEUR'),
        ),
    ]
