# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_auto_20180126_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('marque_smartphone', models.CharField(choices=[('HUAWEI', 'HUAWEI'), ('TECNO', 'TECNO')], max_length=100, verbose_name='MARQUE SMARTPHONE')),
                ('modele_smartphone', models.CharField(choices=[('K7', 'K7'), ('K9', 'K9'), ('Y5', 'Y5')], max_length=100, verbose_name='MODELE SMARTPHONE')),
                ('systeme_exploitation', models.CharField(choices=[('ANDROID', 'ANDROID')], max_length=50, verbose_name="SYSTEME D'EXPLOITATION")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='TelephoneMobileSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('marque_mobile', models.CharField(choices=[('SAMSUNG ', 'SAMSUNG ')], max_length=100, verbose_name='MARQUE TELEPHONE')),
                ('modele_mobile', models.CharField(choices=[('B110E', 'B110E')], max_length=100, verbose_name='MODELE TELEPHONE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AddField(
            model_name='tablette',
            name='marque_tablette',
            field=models.CharField(choices=[('IPAD', 'IPAD'), ('LENOVO', 'LENOVO'), ('SAMSUNG', 'SAMSUNG')], default=1, max_length=100, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desktop',
            name='memoire_ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=50, verbose_name='MEMOIRE RAM'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memoire_ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=50, verbose_name='MEMOIRE RAM'),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='licence',
            field=models.CharField(choices=[('1 UTILISATEUR', '1 UTILISATEUR'), ('10 UTILISATEURS', '10 UTILISATEURS')], max_length=50, verbose_name='LICENCE'),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='type_logiciel',
            field=models.CharField(choices=[('ANTIVIRUS', 'ANTIVIRUS'), ('ANTIVIRUS+PAREFEU', 'ANTIVIRUS+PAREFEU')], max_length=50, verbose_name='TYPE DE LOGICIEL'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='capacite_ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=50, verbose_name='MEMOIRE RAM'),
        ),
        migrations.AlterField(
            model_name='tablette',
            name='memoire_tablette',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=20, verbose_name='MEMOIRE'),
        ),
    ]
