# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20180126_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationdemasse',
            name='type_evenement_de_masse',
        ),
        migrations.AddField(
            model_name='communicationdemasse',
            name='type_communication_de_masse',
            field=models.CharField(choices=[('DISTRIBUTION DE FLYERS', 'DISTRIBUTION DE FLYERS'), ('ACTIVATION', 'ACTIVATION')], default=1, max_length=100, verbose_name='TYPE COMMUNICATION DE MASSE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='communicationdemasse',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='marque_desktop',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY'), ('ASUS', 'ASUS'), ('APPLE', 'APPLE'), ('TOSHIBA', 'TOSHIBA')], max_length=50, verbose_name='MARQUE DESKTOP'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='marque_laptop',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY'), ('ASUS', 'ASUS'), ('APPLE', 'APPLE'), ('TOSHIBA', 'TOSHIBA')], max_length=50, verbose_name='MARQUE LAPTOP'),
        ),
        migrations.AlterField(
            model_name='onduleur',
            name='puissance',
            field=models.CharField(choices=[('200VA', '200VA'), ('600VA', '600VA'), ('650VA', '650VA'), ('700VA', '700VA'), ('750VA', '750VA'), ('900VA', '900VA'), ('1000VA', '1000VA'), ('1100VA', '1100VA'), ('1200VA', '1200VA'), ('1500VA', '1500VA'), ('2000VA', '2000VA')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY'), ('ASUS', 'ASUS'), ('APPLE', 'APPLE'), ('TOSHIBA', 'TOSHIBA')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='puissance',
            field=models.CharField(choices=[('200VA', '200VA'), ('500VA', '500VA'), ('600VA', '600VA'), ('650VA', '650VA'), ('750VA', '750VA'), ('900VA', '900VA'), ('1000VA', '1000VA'), ('1100VA', '1100VA'), ('1200VA', '1200VA'), ('1500VA', '1500VA'), ('2000VA', '2000VA'), ('3000VA', '3000VA'), ('5000VA', '5000VA'), ('10000VA', '10000VA')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='capacite_memoire',
            field=models.CharField(choices=[('700MB', '700MB'), ('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('4,7GB', '4,7GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('750GB', '750GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPAPCITE DE STOCKAGE'),
        ),
    ]
