# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20180126_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementdemasse',
            name='minimum_payable',
            field=models.CharField(blank=True, choices=[('1000 USD', '1000 USD')], max_length=20, null=True, verbose_name='MINIMUM PAYABLE'),
        ),
    ]
