# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20180127_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertionpublicitaire',
            name='dimension',
            field=models.CharField(choices=[('1 PAGE COULEUR', '1 PAGE COULEUR'), ('1 PAGE NB', '1 PAGE NB'), ('1/2 PAGE COULEUR', '1/2 PAGE COULEUR'), ('1/2 PAGE NB', '1/2 PAGE NB'), ('1/4 PAGE NB', '1/4 PAGE NB'), ('LA UNE', 'LA UNE'), ('PUBLI REPORTAGE', 'PUBLI REPORTAGE'), ('PUBLICATION DOCUMENT', 'PUBLICATION DOCUMENT')], max_length=100, verbose_name='DIMENSION INSERTION'),
        ),
    ]
