# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20180127_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveur',
            name='capacite_ram',
        ),
        migrations.AddField(
            model_name='serveur',
            name='capacite_ram_max',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], default=1, max_length=50, verbose_name='MEMOIRE RAM maximum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveur',
            name='controleur_raid',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default=1, max_length=50, verbose_name='CONTROLEUR RAID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveur',
            name='modele_serveur',
            field=models.CharField(choices=[('POWEREDGE', 'POWEREDGE'), ('PROLIANT', 'PROLIANT')], default=1, max_length=50, verbose_name='MODELE SERVEUR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveur',
            name='type_serveur',
            field=models.CharField(choices=[('TOUR', 'TOUR'), ('RACKABLE', 'RACKABLE')], default=1, max_length=50, verbose_name='TYPE SERVEUR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desktop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('900GB', '900GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('900GB', '900GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='capacite_disque_dur',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('800GB', '800GB'), ('900GB', '900GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB')], max_length=50, verbose_name='CAPACITE DU DISQUE DUR'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('SONY', 'SONY'), ('SANDISK', 'SANDISK'), ('TOSHIBA', 'TOSHIBA'), ('SEAGATE', 'SEAGATE'), ('WESTERN DIGITAL', 'WESTERN DIGITAL'), ('IMOTION', 'IMOTION'), ('SEAGATE', 'SEAGATE')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='type_stockage',
            field=models.CharField(choices=[('MEMOIRE SD', 'MEMOIRE SD'), ('FLASHDISK', 'FLASHDISK'), ('DISQUE EXTERNE', 'DISQUE EXTERNE'), ('CD-RW', 'CD-RW'), ('DVD', 'DVD'), ('DISQUE INTERNE LAPTOP', 'DISQUE INTERNE LAPTOP'), ('DISQUE INTERNE DESKTOP', 'DISQUE INTERNE DESKTOP')], max_length=50, verbose_name='TYPE DE STOCKAGE'),
        ),
    ]
