# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20180129_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancecomptable',
            name='secteur',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL')], max_length=100, verbose_name='SECTEUR '),
        ),
    ]
