# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20180130_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurancevoyage',
            name='periode',
            field=models.CharField(choices=[('1-7 JOURS', '1-7 JOURS'), ('8-15 JOURS', '8-15 JOURS'), ('16-21 JOURS', '16-21 JOURS'), ('22-30 JOURS', '22-30 JOURS'), ('31-45 JOURS', '31-45 JOURS'), ('46-60 JOURS', '46-60 JOURS'), ('61-90 JOURS', '61-90 JOURS'), ('91-180 JOURS', '91-180 JOURS')], max_length=20, verbose_name='NOMBRE DES JOURS'),
        ),
    ]
