# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_locationvehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvehicule',
            name='model',
        ),
    ]
