# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20180130_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvehicule',
            name='marque',
            field=models.CharField(choices=[('TOYOTA YARIS', 'TOYOTA YARIS'), ('TOYOTA COROLLA', 'TOYOTA COROLLA'), ('TOYOTA CAMRY ', 'TOYOTA CAMRY '), ('TOYOTA RAV4', 'TOYOTA RAV4'), ('TOYOTA PRADO', 'TOYOTA PRADO'), ('TOYOTA LAND CRUISER', 'TOYOTA LAND CRUISER'), ('TOYOTA HIACE', 'TOYOTA HIACE'), ('TOYOTA HILUX DOUBLE CABINE', 'TOYOTA HILUX DOUBLE CABINE'), ('NISSAN', 'NISSAN'), ('ZX AUTO', 'ZX AUTO'), ('ZOTYE', 'ZOTYE')], max_length=50, verbose_name='MARQUE DU VEHICULE'),
        ),
    ]
