# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20180130_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pienturespeciale',
            name='pienture_speciale',
        ),
        migrations.AddField(
            model_name='pienturespeciale',
            name='type_produit',
            field=models.CharField(choices=[('MASTIC', 'MASTIC'), ('GALVA', 'GALVA'), ('ANTIROUILLE FER', 'ANTIROUILLE FER'), ('SATIN', 'SATIN'), ('ANTIROUILLE PLOMB', 'ANTIROUILLE PLOMB'), ('CHROMATE DE ZINC', 'CHROMATE DE ZINC'), ('VERNIS INT&EXT', 'VERNIS INT&EXT'), ('BOUCHE PORS', 'BOUCHE PORS'), ('VERNIS NOIR', 'VERNIS NOIR'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('PRIMER SURFACER', 'PRIMER SURFACER'), ('MENUICOL', 'MENUICOL'), ('PEINTURE AU LARO', 'PEINTURE AU LARO')], default=1, max_length=20, verbose_name=' TYPE PRODUIT'),
            preserve_default=False,
        ),
    ]
