# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_auto_20180130_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peinturespeciale',
            name='caracteristique',
            field=models.CharField(choices=[('PRIMAIRE', 'PRIMAIRE')], max_length=20, verbose_name='CARACTERISTIQUE'),
        ),
    ]
