# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_auto_20180130_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peinture',
            name='teinte',
            field=models.CharField(choices=[('CLAIR', 'CLAIR'), ('VIF', 'VIF'), ('PASTEL', 'PASTEL'), ('SATIN', 'SATIN'), ('MAT', 'MAT'), ('AUCUNE TEINTE', 'AUCUNE TEINTE')], max_length=20, verbose_name='TEINTE'),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='domaine_application',
            field=models.CharField(choices=[('APPRET MUR', 'APPRET MUR'), ('PROTECTION METAL', 'PROTECTION METAL'), ('PROTECTION BOIS', 'PROTECTION BOIS'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('MENUISERIE', 'MENUISERIE'), ('PROTECTION METAL', 'PROTECTION METAL')], max_length=50, verbose_name='DOMAINE APPLICATION'),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='type_produit',
            field=models.CharField(choices=[('MASTIC', 'MASTIC'), ('GALVA', 'GALVA'), ('ANTIROUILLE FER', 'ANTIROUILLE FER'), ('SATIN', 'SATIN'), ('ANTIROUILLE PLOMB', 'ANTIROUILLE PLOMB'), ('CHROMATE DE ZINC', 'CHROMATE DE ZINC'), ('VERNIS INT&EXT', 'VERNIS INT&EXT'), ('BOUCHE PORS', 'BOUCHE PORS'), ('VERNIS NOIR', 'VERNIS NOIR'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('PRIMER SURFACER', 'PRIMER SURFACER'), ('MENUICOL', 'MENUICOL'), ('PEINTURE AU LARO', 'PEINTURE AU LARO')], max_length=50, verbose_name=' TYPE PRODUIT'),
        ),
    ]
