# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_auto_20180130_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peinturespeciale',
            name='domaine_application',
            field=models.CharField(choices=[('APPRET MUR', 'APPRET MUR'), ('PROTECTION METAL', 'PROTECTION METAL'), ('PROTECTION BOIS', 'PROTECTION BOIS'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('MENUISERIE', 'MENUISERIE'), ('PROTECTION METAL', 'PROTECTION METAL'), ('BOUCHE TROIS', 'BOUCHE TROIS')], max_length=50, verbose_name='DOMAINE APPLICATION'),
        ),
    ]
