# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_auto_20180130_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationsiteweb',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='creationsiteweb',
            name='type_site_web',
            field=models.CharField(choices=[('VITRINE', 'VITRINE'), ('E-COMMERCE', 'E-COMMERCE'), ('SITE AVEC APPLICATION', 'SITE AVEC APPLICATION')], max_length=100, verbose_name='TYPE DE SITE'),
        ),
    ]
