# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0062_auto_20180130_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('plage_surface', models.CharField(choices=[('<50M²', '<50M²'), ('50M²-100M²', '50M²-100M²'), ('100M²-150M²', '100M²-150M²'), ('150M²-200M²', '150M²-200M²'), ('>200M²', '>200M²')], max_length=100, verbose_name='PLAGE DE SURFACE')),
                ('avenue', models.CharField(choices=[('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL')], max_length=100, verbose_name='AVENUE')),
                ('commune', models.CharField(choices=[('LIMETE', 'LIMETE')], max_length=100, verbose_name='COMMUNE')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT'),
        ),
    ]
