# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0063_auto_20180130_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureJeepBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('type_vehicule', models.CharField(choices=[('VOITURE', 'VOITURE'), ('JEEP', 'JEEP'), ('MINIBUS', 'MINIBUS'), ('BUS', 'BUS')], max_length=100, verbose_name='TYPE VEHICULE')),
                ('marque_voiture', models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO')], max_length=100, verbose_name='MARQUE')),
                ('modele_voiture', models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE', 'PATROL 10 PLACE'), ('NAVARA PICK UP', 'NAVARA PICK UP'), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKAI', 'QUASHKAI'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER  PICK UP', 'GRANDTIGER  PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV')], max_length=100, verbose_name='MODELE')),
                ('etat_voiture', models.CharField(choices=[('NEUF', 'NEUF'), ('OCCASION', 'OCCASION')], max_length=100, verbose_name='ETAT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='locationstand',
            name='espace',
        ),
        migrations.AddField(
            model_name='locationstand',
            name='duree_maximum',
            field=models.CharField(choices=[('4 JOURS', '4 JOURS')], default=1, max_length=100, verbose_name='DUREE MAXIMUM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationstand',
            name='surface_stand',
            field=models.CharField(choices=[('6M²', '6M²'), ('9M²', '9M²'), ('12M²', '12M²')], default=1, max_length=100, verbose_name='SURFACE (M²)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationstand',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'VOITURE'), ('JEEP', 'JEEP'), ('MINIBUS', 'MINIBUS'), ('BUS', 'BUS')], max_length=20, verbose_name='TYPE DE VEHICULE'),
        ),
    ]
