# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_mototroisroues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brique',
            name='largeur',
            field=models.CharField(choices=[('220mm', '220mm'), ('140mm', '140mm')], max_length=20, verbose_name='LARGEUR'),
        ),
        migrations.AlterField(
            model_name='brique',
            name='type_brique',
            field=models.CharField(choices=[('ARGILE STABILISE AU CIMENT', 'ARGILE STABILISE AU CIMENT')], max_length=50, verbose_name='TYPE DE BRIQUE'),
        ),
    ]
