# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_auto_20180130_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armoire',
            name='dimension_armoire',
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='type_porte',
        ),
        migrations.AddField(
            model_name='armoire',
            name='hauteur',
            field=models.CharField(choices=[('157', '157'), ('198', '198'), ('200', '200')], default=1, max_length=50, verbose_name='HAUTEUR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armoire',
            name='largeur',
            field=models.CharField(choices=[('27,5', '27,5'), ('37,5', '37,5'), ('30', '30'), ('78', '78')], default=1, max_length=50, verbose_name='LARGEUR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armoire',
            name='longueur',
            field=models.CharField(choices=[('40', '40'), ('92', '92'), ('91', '91'), ('120', '120'), ('150', '150'), ('170', '170')], default=1, max_length=50, verbose_name='LONGUEUR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armoire',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL')], default=1, max_length=50, verbose_name='MATERIAU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armoire',
            name='nombre_de_cases',
            field=models.CharField(choices=[('3', '3'), ('6', '6')], default=1, max_length=50, verbose_name='NOMBRE_CASES'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armoire',
            name='type_armoire',
            field=models.CharField(choices=[('ARMOIRE BASSE', 'ARMOIRE BASSE'), ('ARMOIRE HAUTE', 'ARMOIRE HAUTE'), ('ARMOIRE MI-HAUTE', 'ARMOIRE MI-HAUTE')], max_length=50, verbose_name='TYPE ARMOIRE'),
        ),
    ]
