# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_tablebureau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebureau',
            name='hauteur',
        ),
    ]
