# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_auto_20180131_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moellon',
            name='type',
        ),
        migrations.AddField(
            model_name='moellon',
            name='type_moellon',
            field=models.CharField(choices=[('CAILLASSE', 'CAILLASSE'), ('MOELLON', 'MOELLON')], default=1, max_length=100, verbose_name='TYPE MOELLON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moellon',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
