# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_auto_20180131_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riz',
            name='qualite_riz',
        ),
        migrations.RemoveField(
            model_name='riz',
            name='type_riz',
        ),
    ]
