# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0095_tourteau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('materiau_bureau', models.CharField(choices=[('METAL', 'METAL'), ('BOIS AGGLOMERE', 'BOIS AGGLOMERE')], max_length=20, verbose_name='MATERIAU ')),
                ('longueur', models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR')], max_length=20, verbose_name='LONGUEUR')),
                ('type_bureau', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DIRECTION', 'DIRECTION')], max_length=20, verbose_name='FORME')),
                ('model_bureau', models.CharField(choices=[('001', '001'), ('002', '002'), ('Z001', 'Z001'), ('1205', '1205'), ('1405', '1405'), ('1605', '1605'), ('2022', '2022'), ('2036', '2036'), ('2808', '2808'), ('12019B', '12019B'), ('14019B', '14019B'), ('16019B', '16019B'), ('16129', '16129')], max_length=20, verbose_name='FORME')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='armoire',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR')], max_length=50, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL'), ('BOIS AGGLOMERE', 'BOIS AGGLOMERE')], max_length=50, verbose_name='MATERIAU'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL'), ('BOIS AGGLOMERE', 'BOIS AGGLOMERE')], max_length=20, verbose_name='MATERIAU '),
        ),
        migrations.AlterField(
            model_name='tablebureau',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='tablebureau',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL'), ('BOIS AGGLOMERE', 'BOIS AGGLOMERE')], max_length=20, verbose_name='MATERIAU '),
        ),
    ]
