# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20180131_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabilisateur',
            name='puissance',
            field=models.CharField(choices=[('1000VA', '1000VA'), ('3000VA', '3000VA'), ('1500VA', '1500VA'), ('5000VA', '5000VA'), ('10000VA', '10000VA'), ('2000VA', '2000VA')], max_length=20, verbose_name='PUISSANCE'),
        ),
    ]
