# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0098_auto_20180131_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('longueur', models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR')),
                ('forme', models.CharField(choices=[('RECTANGULAIRE', 'RECTANGULAIRE'), ('OVALE', 'OVALE')], max_length=20, verbose_name='FORME')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='armoire',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=50, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='interrupteur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='onduleur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='split',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('EUROMAX', 'EUROMAX'), ('TANAKA', 'TANAKA')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='puissance',
            field=models.CharField(choices=[('500VA', '500VA'), ('1000VA', '1000VA'), ('3000VA', '3000VA'), ('1500VA', '1500VA'), ('5000VA', '5000VA'), ('10000VA', '10000VA'), ('2000VA', '2000VA')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='tablebureau',
            name='forme',
            field=models.CharField(choices=[('RECTANGULAIRE', 'RECTANGULAIRE'), ('OVALE', 'OVALE')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='tablebureau',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
    ]
