# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_auto_20180131_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteurincendie',
            name='adressable',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default=1, max_length=20, verbose_name='ADRESSABLE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detecteurincendie',
            name='mode_detection',
            field=models.CharField(choices=[('DETECTEUR OPTIQUE ', 'DETECTEUR OPTIQUE '), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE'), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE')], max_length=20, verbose_name='MODE DE DETECTION'),
        ),
        migrations.AlterField(
            model_name='extincteur',
            name='agent',
            field=models.CharField(choices=[('DETECTEUR OPTIQUE ', 'DETECTEUR OPTIQUE '), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE'), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE')], max_length=20, verbose_name='MODE DE DETECTION'),
        ),
    ]
