# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0102_auto_20180201_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='FretRoutier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('lieu_depart', models.CharField(choices=[('KINSHASA', 'KINSHASA'), ('KINSHASA', 'KINSHASA'), ('KINSHASA', 'KINSHASA'), ('KINSHASA', 'KINSHASA')], max_length=20, verbose_name='LIEU DEPART')),
                ('lieu_destination', models.CharField(choices=[('KANANGA', 'KANANGA'), ('MBUJI MAYI ', 'MBUJI MAYI '), ('KIKWIT', 'KIKWIT'), ('TSHIKAPA', 'TSHIKAPA')], max_length=20, verbose_name='LIEU DESTINATION')),
                ('capacite_max', models.CharField(choices=[('20T', '20T')], max_length=20, verbose_name='CAPACITÉ MAXIMUM')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterModelOptions(
            name='demenagement',
            options={'ordering': ['prix']},
        ),
        migrations.AlterField(
            model_name='demenagement',
            name='ville_destination',
            field=models.CharField(choices=[('KINSHASA', 'KINSHASA')], max_length=20, verbose_name='VILLE DE DESTINATION'),
        ),
    ]
