# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_auto_20180201_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertisseur',
            name='chargeur',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, null=True, verbose_name='CHARGEUR'),
        ),
    ]
