# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0106_auto_20180201_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fretroutier',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
