# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0107_auto_20180201_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batteriesolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE')], max_length=20, verbose_name='MARQUE')),
                ('tension', models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE')], max_length=20, verbose_name='TENSION')),
                ('duree_vie', models.CharField(choices=[('25 ans', '25 ans'), ('5 ans', '5 ans')], max_length=20, verbose_name='DUREE')),
                ('garantie', models.CharField(choices=[('30 ans', '30 ans')], max_length=20, verbose_name='GARANTIE')),
                ('capacite', models.CharField(choices=[('102Ah', '102Ah'), ('200Ah', '200Ah'), ('1130Ah', '1130Ah')], max_length=20, verbose_name='CAPACITE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='batterie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='batterie',
            name='vendeur',
        ),
        migrations.AlterField(
            model_name='camion',
            name='modele',
            field=models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS')], max_length=100, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='modele',
            field=models.CharField(blank=True, choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS')], max_length=100, null=True, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='voiturejeepbus',
            name='modele_voiture',
            field=models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE', 'PATROL 10 PLACE'), ('NAVARA PICK UP', 'NAVARA PICK UP'), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKAI', 'QUASHKAI'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER  PICK UP', 'GRANDTIGER  PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('SPRINTER 313 CDI ', 'SPRINTER 313 CDI '), ('SPRINTER 209', 'SPRINTER 209')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.DeleteModel(
            name='Batterie',
        ),
    ]
