# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_locationporteconteneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteriesolaire',
            name='marque',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='tension',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='marque_convertisseur',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE CONVERTISSEUR'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='tension_convertisseur',
            field=models.CharField(choices=[('2V', '2V'), ('12V', '12V'), ('48V', '48V'), ('12/24V', '12/24V'), ('24V', '24V')], max_length=20, verbose_name='TENSION CONVERTISSEUR'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='marque',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='marque',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
    ]
