# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0114_auto_20180201_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteur',
            name='agent',
            field=models.CharField(choices=[('DETECTEUR OPTIQUE ', 'DETECTEUR OPTIQUE '), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE'), ('DETECTION DE CHALEUR', 'DETECTION DE CHALEUR'), ('DETECTION DE FUMEE', 'DETECTION DE FUMEE')], max_length=20, verbose_name='AGENT'),
        ),
    ]
