# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0115_auto_20180201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteur',
            name='agent',
            field=models.CharField(choices=[('CO2', 'CO2'), ('POUDRE', 'POUDRE'), ('EAU', 'EAU')], max_length=20, verbose_name='AGENT'),
        ),
    ]
