# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_auto_20180201_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulateur',
            name='intensite',
            field=models.CharField(choices=[('25A', '25A'), ('20A', '20A'), ('40A', '40A'), ('63A', '63A'), ('9A', '9A'), ('1000A', '1000A'), ('115A', '115A'), ('12A', '12A'), ('150A', '150A'), ('185A', '18A'), ('225A', '225A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('80A', '80A'), ('250A', '250A'), ('40A', '40A'), ('400A', '400A'), ('64A', '64A'), ('18A', '18A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='type_regulation',
            field=models.CharField(choices=[('PWM', 'PWM'), ('MPPT', 'MPPT')], max_length=20, verbose_name='TYPE REGULATION'),
        ),
    ]
