# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0120_consultancedecoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationporteconteneur',
            name='zone',
            field=models.CharField(choices=[('INTRA-URBAIN', 'INTRA-URBAIN')], default=1, max_length=100, verbose_name='POIDS'),
            preserve_default=False,
        ),
    ]
