# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0127_tableau'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterrupteurSectionneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('nombre_phase', models.CharField(choices=[('2P', '2P'), ('4P', '4P')], max_length=100, verbose_name='NOMBRE DE PHASES')),
                ('intensite', models.CharField(choices=[('25A', '25A'), ('40A', '40A'), ('63A', '63A'), ('9A', '9A'), ('1000A', '1000A'), ('115A', '115A'), ('12A', '12A'), ('150A', '150A'), ('185A', '18A'), ('225A', '225A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('80A', '80A'), ('250A', '250A'), ('40A', '40A'), ('400A', '400A'), ('64A', '64A'), ('18A', '18A')], max_length=100, verbose_name='INTENSITE(AMPERE)')),
                ('tension', models.CharField(choices=[('110V', '110V'), ('230V', '230V'), ('24V', '24V'), ('24VCC', '24VCC'), ('380V', '380V'), ('400V', '400V'), ('48V', '48V'), ('220V', '220V'), ('250V', '250V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='TENSION(VOLT)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=100, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='support',
            field=models.CharField(choices=[('AVEC T-SHIRT', 'AVEC T-SHIRT'), ('SANS T-SHIRT', 'SANS T-SHIRT')], max_length=100, verbose_name='SUPPORT'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='type_tshirt',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=100, verbose_name='TYPE TSHIRT'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='type_tshirt',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50),
        ),
    ]
