# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0138_auto_20180201_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='riz',
            name='qualite',
            field=models.CharField(blank=True, choices=[('BIO', 'BIO')], max_length=50, null=True, verbose_name='VARIETE'),
        ),
        migrations.AddField(
            model_name='riz',
            name='type_riz',
            field=models.CharField(blank=True, choices=[('DECORTIQUE', 'DECORTIQUE'), ('NON DECORTIQUE', 'NON DECORTIQUE')], max_length=100, null=True, verbose_name='VARIETE'),
        ),
        migrations.AlterField(
            model_name='abonnementjournal',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='accueilaeroport',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='adresseippublique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='affichagelogosurecran',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='ampoule',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='ampoulesolaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='appareilmesure',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='assainissement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='auditcontroleinterne',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='bandedefilante',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='betonniere',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='bouturemanioc',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='brique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='broderieecussons',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cableinformatique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cablemasse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cablesouple',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cachet',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cahiercharges',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='carreau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='chaisebureau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='chaisesalleattente',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='citerne',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='coffretjeubarre',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='communicationdemasse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='communicationgraphique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='communique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='compacteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='conceptiongraphique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='conceptionpagemagazine',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='consultancedecoration',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='courslangue',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='couverturephoto',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='creationsiteweb',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='decorationamenagement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='decorationsurface',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='demenagement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='detecteurincendie',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='diffusionspotpublicitaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='ecriturescenario',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='enregistreurcamerasurveillance',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='equerre',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='escortefonds',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='evacuationvidangepoubelles',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='evenementdemasse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='extincteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='farine',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='filplastique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='fixeur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='flexible',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='fontaineeau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='fretroutier',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='gant',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='graveur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='gravure',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='hebergementsiteweb',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='huile',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='impressiontasse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='insertionpublicitaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='installationlogicielserveur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='installationsolaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='integrationcustomisationstandard',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='interrupteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationcamion',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationdepot',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationporteconteneur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationremorquematadi',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationstand',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationstudio',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='maintenancebackup',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='mechebeton',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='minuteurcontacteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='missioncontrolechantier',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='modemwifi',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='moellon',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='montecharge',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='navetteaeroport',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='numerisationdonnees',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='onduleur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='outilsmanuel',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pagemagazine',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='palan',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='panneausignalisation',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='paumelle',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='peinture',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='photocopieuse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='plafonnierled',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pointacces',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pompeforage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='postproduction',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='presencephysiquesurplateau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='productiontournage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='produitnettoyage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='projecteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='publicitesurplateau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='ramepapier',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='recrutement',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='redactionprocedures',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='reductionpvc',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='reglette',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='reparationinstallationsolaire',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='reportagetelepromo',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='retransmissiondirect',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='riz',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='riz',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riz',
            name='variete',
            field=models.CharField(choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMINE', 'JASMINE'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, verbose_name='VARIETE'),
        ),
        migrations.AlterField(
            model_name='rollup',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='rouleauflexuble',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='routeur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='sachet',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='sechemain',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='semence',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='semence',
            name='variete',
            field=models.CharField(choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMINE', 'JASMINE'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, verbose_name='VARIETE'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='serviceaccueil',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='serviceagencevoyage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='servicegardiennage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='servicenettoyage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='servicesplit',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='servicetraiteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='shoppingbag',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='siegeetfauteuildebureau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='siphon',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='souris',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='split',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tablebureau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tablette',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='telephonemobilesimple',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tourteau',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='transportbienintrakinshasa',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='travauxpeinture',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='videoprojecteur',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='voiturejeepbus',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='xstand',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='PRODUIT'),
        ),
    ]
