# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0139_auto_20180207_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riz',
            name='qualite',
            field=models.CharField(blank=True, choices=[('BIO', 'BIO')], max_length=50, null=True, verbose_name='QUALITE'),
        ),
        migrations.AlterField(
            model_name='riz',
            name='type_riz',
            field=models.CharField(blank=True, choices=[('DECORTIQUE', 'DECORTIQUE'), ('NON DECORTIQUE', 'NON DECORTIQUE')], max_length=100, null=True, verbose_name='TYPE RIZ'),
        ),
        migrations.AlterField(
            model_name='riz',
            name='variete',
            field=models.CharField(choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMIN', 'JASMIN'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, verbose_name='VARIETE'),
        ),
        migrations.AlterField(
            model_name='semence',
            name='variete',
            field=models.CharField(blank=True, choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMIN', 'JASMIN'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, null=True, verbose_name='VARIETE'),
        ),
    ]
