# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_contacteur_marque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boitederivation',
            name='type_derivation',
        ),
    ]
