# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0143_remove_boitederivation_type_derivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='disjoncteurdifferentiel',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('SUPREMA', 'SUPREMA'), ('TELEMECA', 'TELEMECA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('105X105X55', '105X105X55'), ('175X150X80', '175X150X80'), ('225X175X100', '225X175X100'), ('275X225X120', '275X225X120'), ('65X65X45', '65X65X45'), ('105X105X42', '105X105X42'), ('130X130X30', '130X130X30'), ('160X100X45', '160X100X45'), ('220X160X45', '220X160X45'), ('60X60X25', '60X60X25'), ('80X80X30', '80X80X30'), ('80X80MM', '80X80MM'), ('100X100MM', '100X100MM'), ('150X150MM', '150X150MM'), ('200X150MM', '200X150MM')], max_length=20, verbose_name='DIMENSION(MILLIMETRES)'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='sensibilite',
            field=models.CharField(choices=[('30MA', '30MA'), ('300MA', '300MA')], max_length=100, verbose_name='SENSIBILITE(MILLIAMPERE)'),
        ),
    ]
