# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0144_auto_20180207_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrupteursectionneur',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('SUPREMA', 'SUPREMA'), ('TELEMECA', 'TELEMECA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
    ]
