# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0147_auto_20180207_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meuleuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('puissance_meuleuse', models.CharField(choices=[('2200W', '2200W'), ('3000W', '3000W')], max_length=100, verbose_name='PUISSANCE MEULEUSE')),
                ('diametre', models.CharField(choices=[('5MM', '5MM'), ('6MM', '6MM'), ('8MM', '8MM'), ('10MM', '10MM'), ('12MM', '12MM'), ('14MM', '14MM'), ('16MM', '16MM'), ('20MM', '20MM'), ('25MM', '25MM'), ('32MM', '32MM'), ('50MM', '50MM'), ('63MM', '63MM'), ('90MM', '90MM'), ('110MM', '110MM'), ('230MM', '230MM'), ('125MM', '125MM')], max_length=100, verbose_name='DIAMETRE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='OutillageManuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_outillage', models.CharField(choices=[('RATEAU', 'RATEAU'), ('PELLE', 'PELLE'), ('MACHETTE', 'MACHETTE'), ('ARROSOIR', 'ARROSOIR'), ('HACHE', 'HACHE')], max_length=100, verbose_name='TYPE OUTILLAGE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='pompeimmergee',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='tronconneuse',
            name='model',
        ),
        migrations.AddField(
            model_name='pompeimmergee',
            name='debit_pompe',
            field=models.CharField(choices=[('300 L/H', '300 L/H'), ('600 L/H', '600 L/H'), ('1200 L/H', '1200 L/H'), ('1500 L/H', '1500 L/H'), ('1800 L/H', '1800 L/H'), ('3000 L/H', '3000 L/H'), ('3800 L/H', '3800 L/H'), ('4020 L/H', '4020 L/H'), ('4600 L/H', '4600 L/H'), ('6800 L/H', '6800 L/H'), ('10020 L/H', '10020 L/H'), ('15000 L/H', '15000 L/H'), ('15700 L/H', '15700 L/H'), ('17500 L/H', '17500 L/H'), ('18000 L/H', '18000 L/H'), ('23000 L/H', '23000 L/H')], default=1, max_length=100, verbose_name='DEBIT POMPE(LITRE PAR HEURE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pompeimmergee',
            name='hauteur_pompe',
            field=models.CharField(choices=[('5.5M', '5.5M'), ('8M', '8M'), ('9M', '9M'), ('10M', '10M'), ('11M', '11M'), ('26M', '26M'), ('36M', '36M'), ('65M', '65M'), ('90M', '90M'), ('116M', '116M'), ('141M', '141M'), ('202M', '202M'), ('203M', '203M'), ('228M', '228M'), ('195M', '195M'), ('258M', '258M'), ('271M', '271M'), ('352M', '352M'), ('399M', '399M'), ('419M', '419M'), ('420M', '420M'), ('424M', '424M'), ('485M', '485M'), ('505M', '505M'), ('50M', '50M'), ('80M', '80M'), ('100M', '100M'), ('58M', '58M'), ('70M', '70M'), ('41M', '41M'), ('50M', '50M'), ('70M', '70M'), ('18.5M', '18.5M')], default=1, max_length=100, verbose_name='HAUTEUR POMPE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tondeuse',
            name='type_tondeuse',
            field=models.CharField(choices=[('THERMIQUE', 'THERMIQUE'), ('ELECTRIQUE', 'ELECTRIQUE')], default=1, max_length=100, verbose_name='TYPE TONDEUSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tronconneuse',
            name='modele_tronconneuse',
            field=models.CharField(choices=[('090', '090'), ('070', '070'), ('AV 070', 'AV 070')], default=1, max_length=100, verbose_name='MODELE TRONCONNEUSE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='silencieux',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='SILENCIEUX'),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='puissance_pompe',
            field=models.CharField(choices=[('5,5 HP', '5,5 HP'), ('6.5 HP', '6.5 HP'), ('4.0 HP', '4.0 HP'), ('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('10HP', '10HP'), ('7,5 HP', '7,5H P'), ('0.5 HP', '0.5 HP'), ('0.75 HP', '0.75 HP'), ('1 HP', '1 HP'), ('1.5 HP', '1.5 HP'), ('15 HP', '15 HP'), ('20 HP', '20 HP'), ('25 HP', '25 HP'), ('30 HP', '30 HP'), ('40 HP', '40 HP')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='puissance_pompe',
            field=models.CharField(choices=[('5,5 HP', '5,5 HP'), ('6.5 HP', '6.5 HP'), ('4.0 HP', '4.0 HP'), ('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('10HP', '10HP'), ('7,5 HP', '7,5H P'), ('0.5 HP', '0.5 HP'), ('0.75 HP', '0.75 HP'), ('1 HP', '1 HP'), ('1.5 HP', '1.5 HP'), ('15 HP', '15 HP'), ('20 HP', '20 HP'), ('25 HP', '25 HP'), ('30 HP', '30 HP'), ('40 HP', '40 HP')], max_length=100, verbose_name='PUISSANCE POMPE(CHEVAUX)'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='puissance_tondeuse',
            field=models.CharField(choices=[('12800W', '12800W'), ('4500W', '4500W'), ('1300W', '1300W')], max_length=100, verbose_name='PUISSANCE TONDEUSE'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
