# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0148_auto_20180208_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tronconneuse',
            name='marque',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS')], default=1, max_length=100, verbose_name='MARQUE TRONCONNEUSE'),
            preserve_default=False,
        ),
    ]
