# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0149_tronconneuse_marque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motopompe',
            name='debit',
        ),
        migrations.AddField(
            model_name='motopompe',
            name='marque',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], default=1, max_length=20, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='marque_marchine',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='marque',
            field=models.CharField(blank=True, choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, null=True, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='marque_marchine',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, verbose_name='MACHINE PORTATIF'),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='marque_marchine',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, verbose_name='MACHINE PORTATIF'),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='hauteur_max',
            field=models.CharField(blank=True, choices=[('5.5M', '5.5M'), ('8M', '8M'), ('9M', '9M'), ('10M', '10M'), ('11M', '11M'), ('26M', '26M'), ('36M', '36M'), ('65M', '65M'), ('90M', '90M'), ('116M', '116M'), ('141M', '141M'), ('202M', '202M'), ('203M', '203M'), ('228M', '228M'), ('195M', '195M'), ('258M', '258M'), ('271M', '271M'), ('352M', '352M'), ('399M', '399M'), ('419M', '419M'), ('420M', '420M'), ('424M', '424M'), ('485M', '485M'), ('505M', '505M'), ('50M', '50M'), ('80M', '80M'), ('100M', '100M'), ('58M', '58M'), ('70M', '70M'), ('41M', '41M'), ('50M', '50M'), ('70M', '70M'), ('18.5M', '18.5M')], max_length=20, null=True, verbose_name='HAUTEUR'),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='marque_pompe',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='pompeforage',
            name='marque_pompe',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='marque',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=100, verbose_name='MARQUE TRONCONNEUSE'),
        ),
    ]
