# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0150_auto_20180208_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ampoule',
            old_name='type',
            new_name='type_ampoule',
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='debit_pompe',
            field=models.CharField(choices=[('300 L/H', '300 L/H'), ('600 L/H', '600 L/H'), ('1200 L/H', '1200 L/H'), ('1500 L/H', '1500 L/H'), ('1800 L/H', '1800 L/H'), ('3000 L/H', '3000 L/H'), ('3800 L/H', '3800 L/H'), ('4020 L/H', '4020 L/H'), ('4600 L/H', '4600 L/H'), ('6800 L/H', '6800 L/H'), ('10020 L/H', '10020 L/H'), ('10500 L/H', '10500 L/H'), ('15700 L/H', '15700 L/H'), ('17500 L/H', '17500 L/H'), ('18000 L/H', '18000 L/H'), ('23000 L/H', '23000 L/H'), ('66000 L/H', '66000 L/H')], max_length=20, verbose_name='DEBIT'),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='debit',
            field=models.CharField(choices=[('300 L/H', '300 L/H'), ('600 L/H', '600 L/H'), ('1200 L/H', '1200 L/H'), ('1500 L/H', '1500 L/H'), ('1800 L/H', '1800 L/H'), ('3000 L/H', '3000 L/H'), ('3800 L/H', '3800 L/H'), ('4020 L/H', '4020 L/H'), ('4600 L/H', '4600 L/H'), ('6800 L/H', '6800 L/H'), ('10020 L/H', '10020 L/H'), ('10500 L/H', '10500 L/H'), ('15700 L/H', '15700 L/H'), ('17500 L/H', '17500 L/H'), ('18000 L/H', '18000 L/H'), ('23000 L/H', '23000 L/H'), ('66000 L/H', '66000 L/H')], max_length=20, verbose_name='DEBIT'),
        ),
        migrations.AlterField(
            model_name='pompehydrophore',
            name='puissance_pompe',
            field=models.CharField(choices=[('5,5 HP', '5,5 HP'), ('6,5 HP', '6,5 HP'), ('4,0 HP', '4,0 HP'), ('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('10HP', '10HP'), ('7,5 HP', '7,5H P'), ('0,5 HP', '0,5 HP'), ('0.75 HP', '0.75 HP'), ('1 HP', '1 HP'), ('1,5 HP', '1,5 HP'), ('15 HP', '15 HP'), ('20 HP', '20 HP'), ('25 HP', '25 HP'), ('30 HP', '30 HP'), ('40 HP', '40 HP')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='debit_pompe',
            field=models.CharField(choices=[('300 L/H', '300 L/H'), ('600 L/H', '600 L/H'), ('1200 L/H', '1200 L/H'), ('1500 L/H', '1500 L/H'), ('1800 L/H', '1800 L/H'), ('3000 L/H', '3000 L/H'), ('3800 L/H', '3800 L/H'), ('4020 L/H', '4020 L/H'), ('4600 L/H', '4600 L/H'), ('6800 L/H', '6800 L/H'), ('10020 L/H', '10020 L/H'), ('10500 L/H', '10500 L/H'), ('15700 L/H', '15700 L/H'), ('17500 L/H', '17500 L/H'), ('18000 L/H', '18000 L/H'), ('23000 L/H', '23000 L/H'), ('66000 L/H', '66000 L/H')], max_length=100, verbose_name='DEBIT POMPE(LITRE PAR HEURE)'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='puissance_pompe',
            field=models.CharField(choices=[('5,5 HP', '5,5 HP'), ('6,5 HP', '6,5 HP'), ('4,0 HP', '4,0 HP'), ('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('10HP', '10HP'), ('7,5 HP', '7,5H P'), ('0,5 HP', '0,5 HP'), ('0.75 HP', '0.75 HP'), ('1 HP', '1 HP'), ('1,5 HP', '1,5 HP'), ('15 HP', '15 HP'), ('20 HP', '20 HP'), ('25 HP', '25 HP'), ('30 HP', '30 HP'), ('40 HP', '40 HP')], max_length=100, verbose_name='PUISSANCE POMPE(CHEVAUX)'),
        ),
    ]
