# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_auto_20180208_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduleur',
            name='marque',
            field=models.CharField(choices=[('PREMAX', 'PREMAX'), ('APC', 'APC'), ('ITC', 'ITC'), ('MERCURY', 'MERCURY')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='onduleur',
            name='puissance',
            field=models.CharField(choices=[('110VA', '110VA')], max_length=20, verbose_name='PUISSANCE'),
        ),
    ]
