# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0157_auto_20180208_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulateur',
            name='intensite',
            field=models.CharField(choices=[('25A', '25A'), ('20A', '20A'), ('40A', '40A'), ('63A', '63A'), ('9A', '9A'), ('1000A', '1000A'), ('115A', '115A'), ('12A', '12A'), ('150A', '150A'), ('185A', '18A'), ('225A', '225A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A'), ('80A', '80A'), ('250A', '250A'), ('40A', '40A'), ('400A', '400A'), ('64A', '64A'), ('18A', '18A'), ('30A', '30A'), ('45A', '45A'), ('50A', '50A'), ('60A', '60A'), ('85A', '85A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
