# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0158_auto_20180208_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertisseur',
            name='duree_vie',
            field=models.CharField(choices=[('25 ans', '25 ans'), ('5 ans', '5 ans')], max_length=20, verbose_name='DUREE DE VIE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
