# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0163_auto_20180215_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roseareliure',
            name='quantite',
        ),
        migrations.AddField(
            model_name='roseareliure',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('50', '50'), ('100', '100'), ('500', '500')], default=1, max_length=100, verbose_name='QUANTITE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='type_carbonne',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE FACE', 'DOUBLE FACE')], max_length=100, null=True, verbose_name='TYPE CARBONNE'),
        ),
    ]
