# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0165_auto_20180215_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleliquide',
            old_name='taille_colle',
            new_name='quantite_colle',
        ),
    ]
