# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0166_auto_20180215_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecritoire',
            name='type_ecritoire',
        ),
        migrations.AddField(
            model_name='ecritoire',
            name='matiere_ecritoire',
            field=models.CharField(choices=[('BOIS', 'BOIS'), ('PLASTIQUE', 'PLASTIQUE')], default=1, max_length=100, verbose_name='MATIERE ECRITOIRE'),
            preserve_default=False,
        ),
    ]
