# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0168_auto_20180216_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attache',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='elastiques',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='enveloppe',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='enveloppe',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='etui',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='etui',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='intercalaire',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='marqueur',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='marqueur',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='papier',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='papier',
            name='quantite_par_contenant',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR CONTENANT'),
        ),
        migrations.AlterField(
            model_name='perforateur',
            name='format_perforateur',
            field=models.CharField(choices=[('DP 720', 'DP 720'), ('DP 750', 'DP 750'), ('DP 600', 'DP 600')], max_length=100, verbose_name='FORMAT PERFORATEUR'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='format_pile',
            field=models.CharField(choices=[('CRAYON', 'CRAYON'), ('GRAND', 'GRAND'), ('TOUCHE', 'TOUCHE')], max_length=100, verbose_name='FORMAT PILE'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='punaise',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='punaise',
            name='quantite_par_boite',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR BOITE'),
        ),
        migrations.AlterField(
            model_name='roseareliure',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='roseareliure',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='stylopapeterie',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='stylopapeterie',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='transparentareliure',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('CARNET', 'CARNET'), ('BOITE', 'BOITE'), ('JEUX', 'JEUX'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='transparentareliure',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('40', '40'), ('50', '50'), ('60', '60'), ('100', '100'), ('500', '500')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
    ]
