# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0170_auto_20180217_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocnoteligne',
            name='nombre_page',
        ),
        migrations.AlterField(
            model_name='attache',
            name='quantite',
            field=models.CharField(choices=[('10 BOITES', '10 BOITES'), ('500GR', '500GR')], max_length=100, verbose_name='NOMBRE DE BOITE'),
        ),
    ]
