# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0173_auto_20180219_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvehicule',
            name='modele',
            field=models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS'), ('LAND CRUISER RUNNER', 'LAND CRUISER RUNNER'), ('NOAH', 'NOAH'), ('ALLEX', 'ALLEX')], default=1, max_length=100, verbose_name='MODELE DU VEHICULE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camion',
            name='marque',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO'), ('MAN', 'MAN'), ('IVECO', 'IVECO')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='modele',
            field=models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS'), ('LAND CRUISER RUNNER', 'LAND CRUISER RUNNER'), ('NOAH', 'NOAH'), ('ALLEX', 'ALLEX')], max_length=100, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='marque',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO'), ('MAN', 'MAN'), ('IVECO', 'IVECO')], max_length=100, verbose_name='MARQUE DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='marque',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO'), ('MAN', 'MAN'), ('IVECO', 'IVECO')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='modele',
            field=models.CharField(blank=True, choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS'), ('LAND CRUISER RUNNER', 'LAND CRUISER RUNNER'), ('NOAH', 'NOAH'), ('ALLEX', 'ALLEX')], max_length=100, null=True, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_chaude',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX BOISSON CHAUDE'),
        ),
        migrations.AlterField(
            model_name='voiturejeepbus',
            name='marque_voiture',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO'), ('MAN', 'MAN'), ('IVECO', 'IVECO')], max_length=100, verbose_name='MARQUE'),
        ),
    ]
