# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0175_auto_20180219_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque_batterie', models.CharField(choices=[('TUDOR', 'TUDOR'), ('LARGESTAR', 'LARGESTAR'), ('AK', 'AK')], max_length=100, verbose_name='MARQUE')),
                ('capacite_batterie', models.CharField(choices=[('100AH', '100AH'), ('105AH', '105AH'), ('120AH', '120AH'), ('150AH', '150AH'), ('180AH', '180AH'), ('200AH', '200AH'), ('220AH', '220AH'), ('40AH ', '40AH'), ('45AH ', '45AH'), ('60AH ', '60AH'), ('62AH ', '62AH'), ('65AH ', '65AH'), ('66AH ', '66AH'), ('70AH ', '70AH'), ('75AH ', '75AH'), ('80AH ', '80AH'), ('85AH ', '85AH'), ('85AH ', '85AH'), ('88AH ', '88AH'), ('90AH ', '90AH'), ('95AH ', '95AH')], max_length=100, verbose_name='CAPACITE(AMPERE-HEURE)')),
                ('garantie_batterie', models.CharField(choices=[('3 MOIS', '3 MOIS')], max_length=100, verbose_name='GARANTIE')),
                ('entretien_batterie', models.CharField(choices=[('AVEC ENTRETIEN', 'AVEC ENTRETIEN'), ('SANS ENTRETIEN', 'SANS ENTRETIEN')], max_length=100, verbose_name='ENTRETIEN')),
                ('forme_batterie', models.CharField(choices=[('N ', 'N '), ('NL', 'NL'), ('DIN', 'DIN')], max_length=100, verbose_name='FORME')),
                ('format_batterie', models.CharField(choices=[('STANDARD', 'STANDARD'), ('PETIT FORMAT', 'PETIT FORMAT')], max_length=100, verbose_name='FORMAT')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/M', 'USD/M'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²'), ('USD/BOITE', 'USD/BOITE'), ('USD/PAQUET', 'USD/PAQUET'), ('USD/JEU', 'USD/JEU'), ('USD/CONTENANT', 'USD/CONTENANT'), ('USD/CARNET', 'USD/CARNET')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='CosseBatterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/M', 'USD/M'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²'), ('USD/BOITE', 'USD/BOITE'), ('USD/PAQUET', 'USD/PAQUET'), ('USD/JEU', 'USD/JEU'), ('USD/CONTENANT', 'USD/CONTENANT'), ('USD/CARNET', 'USD/CARNET')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque_pneu', models.CharField(choices=[('GT RADIAL', 'GT RADIAL')], max_length=100, verbose_name='MARQUE')),
                ('dimension_pneu', models.CharField(choices=[('155/70R13', '155/70R13'), ('165/70R13', '165/70R13'), ('175/70R13', '175/70R13'), ('185/70R13', '185/70R13'), ('225/70R14', '225/70R14'), ('165/65R14', '165/65R14'), ('175/70R14', '175/70R14'), ('175/70R15', '175/70R15'), ('185/65R14', '185/65R14'), ('185/70R14', '185/70R14'), ('185/65R15', '185/65R15'), ('195/70R14', '195/70R14'), ('195/70R15', '195/70R15'), ('185R14C', '185R14C'), ('195R14C', '195R14C'), ('145R12', '145R12'), ('195/65R15', '195/65R15'), ('215R14C', '215R14C'), ('195/75R15C', '195/75R15C'), ('205/55R16', '205/55R16'), ('225/70R15', '225/70R15'), ('205R14C', '205R14C'), ('235/70R15', '235/70R15'), ('195R15C', '195R15C'), ('205/65R15', '205/65R15'), ('205R15', '205R15'), ('215R15', '215R15'), ('225/70R15', '225/70R15'), ('205/70R15C', '205/70R15C'), ('215/65R16', '215/65R16'), ('215/70R16', '215/70R16'), ('215/80R15', '215/80R15'), ('235/75R15', '235/75R15'), ('205R16', '205R16'), ('235/60R16', '235/60R16'), ('225/70R16', '225/70R16'), ('225/75R16', '225/75R16'), ('235/70R16', '235/70R16'), ('205/80R16', '205/80R16'), ('265/70R15', '265/70R15'), ('245/70R16', '245/70R16'), ('245/75R16', '245/75R16'), ('225/70R17', '225/70R17'), ('225/60R17', '225/60R17'), ('225/65R17', '225/65R17'), ('235/65R17', '235/65R17'), ('235/70R17', '235/70R17'), ('255/55R17', '255/55R17'), ('245/65R17', '245/65R17'), ('245/70R17', '245/70R17'), ('255/70R16', '255/70R16'), ('650R16', '650R16'), ('265/70R16', '265/70R16'), ('255/55R18', '255/55R18'), ('265/70R17', '265/70R17'), ('275/60R17', '275/60R17'), ('275/75R16', '275/75R16'), ('750R16 LT', '750R16 LT'), ('275/65R17', '275/65R17'), ('825R16', '825R16'), ('245/70R18', '245/70R18'), ('235/70R18', '235/70R18'), ('265/60R18', '265/60R18'), ('1200R20', '1200R20'), ('315/80R20', '315/80R20'), ('315R20', '315R20'), ('900R22.5', '900R22.5'), ('1100R20', '1100R20'), ('1100R22.5', '1100R22.5'), ('1200R22.5', '1200R22.5'), ('295/80R22.5', '295/80R22.5'), ('900R20', '900R20'), ('1400R20', '1400R20'), ('1400R22.5', '1400R22.5')], max_length=100, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/M', 'USD/M'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²'), ('USD/BOITE', 'USD/BOITE'), ('USD/PAQUET', 'USD/PAQUET'), ('USD/JEU', 'USD/JEU'), ('USD/CONTENANT', 'USD/CONTENANT'), ('USD/CARNET', 'USD/CARNET')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
