# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0176_batterie_cossebatterie_pneu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecederechangecarrosserie',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangecarrosserie',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangecarrosserie',
            name='pieces_rechange_carrosserie',
        ),
        migrations.RemoveField(
            model_name='piecederechangedirectionsuspension',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangedirectionsuspension',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangedirectionsuspension',
            name='pieces_rechange_direction_suspension',
        ),
        migrations.RemoveField(
            model_name='piecederechangeelectrique',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangeelectrique',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangeelectrique',
            name='pieces_rechange_electrique',
        ),
        migrations.RemoveField(
            model_name='piecederechangeembrayage',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangeembrayage',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangefreinage',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangefreinage',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangerefroidissement',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangerefroidissement',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangerefroidissement',
            name='pieces_rechange_refroidissement',
        ),
        migrations.RemoveField(
            model_name='piecederechangetransmission',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangetransmission',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecederechangetransmission',
            name='pieces_rechange_transmission',
        ),
        migrations.RemoveField(
            model_name='piecerechangemoteur',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecerechangemoteur',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecerevisionmoteur',
            name='annee_debut_fabrication_vehicule',
        ),
        migrations.RemoveField(
            model_name='piecerevisionmoteur',
            name='annee_fin_fabrication_vehicule',
        ),
        migrations.AddField(
            model_name='appareildemesure',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/M', 'USD/M'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²'), ('USD/BOITE', 'USD/BOITE'), ('USD/PAQUET', 'USD/PAQUET'), ('USD/JEU', 'USD/JEU'), ('USD/CONTENANT', 'USD/CONTENANT'), ('USD/CARNET', 'USD/CARNET')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangecarrosserie',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangecarrosserie',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangecarrosserie',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangecarrosserie',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangecarrosserie',
            name='type_piece_carosserie',
            field=models.CharField(choices=[('PHARE AVANT GAUCHE', 'PHARE AVANT GAUCHE'), ('PHARE AVANT DROIT', 'PHARE AVANT DROIT'), ('FEU ARRIERE GAUCHE', 'FEU ARRIERE GAUCHE'), ('FEU ARRIERE DROIT', 'FEU ARRIERE DROIT'), ('BALAI ESSUIE GLACE AVANT', 'BALAI ESSUIE GLACE AVANT'), ('RETROVISEUR GAUCHE', 'RETROVISEUR GAUCHE'), ('RETROVISEUR DROIT', 'RETROVISEUR DROIT')], default=1, max_length=50, verbose_name='PIECE RECHANGE CARROSSERIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangedirectionsuspension',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangedirectionsuspension',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangedirectionsuspension',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangedirectionsuspension',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangedirectionsuspension',
            name='type_piece_direction_suspension',
            field=models.CharField(choices=[('ROTULE DE DIRECTION EXTERIEURE GAUCHE', 'ROTULE DE DIRECTION EXTERIEURE GAUCHE'), ('ROTULE DE DIRECTION EXTERIEURE DROIT', 'ROTULE DE DIRECTION EXTERIEURE DROIT'), ('ROTULE DE DIRECTION INFERIEUR GAUCHE', 'ROTULE DE DIRECTION INFERIEUR GAUCHE'), ('ROTULE DE DIRECTION INFERIEUR DROIT', 'ROTULE DE DIRECTION INFERIEUR DROIT'), ('ROTULE DE SUSPENSION INFERIEURE GAUCHE', 'ROTULE DE SUSPENSION INFERIEURE GAUCHE'), ('ROTULE DE SUSPENSION INFERIEURE DROITE', 'ROTULE DE SUSPENSION INFERIEURE DROITE'), ('ROTULE DE SUSPENSION SUPERIEURE GAUCHE', 'ROTULE DE SUSPENSION SUPERIEURE GAUCHE'), ('ROTULE DE SUSPENSION SUPERIEURE DROITE', 'ROTULE DE SUSPENSION SUPERIEURE DROITE'), ('BRAS DE SUSPENSION INFERIEURE GAUCHE', 'BRAS DE SUSPENSION INFERIEURE GAUCHE'), ('BRAS DE SUSPENSION INFERIEURE DROITE', 'BRAS DE SUSPENSION INFERIEURE DROITE'), ('BRAS DE SUSPENSION SUPERIEUR GAUCHE', 'BRAS DE SUSPENSION SUPERIEUR GAUCHE'), ('BRAS DE SUSPENSION SUPERIEUR DROITE', 'BRAS DE SUSPENSION SUPERIEUR DROITE'), ('BIELLETTE STABILISATRICE AVANT GAUCHE', 'BIELLETTE STABILISATRICE AVANT GAUCHE'), ('BIELLETTE STABILISATRICE AVANT DROITE', 'BIELLETTE STABILISATRICE AVANT DROITE'), ('SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1', 'SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1'), ('SILEMBLOC BRAS DE SUSPENSION SUPERIEURE', 'SILEMBLOC BRAS DE SUSPENSION SUPERIEURE'), ('SILEMBLOC BRAS DE STABILISATION AV', 'SILEMBLOC BRAS DE STABILISATION AV'), ('AMORTISSEUR AVANT GAUCHE', 'AMORTISSEUR AVANT GAUCHE'), ('AMORTISSEUR AVANT DROIT', 'AMORTISSEUR AVANT DROIT'), ('AMORTISSEUR ARRIERE GAUCHE', 'AMORTISSEUR ARRIERE GAUCHE'), ('AMORTISSEUR ARRIERE DROIT', 'AMORTISSEUR ARRIERE DROIT'), ('LAME MAITRESSE', 'LAME MAITRESSE'), ('SILEMBLOC LAME INFERIEURE', 'SILEMBLOC LAME INFERIEURE'), ('SILEMBLOC LAME SUPERIEURE', 'SILEMBLOC LAME SUPERIEURE'), ('CREMAILLEUR DE DIRECTION', 'CREMAILLEUR DE DIRECTION'), ('POMPE DE DIRECTION', 'POMPE DE DIRECTION')], default=1, max_length=50, verbose_name='PIECE RECHANGE DIRECTION-SUSPENSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeelectrique',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeelectrique',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeelectrique',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeelectrique',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeelectrique',
            name='type_piece_electrique',
            field=models.CharField(choices=[('DEMARREUR', 'DEMARREUR'), ('ALTERNATEUR', 'ALTERNATEUR'), ('POMPE A VIDE ALTERNATEUR', 'POMPE A VIDE ALTERNATEUR')], default=1, max_length=50, verbose_name='PIECE RECHANGE ELECTRIQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeembrayage',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeembrayage',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeembrayage',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangeembrayage',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangefreinage',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangefreinage',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangefreinage',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangefreinage',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangerefroidissement',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangerefroidissement',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangerefroidissement',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangerefroidissement',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangerefroidissement',
            name='type_piece_refroidissement',
            field=models.CharField(choices=[('POMPE A EAU', 'POMPE A EAU'), ('THERMOSTAT', 'THERMOSTAT'), ('COURROIE ALTERNATEUR', 'COURROIE ALTERNATEUR'), ('RADIATEUR', 'RADIATEUR'), ('BOUCHON RADIATEUR', 'BOUCHON RADIATEUR'), ('ACCOUPLEMENT HYDRAULIQUE', 'ACCOUPLEMENT HYDRAULIQUE'), ('VENTILLATEUR', 'VENTILLATEUR')], default=1, max_length=50, verbose_name='TYPE_PIECE_REFROIDISSEMENT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangetransmission',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangetransmission',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangetransmission',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangetransmission',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecederechangetransmission',
            name='type_piece_transmission',
            field=models.CharField(choices=[('KIT ROULEMENT DE ROUE AVANT DROIT', 'KIT ROULEMENT DE ROUE AVANT DROIT'), ('KIT ROULEMENT DE ROUE AVANT GAUCHE', 'KIT ROULEMENT DE ROUE AVANT GAUCHE'), ('GOUJON DE ROUE AVANT', 'GOUJON DE ROUE AVANT'), ('CROISILLON', 'CROISILLON')], default=1, max_length=50, verbose_name='PIECE RECHANGE TRANSMISSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerechangemoteur',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerechangemoteur',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerechangemoteur',
            name='marque',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('ZOTYE', 'ZOTYE'), ('ZX AUTO', 'ZX AUTO'), ('MAN', 'MAN'), ('IVECO', 'IVECO')], default=1, max_length=100, verbose_name='MARQUE DU VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerechangemoteur',
            name='modele',
            field=models.CharField(choices=[('PATROL V8-SE', 'PATROL V8-SE'), ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'), ('PATROL 10 PLACE ', 'PATROL 10 PLACE '), ('NAVARA PICK UP ', 'NAVARA PICK UP '), ('HARDBODY', 'HARDBODY'), ('URVAN', 'URVAN'), ('CIVILIAN', 'CIVILIAN'), ('QUASHKA', 'QUASHKA'), ('JUKE', 'JUKE'), ('PATHFINDER', 'PATHFINDER'), ('SENTRA', 'SENTRA'), ('ALMERA', 'ALMERA'), ('SUNNY', 'SUNNY'), ('X TRAIL 2X4', 'X TRAIL 2X4'), ('X TRAIL 4X4', 'X TRAIL 4X4'), ('GRANDTIGER PICK UP', 'GRANDTIGER PICK UP'), ('TERRALORD LUXURY', 'TERRALORD LUXURY'), ('Z100', 'Z100'), ('GRAND TIGER SUV', 'GRAND TIGER SUV'), ('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS'), ('LAND CRUISER RUNNER', 'LAND CRUISER RUNNER'), ('LAND CRUISER', 'LAND CRUISER'), ('NOAH', 'NOAH'), ('ALLEX', 'ALLEX'), ('YARIS', 'YARIS'), ('HILUX DOUBLE CABINE', 'HILUX DOUBLE CABINE'), ('COROLLA', 'COROLLA'), ('CAMRY', 'CAMRY'), ('RAV4', 'RAV4'), ('PRADO', 'PRADO'), ('HIACE', 'HIACE')], default=1, max_length=100, verbose_name='MODELE DU VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerevisionmoteur',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE DEBUT FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerevisionmoteur',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default=1, max_length=50, verbose_name='ANNEE FIN FABRICATION VEHICULE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerevisionmoteur',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], default=1, max_length=50, verbose_name='MARQUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecerevisionmoteur',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], default=1, max_length=50, verbose_name='MODELE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ampoule',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('6W', '6W'), ('8W', '8W'), ('12W', '12W'), ('14W', '14W'), ('16W', '16W'), ('20W', '20W'), ('23W', '23W'), ('40W', '40W'), ('45W', '45W'), ('48W', '48W'), ('50W', '50W'), ('65W', '65W'), ('100W', '100W'), ('300W', '300W'), ('400W', '400W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W'), ('4KW', '4KW'), ('5,5KW', '5,5KW'), ('7,5KW', '7,5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('75KW', '75KW'), ('90KW', '90KW'), ('110KW', '110KW'), ('335KW', '335KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='ampoulesolaire',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('5W', '5W'), ('8W', '8W'), ('10W', '10W'), ('14W', '14W'), ('23W', '23W'), ('45W', '45W'), ('50W', '50W'), ('80W', '80W'), ('100W', '100W'), ('150W', '150W'), ('180W', '180W'), ('190W', '190W'), ('250W', '250W'), ('300W', '300W'), ('400W', '400W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=20, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='appareilmesure',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=20, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='batterie',
            name='forme_batterie',
            field=models.CharField(choices=[('N', 'N'), ('NL', 'NL'), ('DIN', 'DIN')], max_length=100, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='capacite',
            field=models.CharField(choices=[('100Ah', '100Ah'), ('102Ah', '102Ah'), ('200Ah', '200Ah'), ('1130Ah', '1130Ah')], max_length=20, verbose_name='CAPACITE(AMPERE-HEURE)'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='duree_vie',
            field=models.CharField(choices=[('5 ANS', '5 ANS'), ('20 ANS', '20 ANS'), ('25 ANS', '25 ANS')], max_length=20, verbose_name='DUREE DE VIE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='garantie',
            field=models.CharField(choices=[('3 ANS', '3 ANS'), ('5 ANS', '5 ANS')], max_length=20, verbose_name='GARANTIE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='tension',
            field=models.CharField(choices=[('2V', '2V'), ('12V', '12V')], max_length=20, verbose_name='TENSION(VOLT)'),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='dimension',
            field=models.CharField(choices=[('80X80MM', '80X80MM'), ('100X100MM', '100X100MM'), ('150X150MM', '150X150MM'), ('200X150MM', '200X150MM')], max_length=20, verbose_name='DIMENSION(MILLIMETRE)'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='quantite',
            field=models.CharField(choices=[('100', '100')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='numero_cartouche',
            field=models.CharField(choices=[('05A', '05A'), ('12A', '12A'), ('15', '15'), ('17A', '17A'), ('21', '21'), ('22', '22'), ('28', '28'), ('29', '29'), ('35A', '35A'), ('36A', '36A'), ('42 A', '42 A'), ('49', '49'), ('49A', '49A'), ('55 A', '55 A'), ('57', '57'), ('60', '60'), ('61', '61'), ('63', '63'), ('63A', '63A'), ('73', '73'), ('78A', '78A'), ('80 A', '80 A'), ('80A', '80A'), ('83 A', '83 A'), ('83A', '83A'), ('88', '88'), ('94', '94'), ('104 S', '104 S'), ('104S', '104S'), ('121', '121'), ('122', '122'), ('123', '123'), ('123A', '123A'), ('126 A', '126 A'), ('126A', '126A'), ('128 A', '128 A'), ('128A', '128A'), ('129', '129'), ('131 A', '131 A'), ('131A', '131A'), ('136', '136'), ('140', '140'), ('141', '141'), ('178', '178'), ('201 A', '201 A'), ('201A', '201A'), ('300', '300'), ('301', '301'), ('304 A', '304 A'), ('305 A', '305 A'), ('305A', '305A'), ('336', '336'), ('364', '364'), ('401A', '401A'), ('563', '563'), ('650', '650'), ('716', '716'), ('725', '725'), ('728', '728'), ('731', '731'), ('920 XL', '920 XL'), ('920', '920'), ('920', '920'), ('932', '932'), ('933 XL', '933 XL'), ('933', '933'), ('940', '940'), ('951', '951'), ('C-EXV14', 'C-EXV14'), ('C-EXV40', 'C-EXV40'), ('CEXV 33', 'CEXV 33'), ('CF 350', 'CF 350'), ('CF 351', 'CF 351'), ('GPR08', 'GPR08'), ('GPR18', 'GPR18'), ('GPR22', 'GPR22'), ('IR 2202-CEXV 42', 'IR 2202-CEXV 42'), ('NPG 32', 'NPG 32'), ('TN 1000', 'TN 1000'), ('TN 2025', 'TN 2025'), ('TN 2060', 'TN 2060'), ('TN 2130', 'TN 2130'), ('TN 2260', 'TN 2260'), ('TN 2280', 'TN 2280'), ('TN 240BK', 'TN 240BK'), ('TN 240C', 'TN 240C'), ('TN 240M', 'TN 240M'), ('TN 240Y', 'TN 240Y'), ('TN 261BK', 'TN 261BK'), ('TN 261C', 'TN 261C'), ('TN 261M', 'TN 261M'), ('TN 261Y', 'TN 261Y'), ('TN 3185', 'TN 3185'), ('TN 3250', 'TN 3250'), ('TN 3290', 'TN 3290'), ('TN 3320', 'TN 3320'), ('TN-260', 'TN-260')], max_length=50, verbose_name='NUMERO DE CARTOUCHE'),
        ),
        migrations.AlterField(
            model_name='coffretjeubarre',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='puissance',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='PUISSANCE(KILOWATT)'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='TENSION(VOLT)'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='mode_fonctionnement',
            field=models.CharField(choices=[('CODE', 'CODE'), ('BADGE', 'BADGE'), ('EMPREINTE DIGITALE', 'EMPREINTE DIGITALE'), ('BADGE + EMPREINTE DIGITALE', 'BADGE + EMPREINTE DIGITALE')], max_length=50, verbose_name='MODE DE FONCTIONNEMENT'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='duree_vie',
            field=models.CharField(choices=[('5 ANS', '5 ANS'), ('20 ANS', '20 ANS'), ('25 ANS', '25 ANS')], max_length=20, verbose_name='DUREE DE VIE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='garantie',
            field=models.CharField(choices=[('3 ANS', '3 ANS'), ('5 ANS', '5 ANS')], max_length=20, verbose_name='GARANTIE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='puissance_convertisseur',
            field=models.CharField(choices=[('300W', '300W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W')], max_length=20, verbose_name='PUISSANCE CONVERTISSEUR(WATT)'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='tension_convertisseur',
            field=models.CharField(choices=[('2V', '2V'), ('12V', '12V'), ('12/24V', '12/24V'), ('24V', '24V'), ('48V', '48V')], max_length=20, verbose_name='TENSION CONVERTISSEUR(VOLT)'),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='intensite',
            field=models.CharField(choices=[('6-10A', '6-10A'), ('13-17A', '13-17A'), ('17-23A', '17-23A')], max_length=50, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='gravure',
            name='support_gravure',
            field=models.CharField(choices=[('VERRE', 'VERRE'), ('CRISTAL', 'CRISTAL'), ('BOIS', 'BOIS'), ('PLEXIGLAS', 'PLEXIGLAS')], max_length=50, verbose_name='SUPPORT DE GRAVURE'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='TENSION(VOLT)'),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='intensite',
            field=models.CharField(choices=[('63A', '63A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A')], max_length=50, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='duree_vie',
            field=models.CharField(choices=[('5 ANS', '5 ANS'), ('20 ANS', '20 ANS'), ('25 ANS', '25 ANS')], max_length=20, verbose_name='DUREE DE VIE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='garantie',
            field=models.CharField(choices=[('3 ANS', '3 ANS'), ('5 ANS', '5 ANS')], max_length=20, verbose_name='GARANTIE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('5W', '5W'), ('8W', '8W'), ('10W', '10W'), ('14W', '14W'), ('23W', '23W'), ('45W', '45W'), ('50W', '50W'), ('80W', '80W'), ('100W', '100W'), ('150W', '150W'), ('180W', '180W'), ('190W', '190W'), ('250W', '250W'), ('300W', '300W'), ('400W', '400W')], max_length=20, verbose_name='PUISSANCE(WATT)'),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='pieces_rechange_embrayage',
            field=models.CharField(choices=[('DISQUE EMBRAYAGE', 'DISQUE EMBRAYAGE'), ('PLATEAU EMBRAYAGE', 'PLATEAU EMBRAYAGE'), ('BUTEE EMBRAYAGE', 'BUTEE EMBRAYAGE'), ('CYLINDRE RECEPTEUR', 'CYLINDRE RECEPTEUR')], max_length=50, verbose_name='PIECE RECHANGE EMBRAYAGE'),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='pieces_rechange_freinage',
            field=models.CharField(choices=[('PLAQUETTE DE FREIN AVANT', 'PLAQUETTE DE FREIN AVANT'), ('PLAQUETTE/MACHOIRE DE FREIN ARRIERE', 'PLAQUETTE/MACHOIRE DE FREIN ARRIERE'), ('DISQUE DE FREIN AVANT', 'DISQUE DE FREIN AVANT'), ('DISQUE/TAMBOUR DE FREIN ARRIERE', 'DISQUE/TAMBOUR DE FREIN ARRIERE'), ('CYLINDRE DE ROUE ARRIERE DROITE', 'CYLINDRE DE ROUE ARRIERE DROITE'), ('CYLINDRE DE ROUE ARRIERE GAUCHE', 'CYLINDRE DE ROUE ARRIERE GAUCHE'), ('MAITRE CYLINDRE DE FREIN', 'MAITRE CYLINDRE DE FREIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='pieces_rechange_moteur',
            field=models.CharField(choices=[('FILTRE A HUILE', 'FILTRE A HUILE'), ('FILTRE A AIR', 'FILTRE A AIR'), ('FILTRE A CARBURANT', 'FILTRE A CARBURANT'), ('FILTRE HABITACLE', 'FILTRE HABITACLE'), ('BOUGIE', 'BOUGIE'), ('COURROIE DIRECTION', 'COURROIE DIRECTION'), ('POMPE A HUILE', 'POMPE A HUILE'), ('TURBO COMPRESSEUR', 'TURBO COMPRESSEUR'), ('SUPPORT MOTEUR', 'SUPPORT MOTEUR')], max_length=50, verbose_name='PIECE RECHANGE MOTEUR'),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='pieces_revision_moteur',
            field=models.CharField(choices=[('POCHETTE DE JOINT', 'POCHETTE DE JOINT'), ('JOINT DE CULASSE', 'JOINT DE CULASSE'), ('SEGMENTS', 'SEGMENTS'), ('COUSSINET PALIER', 'COUSSINET PALIER'), ('COUSSINET BIELLE', 'COUSSINET BIELLE'), ('BOURRAGE MOTEUR ', 'BOURRAGE MOTEUR '), ('CHEMISE(JEU DE 4 PCES)', 'CHEMISE(JEU DE 4 PCES)'), ('PISTON(SANS SEGMENT)', 'PISTON(SANS SEGMENT)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plafonnierled',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('6W', '6W'), ('8W', '8W'), ('12W', '12W'), ('14W', '14W'), ('16W', '16W'), ('20W', '20W'), ('23W', '23W'), ('40W', '40W'), ('45W', '45W'), ('48W', '48W'), ('50W', '50W'), ('65W', '65W'), ('100W', '100W'), ('300W', '300W'), ('400W', '400W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W'), ('4KW', '4KW'), ('5,5KW', '5,5KW'), ('7,5KW', '7,5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('75KW', '75KW'), ('90KW', '90KW'), ('110KW', '110KW'), ('335KW', '335KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='plafonnierled',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=20, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='projecteur',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('6W', '6W'), ('8W', '8W'), ('12W', '12W'), ('14W', '14W'), ('16W', '16W'), ('20W', '20W'), ('23W', '23W'), ('40W', '40W'), ('45W', '45W'), ('48W', '48W'), ('50W', '50W'), ('65W', '65W'), ('100W', '100W'), ('300W', '300W'), ('400W', '400W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W'), ('4KW', '4KW'), ('5,5KW', '5,5KW'), ('7,5KW', '7,5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('75KW', '75KW'), ('90KW', '90KW'), ('110KW', '110KW'), ('335KW', '335KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='reglette',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('6W', '6W'), ('8W', '8W'), ('12W', '12W'), ('14W', '14W'), ('16W', '16W'), ('20W', '20W'), ('23W', '23W'), ('40W', '40W'), ('45W', '45W'), ('48W', '48W'), ('50W', '50W'), ('65W', '65W'), ('100W', '100W'), ('300W', '300W'), ('400W', '400W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W'), ('4KW', '4KW'), ('5,5KW', '5,5KW'), ('7,5KW', '7,5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('75KW', '75KW'), ('90KW', '90KW'), ('110KW', '110KW'), ('335KW', '335KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='intensite',
            field=models.CharField(choices=[('9A', '9A'), ('12A', '12A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('30A', '30A'), ('40A', '40A'), ('45A', '45A'), ('50A', '50A'), ('60A', '60A'), ('63A', '63A'), ('64A', '64A'), ('80A', '80A'), ('85A', '85A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE(AMPERE)'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('6W', '6W'), ('8W', '8W'), ('12W', '12W'), ('14W', '14W'), ('16W', '16W'), ('20W', '20W'), ('23W', '23W'), ('40W', '40W'), ('45W', '45W'), ('48W', '48W'), ('50W', '50W'), ('65W', '65W'), ('100W', '100W'), ('300W', '300W'), ('400W', '400W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W'), ('4KW', '4KW'), ('5,5KW', '5,5KW'), ('7,5KW', '7,5KW'), ('11KW', '11KW'), ('55KW', '55KW'), ('75KW', '75KW'), ('90KW', '90KW'), ('110KW', '110KW'), ('335KW', '335KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
    ]
