# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0178_produitpharmaceutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpharmaceutique',
            name='produit',
            field=models.CharField(choices=[('250MG', '250MG'), ('500MG', '500MG'), ('10MG', '10MG'), ('50G', '50G'), ('100MG', '100MG'), ('60ML', '60ML'), ('10ML', '10ML'), ('10G', '10G'), ('5MG/2MG/8MG', '5MG/2MG/8MG'), ('100ML', '100ML'), ('400MG', '400MG')], default=1, max_length=50, verbose_name='PRODUIT'),
            preserve_default=False,
        ),
    ]
