# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0180_auto_20180416_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='classe_therapeutique',
            field=models.CharField(choices=[('ANTIHELMINTHIQUES', 'ANTIHELMINTHIQUES'), ('INFECTIOLOGIE', 'INFECTIOLOGIE'), ('ANTI-INFLAMMATOIRE ET ANTALGIQUES', 'ANTI-INFLAMMATOIRE ET ANTALGIQUES'), ('ANTISPASMODIQUE ET ANTIFLATULENCE', 'ANTISPASMODIQUE ET ANTIFLATULENCE'), ('GASTRO-ENTEROLOGIE', 'GASTRO-ENTEROLOGIE'), ('DERMATOLOGIE', 'DERMATOLOGIE'), ('BRONCHOPNEUMONIE', 'BRONCHOPNEUMONIE'), ('ALLERGOLIGIE', 'ALLERGOLIGIE')], max_length=50, verbose_name='CLASSE THERAPEUTIQUE'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='dosage',
            field=models.CharField(choices=[('250MG', '250MG'), ('500MG', '500MG'), ('10MG', '10MG'), ('50G', '50G'), ('100MG', '100MG'), ('60ML', '60ML'), ('10ML', '10ML'), ('10G', '10G'), ('20MG', '20MG'), ('5MG/2MG/8MG', '5MG/2MG/8MG'), ('100ML', '100ML'), ('400MG', '400MG')], max_length=50, verbose_name='DOSAGE'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='presentation',
            field=models.CharField(choices=[('COMPRIME', 'COMPRIME'), ('CREME ANTI-INFLAMMATOIRE', 'CREME ANTI-INFLAMMATOIRE'), ('SUSPENSION LIQUIDE', 'SUSPENSION LIQUIDE'), ('GOUTTES', 'GOUTTES'), ('AMPOULE', 'AMPOULE'), ('GELULES', 'GELULES'), ('CREME DERMIQUE', 'CREME DERMIQUE'), ('SIROP', 'SIROP')], max_length=50, verbose_name='PRESENTATION'),
        ),
    ]
