# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0182_auto_20180417_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
