# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0183_auto_20180417_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='marque',
            field=models.CharField(choices=[('ISUZU', 'ISUZU'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='modele',
            field=models.CharField(choices=[('D-MAX TFR54', 'D-MAX TFR54'), ('D-MAX TFR85', 'D-MAX TFR85'), ('L300', 'L300'), ('PATROL Y61', 'PATROL Y61'), ('HILUX', 'HILUX'), ('LAND CRUISER PRADO', 'LAND CRUISER PRADO')], max_length=50, verbose_name='MODELE'),
        ),
    ]
