# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0184_auto_20180417_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
