# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0188_auto_20180418_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbatiment',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
