# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0189_auto_20180418_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbatiment',
            name='nombre_d_etages',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, verbose_name="NOMBRE D'ETAGE"),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='nombre_de_pieces',
            field=models.CharField(choices=[('1 -10', '1 -10'), ('11 - 20', '11 - 20'), ('21 - 30', '21 - 30'), ('31 - 40', '31 - 40'), ('41 - 50', '41 - 50'), ('51 - 60', '51 - 60'), ('61 - 70', '61 - 70'), ('71 - 80', '71 - 80'), ('81 - 90', '81 - 90'), ('91 -100', '91 -100'), ('1 -10', '1 -10')], max_length=50, verbose_name='NOMBRE DE PIECES'),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='qualite_du_terrain',
            field=models.CharField(choices=[('SABLONEUX', 'SABLONEUX'), ('ARGILEUX', 'ARGILEUX'), ('MARECAGEUX', 'MARECAGEUX'), ('ALCALINO-TERREUX', 'ALCALINO-TERREUX')], max_length=50, verbose_name='QUALITE DU TERRAIN'),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='type_de_terrain',
            field=models.CharField(choices=[('TERRAIN PLAT', 'TERRAIN PLAT'), ('TERRAIN INCLINÉ', 'TERRAIN INCLINÉ')], max_length=50, verbose_name='TYPE DE TERRAIN'),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='usage_du_batiment',
            field=models.CharField(choices=[('ENTREPOT', 'ENTREPOT'), ('COMMERCIAL ORDINAIRE', 'COMMERCIAL ORDINAIRE'), ('COMMERCIAL LUXUEUX', 'COMMERCIAL LUXUEUX'), ('RESIDENTIEL ORDINAIRE', 'RESIDENTIEL ORDINAIRE'), ('RESIDENTIEL LUXUEUX', 'RESIDENTIEL LUXUEUX')], max_length=50, verbose_name='USAGE DU BATIMENT'),
        ),
    ]
