# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0192_auto_20180418_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionroute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='constructionroute',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='ConstructionRoute',
        ),
    ]
