# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0194_auto_20180418_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ramepapier',
            name='format',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='rollup',
            name='dimension',
            field=models.CharField(choices=[('200CMX80CM', '200cmX80CM'), ('180CMX80CM', '180CMX80CM'), ('10cmX15CM', '10cmX15CM'), ('85X200CM', '85X200CM')], max_length=50, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='xstand',
            name='dimensions',
            field=models.CharField(choices=[('200CMX80CM', '200cmX80CM'), ('180CMX80CM', '180CMX80CM'), ('10cmX15CM', '10cmX15CM'), ('85X200CM', '85X200CM')], max_length=50, verbose_name='DIMENSION'),
        ),
    ]
