# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0197_poisson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poisson',
            name='type_de_poisson',
            field=models.CharField(choices=[('CAPITAINE', 'CAPITAINE'), ('MBOTO', 'MBOTO'), ('MUNGUSU', 'MUNGUSU'), ('MOJOMBO', 'MOJOMBO'), ('MINZANDA', 'MINZANDA'), ('NGOLO', 'NGOLO'), ('MGOMGO', 'MGOMGO')], max_length=50, verbose_name='TYPE POISSON'),
        ),
    ]
