# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0203_auto_20180423_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoicolisnational0a20kgs',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='envoicolisnational100kgsetplus',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='envoicolisnational20kgsa99kgs',
            name='zone',
        ),
    ]
