# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0207_auto_20180424_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxde10kg',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PRIX'),
        ),
    ]
