# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0213_auto_20180426_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poulet',
            old_name='type_de_morceau',
            new_name='type_de_poulet',
        ),
        migrations.AlterField(
            model_name='legume',
            name='type_legume',
            field=models.CharField(choices=[('ARTICHAUX DU KIVU', 'ARTICHAUX DU KIVU'), ('AUBERGINE', 'AUBERGINE'), ('AVOCAT', 'AUBERGINE'), ('BETTERAVE DU KIVU', 'BETTERAVE DU KIVU'), ('BROCOLIS', 'BROCOLIS'), ('CAROTTE', 'CAROTTE'), ('CAROTTE (GOMA)', 'CAROTTE (GOMA)'), ('CELERI', 'CELERI'), ('CHOUX FLEUR DU KIVU', 'CHOUX FLEUR DU KIVU'), ('CHOUX POMME', 'CHOUX POMME'), ('CONCOMBRE', 'CONCOMBRE'), ('COURGE', 'COURGE'), ('COURGETTES', 'COURGETTES'), ('EPINARD', 'EPINARD'), ('HARICOT', 'HARICOT'), ('HARICOT GOMA 1ER CHOIX', 'HARICOT GOMA 1ER CHOIX'), ('HARICO PRINCESSE', 'HARICO PRINCESSE'), ('LAITUE', 'LAITUE'), ('NAVET', 'NAVET'), ('OIGNON BLANC', 'OIGNON BLANC'), ('OIGNON BLANC (GOMA)', 'OIGNON BLANC (GOMA)'), ('OIGNON ROUGE', 'OIGNON ROUGE'), ('OIGNON ROUGE(GOMA)', 'OIGNON ROUGE(GOMA)'), ('PATATE DOUCE', 'PATATE DOUCE'), ('PETITS POIDS DU KIVU', 'PETITS POIDS DU KIVU'), ('POIVRON VERT', 'POIVRON VERT'), ('POMME DE TERRE(RSA) ', 'POMME DE TERRE(RSA)'), ('POMME DE TERRE(GOMA) ', 'POMME DE TERRE(GOMA) '), ('POMME DE TERRE(LOCAL) ', 'POMME DE TERRE(LOCAL)'), ('RADIS DU KIVU', 'RADIS DU KIVU'), ('RHUBARBE DU KIVU', 'RHUBARBE DU KIVU'), ('TOMATE', 'TOMATE'), ('GOMBO', 'GOMBO'), ('HARICOT (GOMA)', 'HARICOT (GOMA)')], max_length=50, verbose_name='TYPE LEGUME'),
        ),
    ]
