# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0215_auto_20180426_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebureau',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tablebureau',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='model_bureau',
        ),
        migrations.AddField(
            model_name='bureau',
            name='forme',
            field=models.CharField(choices=[('RECTANGULAIRE', 'RECTANGULAIRE'), ('OVALE', 'OVALE')], default=1, max_length=20, verbose_name='FORME'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boitedarchive',
            name='dimension_boite',
            field=models.CharField(blank=True, choices=[('80MM', '80MM'), ('100MM', '100MM'), ('150MM', '150MM')], max_length=100, null=True, verbose_name='DIMENSION BOITE'),
        ),
        migrations.AlterField(
            model_name='boitedarchive',
            name='type_boite',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('CONTAINER', 'CONTAINER')], max_length=100, verbose_name='TYPE DE BOITE'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='type_bureau',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DIRECTION', 'DIRECTION')], max_length=20, verbose_name='TYPE DE BUREAU'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_lit',
            field=models.CharField(choices=[('LIT SIMPLE', 'LIT SIMPLE'), ('LIT DOUBLE', 'LIT DOUBLE')], max_length=20, verbose_name='TYPE DE LIT'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='type_envoie',
            field=models.CharField(choices=[('COLIS', 'COLIS'), ('COURRIER', 'COURRIER'), ('courrier', 'courrier')], max_length=20, verbose_name="TYPE D'ENVOIE"),
        ),
        migrations.AlterField(
            model_name='envoicolisinternationalplus70kg',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational0a20kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational100kgsetplus',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational20kgsa99kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='type_envoie',
            field=models.CharField(choices=[('COLIS', 'COLIS'), ('COURRIER', 'COURRIER'), ('courrier', 'courrier')], max_length=20, verbose_name="TYPE D'ENVOIE"),
        ),
        migrations.DeleteModel(
            name='TableBureau',
        ),
    ]
