# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0216_auto_20180426_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacuationvidangepoubelles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='evacuationvidangepoubelles',
            name='vendeur',
        ),
        migrations.AlterField(
            model_name='armoire',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('140CM', '140CM'), ('160CM', '160CM'), ('180CM', '180CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=50, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='forme',
            field=models.CharField(choices=[('RECTANGULAIRE', 'RECTANGULAIRE'), ('OVALE', 'OVALE'), ('EN L', 'EN L')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('140CM', '140CM'), ('160CM', '160CM'), ('180CM', '180CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('140CM', '140CM'), ('160CM', '160CM'), ('180CM', '180CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='forme',
            field=models.CharField(choices=[('RECTANGULAIRE', 'RECTANGULAIRE'), ('OVALE', 'OVALE'), ('EN L', 'EN L')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM'), ('92CM', '92CM'), ('91CM', '91CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('140CM', '140CM'), ('160CM', '160CM'), ('180CM', '180CM'), ('120CM', '120CM'), ('150CM', '150CM'), ('170CM', '170CM'), ('1.40 MTR', '1.40 MTR'), ('1.60 MTR', '1.60 MTR'), ('1.80 MTR', '1.80 MTR'), ('1.20 MTR', '1.20 MTR'), ('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.DeleteModel(
            name='EvacuationVidangePoubelles',
        ),
    ]
