# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0218_auto_20180430_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charcuterie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='charcuterie',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='condiment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='condiment',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='conditionnementproduit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='conditionnementproduit',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='veau',
            name='category',
        ),
        migrations.RemoveField(
            model_name='veau',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='Charcuterie',
        ),
        migrations.DeleteModel(
            name='Condiment',
        ),
        migrations.DeleteModel(
            name='ConditionnementProduit',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Veau',
        ),
    ]
