# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0219_auto_20180430_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenettoyage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicenettoyage',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='servicetraiteur',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicetraiteur',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='siegeetfauteuildebureau',
            name='category',
        ),
        migrations.RemoveField(
            model_name='siegeetfauteuildebureau',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='ServiceNettoyage',
        ),
        migrations.DeleteModel(
            name='ServiceTraiteur',
        ),
        migrations.DeleteModel(
            name='ShoppingBag',
        ),
        migrations.DeleteModel(
            name='SiegeEtFauteuilDeBureau',
        ),
    ]
