# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0221_auto_20180502_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableinformatique',
            name='longueur',
            field=models.CharField(choices=[('2M', '2M'), ('5M', '5M'), ('10M', '10M'), ('20M', '20M'), ('100M', '100M'), ('300M', '300M'), ('305M', '305M'), ('30CM', '30CM')], max_length=50, verbose_name='LONGUEUR CABLE(METRE)'),
        ),
    ]
