# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0224_auto_20180502_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citerne',
            name='capacite',
            field=models.CharField(choices=[('100L', '100L'), ('150L', '150L'), ('200L', '200L'), ('300L', '300L'), ('500L', '500L'), ('1000L', '1000L'), ('2000L', '2000L'), ('3000L', '3000L'), ('5000L', '5000L'), ('10000L', '10000L')], max_length=20, verbose_name='CAPACITE(LITRE)'),
        ),
    ]
