# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0228_auto_20180502_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fretroutier',
            name='capacite_max',
            field=models.CharField(choices=[('20T', '20T')], max_length=20, verbose_name='CAPACITÉ MAXIMUM(TONNES)'),
        ),
    ]
