# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0229_auto_20180502_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('60X60X25MM', '60X60X25MM'), ('65X65X45MM', '65X65X45MM'), ('80X80X30MM', '80X80X30MM'), ('105X105X42MM', '105X105X42MM'), ('130X130X30MM', '130X130X30MM'), ('160X100X45MM', '160X100X45MM'), ('220X160X45MM', '220X160X45MM'), ('105X105X55MM', '105X105X55MM'), ('175X150X80MM', '175X150X80MM'), ('225X175X100MM', '225X175X100MM'), ('275X225X120MM', '275X225X120MM')], max_length=20, verbose_name='DIMENSION(MILLIMETRES)'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE '),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='interrupteur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='marque',
            field=models.CharField(choices=[('SCHNEIDER', 'SCHNEIDER'), ('APC', 'APC'), ('MACKEL', 'MACKEL'), ('VINCKIER', 'VINCKIER'), ('ABB', 'ABB'), ('WESTECH', 'WESTECH'), ('VICTRON', 'VICTRON'), ('MERCURY', 'MERCURY'), ('VICKO', 'VICKO'), ('LE GRAND', 'LE GRAND'), ('NIKO', 'NIKO'), ('INGELEC', 'INGELEC'), ('TANAKA', 'TANAKA'), ('EUROMAX', 'EUROMAX')], max_length=20, verbose_name='MARQUE'),
        ),
    ]
