# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0237_auto_20180502_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palan',
            name='longueur',
            field=models.CharField(choices=[('10M', '10M')], max_length=100, verbose_name='LONGUEUR(METRE)'),
        ),
    ]
