# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0239_booster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compresseur',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='compresseur',
            name='pression',
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='capacite_compresseur',
            field=models.CharField(choices=[('100L', '100L'), ('150L', '150L'), ('200L', '200L'), ('300L', '300L'), ('500L', '500L'), ('1000L', '1000L')], max_length=20, verbose_name='CAPACITE (LITRE)'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='puissance_compresseur',
            field=models.CharField(choices=[('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('5,5 HP', '5,5 HP'), ('6,5 HP', '6,5 HP'), ('7,5 HP', '7,5 HP'), ('10 HP', '10 HP')], max_length=20, verbose_name='PUISSANCE (WATT)'),
        ),
    ]
