# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0241_auto_20180503_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compresseur',
            name='puissance_compresseur',
            field=models.CharField(choices=[('1100W', '1100W'), ('1125W', '1125W'), ('1500W', '1500W'), ('1875W', '1875W'), ('1800W', '1800W'), ('2200W', '2200W'), ('3000W', '3000W')], max_length=20, verbose_name='PUISSANCE (WATT)'),
        ),
    ]
