# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0244_auto_20180503_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupCarrelage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('EINHELL', 'EINHELL')], max_length=100, verbose_name='MARQUE')),
                ('puissance', models.CharField(choices=[('900W', '900W'), ('600W', '600W'), ('800W', '800W'), ('2200W', '2200W')], max_length=100, verbose_name='PUISSANCE (WATT)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('EUROS', 'EUROS'), ('USD/JOUR', 'USD/JOUR'), ('USD/PAGE', 'USD/PAGE'), ('USD/M2', 'USD/M2'), ('USD/MOIS', 'USD/MOIS'), ('USD/PIECE', 'USD/PIECE'), ('USD', 'USD'), ('USD/M', 'USD/M'), ('USD/KG', 'USD/KG'), ('USD/PERSONNE', 'USD/PERSONNE'), ('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS'), ('USD/LITRE', 'USD/LITRE'), ('USD/SPLIT', 'USD/SPLIT'), ('%', '%'), ('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE'), ('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES'), ('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR'), ('USD/THEME', 'USD/THEME'), ('USD/KG', 'USD/KG'), ('USD/AN', 'USD/AN'), ('USD/HEURE', 'USD/HEURE'), ('USD/MODULE', 'USD/MODULE'), ('USD/KG OU L', 'USD/KG OU L'), ('% DU DEVIS', '% DU DEVIS'), ('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS'), ('USD/TONNE', 'USD/TONNE'), ('USD/SECONDE', 'USD/SECONDE'), ('USD/M²', 'USD/M²'), ('USD/BOITE', 'USD/BOITE'), ('USD/PAQUET', 'USD/PAQUET'), ('USD/JEU', 'USD/JEU'), ('USD/CONTENANT', 'USD/CONTENANT'), ('USD/CARNET', 'USD/CARNET'), ('$/M2', '$/M2'), ('$/KM', '$/KM'), ('USD/COMMUNIQUE', 'USD/COMMUNIQUE'), ('USD/PCE', 'USD/PCE'), ('US/JOUR', 'US/JOUR'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='nombre_phase',
            field=models.CharField(choices=[('2P', '2P'), ('3P', '3P'), ('4P', '4P')], max_length=50, verbose_name='NOMBRE DE PHASE'),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='nombre_pole',
            field=models.CharField(choices=[('2P', '2P'), ('3P', '3P'), ('4P', '4P')], max_length=20, verbose_name='NOMBRE DE POLE'),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='puissance_moteur',
            field=models.CharField(choices=[('180W', '180W'), ('250W', '250W'), ('370W', '370W'), ('550W', '550W'), ('750W', '750W'), ('1.1KW', '1.1KW'), ('1.5KW', '1.5KW'), ('2.2KW', '2.2KW'), ('3KW', '3KW'), ('4KW', '4KW'), ('7.5KW', '7.5KW'), ('11KW', '11KW'), ('15KW', '15KW'), ('18.5KW', '18.5KW'), ('75KW', '75KW'), ('45KW', '45KW'), ('5.5KW', '5.5KW'), ('37KW', '37KW')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name='CHOIX AMUSE GUEULE'),
        ),
    ]
