# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0247_decapeuthermique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecapeuThermique',
            new_name='DecapeurThermique',
        ),
    ]
