# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0264_charniere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rivet',
            old_name='dimension_en_mm',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='tente',
            old_name='dimension_metre_x_metre',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='treillis',
            old_name='dimension_metre_x_metre',
            new_name='dimension',
        ),
    ]
