# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0272_balastre'),
    ]

    operations = [
        migrations.AddField(
            model_name='balastre',
            name='marque',
            field=models.CharField(choices=[('PHILIPS', 'PHILIPS')], default=1, max_length=100, verbose_name='MARQUE DE BALASTRE'),
            preserve_default=False,
        ),
    ]
