# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0278_auto_20180504_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandedesignalisation',
            name='longueur',
            field=models.CharField(choices=[('500', '500')], max_length=100, verbose_name='LONGUEUR EN METTRE'),
        ),
    ]
