# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0280_filbarbele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupcarrelage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupcarrelage',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='CoupCarrelage',
        ),
    ]
