# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0281_auto_20180505_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScieACloche',
            new_name='ScieCloche',
        ),
    ]
