# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0282_auto_20180505_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinche',
            name='taille_clinche',
            field=models.CharField(choices=[('GRANDE', 'GRANDE'), ('PETITE', 'PETITE')], max_length=100, verbose_name='TAILLE DE LA CLINCHE'),
        ),
    ]
