# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0283_auto_20180505_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantoire',
            new_name='Plantoir',
        ),
    ]
