# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0297_remove_xstand_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffet',
            name='sur_place',
        ),
        migrations.AddField(
            model_name='buffet',
            name='lieu',
            field=models.CharField(blank=True, choices=[('SUR PLACE', 'SUR PLACE'), ('A CONVENIR', 'A CONVENIR')], max_length=20, null=True, verbose_name='LIEU'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='sur_place',
            field=models.CharField(blank=True, choices=[('SUR PLACE', 'SUR PLACE'), ('A CONVENIR', 'A CONVENIR')], max_length=20, null=True, verbose_name='LIEU'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='sur_place',
            field=models.CharField(blank=True, choices=[('SUR PLACE', 'SUR PLACE'), ('A CONVENIR', 'A CONVENIR')], max_length=20, null=True, verbose_name='LIEU'),
        ),
    ]
