# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0300_auto_20180510_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktails',
            name='choix_boisson_froide',
        ),
        migrations.AddField(
            model_name='cocktails',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=20, verbose_name='CHOIX DE BOISSON NON ALCOOLISÉE'),
            preserve_default=False,
        ),
    ]
