# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0315_brandingvehiculefull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingvehiculefull',
            name='quantite',
        ),
    ]
