# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0319_boxlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocollantvinyleadhesif',
            name='quantite',
            field=models.CharField(choices=[('1-500M2', '1-500M2'), ('501-1000M2', '501-1000M2'), ('1001-2000M2', '1001-2000M2'), ('2000M2<', '2000M2<')], default=1, max_length=50, verbose_name='TYPE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000')], max_length=50),
        ),
    ]
