# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0320_auto_20180511_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='backdrops',
            name='quantite',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101<', '101<')], default=1, max_length=50, verbose_name='QUANTITE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='dimension',
            field=models.CharField(choices=[('2,25Mx2,25M', '2,25Mx2,25M'), ('4,6Mx2,25M', '4,6Mx2,25M')], max_length=50, verbose_name='DIMENSION'),
        ),
    ]
