# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0321_auto_20180511_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='quantite',
            field=models.CharField(choices=[('1-1000', '1-1000'), ('1001-5000', '1001-5000'), ('10001-20000', '10001-20000'), ('20000<', '20000<')], default=1, max_length=50, verbose_name='QUANTITE DE CALENDRIER'),
            preserve_default=False,
        ),
    ]
