# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0323_auto_20180511_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressionbanderole',
            name='quantite',
            field=models.CharField(choices=[('1-500M2', '1-500M2'), ('501-1000M2', '501-1000M2'), ('1001-2000M2', '1001-2000M2'), ('2001M2<', '2001M2<')], default=1, max_length=50, verbose_name='TYPE SUPPORT'),
            preserve_default=False,
        ),
    ]
