# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0326_auto_20180511_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollup',
            name='quantite',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101<', '101<')], default=1, max_length=50, verbose_name='DIMENSION'),
            preserve_default=False,
        ),
    ]
