# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0327_rollup_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sachet',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10001<', '10001<')], max_length=50, verbose_name='QUANTITÉ'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000'), ('100000<', '100000<')], max_length=50),
        ),
    ]
