# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0328_auto_20180511_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000'), ('10000<', '10000<')], max_length=50),
        ),
    ]
