# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0329_auto_20180511_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000'), ('1-500', '1-500')], max_length=50),
        ),
    ]
