# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0336_auto_20180515_1045'),
    ]

    operations = [

        migrations.AlterField(
            model_name='autocollant',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2'), ('USD/M²', 'USD/M²'), ('$/M2', '$/M2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bacacourrier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='baguette',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='balastre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bandeadhesive',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bandedefilante',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR'), ('US/JOUR', 'US/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bandedesignalisation',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='units',
            field=models.CharField(choices=[('USD/MOIS', 'USD/MOIS')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='batondecolle',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='batterie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='betonniere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='blocnoteligne',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='blocnotememo',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='boeuf',
            name='units',
            field=models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='boitedarchive',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booster',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='botte',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bougie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='units',
            field=models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bouturemanioc',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='boxlight',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='brandingvehiculefull',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2'), ('USD/M²', 'USD/M²'), ('$/M2', '$/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='brique',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='broderieecussons',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name='CHOIX ENTRÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_legumes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DE LEGUMES'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_plats',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('8', '8')], max_length=20, verbose_name='CHOIX DU PLATS'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cablederemorquage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cableenacier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cableinformatique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cablemasse',
            name='units',
            field=models.CharField(choices=[('USD/M', 'USD/M')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cablesouple',
            name='units',
            field=models.CharField(choices=[('USD/M', 'USD/M')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cachet',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cachetdateur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cahier',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cahiercharges',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='calculatrice',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR'), ('US/JOUR', 'US/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnetderecu',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='carreau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chaisebureau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chaisesalleattente',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='charniere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chemise',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chevre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ciseau',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='citerne',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='classeur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cleallen',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clinche',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='clous',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='coffretdeclecomplet',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='coffretjeubarre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='colleliquide',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='combinaison',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='communicationdemasse',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='communicationgraphique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='communique',
            name='units',
            field=models.CharField(choices=[('USD/COMMUNIQUE', 'USD/COMMUNIQUE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='compacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='conceptiongraphique',
            name='units',
            field=models.CharField(choices=[('USD/THEME', 'USD/THEME')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='conceptionpagemagazine',
            name='units',
            field=models.CharField(choices=[('USD/PAGE', 'USD/PAGE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2'), ('USD/M²', 'USD/M²'), ('$/M2', '$/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='constructionroute',
            name='units',
            field=models.CharField(choices=[('USD/KM', 'USD/KM')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='consultancedecoration',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='correcteurliquide',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cossebatterie',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cossettemanioc',
            name='units',
            field=models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coupecarreau',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='couphaieelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='courslangueetrangere',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='courslanguenationale',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='couverturephoto',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='creationsiteweb',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cyclometre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='damesauteuse',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='debrousailleuse',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='decapeurthermique',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='decorationamenagement',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='decorationsurface',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2'), ('USD/M²', 'USD/M²'), ('$/M2', '$/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='dedouanement',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),

    ]
