# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0338_auto_20180515_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramepapier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ramepapier',
            name='vendeur',
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='quantite',
            field=models.CharField(choices=[('1-500M2', '1-500M2'), ('501-1000M2', '501-1000M2'), ('1001-2000M2', '1001-2000M2'), ('2000M2<', '2000M2<'), ('0-500M2', '0-500M2')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='dimension',
            field=models.CharField(choices=[('2,25Mx2,25M', '2,25Mx2,25M'), ('4,6Mx2,25M', '4,6Mx2,25M'), ('3,2X3,29M', '3,2X3,29M'), ('3X3M', '3X3M')], max_length=50, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='quantite',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101<', '101<'), ('1-19', '1-19'), ('20-49', '20-49'), ('50-99', '50-99'), ('100<', '100<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),

        migrations.AlterField(
            model_name='boxlight',
            name='quantite',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('1-19', '1-19'), ('20-49', '20-49'), ('50-99', '50-99'), ('100<', '100<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10000<', '10000<')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chemise',
            name='quantite',
            field=models.CharField(choices=[('1-2000', '1-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10000<', '10000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='combinaison',
            name='quantite',
            field=models.CharField(choices=[('1-2000', '1-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10000<', '10000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='courslangueetrangere',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='quantite',
            field=models.CharField(choices=[('1-500M2', '1-500M2'), ('501-1000M2', '501-1000M2'), ('1001-2000M2', '1001-2000M2'), ('2001M2<', '2001M2<'), ('0-499M2', '0-499M2'), ('500-999M2', '500-999M2'), ('1000-1999M2', '1000-1999M2'), ('2000M2<', '2000M2<')], max_length=50, verbose_name='TYPE SUPPORT'),
        ),
        migrations.AlterField(
            model_name='impressiononeway',
            name='quantite',
            field=models.CharField(choices=[('0-499M2', '0-499M2'), ('500-999M2', '500-999M2'), ('1000-1999M2', '1000-1999M2'), ('2000M2<', '2000M2<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000'), ('10000<', '10000<'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='units',
            field=models.CharField(choices=[('USD/PAGE', 'USD/PAGE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.DeleteModel(
            name='RamePapier',
        ),
    ]
