# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0340_auto_20180515_1530'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='serviceagencevoyage',
            name='type_service',
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name='CHOIX ENTRÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_legumes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=20, verbose_name='CHOIX DE LEGUMES'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_plats',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DU PLATS'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='quantite',
            field=models.CharField(choices=[('0-499M2', '0-499M2'), ('500-999M2', '500-999M2'), ('1000-1999M2', '1000-1999M2'), ('2000M2<', '2000M2<')], max_length=50, verbose_name='TYPE SUPPORT'),
        ),
        migrations.AlterField(
            model_name='rollup',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),
    ]
