# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0342_assistanceobtentionvisa'),
    ]

    operations = [

        migrations.CreateModel(
            name='ScieCirculaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_scie_circulaire', models.CharField(choices=[('SCIE CIRCULAIRE DE PRECISION', 'SCIE CIRCULAIRE DE PRECISION'), ('SCIE RADIALE SUR TABLE', 'SCIE RADIALE SUR TABLE'), ('SCIE CIRCULAIRE', 'SCIE CIRCULAIRE'), ('SCIE CIRCULAIRE METAL', 'SCIE CIRCULAIRE METAL'), ('SCIE CIRCULAIRE SUR TABLE', 'SCIE CIRCULAIRE SUR TABLE'), ('SCIE A ONGLET', 'SCIE A ONGLET')], max_length=100, verbose_name='TYPE DE SCIE')),
                ('marque_outillage', models.CharField(choices=[('DEWALT', 'DEWALT'), ('EINHELL', 'EINHELL')], max_length=100, verbose_name='MARQUE')),
                ('puissance_outillage', models.CharField(choices=[('1750W', '1750W'), ('2200W', '2200W'), ('1200W', '1200W'), ('1230W', '1230W'), ('1400W', '1400W'), ('1500W', '1500W'), ('2000W', '2000W'), ('1800W', '1800W'), ('2800W', '2800W'), ('1600W', '1600W')], max_length=100, verbose_name='PUISSANCE')),
                ('diametre_lame', models.CharField(choices=[('235mm', '235mm'), ('350mm', '350mm'), ('165mm', '165mm'), ('160mm', '160mm'), ('190mm', '190mm'), ('210mm', '210mm'), ('250mm', '250mm'), ('300mm', '300mm')], max_length=100, verbose_name='DIAMETRE DE LAME(MILLIMETRE)')),
                ('alimentation', models.CharField(choices=[('SECTEUR', 'SECTEUR')], max_length=100, verbose_name='ALIMENTATION')),
                ('tension', models.CharField(choices=[('220V', '220V')], max_length=100, verbose_name='TENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
