# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0346_raboteuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burineur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque_outillage', models.CharField(choices=[('EINHELL', 'EINHELL')], max_length=100, verbose_name='MARQUE')),
                ('transmission', models.CharField(choices=[('1 VITESSE', '1 VITESSE')], max_length=100, verbose_name='TRANSMISSION')),
                ('alimentation', models.CharField(choices=[('PNEUMATQUE', 'PNEUMATQUE')], max_length=100, verbose_name='ALIMENTATION')),
                ('consommation_air', models.CharField(choices=[('115L/MIN', '115L/MIN')], max_length=100, verbose_name="CONSOMMATION D'AIR")),
                ('pression_air', models.CharField(choices=[('6,3', '6,3')], max_length=100, verbose_name="PRESSION D'AIR")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
