# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0348_boulonneuse_rainureuse_tourabois'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocollant',
            name='format_autocollant',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], default=1, max_length=50, verbose_name='SUPPORT DE GRAVURE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autocollant',
            name='quantite',
            field=models.CharField(choices=[('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000<', '20000<'), ('1-5000', '1-5000')], default=1, max_length=50, verbose_name='SUPPORT DE GRAVURE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='quantite',
            field=models.CharField(choices=[('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000<', '20000<'), ('1-5000', '1-5000')], max_length=50, verbose_name='QUANTITE'),
        ),
    ]
