# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0350_auto_20180516_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visseuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque_outillage', models.CharField(choices=[('MAKITA', 'MAKITA')], max_length=100, verbose_name='MARQUE')),
                ('tension_batterie', models.CharField(choices=[('12V', '12V')], max_length=100, verbose_name='TENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX ACCOMPAGNEMENT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name='CHOIX ENTRÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_legumes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DE LEGUMES'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_plats',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('8', '8')], max_length=20, verbose_name='CHOIX DU PLATS'),
        ),
    ]
