# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0351_auto_20180516_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=20, verbose_name='CHOIX BOISSON ALCOOLISÉE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buffet',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=20, verbose_name='CHOIX DE BOISSON NON ALCOOLISÉE'),
            preserve_default=False,
        ),
    ]
