# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0353_auto_20180516_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollup',
            name='quantite',
            field=models.CharField(choices=[('1-19', '1-19'), ('20-49', '20-49'), ('50-99', '50-99'), ('100<', '100<')], max_length=50, verbose_name='QUANTITE'),
        ),
    ]
