# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0354_auto_20180518_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assainissement',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2'), ('USD/M²', 'USD/M²'), ('$/M2', '$/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='autocollant',
            name='quantite',
            field=models.CharField(choices=[('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000<', '20000<')], max_length=50, verbose_name='SUPPORT DE GRAVURE'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='quantite',
            field=models.CharField(choices=[('0-500M2', '0-500M2'), ('501-1000M2', '501-1000M2'), ('1001-2000M2', '1001-2000M2'), ('2000M2<', '2000M2<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50),
        ),
    ]
