# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0356_auto_20180518_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assainissement',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='brandingvehiculefull',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='constructionbatiment',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='decorationsurface',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='elastiques',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='entreposage',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='escortefonds',
            name='units',
            field=models.CharField(choices=[('% DES FONDS TRANSPORTES', '% DES FONDS TRANSPORTES')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='giletkaki',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='impressionabs',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='impressiononeway',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='reboisement',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
