# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0357_auto_20180518_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escortefonds',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='graphismeetanimation3d',
            name='units',
            field=models.CharField(choices=[('USD/SECONDE', 'USD/SECONDE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='impressionsurbriquet',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001<', '1001<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='impressionsurbriquet',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='impressionsurpapierphoto',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='installationreseauinformatique',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='installationreseautelephonique',
            name='units',
            field=models.CharField(choices=[('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='jardinage',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
