# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0358_auto_20180518_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legume',
            name='type_legume',
            field=models.CharField(choices=[('AUBERGINE', 'AUBERGINE'), ('GOMBO', 'GOMBO'), ('TOMATE', 'TOMATE'), ('AVOCAT', 'AVOCAT'), ('POMME DE TERRE (LOCAL)', 'POMME DE TERRE (LOCAL)'), ('OIGNON BLANC', 'OIGNON BLANC'), ('POMME DE TERRE DE GOMA', 'POMME DE TERRE DE GOMA'), ('OIGNON ROUGE', 'OIGNON ROUGE'), ('HARICOT DE GOMA', 'HARICOT DE GOMA'), ('HARICOT PRINCESSE', 'HARICOT PRINCESSE'), ('HARICOT GOMA 1ER CHOIX', 'HARICOT GOMA 1ER CHOIX')], max_length=50, verbose_name='TYPE LEGUME'),
        ),
    ]
