# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0359_auto_20180518_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceobtentionvisa',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bandedefilante',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('KASAI', 'KASAI'), ('COLONNEL EBEYA', 'COLONNEL EBEYA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='locationcamion',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='locationdepot',
            name='avenue',
            field=models.CharField(choices=[('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL'), ('7EME RUE', '7EME RUE')], max_length=100, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='locationporteconteneur',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='navetteaeroport',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='produitdenettoyage',
            name='units',
            field=models.CharField(choices=[('USD/LITRE', 'USD/LITRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produitnettoyage',
            name='units',
            field=models.CharField(choices=[('USD/LITRE', 'USD/LITRE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='reservationhoteletranger',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('COLONNEL EBEYA', 'COLONNEL EBEYA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='superficie',
            field=models.CharField(choices=[('140 M2', '140 M2'), ('71,5 M2', '71,5 M2'), ('72 M2', '72 M2')], max_length=20, verbose_name='SUPERFICIE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='avenue',
            field=models.CharField(choices=[('SENEGALAIS', 'SENEGALAIS'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('COLONNEL EBEYA', 'COLONNEL EBEYA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='serviceagencevoyage',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='servicesplit',
            name='units',
            field=models.CharField(choices=[('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='split',
            name='units',
            field=models.CharField(choices=[('USD', 'US$'), ('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
