# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0363_ventilateurplafonier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePlastique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('forme', models.CharField(choices=[('CARRE', 'CARRE'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=100, verbose_name='FORME')),
                ('dimensions', models.CharField(choices=[('70X70CM', '70X70CM'), ('60X60CM', '60X60CM'), ('90X90CM', '90X90CM'), ('242X76CM', '242X76CM')], max_length=100, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='presencephysiquesurplateau',
            name='units',
            field=models.CharField(choices=[('USD/MIN', 'USD/MIN')], max_length=50, verbose_name='UNITÉS'),
        ),
    ]
