# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0364_auto_20180518_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('dimension_triplex', models.CharField(choices=[('1220x2440MM', '1220x2440MM')], max_length=100, verbose_name='DIMENSION')),
                ('type_triplex', models.CharField(choices=[('DOUBLE PRESS', 'DOUBLE PRESS')], max_length=100, verbose_name='TYPE')),
                ('epaisseur', models.CharField(choices=[('10MM', '10MM'), ('5MM', '5MM'), ('8MM', '8MM'), ('10MM', '10MM')], max_length=100, verbose_name='MARQUE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
