# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0367_auto_20180518_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('format_poele', models.CharField(choices=[('20 CM', '20 CM'), ('22 CM', '22 CM'), ('24 CM', '24 CM'), ('26 CM', '26 CM'), ('28 CM', '28 CM'), ('30 CM', '30 CM'), ('40 CM', '40 CM')], max_length=100, verbose_name='NOMBRE DE PORTE')),
                ('marque', models.CharField(choices=[('WEST POOL', 'WEST POOL')], max_length=100, verbose_name='MARQUE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
