# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0370_cafetiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChauffeEau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('ARISTON', 'ARISTON'), ('PANASONIC', 'PANASONIC'), ('IGNIS', 'IGNIS')], max_length=100, verbose_name='MARQUE')),
                ('volume', models.CharField(choices=[('100 L', '100 L'), ('80 L', '80 L'), ('50 L', '50 L'), ('30 L', '30 L')], max_length=100, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.AlterField(
            model_name='riz',
            name='variete',
            field=models.CharField(choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMIN', 'JASMIN'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, verbose_name='VARIETE'),
        ),
    ]
