# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0371_auto_20180519_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestructeurPapier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('DELI', 'DELI')], max_length=100, verbose_name='MARQUE')),
                ('capacite_papier', models.CharField(choices=[('12 PAPIERS', '12 PAPIERS'), ('17 PAPIERS', '17 PAPIERS'), ('2 PAPIERS', '2 PAPIERS'), ('8 PAPIERS', '8 PAPIERS')], max_length=100, verbose_name='MARQUE')),
                ('Volume_panier_dechet', models.CharField(choices=[('23L', '23L'), ('16L', '16L'), ('31L', '31L'), ('13L', '13L'), ('3,5L', '3,5L')], max_length=100, verbose_name='MARQUE')),
                ('destruction_cd', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, verbose_name='MARQUE')),
                ('destruction_carte_credit', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, verbose_name='DIMENSION')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
    ]
