# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0379_antennewifi_autocollantcodebar_batterielaptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoitierDisqueDur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_disque_dur', models.CharField(choices=[('SATA', 'SATA'), ('IDE', 'IDE')], max_length=100, verbose_name='TYPE DE DISQUE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_carte', models.CharField(choices=[('GRAPHIQUE PCI EXPRESS NVIDIA 1GO', 'GRAPHIQUE PCI EXPRESS NVIDIA 1GO'), ('GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO', 'GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO'), ('READER EXTERNAL', 'READER EXTERNAL'), ('RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND', 'RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND')], max_length=100, verbose_name='TYPE CARTE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Chargeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque_appareil', models.CharField(choices=[('ACER', 'ACER'), ('DELL', 'DELL'), ('HP', 'HP'), ('UNIVERSEL', 'UNIVERSEL'), ('SELPHY CP910', 'SELPHY CP910'), ('TOSHIBA', 'TOSHIBA')], max_length=100, verbose_name='MARQUE')),
                ('tension', models.CharField(choices=[('19V', '19V'), ('19,5V', '19,5V'), ('18,5V', '18,5V')], max_length=100, verbose_name='TENSION(VOLT)')),
                ('intensite', models.CharField(choices=[('3,42A', '3,42A'), ('3,34A', '3,34A'), ('4,62A', '4,62A'), ('3,5A', '3,5A'), ('3,5A SMALL PIN', '3,5A SMALL PIN'), ('1,58A', '1,58A'), ('4,74A BIG PIN', '4,74A BIG PIN'), ('4,74A SMALL PIN', '4,74A SMALL PIN'), ('3,42A', '3,42A'), ('3,95A', '3,95A')], max_length=100, verbose_name='INTENSITE(AMPERE)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Connecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_connecteur', models.CharField(choices=[('RJ45 CAT6 METAL', 'RJ45 CAT6 METAL'), ('RJ45 COUVERT', 'RJ45 COUVERT'), ('RJ11', 'RJ11'), ('RJ45 CAT5E', 'RJ45 CAT5E'), ('RJ45 CAT6E', 'RJ45 CAT6E')], max_length=100, verbose_name='TYPE CONNECTEUR')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='MemoireRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_ordinateur', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('DESKTOP', '1DESKTOP')], max_length=100, verbose_name="TYPE D'ORDINATEUR")),
                ('type_memoire', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=100, verbose_name='TYPE MEMOIRE')),
                ('capacite_memoire', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], max_length=100, verbose_name='TYPE CONNECTEUR')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='PatchCord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('longueur', models.CharField(choices=[('15M', '15M'), ('1M', '1M'), ('0,3M ', '0,3M '), ('3M', '3M')], max_length=100, verbose_name='LONGUEUR PATCH CORD')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionSurtensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('marque', models.CharField(choices=[('APC', 'APC'), ('MERCURY', 'MERCURY')], max_length=100, verbose_name='MARQUE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='RepartiteurHdmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('entree_sortie', models.CharField(choices=[('1x4', '1x4'), ('1x8', '1x8')], max_length=100, verbose_name='ENTRE ET SORTIE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_webcam', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('HD', 'HD')], max_length=100, verbose_name='TYPE WEBCAM')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='rack',
            name='unites',
        ),
        migrations.AddField(
            model_name='patchpanel',
            name='type_patch_panel',
            field=models.CharField(choices=[('CAT 5E', 'CAT 5E'), ('CAT 6E', 'CAT 6E')], default=1, max_length=100, verbose_name='TYPE PATCH PANEL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='avec_fan',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON'), ('DOUBLE', 'DOUBLE')], default=1, max_length=100, verbose_name='RACK AVEC FAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='nombre_unites',
            field=models.CharField(choices=[('12U', '12U'), ('15U', '15U'), ('18U', '18U'), ('22U', '22U'), ('27U', '27U'), ('32U', '32U'), ('37U', '37U'), ('42U', '42U'), ('6U', '6U'), ('9U', '9U')], default=1, max_length=100, verbose_name='UNITE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='nombre_port',
            field=models.CharField(choices=[('24 PORTS', '24 PORTS'), ('24 PORTS', '24 PORTS'), ('48 PORTS', '48 PORTS')], max_length=100, verbose_name='NOMBRE DE PORT'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='dimension',
            field=models.CharField(choices=[('APC', 'APC'), ('MERCURY', 'MERCURY')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='montage',
            field=models.CharField(choices=[('SOL', 'SOL'), ('MUR', 'MUR')], max_length=100, verbose_name='MONTAGE'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
    ]
