# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0381_auto_20180519_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adapteur',
            new_name='Adaptateur',
        ),
        migrations.RenameField(
            model_name='congelateur',
            old_name='Volume',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='frigo',
            old_name='Volume',
            new_name='volume',
        ),
        migrations.AlterField(
            model_name='rack',
            name='dimension',
            field=models.CharField(choices=[('600x600MM', '600x600MM'), ('600x800MM', '600x800MM'), ('600x1000MM', '600x1000MM'), ('800x800MM', '800x800MM'), ('800X1000MM', '800X1000MM'), ('600X550MM', '600X550MM')], max_length=100, verbose_name='DIMENSION'),
        ),
    ]
