# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0384_auto_20180522_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptateur',
            name='type_adaptateur',
            field=models.CharField(choices=[('ALIMENTATION CCTV CAMERA 12V', 'ALIMENTATION CCTV CAMERA 12V'), ('USB VERS PORT PARALLELE', 'USB VERS PORT PARALLELE'), ('USB VERS RJ45', 'USB VERS RJ45'), ('USB VERS PORT SERIE', 'USB VERS PORT SERIE'), ('USB VERS SON', 'USB VERS SON'), ('USB WIFI TPLINK T2U AC600', 'USB WIFI TPLINK T2U AC600'), ('USB WIRELESS TL-WN7200ND', 'USB WIRELESS TL-WN7200ND'), ('USB WIFI TPLINK TL-WN725N', 'USB WIFI TPLINK TL-WN725N'), ('1VGA VERS HDMI', 'VGA VERS HDMI'), ('WIFI POUR IMPRIMANTE', 'WIFI POUR IMPRIMANTE'), ('IHPONE 5/6 VERS HDMI AVEC ALIMENTATION', 'IHPONE 5/6 VERS HDMI AVEC ALIMENTATION'), ('DVI VERS VGA', 'DVI VERS VGA'), ('POUR ORDINATEUR', 'POUR ORDINATEUR'), ('UNIVERSEL POUR LAPTOP', 'UNIVERSEL POUR LAPTOP'), ('CARTE MEMOIRE', 'CARTE MEMOIRE'), ('USB 3.0 VERS HDMI', 'USB 3.0 VERS HDMI'), ('USB 3.0 VERS VGA', 'USB 3.0 VERS VGA'), ('HUB CHARGEUR DE SORTIE UNIVERSEL USB', 'HUB CHARGEUR DE SORTIE UNIVERSEL USB'), ('HDMI VERS 3RCA AVEC ALIMENTATON', 'HDMI VERS 3RCA AVEC ALIMENTATON'), ('HDMI VERS VGA AVEC ALIMENTATION', 'HDMI VERS VGA AVEC ALIMENTATION'), ('VGA VERS HDMI', 'VGA VERS HDMI'), ('PORT DISPLAY DVI', 'PORT DISPLAY DVI'), ('HDMI VERS VGA ', 'HDMI VERS VGA '), ('IPAD VERS HDMI', 'IPAD VERS HDMI'), ('PORT MINI DISPLAY VERS DVI', 'PORT MINI DISPLAY VERS DVI'), ('PORT MINI DISPLAY VERS HDMI', 'PORT MINI DISPLAY VERS HDMI'), ('POUR ALIMENTATION IMPRIMANTE HP', 'POUR ALIMENTATION IMPRIMANTE HP')], max_length=100, verbose_name='TYPE ADAPTATEUR '),
        ),
        migrations.AlterField(
            model_name='carte',
            name='type_carte',
            field=models.CharField(choices=[('GRAPHIQUE PCI EXPRESS NVIDIA 1GO', 'GRAPHIQUE PCI EXPRESS NVIDIA 1GO'), ('GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO', 'GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO'), ('READER EXTERNAL', 'READER EXTERNAL'), ('RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND', 'RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND'), ('FIREWIRE PCI LW', 'FIREWIRE PCI LW'), ('GRAPHIQUE NVIDIA 1GB', 'GRAPHIQUE NVIDIA 1GB'), ('PCI COMBO 2 SERIAL+1PARRALE', 'PCI COMBO 2 SERIAL+1PARRALE'), ('PCI EXPRESS', 'PCI EXPRESS'), ('PCI SERIAL ATA HOST', 'PCI SERIAL ATA HOST'), ('PCI TO PCMCI', 'PCI TO PCMCI'), ('PCI ULTRA ATA', 'PCI ULTRA ATA'), ('PCMCI RJ45', 'PCMCI RJ45'), ('SON PCI', 'SON PCI'), ('CARTE MERE INTEL DG 41BL', 'CARTE MERE INTEL DG 41BL')], max_length=100, verbose_name='TYPE CARTE'),
        ),
        migrations.AlterField(
            model_name='connecteur',
            name='type_connecteur',
            field=models.CharField(choices=[('RJ45 CAT6 METAL', 'RJ45 CAT6 METAL'), ('RJ45 COUVERT', 'RJ45 COUVERT'), ('RJ11', 'RJ11'), ('RJ45 CAT5E', 'RJ45 CAT5E'), ('RJ45 CAT6E', 'RJ45 CAT6E'), ('COUVERTURE CABLE RJ45', 'COUVERTURE CABLE RJ45'), ('RJ45 AICO', 'RJ45 AICO'), ('RJ45 CAT6', 'RJ45 CAT6'), ('RJ45 METAL', 'RJ45 METAL'), ('RJ45 NORMA', 'RJ45 NORMA'), ('CAT6 RJ45 POUR PRISE MURALE', 'CAT6 RJ45 POUR PRISE MURALE')], max_length=100, verbose_name='TYPE CONNECTEUR'),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='capacite_memoire',
            field=models.CharField(choices=[('128MB', '128MB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], max_length=100, verbose_name='TYPE CONNECTEUR'),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='type_memoire',
            field=models.CharField(choices=[('DDR1', 'DDR1'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=100, verbose_name='TYPE MEMOIRE'),
        ),
    ]
