# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-23 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0387_auto_20180522_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoireram',
            name='capacite_memoire',
            field=models.CharField(choices=[('128MB', '128MB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], max_length=100, verbose_name='CAPACITE MEMOIRE'),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='type_ordinateur',
            field=models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('DESKTOP', 'DESKTOP')], max_length=100, verbose_name="TYPE D'ORDINATEUR"),
        ),
        migrations.AlterField(
            model_name='switchkvm',
            name='nombre_pc',
            field=models.CharField(choices=[('2', '2')], max_length=100, verbose_name='NOMBRE DE PC'),
        ),
    ]
