# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-23 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0390_auto_20180523_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batteriecartemere',
            name='category',
        ),
        migrations.RemoveField(
            model_name='batteriecartemere',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='BatterieCarteMere',
        ),
    ]
