# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0400_plaqueafacedoublepoursocketmural_poincon_tableordinateur_tapisdecourse_veloelliptique_velomagnetique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baredemine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='baredemine',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='BareDeMine',
        ),
    ]
