# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0401_auto_20180524_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainureuse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rainureuse',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='Rainureuse',
        ),
    ]
