# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0402_auto_20180524_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourabois',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tourabois',
            name='vendeur',
        ),
        migrations.AlterField(
            model_name='poisson',
            name='type_de_poisson',
            field=models.CharField(choices=[('MUNGUSU', 'MUNGUSU'), ('MOJOMBO', 'MOJOMBO'), ('MINZANDA', 'MINZANDA'), ('MGOMGO', 'MGOMGO'), ('CAPITAINE', 'CAPITAINE'), ('MBOTO', 'MBOTO'), ('MINZANDA', 'MINZANDA'), ('NGOLO', 'NGOLO'), ('SOLE MOYENNE', 'SOLE MOYENNE'), ('GRANDE SOLE', 'GRANDE SOLE'), ('CAPITAINE MOYEN', 'CAPITAINE MOYEN'), ('GRAND CAPITAINE', 'GRAND CAPITAINE'), ('FILET DE CAPITAINE', 'FILET DE CAPITAINE'), ('PERCHE', 'PERCHE'), ('FILET DE PERCHE', 'FILET DE PERCHE'), ('MEROU', 'MEROU'), ('RAIE (MAZIBA)', 'RAIE (MAZIBA)'), ('AILE DE RAIE', 'AILE DE RAIE'), ('ROUGET', 'ROUGET'), ('SAINT PIERRE', 'SAINT PIERRE'), ('BARRACUDA', 'BARRACUDA'), ('COSSA MOYEN MOANDA', 'COSSA MOYEN MOANDA'), ('COSSA MOYEN POINTE NOIRE', 'COSSA MOYEN POINTE NOIRE'), ('COSSA ROYALE POINTE NOIRE', 'COSSA ROYALE POINTE NOIRE'), ('PETITE LANGOUSTE MOANDA', 'PETITE LANGOUSTE MOANDA'), ('LANGOUSTE MOYENNE POINTE NOIRE', 'LANGOUSTE MOYENNE POINTE NOIRE'), ('GRANDE LANGOUSTE POINTE NOIRE', 'GRANDE LANGOUSTE POINTE NOIRE'), ('PIEUVRE POINTE NOIR', 'PIEUVRE POINTE NOIR'), ('CRABE', 'CRABE'), ('CALAMARD', 'CALAMARD'), ('SECHE', 'SECHE'), ('COSSA DECORTIQUE', 'COSSA DECORTIQUE'), ('MORUE', 'MORUE'), ('CROQUETTES POISSON 10PCS', 'CROQUETTES POISSON 10PCS'), ('CROQUETTES COSSA 10PCS', 'CROQUETTES COSSA 10PCS'), ('CROQUETTE MORUE 10PCS', 'CROQUETTE MORUE 10PCS')], max_length=50, verbose_name='TYPE POISSON'),
        ),
        migrations.DeleteModel(
            name='TourABois',
        ),
    ]
