# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0404_diffusioncontenumediatique'),
    ]

    operations = [
        migrations.AddField(
            model_name='assainissement',
            name='detail_assainissement',
            field=models.CharField(choices=[('NON APPLICABLE', 'NON APPLICABLE'), ('VITRE', 'VITRE'), ('ALUCOBONDE', 'ALUCOBONDE'), ('PEINTURE', 'PEINTURE'), ('CARRELAGE', 'CARRELAGE'), ('GRANITO QUARTZ', 'GRANITO QUARTZ'), ('GRATTAGE', 'GRATTAGE')], default=1, max_length=100, verbose_name="DETAIL D'ASSAINISSEMENT"),
            preserve_default=False,
        ),
    ]
