# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0405_assainissement_detail_assainissement'),
    ]

    operations = [

        migrations.AlterField(
            model_name='affichagelogosurecran',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000'), ('1-500', '1-500')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='affiche',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='agrafe',
            name='units',
            field=models.CharField(choices=[('USD/BOITE', 'USD/BOITE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='agrafeuse',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='aiguilleavibrerlebeton',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='albumcartedevisite',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ampoule',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ampoulesolaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='anneauplastique',
            name='taille_anneau',
            field=models.CharField(choices=[('6MM', '6MM'), ('8MM', '8MM'), ('10MM', '10MM'), ('12MM', '12MM'), ('16MM', '16MM'), ('20MM', '20MM'), ('25MM', '25MM'), ('50MM', '50MM')], max_length=100, verbose_name="TAILLE DE L'ANNEAU"),
        ),
        migrations.AlterField(
            model_name='anneauplastique',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='appareildegym',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='appareilmesure',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='nombre_de_cases',
            field=models.CharField(choices=[('3', '3'), ('6', '6')], max_length=50, verbose_name='NOMBRE DE CASES'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='type_armoire',
            field=models.CharField(choices=[('ARMOIRE BASSE', 'ARMOIRE BASSE'), ('ARMOIRE HAUTE', 'ARMOIRE HAUTE'), ('ARMOIRE MI-HAUTE', 'ARMOIRE MI-HAUTE'), ('RAYONNAGE SQUELETTE', 'RAYONNAGE SQUELETTE'), ('VESTIAIRE', 'VESTIAIRE')], max_length=50, verbose_name="TYPE D'ARMOIRE"),
        ),
        migrations.AlterField(
            model_name='arracheclou',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='aspirateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='periode',
            field=models.CharField(choices=[('1-5 JOURS', '1-5 JOURS'), ('6-7 JOURS', '6-7 JOURS'), ('1-7 JOURS', '1-7 JOURS'), ('8-10 JOURS', '8-10 JOURS'), ('11-15 JOURS', '11-15 JOURS'), ('8-15 JOURS', '8-15 JOURS'), ('16-21 JOURS', '16-21 JOURS'), ('22-30 JOURS', '22-30 JOURS'), ('31-45 JOURS', '31-45 JOURS'), ('46-60 JOURS', '46-60 JOURS'), ('61-90 JOURS', '61-90 JOURS'), ('91-180 JOURS', '91-180 JOURS')], max_length=20, verbose_name='NOMBRE DES JOURS'),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='tranche_age',
            field=models.CharField(choices=[('0-55 ANS', '0-55 ANS'), ('55-65 ANS', '55-65 ANS'), ('65-69 ANS', '65-69 ANS')], max_length=20, verbose_name='TRANCHE AGE'),
        ),
        migrations.AlterField(
            model_name='attache',
            name='nombre_boite',
            field=models.CharField(choices=[('10 BOITES', '10 BOITES'), ('500GR', '500GR')], max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='attache',
            name='taille_attache',
            field=models.CharField(choices=[('28MM', '28MM'), ('50MM', '50MM')], max_length=100, verbose_name="TAILLE DE L'ATTACHE"),
        ),
        migrations.AlterField(
            model_name='attache',
            name='units',
            field=models.CharField(choices=[('USD/BOITE', 'USD/BOITE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='attachecableaclouer',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='autocollant',
            name='format_autocollant',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='autocollant',
            name='quantite',
            field=models.CharField(choices=[('1-5000', '1-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000<', '20000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='autocollant',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='autocollantvinyleadhesif',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),

    ]
