# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0406_auto_20180531_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='forme_ampoule',
            field=models.CharField(choices=[('AR 111', 'AR 111'), ('CAPSULE', 'CAPSULE'), ('COUP DE VENT', 'COUP DE VENT'), ('FLAMME', 'FLAMME'), ('GOUTTE', 'GOUTTE'), ('HELICOÏDALE', 'HELICOÏDALE'), ('LINOLITE', 'LINOLITE'), ('MINI TUBE', 'MINI TUBE'), ('PEPITE', 'PEPITE'), ('SPHERIQUE', 'SPHERIQUE'), ('SPOT', 'SPOT'), ('REFLECTEUR', 'REFLECTEUR')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='puissance_ampoule',
            field=models.CharField(choices=[('1W', '1W'), ('3W', '3W'), ('5W', '5W'), ('6W', '6W'), ('9W', '9W'), ('10W', '10W'), ('11W', '11W'), ('12W', '12W'), ('15W', '15W'), ('18W', '18W'), ('32W', '32W'), ('50W', '50W'), ('60W', '60W'), ('100W', '100W'), ('200W', '200W'), ('250W', '250W'), ('400W', '400W'), ('500W', '500W'), ('1000W', '1000W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='type_ampoule',
            field=models.CharField(choices=[('ECONOMIQUE', 'ECONOMIQUE'), ('SODIUM', 'SODIUM'), ('HALOGENE', 'HALOGENE'), ('INCANDESCENCE', 'INCANDESCENCE'), ('INFRAROUGE', 'INFRAROUGE'), ('LED', 'LED'), ('PROJECTEUR', 'PROJECTEUR')], max_length=20, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='ampouleelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='appareildemesure',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='appareilmesure',
            name='type_appareil_mesure',
            field=models.CharField(choices=[('PINCE AMPEREMETRIQUE', 'PINCE AMPEREMETRIQUE'), ('DIGITAL', 'DIGITAL'), ('MECANIQUE', 'MECANIQUE')], max_length=20, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='arracheclou',
            name='dimension_arrache_clou',
            field=models.CharField(choices=[('1M', '1M'), ('0,8M', '0,8M'), ('0,6M', '0,6M'), ('0,4M', '0,4M')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='aspirateur',
            name='capacite_reservoir',
            field=models.CharField(choices=[('12L', '12L'), ('30L', '30L'), ('25L', '25L'), ('25L', '25L')], max_length=100, verbose_name='CAPACITE DU RESERVOIR'),
        ),
        migrations.AlterField(
            model_name='aspirateur',
            name='puissance',
            field=models.CharField(choices=[('1250W', '1250W'), ('2250W', '2250W'), ('2600W', '2600W'), ('700W', '700W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='attachecableaclouer',
            name='dimension_attache_mm',
            field=models.CharField(choices=[('25', '25'), ('20', '20'), ('16', '16'), ('10', '10'), ('8', '8'), ('6', '6')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='balastre',
            name='puissance_balastre',
            field=models.CharField(choices=[('40W', '40W'), ('20W', '20W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='bandedesignalisation',
            name='longueur',
            field=models.CharField(choices=[('500', '500')], max_length=100, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='betonniere',
            name='capacite_betonniere',
            field=models.CharField(choices=[('180L', '180L'), ('260L', '260L'), ('350L', '350L'), ('360L', '360L'), ('500L', '500L')], max_length=100, verbose_name='CAPACITE EN LITRE'),
        ),
        migrations.AlterField(
            model_name='betonniere',
            name='type_betonniere',
            field=models.CharField(choices=[('ELECTRIQUE', 'ELECTRIQUE'), ('DIESEL', 'DIESEL')], max_length=100, verbose_name='TYPE DE BETONNIERE'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='intesite',
            field=models.CharField(choices=[('600A', '600A'), ('400A', '400A')], max_length=100, verbose_name='INTESITE EN AMPERE'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='tension',
            field=models.CharField(choices=[('12V', '12V')], max_length=100, verbose_name='TENSION EN VOLT'),
        ),
        migrations.AlterField(
            model_name='cablecameraccd',
            name='longueur',
            field=models.CharField(choices=[('10M', '10M'), ('15M', '15M'), ('20M', '20M'), ('5M', '5M')], max_length=100, verbose_name='LONGUEUR DU CABLE'),
        ),
        migrations.AlterField(
            model_name='cablesouple',
            name='section',
            field=models.CharField(choices=[('4', '4'), ('6', '6'), ('10', '10'), ('16', '16'), ('25', '25'), ('35', '35'), ('50MM2', '50MM2'), ('3X2,5MM2', '3X2,5MM2'), ('3X1,5MM2', '3X1,5MM2')], max_length=20, verbose_name='SECTION EN MILLIMETRE CARRÉ'),
        ),
        migrations.AlterField(
            model_name='cameraccd',
            name='style_camera',
            field=models.CharField(choices=[('DOME', 'DOME'), ('BOX', 'BOX'), ('BULLET', 'BULLET')], max_length=100, verbose_name='STYLE'),
        ),
        migrations.AlterField(
            model_name='cameraccd',
            name='technologie',
            field=models.CharField(choices=[('INFRAROUGE', 'INFRAROUGE')], max_length=100, verbose_name='TECHNOLOGIE'),
        ),
        migrations.AlterField(
            model_name='cameraip',
            name='style_camera',
            field=models.CharField(choices=[('DOME', 'DOME'), ('BOX', 'BOX'), ('BULLET', 'BULLET')], max_length=100, verbose_name='STYLE'),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='couleur_cartouche',
            field=models.CharField(choices=[('COULEUR', 'COULEUR'), ('NOIR', 'NOIR'), ('CYAN', 'CYAN'), ('MAGENTA', 'MAGENTA'), ('JAUNE', 'JAUNE')], max_length=50, verbose_name='COULEUR DE LA CARTOUCHE'),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='marque_cartouche',
            field=models.CharField(choices=[('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('CANON', 'CANON'), ('EPSON', 'EPSON'), ('BROTHER', 'BROTHER'), ('KATUN', 'KATUN')], max_length=50, verbose_name='MARQUE DE LA CARTOUCHE'),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='numero_cartouche',
            field=models.CharField(choices=[('05A', '05A'), ('12A', '12A'), ('15', '15'), ('17A', '17A'), ('21', '21'), ('22', '22'), ('28', '28'), ('29', '29'), ('35A', '35A'), ('36A', '36A'), ('42 A', '42 A'), ('49', '49'), ('49A', '49A'), ('55 A', '55 A'), ('57', '57'), ('60', '60'), ('61', '61'), ('63', '63'), ('63A', '63A'), ('73', '73'), ('78A', '78A'), ('80 A', '80 A'), ('80A', '80A'), ('83 A', '83 A'), ('83A', '83A'), ('88', '88'), ('94', '94'), ('104 S', '104 S'), ('104S', '104S'), ('121', '121'), ('122', '122'), ('123', '123'), ('123A', '123A'), ('126 A', '126 A'), ('126A', '126A'), ('128 A', '128 A'), ('128A', '128A'), ('129', '129'), ('131 A', '131 A'), ('131A', '131A'), ('136', '136'), ('140', '140'), ('141', '141'), ('178', '178'), ('201 A', '201 A'), ('201A', '201A'), ('300', '300'), ('301', '301'), ('304 A', '304 A'), ('305 A', '305 A'), ('305A', '305A'), ('336', '336'), ('364', '364'), ('401A', '401A'), ('563', '563'), ('650', '650'), ('716', '716'), ('725', '725'), ('728', '728'), ('731', '731'), ('920 XL', '920 XL'), ('920', '920'), ('920', '920'), ('932', '932'), ('933 XL', '933 XL'), ('933', '933'), ('940', '940'), ('951', '951'), ('C-EXV14', 'C-EXV14'), ('C-EXV40', 'C-EXV40'), ('CEXV 33', 'CEXV 33'), ('CF 350', 'CF 350'), ('CF 351', 'CF 351'), ('GPR08', 'GPR08'), ('GPR18', 'GPR18'), ('GPR22', 'GPR22'), ('IR 2202-CEXV 42', 'IR 2202-CEXV 42'), ('NPG 32', 'NPG 32'), ('TN 1000', 'TN 1000'), ('TN 2025', 'TN 2025'), ('TN 2060', 'TN 2060'), ('TN 2130', 'TN 2130'), ('TN 2260', 'TN 2260'), ('TN 2280', 'TN 2280'), ('TN 240BK', 'TN 240BK'), ('TN 240C', 'TN 240C'), ('TN 240M', 'TN 240M'), ('TN 240Y', 'TN 240Y'), ('TN 261BK', 'TN 261BK'), ('TN 261C', 'TN 261C'), ('TN 261M', 'TN 261M'), ('TN 261Y', 'TN 261Y'), ('TN 3185', 'TN 3185'), ('TN 3250', 'TN 3250'), ('TN 3290', 'TN 3290'), ('TN 3320', 'TN 3320'), ('TN-260', 'TN-260')], max_length=50, verbose_name='NUMERO DE SERIE'),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='chargeurbatterie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='charniere',
            name='taille_charniere',
            field=models.CharField(choices=[('GRANDE', 'GRANDE'), ('PETITE', 'PETITE')], max_length=100, verbose_name='TAILLE'),
        ),
        migrations.AlterField(
            model_name='chauffeeau',
            name='volume',
            field=models.CharField(choices=[('100 L', '100 L'), ('80 L', '80 L'), ('50 L', '50 L'), ('30 L', '30 L')], max_length=100, verbose_name='VOLUME'),
        ),
        migrations.AlterField(
            model_name='citerne',
            name='capacite',
            field=models.CharField(choices=[('100L', '100L'), ('150L', '150L'), ('200L', '200L'), ('300L', '300L'), ('500L', '500L'), ('1000L', '1000L'), ('2000L', '2000L'), ('3000L', '3000L'), ('5000L', '5000L'), ('10000L', '10000L')], max_length=20, verbose_name='CAPACITE'),
        ),
        migrations.AlterField(
            model_name='citerne',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='citerne',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clinche',
            name='taille_clinche',
            field=models.CharField(choices=[('GRANDE', 'GRANDE'), ('PETITE', 'PETITE')], max_length=100, verbose_name='TAILLE'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='nombre_circuit',
            field=models.CharField(choices=[('8', '8'), ('12', '12'), ('16', '16'), ('24', '24'), ('36', '36')], max_length=20, verbose_name='NOMBRE DE CIRCUIT'),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='encastre_saili',
            field=models.CharField(choices=[('SAILLI', 'SAILLI'), ('ENCASTRE', 'ENCASTRE')], max_length=20, verbose_name="TYPE D'INSTALLATION"),
        ),
        migrations.AlterField(
            model_name='coffretjeubarre',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='compacteur',
            name='type_compacteur',
            field=models.CharField(choices=[('PLATE', 'PLATE'), ('PLATE 50CM', 'PLATE 50CM'), ('PLATE 60CM', 'PLATE 60CM'), ('BARE', 'BARE')], max_length=100, verbose_name='TYPE DE COMPACTEUR'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='capacite_compresseur',
            field=models.CharField(choices=[('6 LITRES', '6 LITRES'), ('24 LITRES', '24 LITRES'), ('50 LITRES', '50 LITRES'), ('100 LITRES', '100 LITRES'), ('200 LITRES', '200 LITRES'), ('300 LITRES', '300 LITRES')], max_length=20, verbose_name='CAPACITE EN LITRE'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='puissance_compresseur',
            field=models.CharField(choices=[('2 HP', '2 HP'), ('3 HP', '3 HP'), ('4 HP', '4 HP'), ('5,5 HP', '5,5 HP'), ('6,5 HP', '6,5 HP'), ('7,5 HP', '7,5 HP'), ('10 HP', '10 HP'), ('1,5 HP', '1,5 HP'), ('2,25 HP', '2,25 HP')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='capacite_compresseur',
            field=models.CharField(choices=[('6 LITRES', '6 LITRES'), ('24 LITRES', '24 LITRES'), ('50 LITRES', '50 LITRES'), ('100 LITRES', '100 LITRES'), ('200 LITRES', '200 LITRES'), ('300 LITRES', '300 LITRES')], max_length=100, verbose_name='CAPACITE'),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='debit',
            field=models.CharField(choices=[('250L/MIN', '250L/MIN'), ('360L/MIN', '360L/MIN'), ('900L/MIN', '900L/MIN'), ('1000L/MIN', '1000L/MIN'), ('1050L/MIN', '1050L/MIN')], max_length=100, verbose_name='DEBIT EN LITRE/MIN'),
        ),

    ]
