# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0408_auto_20180531_1136'),
    ]

    operations = [


        migrations.AlterField(
            model_name='outilsmanuel',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='outilsmanuel',
            name='type_outils',
            field=models.CharField(choices=[('PLANTOIR', 'PLANTOIR'), ('PINCEAU', 'PINCEAU'), ('RATEAU', 'RATEAU'), ('PELLE', 'PELLE'), ('MACHETTE', 'MACHETTE'), ('ARROSOIR', 'ARROSOIR'), ('HACHE', 'HACHE')], max_length=20, verbose_name="TYPE D'OUTIL"),
        ),
        migrations.AlterField(
            model_name='outilsmanuel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='pagemagazine',
            name='duree_magazine',
            field=models.CharField(choices=[('1-5 MIN', '1-5 MIN'), ('5-10 MIN', '5-10 MIN')], max_length=100, verbose_name='DUREE DU MAGAZINE'),
        ),
        migrations.AlterField(
            model_name='pagemagazine',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='palan',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='poids',
            field=models.CharField(choices=[('1 TONNE', '1 TONNE'), ('2 TONNES', '2 TONNES'), ('3 TONNES', '3 TONNES'), ('4 TONNES', '4 TONNES'), ('5 TONNES', '5 TONNES')], max_length=50, verbose_name='POID DU PALAN'),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='palanmecanique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('5W', '5W'), ('8W', '8W'), ('10W', '10W'), ('14W', '14W'), ('23W', '23W'), ('45W', '45W'), ('50W', '50W'), ('80W', '80W'), ('100W', '100W'), ('150W', '150W'), ('180W', '180W'), ('190W', '190W'), ('250W', '250W'), ('300W', '300W'), ('400W', '400W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='type_cellule',
            field=models.CharField(choices=[('POLYCRISTTALLIN', 'POLYCRISTTALLIN'), ('MONOCRISTTALLIN', 'MONOCRISTTALLIN')], max_length=20, verbose_name='TYPE DE CELLULE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='papier',
            name='units',
            field=models.CharField(choices=[('USD/CONTENANT', 'USD/CONTENANT')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='papieraponcer',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='patchcord',
            name='longueur',
            field=models.CharField(choices=[('15M', '15M'), ('1M', '1M'), ('0,3M ', '0,3M '), ('3M', '3M')], max_length=100, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='type_patch_panel',
            field=models.CharField(choices=[('CAT 5E', 'CAT 5E'), ('CAT 6E', 'CAT 6E')], max_length=100, verbose_name='TYPE DE PATCH PANEL'),
        ),
        migrations.AlterField(
            model_name='paumelle',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='paumelle',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='domaine_application',
            field=models.CharField(choices=[('APPRET MUR', 'APPRET MUR'), ('PROTECTION METAL', 'PROTECTION METAL'), ('PROTECTION BOIS', 'PROTECTION BOIS'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('MENUISERIE', 'MENUISERIE'), ('PROTECTION METAL', 'PROTECTION METAL'), ('BOUCHE TROIS', 'BOUCHE TROIS')], max_length=50, verbose_name="DOMAINE D'APPLICATION"),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='type_produit',
            field=models.CharField(choices=[('MASTIC', 'MASTIC'), ('GALVA', 'GALVA'), ('ANTIROUILLE FER', 'ANTIROUILLE FER'), ('SATIN', 'SATIN'), ('ANTIROUILLE PLOMB', 'ANTIROUILLE PLOMB'), ('CHROMATE DE ZINC', 'CHROMATE DE ZINC'), ('VERNIS INT&EXT', 'VERNIS INT&EXT'), ('BOUCHE PORS', 'BOUCHE PORS'), ('VERNIS NOIR', 'VERNIS NOIR'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('PRIMER SURFACER', 'PRIMER SURFACER'), ('MENUICOL', 'MENUICOL'), ('PEINTURE AU LARO', 'PEINTURE AU LARO')], max_length=50, verbose_name=' TYPE DE PRODUIT'),
        ),
        migrations.AlterField(
            model_name='perforateur',
            name='format_perforateur',
            field=models.CharField(choices=[('DP 720', 'DP 720'), ('DP 750', 'DP 750'), ('DP 600', 'DP 600')], max_length=100, verbose_name='FORMAT DU PERFORATEUR'),
        ),
        migrations.AlterField(
            model_name='perforateur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangecarrosserie',
            name='type_piece_carosserie',
            field=models.CharField(choices=[('PHARE AVANT GAUCHE', 'PHARE AVANT GAUCHE'), ('PHARE AVANT DROIT', 'PHARE AVANT DROIT'), ('FEU ARRIERE GAUCHE', 'FEU ARRIERE GAUCHE'), ('FEU ARRIERE DROIT', 'FEU ARRIERE DROIT'), ('BALAI ESSUIE GLACE AVANT', 'BALAI ESSUIE GLACE AVANT'), ('RETROVISEUR GAUCHE', 'RETROVISEUR GAUCHE'), ('RETROVISEUR DROIT', 'RETROVISEUR DROIT')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangedirectionsuspension',
            name='type_piece_direction_suspension',
            field=models.CharField(choices=[('ROTULE DE DIRECTION EXTERIEURE GAUCHE', 'ROTULE DE DIRECTION EXTERIEURE GAUCHE'), ('ROTULE DE DIRECTION EXTERIEURE DROIT', 'ROTULE DE DIRECTION EXTERIEURE DROIT'), ('ROTULE DE DIRECTION INFERIEUR GAUCHE', 'ROTULE DE DIRECTION INFERIEUR GAUCHE'), ('ROTULE DE DIRECTION INFERIEUR DROIT', 'ROTULE DE DIRECTION INFERIEUR DROIT'), ('ROTULE DE SUSPENSION INFERIEURE GAUCHE', 'ROTULE DE SUSPENSION INFERIEURE GAUCHE'), ('ROTULE DE SUSPENSION INFERIEURE DROITE', 'ROTULE DE SUSPENSION INFERIEURE DROITE'), ('ROTULE DE SUSPENSION SUPERIEURE GAUCHE', 'ROTULE DE SUSPENSION SUPERIEURE GAUCHE'), ('ROTULE DE SUSPENSION SUPERIEURE DROITE', 'ROTULE DE SUSPENSION SUPERIEURE DROITE'), ('BRAS DE SUSPENSION INFERIEURE GAUCHE', 'BRAS DE SUSPENSION INFERIEURE GAUCHE'), ('BRAS DE SUSPENSION INFERIEURE DROITE', 'BRAS DE SUSPENSION INFERIEURE DROITE'), ('BRAS DE SUSPENSION SUPERIEUR GAUCHE', 'BRAS DE SUSPENSION SUPERIEUR GAUCHE'), ('BRAS DE SUSPENSION SUPERIEUR DROITE', 'BRAS DE SUSPENSION SUPERIEUR DROITE'), ('BIELLETTE STABILISATRICE AVANT GAUCHE', 'BIELLETTE STABILISATRICE AVANT GAUCHE'), ('BIELLETTE STABILISATRICE AVANT DROITE', 'BIELLETTE STABILISATRICE AVANT DROITE'), ('SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1', 'SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1'), ('SILEMBLOC BRAS DE SUSPENSION SUPERIEURE', 'SILEMBLOC BRAS DE SUSPENSION SUPERIEURE'), ('SILEMBLOC BRAS DE STABILISATION AV', 'SILEMBLOC BRAS DE STABILISATION AV'), ('AMORTISSEUR AVANT GAUCHE', 'AMORTISSEUR AVANT GAUCHE'), ('AMORTISSEUR AVANT DROIT', 'AMORTISSEUR AVANT DROIT'), ('AMORTISSEUR ARRIERE GAUCHE', 'AMORTISSEUR ARRIERE GAUCHE'), ('AMORTISSEUR ARRIERE DROIT', 'AMORTISSEUR ARRIERE DROIT'), ('LAME MAITRESSE', 'LAME MAITRESSE'), ('SILEMBLOC LAME INFERIEURE', 'SILEMBLOC LAME INFERIEURE'), ('SILEMBLOC LAME SUPERIEURE', 'SILEMBLOC LAME SUPERIEURE'), ('CREMAILLEUR DE DIRECTION', 'CREMAILLEUR DE DIRECTION'), ('POMPE DE DIRECTION', 'POMPE DE DIRECTION'), ('AMORTISSEUR DE DIRECTION', 'AMORTISSEUR DE DIRECTION'), ('SILEMBLOC BARRE STABILISATRICE ARRIERE', 'SILEMBLOC BARRE STABILISATRICE ARRIERE'), ('SILEMBLOC BARRE STABILISATRICE AVANT', 'SILEMBLOC BARRE STABILISATRICE AVANT'), ('BIELLETTE STABILISATRICE ARRIERE GAUCHE', 'BIELLETTE STABILISATRICE ARRIERE GAUCHE'), ('BIELLETTE STABILISATRICE ARRIERE DROITE', 'BIELLETTE STABILISATRICE ARRIERE DROITE'), ('BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE', 'BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE'), ('SILEMBLOC BARRE STABILISATRICE AV', 'SILEMBLOC BARRE STABILISATRICE AV'), ('BRAS DE SUSPENSION SUPERIEURE GAUCHE', 'BRAS DE SUSPENSION SUPERIEURE GAUCHE'), ('BRAS DE SUSPENSION SUPERIEURE DROITE', 'BRAS DE SUSPENSION SUPERIEURE DROITE'), ('SOUFFLET DE DIRECTION', 'SOUFFLET DE DIRECTION'), ('ROTULE DE DIRECTION INFERIEURE GAUCHE', 'ROTULE DE DIRECTION INFERIEURE GAUCHE'), ('ROTULE DE DIRECTION INFERIEURE DROITE', 'ROTULE DE DIRECTION INFERIEURE DROITE'), ('ROTULE DE DIRECTION EXTERIEURE GAUCHE', 'ROTULE DE DIRECTION EXTERIEURE GAUCHE'), ('ROTULE DE DIRECTION EXTERIEURE DROITE', 'ROTULE DE DIRECTION EXTERIEURE DROITE'), ('DEMARREUR', 'DEMARREUR'), ('SILEMBLOC BARRE STABILISATRICE AV 48815-60180', 'SILEMBLOC BARRE STABILISATRICE AV 48815-60180'), ('SILEMBLOC BARRE STABILISATRICE AV 48632-60020', 'SILEMBLOC BARRE STABILISATRICE AV 48632-60020'), ('SILEMBLOC BRAS DE SUSPENSION SUPERIEUR', 'SILEMBLOC BRAS DE SUSPENSION SUPERIEUR')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeelectrique',
            name='type_piece_electrique',
            field=models.CharField(choices=[('DEMARREUR', 'DEMARREUR'), ('ALTERNATEUR', 'ALTERNATEUR'), ('POMPE A VIDE ALTERNATEUR', 'POMPE A VIDE ALTERNATEUR'), ('CONTACTEUR PRESSION HUILE', 'CONTACTEUR PRESSION HUILE'), ('INTERRUPTEUR DE TEMPERATURE', 'INTERRUPTEUR DE TEMPERATURE'), ('RELAI DE DEMARRAGE', 'RELAI DE DEMARRAGE'), ('CONTACTEUR DE PRESSION D’HUILE', 'CONTACTEUR DE PRESSION D’HUILE')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangeembrayage',
            name='type_piece_embrayage',
            field=models.CharField(choices=[('DISQUE EMBRAYAGE', 'DISQUE EMBRAYAGE'), ('PLATEAU EMBRAYAGE', 'PLATEAU EMBRAYAGE'), ('BUTEE EMBRAYAGE', 'BUTEE EMBRAYAGE'), ('CYLINDRE RECEPTEUR', 'CYLINDRE RECEPTEUR'), ('CYLINDRE EMETTEUR', 'CYLINDRE EMETTEUR'), ('KIT DE REPARATION CYLINDRE EMETTEUR', 'KIT DE REPARATION CYLINDRE EMETTEUR'), ('KIT DE REPARATION CYLINDRE RECEPTEUR', 'KIT DE REPARATION CYLINDRE RECEPTEUR')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangefreinage',
            name='pieces_rechange_freinage',
            field=models.CharField(choices=[('PLAQUETTE DE FREIN AVANT', 'PLAQUETTE DE FREIN AVANT'), ('PLAQUETTE/MACHOIRE DE FREIN ARRIERE', 'PLAQUETTE/MACHOIRE DE FREIN ARRIERE'), ('DISQUE DE FREIN AVANT', 'DISQUE DE FREIN AVANT'), ('DISQUE/TAMBOUR DE FREIN ARRIERE', 'DISQUE/TAMBOUR DE FREIN ARRIERE'), ('CYLINDRE DE ROUE ARRIERE DROITE', 'CYLINDRE DE ROUE ARRIERE DROITE'), ('CYLINDRE DE ROUE ARRIERE GAUCHE', 'CYLINDRE DE ROUE ARRIERE GAUCHE'), ('MAITRE CYLINDRE DE FREIN', 'MAITRE CYLINDRE DE FREIN')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DE LA FIN DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangerefroidissement',
            name='type_piece_refroidissement',
            field=models.CharField(choices=[('POMPE A EAU', 'POMPE A EAU'), ('THERMOSTAT', 'THERMOSTAT'), ('COURROIE ALTERNATEUR', 'COURROIE ALTERNATEUR'), ('RADIATEUR', 'RADIATEUR'), ('BOUCHON RADIATEUR', 'BOUCHON RADIATEUR'), ('ACCOUPLEMENT HYDRAULIQUE', 'ACCOUPLEMENT HYDRAULIQUE'), ('VENTILATEUR', 'VENTILATEUR')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecederechangetransmission',
            name='type_piece_transmission',
            field=models.CharField(choices=[('KIT ROULEMENT DE ROUE AVANT DROIT', 'KIT ROULEMENT DE ROUE AVANT DROIT'), ('KIT ROULEMENT DE ROUE AVANT GAUCHE', 'KIT ROULEMENT DE ROUE AVANT GAUCHE'), ('GOUJON DE ROUE AVANT', 'GOUJON DE ROUE AVANT'), ('CROISILLON', 'CROISILLON'), ('CROISILLON 1', 'CROISILLON 1'), ('SOUFFLET DE TRANSMISSION', 'SOUFFLET DE TRANSMISSION'), ('KIT DE ROULEMENT ROUE ARRIERE', 'KIT DE ROULEMENT ROUE ARRIERE'), ('PALIER DE TRANSMISSION', 'PALIER DE TRANSMISSION'), ('ECROU DE ROUE ARRIERE', 'ECROU DE ROUE ARRIERE'), ('GOUJON DE ROUE ARRIERE', 'GOUJON DE ROUE ARRIERE'), ('KIT DE ROULEMENT ROUE AVANT DROITE', 'KIT DE ROULEMENT ROUE AVANT DROITE'), ('KIT DE ROULEMENT ROUE AVANT GAUCHE', 'KIT DE ROULEMENT ROUE AVANT GAUCHE'), ('MOYEU AVANT GAUCHE', 'MOYEU AVANT GAUCHE'), ('ECROU DE ROUE AVANT', 'ECROU DE ROUE AVANT')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='pieces_rechange_moteur',
            field=models.CharField(choices=[('FILTRE A HUILE', 'FILTRE A HUILE'), ('FILTRE A AIR', 'FILTRE A AIR'), ('FILTRE A CARBURANT', 'FILTRE A CARBURANT'), ('FILTRE HABITACLE', 'FILTRE HABITACLE'), ('BOUGIE', 'BOUGIE'), ('INJECTEUR', 'INJECTEUR'), ('COURROIE DIRECTION', 'COURROIE DIRECTION'), ('COURROIE DISTRIBUTION', 'COURROIE DISTRIBUTION'), ('POMPE A HUILE', 'POMPE A HUILE'), ('TURBO COMPRESSEUR', 'TURBO COMPRESSEUR'), ('SUPPORT MOTEUR', 'SUPPORT MOTEUR'), ('COURROIE COMPRESSEUR', 'COURROIE COMPRESSEUR'), ('TENDEUR DISTRIBUTION', 'TENDEUR DISTRIBUTION'), ('NEZ INJECTEUR', 'NEZ INJECTEUR'), ('FILTRE A CARBURANT  16405-01T0A', 'FILTRE A CARBURANT  16405-01T0A'), ('FILTRE A CARBURANT  16405-02N0A', 'FILTRE A CARBURANT  16405-02N0A'), ('INJECTEUR COMPLET', 'INJECTEUR COMPLET'), ('POMPE A CARBURANT', 'POMPE A CARBURANT'), ('COURROIE DE DISTRIBUTION', 'COURROIE DE DISTRIBUTION'), ('TENDEUR ALTERNATEUR', 'TENDEUR ALTERNATEUR')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='annee_debut',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='annee_fin',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50, verbose_name='ANNEE DU DEBUT DE FABRICATION DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='piecerevisionmoteur',
            name='pieces_revision_moteur',
            field=models.CharField(choices=[('POCHETTE DE JOINT', 'POCHETTE DE JOINT'), ('JOINT DE CULASSE', 'JOINT DE CULASSE'), ('SEGMENTS', 'SEGMENTS'), ('BOURRAGE MOTEUR BOUR04403', 'BOURRAGE MOTEUR BOUR04403'), ('RETIENT HUILE', 'RETIENT HUILE'), ('COUSSINET PALIER', 'COUSSINET PALIER'), ('COUSSINET BIELLE', 'COUSSINET BIELLE'), ('BOURRAGE MOTEUR ', 'BOURRAGE MOTEUR '), ('CHEMISE(JEU DE 4 PCES)', 'CHEMISE(JEU DE 4 PCES)'), ('PISTON(SANS SEGMENT)', 'PISTON(SANS SEGMENT)'), ('CHEMISE (JEU DE 4 PIECES)', 'CHEMISE (JEU DE 4 PIECES)'), ('PISTON (SANS SEGMENT)', 'PISTON (SANS SEGMENT)'), ('ROULEMENT MOYEU ARRIERE', 'ROULEMENT MOYEU ARRIERE'), ('GOUJON DE ROUE ARRIERE', 'GOUJON DE ROUE ARRIERE'), ('CROISILLON 2', 'CROISILLON 2'), ('CROISILLON 1', 'CROISILLON 1'), ('BOURRAGE MOTEUR', 'BOURRAGE MOTEUR'), ('BIELLE MOTEUR', 'BIELLE MOTEUR'), ('COUSSINET LATERAL', 'COUSSINET LATERAL')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='format_pile',
            field=models.CharField(choices=[('CRAYON', 'CRAYON'), ('GRAND', 'GRAND'), ('TOUCHE', 'TOUCHE')], max_length=100, verbose_name='FORMAT DE LA PILE'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='pinceau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10000<', '10000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='plafonnierled',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='plantoir',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='plaqueafacedoublepoursocketmural',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='poincon',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='poisson',
            name='type_de_poisson',
            field=models.CharField(choices=[('MUNGUSU', 'MUNGUSU'), ('MOJOMBO', 'MOJOMBO'), ('MINZANDA', 'MINZANDA'), ('MGOMGO', 'MGOMGO'), ('CAPITAINE', 'CAPITAINE'), ('MBOTO', 'MBOTO'), ('MINZANDA', 'MINZANDA'), ('NGOLO', 'NGOLO'), ('SOLE MOYENNE', 'SOLE MOYENNE'), ('GRANDE SOLE', 'GRANDE SOLE'), ('CAPITAINE MOYEN', 'CAPITAINE MOYEN'), ('GRAND CAPITAINE', 'GRAND CAPITAINE'), ('FILET DE CAPITAINE', 'FILET DE CAPITAINE'), ('PERCHE', 'PERCHE'), ('FILET DE PERCHE', 'FILET DE PERCHE'), ('MEROU', 'MEROU'), ('RAIE (MAZIBA)', 'RAIE (MAZIBA)'), ('AILE DE RAIE', 'AILE DE RAIE'), ('ROUGET', 'ROUGET'), ('SAINT PIERRE', 'SAINT PIERRE'), ('BARRACUDA', 'BARRACUDA'), ('COSSA MOYEN MOANDA', 'COSSA MOYEN MOANDA'), ('COSSA MOYEN POINTE NOIRE', 'COSSA MOYEN POINTE NOIRE'), ('COSSA ROYALE POINTE NOIRE', 'COSSA ROYALE POINTE NOIRE'), ('PETITE LANGOUSTE MOANDA', 'PETITE LANGOUSTE MOANDA'), ('LANGOUSTE MOYENNE POINTE NOIRE', 'LANGOUSTE MOYENNE POINTE NOIRE'), ('GRANDE LANGOUSTE POINTE NOIRE', 'GRANDE LANGOUSTE POINTE NOIRE'), ('PIEUVRE POINTE NOIR', 'PIEUVRE POINTE NOIR'), ('CRABE', 'CRABE'), ('CALAMARD', 'CALAMARD'), ('SECHE', 'SECHE'), ('COSSA DECORTIQUE', 'COSSA DECORTIQUE'), ('MORUE', 'MORUE'), ('CROQUETTES POISSON 10PCS', 'CROQUETTES POISSON 10PCS'), ('CROQUETTES COSSA 10PCS', 'CROQUETTES COSSA 10PCS'), ('CROQUETTE MORUE 10PCS', 'CROQUETTE MORUE 10PCS')], max_length=50, verbose_name='TYPE DE POISSON'),
        ),
        migrations.AlterField(
            model_name='pompeimmergee',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='portecle',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000'), ('10000<', '10000<'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='porteclef',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='dimension_postit',
            field=models.CharField(choices=[('76X76MM', '76X76MM'), ('125X75MM', '125X75MM')], max_length=100, verbose_name='DIMENSION EN MILLIMETRE'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='type_postit',
            field=models.CharField(choices=[('CARRE', 'CARRE'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=100, verbose_name='TYPE DE POST-IT'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='units',
            field=models.CharField(choices=[('USD/CARNET', 'USD/CARNET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='postproduction',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='poubelleuac',
            name='volume',
            field=models.CharField(choices=[('12L', '12L'), ('30L', '30L'), ('8L', '8L'), ('20L', '20L'), ('6L', '6L')], max_length=100, verbose_name='VOLUME EN LITRE'),
        ),
        migrations.AlterField(
            model_name='presencephysiquesurplateau',
            name='units',
            field=models.CharField(choices=[('USD/MIN', 'USD/MIN')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='presentoir',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='priseelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='prisewifi',
            name='modele_prise',
            field=models.CharField(choices=[('HS 100', 'HS 100'), ('HS 110', 'HS 110')], max_length=100, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='processeur',
            name='marque_processeur',
            field=models.CharField(choices=[('INTEL', 'INTEL')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='processeur',
            name='modele_processeur',
            field=models.CharField(choices=[('P4', 'P4')], max_length=100, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='productiontournage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='projecteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='protectiondetravail',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='publicitesurplateau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='punaise',
            name='units',
            field=models.CharField(choices=[('USD/BOITE', 'USD/BOITE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='raboteuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='nombre_prise',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8')], max_length=20, verbose_name='NOMBRE DE PRISE'),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='rallonge',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='registreindicateurdecourrier',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='reglette',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='intensite',
            field=models.CharField(choices=[('9A', '9A'), ('12A', '12A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('30A', '30A'), ('40A', '40A'), ('45A', '45A'), ('50A', '50A'), ('60A', '60A'), ('63A', '63A'), ('64A', '64A'), ('80A', '80A'), ('85A', '85A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='type_regulation',
            field=models.CharField(choices=[('PWM', 'PWM'), ('MPPT', 'MPPT')], max_length=20, verbose_name='TYPE DE REGULATION'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='reparationinstallationsolaire',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='reparationsplit',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='reportagetelepromo',
            name='type_telepromo',
            field=models.CharField(choices=[('REPORTAGE DANS JOURNAL TELEVISE', 'REPORTAGE DANS JOURNAL TELEVISE'), ('INVITE DU JOURNAL TELEVISE', 'INVITE DU JOURNAL TELEVISE')], max_length=100, verbose_name='TYPE DE TELEPROMO'),
        ),
        migrations.AlterField(
            model_name='reportagetelepromo',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='retransmissiondirect',
            name='duree_retransmission',
            field=models.CharField(choices=[('1 HEURE', '1 HEURE'), ('3 HEURES', '3 HEURES')], max_length=100, verbose_name='DUREE DE LA RETRANSMISSION'),
        ),

    ]
