# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0410_auto_20180531_1237'),
    ]

    operations = [

        migrations.AlterField(
            model_name='teflon',
            name='modele_teflon',
            field=models.CharField(choices=[('GRAND MODELE', 'GRAND MODELE'), ('PETIT MODELE', 'PETIT MODELE')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='teflon',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='telephonebureau',
            name='marque',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('SUPREMA', 'SUPREMA'), ('PROLINE', 'PROLINE'), ('TELEMECA', 'TELEMECA'), ('NEC', 'NEC')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='telephonebureau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tenaille',
            name='dimension_tenaille',
            field=models.CharField(choices=[('6’’', '6’’'), ('8’’', '8’’')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='tenaille',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tente',
            name='dimension',
            field=models.CharField(choices=[('3Mx3M', '3Mx3M')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='tente',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='testeurdecable',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tetedevisseuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='toiture',
            name='dimension',
            field=models.CharField(choices=[('1,7MX0,4M', '1,7MX0,4M')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='toiture',
            name='type_toiture',
            field=models.CharField(choices=[('TOLE SABLE', 'TOLE SABLE'), ('TUILE SABLE', 'TUILE SABLE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='toiture',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='puissance_tondeuse',
            field=models.CharField(choices=[('12800W', '12800W'), ('4500W', '4500W'), ('1300W', '1300W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='touretameulet',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tourteau',
            name='base',
            field=models.CharField(choices=[('TOURNESOL', 'TOURNESOL'), ('TAPIOCA', 'TAPIOCA')], max_length=100, verbose_name='PRODUIT DE BASE'),
        ),
        migrations.AlterField(
            model_name='transparentareliure',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='treillis',
            name='dimension',
            field=models.CharField(choices=[('1Mx25M', '1Mx25M'), ('2Mx25M', '2Mx25M')], max_length=100, verbose_name='DIMENSION (METRE X METRE)'),
        ),
        migrations.AlterField(
            model_name='treillis',
            name='type_treillis',
            field=models.CharField(choices=[('MAISON', 'MAISON'), ('MAILLE CARRE GRAND', 'MAILLE CARRE GRAND'), ('MAILLE CARRE PETIT', 'MAILLE CARRE PETIT'), ('MAILLE HEXAGONALE', 'MAILLE HEXAGONALE'), ('CARRE FERME', 'CARRE FERME')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='treillis',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='triplex',
            name='epaisseur',
            field=models.CharField(choices=[('10MM', '10MM'), ('5MM', '5MM'), ('8MM', '8MM'), ('10MM', '10MM')], max_length=100, verbose_name='EPAISSEUR'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='marque',
            field=models.CharField(choices=[('EINHELL', 'EINHELL'), ('ELEMAX', 'ELEMAX'), ('EMERGY', 'EMERGY'), ('DEWALT', 'DEWALT'), ('IMO ITALIA', 'IMO ITALIA'), ('MAKITA', 'MAKITA'), ('STIHL', 'STIHL'), ('ROBEN', 'ROBEN'), ('SACO', 'SACO'), ('TALA', 'TALA'), ('DEUTZ', 'DEUTZ'), ('PERKINS', 'PERKINS'), ('ITALIAN POINT', 'ITALIAN POINT')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='modele_tronconneuse',
            field=models.CharField(choices=[('090', '090'), ('070', '070'), ('AV 070', 'AV 070')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='tronconneuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='trousseaoutil',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000'), ('10000<', '10000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='type_tshirt',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=50, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='tshirtblanc',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='type_tube',
            field=models.CharField(choices=[('FLUORESCENT', 'FLUORESCENT'), ('LED', 'LED')], max_length=20, verbose_name='TYPE DE TUBE'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tuyauarrosage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tuyaumotopompe',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='tuyauterie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='unite_stockage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='unitealimlentationcameraccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='vase',
            name='dimension_carreau',
            field=models.CharField(choices=[('24x40', '24x40'), ('29x31', '29x31'), ('34x60', '34x60'), ('36x36', '36x36'), ('40x43', '40x43'), ('42x78', '42x78'), ('44x80', '44x80'), ('50x20', '50x20'), ('60x30', '60x30'), ('80x40', '80x40')], max_length=100, verbose_name='DIMENSION DU CARREAU'),
        ),
        migrations.AlterField(
            model_name='veloelliptique',
            name='modele',
            field=models.CharField(choices=[('ORBITRAC', 'ORBITRAC')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='veloelliptique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='velomagnetique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ventilateurcartemere',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ventilateurplafonier',
            name='dimension_ventilateur',
            field=models.CharField(choices=[('48’’', '48’’'), ('56’’', '56’’')], max_length=100, verbose_name='DIMENSION DU VENTILATEUR'),
        ),
        migrations.AlterField(
            model_name='ventilateurplafonier',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='videoprojecteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='vismetallique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='visseuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='visseuseelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='voiturejeepbus',
            name='type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'VOITURE'), ('JEEP', 'JEEP'), ('MINIBUS', 'MINIBUS'), ('BUS', 'BUS')], max_length=100, verbose_name='TYPE DE VEHICULE'),
        ),
        migrations.AlterField(
            model_name='wc',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='type_webcam',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('HD', 'HD')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='xstand',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='xstand',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
    ]
