# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0411_auto_20180531_1403'),
    ]

    operations = [

        migrations.AlterField(
            model_name='hublot',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='hubusb',
            name='type_hub',
            field=models.CharField(choices=[('3 PORTS AVEC ETHERNET RJ45', '3 PORTS AVEC ETHERNET RJ45'), ('7 PORTS', '7 PORTS'), ('LECTEUR CARTE MEMOIRE', 'LECTEUR CARTE MEMOIRE'), ('4 PORTS', '4 PORTS'), ('3 PORTS AVEC LECTEUR CARTE MEMOIRE', '3 PORTS AVEC LECTEUR CARTE MEMOIRE'), ('4 PORT SMART HUB', '4 PORT SMART HUB')], max_length=100, verbose_name='TYPE DE HUB'),
        ),
        migrations.AlterField(
            model_name='hubusb',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='huile',
            name='base',
            field=models.CharField(choices=[('TOURNESOL', 'TOURNESOL'), ('TAPIOCA', 'TAPIOCA')], max_length=100, verbose_name='PRODUIT DE BASE'),
        ),
        migrations.AlterField(
            model_name='impermeable',
            name='type_impermeable',
            field=models.CharField(choices=[('ROBE', 'ROBE'), ('COMPLET', 'COMPLET')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='impermeable',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressionabs',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='impressionbanderole',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressiononeway',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressionsurbriquet',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressionsurpapierphoto',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='impressiontasse',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='couleur',
            field=models.CharField(choices=[('COULEUR', 'COULEUR'), ('NOIR ET BLANC', 'NOIR ET BLANC')], max_length=50, verbose_name="COULEUR D'IMPRESSION"),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='format_max_papier',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], max_length=50, verbose_name='FORMAT MAXIMUM'),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='marque_imprimante',
            field=models.CharField(choices=[('HP', 'HP'), ('CANON', 'CANON'), ('EPSON', 'EPSON'), ('SAMSUNG', 'SAMSUNG'), ('BROTHER', 'BROTHER')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='multifonction',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=50, verbose_name='OPTION MULTIFONCTION'),
        ),
        migrations.AlterField(
            model_name='imprimante',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='imprimanteabadge',
            name='marque_imprimante_badge',
            field=models.CharField(choices=[('EVOLIS', 'EVOLIS')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='imprimanteabadge',
            name='technologe_impression_badge',
            field=models.CharField(choices=[('TRANSFERT THERMIQUE', 'TRANSFERT THERMIQUE'), ('RETRANSFERT', 'RETRANSFERT')], max_length=100, verbose_name="TECHNOLOGIE D'IMPRESSION"),
        ),
        migrations.AlterField(
            model_name='imprimanteabadge',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='imprimanteetiquette',
            name='modele_imprimante_etiquette',
            field=models.CharField(choices=[('P-TOUCH PC QL-720NW', 'P-TOUCH PC QL-720NW'), ('P-TOUCH PT-E300VP', 'P-TOUCH PT-E300VP'), ('P-TOUCH QL-1050', 'P-TOUCH QL-1050')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='imprimanteetiquette',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='imprimantephoto',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='insertionpublicitaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='installationlogicielserveur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='installationreseauinformatique',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='installationreseautelephonique',
            name='units',
            field=models.CharField(choices=[('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='installationsanitaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='installationsolaire',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='integrationcustomisationstandard',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='intercalaire',
            name='units',
            field=models.CharField(choices=[('USD/JEU', 'USD/JEU')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='interrupteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='sensibilite',
            field=models.CharField(choices=[('30MA', '30MA'), ('300MA', '300MA')], max_length=50, verbose_name='SENSIBILITTE EN MILLIAMPERE'),
        ),
        migrations.AlterField(
            model_name='interrupteurdifferentiel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='interrupteurelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='interrupteursectionneur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='intensite',
            field=models.CharField(choices=[('63A', '63A'), ('100A', '100A'), ('125A', '125A'), ('160A', '160A'), ('200A', '200A')], max_length=50, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='inverseur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='inverseurcoffret',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='karcher',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='kitaccessoiressplit',
            name='puissance_split',
            field=models.CharField(choices=[('12000BTU', '12000BTU'), ('18000BTU', '18000BTU'), ('24000BTU', '24000BTU')], max_length=100, verbose_name='PUISSANCE DU SPLIT'),
        ),
        migrations.AlterField(
            model_name='kitaccessoiressplit',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='kitdenettoyageimprimante',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='lamedescie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='lampetorche',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-1000', '101-1000'), ('1001-10000', '1001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='laniere',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='latte',
            name='longueur',
            field=models.CharField(choices=[('30CM', '30CM'), ('50CM', '50CM'), ('3M', '3M'), ('23M', '23M'), ('100M', '100M'), ('250M', '250M')], max_length=100, verbose_name='LONGUEUR EN CENTIMETRE'),
        ),
        migrations.AlterField(
            model_name='latte',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='lecteurdvd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='legume',
            name='type_legume',
            field=models.CharField(choices=[('AUBERGINE', 'AUBERGINE'), ('GOMBO', 'GOMBO'), ('TOMATE', 'TOMATE'), ('AVOCAT', 'AVOCAT'), ('POMME DE TERRE LOCAL', 'POMME DE TERRE LOCAL'), ('OIGNON BLANC', 'OIGNON BLANC'), ('POMME DE TERRE DE GOMA', 'POMME DE TERRE DE GOMA'), ('OIGNON ROUGE', 'OIGNON ROUGE'), ('HARICOT DE GOMA', 'HARICOT DE GOMA'), ('HARICOT PRINCESSE', 'HARICOT PRINCESSE'), ('HARICOT GOMA 1ER CHOIX', 'HARICOT GOMA 1ER CHOIX')], max_length=50, verbose_name='TYPE DE LEGUME'),
        ),
        migrations.AlterField(
            model_name='lentillecameraccd',
            name='distance_focale',
            field=models.CharField(choices=[('6MM', '6MM'), ('8MM', '8MM'), ('12MM', '12MM'), ('16MM', '16MM')], max_length=100, verbose_name='DISTANCE FOCALE'),
        ),
        migrations.AlterField(
            model_name='lentillecameraccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='locationstand',
            name='surface_stand',
            field=models.CharField(choices=[('6M2', '6M2'), ('9M2', '9M2'), ('12M2', '12M2')], max_length=100, verbose_name='SURFACE EN M2'),
        ),
        migrations.AlterField(
            model_name='locationstudio',
            name='duree_location',
            field=models.CharField(choices=[('30 MIN', '30 MIN'), ('1H', '1H')], max_length=100, verbose_name='DUREE DE LOCATION'),
        ),
        migrations.AlterField(
            model_name='locationstudio',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='machineagricole',
            name='consommation',
            field=models.CharField(choices=[('0,7L/H', '0,7L/H')], max_length=100, verbose_name='CONSOMMATION EN LITRE/HEURE'),
        ),
        migrations.AlterField(
            model_name='machineagricole',
            name='puissance',
            field=models.CharField(choices=[('3,5 CV', '3,5 CV')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='machineagricole',
            name='rendement',
            field=models.CharField(choices=[('600KG/HEURE', '600KG/HEURE')], max_length=100, verbose_name='RENDEMENT EN KILOGRAMME/HEURE'),
        ),
        migrations.AlterField(
            model_name='machineagricole',
            name='type_machine_agricole',
            field=models.CharField(choices=[('DECORTIQUEUSE MAIS', 'DECORTIQUEUSE MAIS'), ('MOULIN CEREALES', 'MOULIN CEREALES')], max_length=100, verbose_name='TYPE DE MACHINE AGRICOLE'),
        ),
        migrations.AlterField(
            model_name='machineagricole',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='machineateliernonportatif',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='machineatelierportatif',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='machinecreme',
            name='puissance',
            field=models.CharField(choices=[('2,6 KW', '2,6 KW')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='machinecreme',
            name='volume',
            field=models.CharField(choices=[('36 L', '36 L')], max_length=100, verbose_name='VOLUME'),
        ),
        migrations.AlterField(
            model_name='maintenancebackup',
            name='units',
            field=models.CharField(choices=[('USD/MOIS', 'USD/MOIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='marqueur',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='marteau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='mechebeton',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='mechebeton',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='melangeur',
            name='puissance',
            field=models.CharField(choices=[('1600W', '1600W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='melangeur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='type_memoire',
            field=models.CharField(choices=[('DDR1', 'DDR1'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=100, verbose_name='TYPE DE MEMOIRE'),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='meuleuse',
            name='puissance_meuleuse',
            field=models.CharField(choices=[('2200W', '2200W'), ('3000W', '3000W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='meuleuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='microonde',
            name='puissance',
            field=models.CharField(choices=[('1000W', '1000W'), ('800W', '800W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='microonde',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='microphonepourcameraip',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='minuteurcontacteur',
            name='domaine_reglage',
            field=models.CharField(choices=[('0.1..3S', '0.1..3S'), ('0.1..30S', '0.1..30S'), ('10..180S', '10..180S')], max_length=100, verbose_name='DOMAINE DE REGLAGE EN SECONDES'),
        ),
        migrations.AlterField(
            model_name='minuteurcontacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='modemwifi',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='moellon',
            name='type_moellon',
            field=models.CharField(choices=[('CAILLASSE', 'CAILLASSE'), ('MOELLON', 'MOELLON')], max_length=100, verbose_name='TYPE DE MOELLON'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('ACER', 'ACER'), ('DELL', 'DELL')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='taille_ecran',
            field=models.CharField(choices=[('18.5"', '18.5"'), ('19.5"', '19.5"'), ('20"', '20"'), ('22"', '22"'), ('23"', '23"')], max_length=100, verbose_name='TAILLE'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='type_ecran',
            field=models.CharField(choices=[('LED', 'LED')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='montecharge',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='montecharge',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='nombre_cylindres',
            field=models.CharField(blank=True, choices=[('6', '6'), ('8', '8'), ('10', '10')], max_length=100, null=True, verbose_name='NOMBRE DE CYLINDRE'),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='moteurelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='puissance_moteur',
            field=models.CharField(choices=[('100CC', '100CC'), ('125CC', '125CC'), ('160CC', '160CC'), ('180CC', '180CC'), ('200CC', '200CC')], max_length=100, verbose_name='PUISSANCE DU MOTEUR'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='type_demarrage',
            field=models.CharField(choices=[('DEMARRAGE AU KICK', 'DEMARRAGE AU KICK'), ('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE')], max_length=100, verbose_name='TYPE DE DEMARRAGE'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='type_usage',
            field=models.CharField(choices=[('USAGE COMMERCIAL', 'USAGE COMMERCIAL'), ('USAGE PERSONNEL', 'USAGE PERSONNEL')], max_length=100, verbose_name="TYPE D'USAGE"),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='motopompe',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='puissance_moteur',
            field=models.CharField(choices=[('100CC', '100CC'), ('125CC', '125CC'), ('160CC', '160CC'), ('180CC', '180CC'), ('200CC', '200CC')], max_length=100, verbose_name='PUISSANCE DUMOTEUR'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='type_demarrage',
            field=models.CharField(choices=[('DEMARRAGE AU KICK', 'DEMARRAGE AU KICK'), ('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE')], max_length=100, verbose_name='TYPE DE DEMARRAGE'),
        ),
        migrations.AlterField(
            model_name='moussenettoyante',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='nettoyeurhautepression',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='numerisationdonnees',
            name='units',
            field=models.CharField(choices=[('USD/PAGE', 'USD/PAGE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='onduleur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='outillagemanuel',
            name='type_outillage',
            field=models.CharField(choices=[('RATEAU', 'RATEAU'), ('PELLE', 'PELLE'), ('MACHETTE', 'MACHETTE'), ('ARROSOIR', 'ARROSOIR'), ('HACHE', 'HACHE')], max_length=100, verbose_name="TYPE D'OUTILLAGE"),
        ),
        migrations.AlterField(
            model_name='outillagemanuel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='outilsertissage',
            name='modele_outil_sertissage',
            field=models.CharField(choices=[('TL-2810', 'TL-2810'), ('TL-315', 'TL-315'), ('TL-568', 'TL-568')], max_length=100, verbose_name="MODELE D'OUTIL DE SERTISSAGE"),
        ),
        migrations.AlterField(
            model_name='outilsertissage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='palan',
            name='longueur',
            field=models.CharField(choices=[('10M', '10M')], max_length=100, verbose_name='LONGUEUR EN METRE'),
        ),
        migrations.AlterField(
            model_name='palan',
            name='poids_max',
            field=models.CharField(choices=[('3T', '3T'), ('5T', '5T')], max_length=100, verbose_name='POIDS MAX EN TONNE'),
        ),
        migrations.AlterField(
            model_name='panneausignalisation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='panneausignalisation',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='parasoleil',
            name='diametre',
            field=models.CharField(choices=[('120CM', '120CM'), ('125CM', '125CM')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='patchcord',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='photocopieuse',
            name='format_max_papier',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], max_length=50, verbose_name='FORMAT MAXIMUM'),
        ),
        migrations.AlterField(
            model_name='photocopieuse',
            name='reseau',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=50, verbose_name='CONNEXION RESEAU'),
        ),
        migrations.AlterField(
            model_name='photocopieuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='poele',
            name='format_poele',
            field=models.CharField(choices=[('20 CM', '20 CM'), ('22 CM', '22 CM'), ('24 CM', '24 CM'), ('26 CM', '26 CM'), ('28 CM', '28 CM'), ('30 CM', '30 CM'), ('40 CM', '40 CM')], max_length=100, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='pointacces',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='pompeeau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(choices=[('LES PRINCIPALES PREOCCUPATIOS DES CONGOLAIS', 'LES PRINCIPALES PREOCCUPATIOS DES CONGOLAIS'), ('STATISTIQUES SUR LES MEDIAS A KINSHASA', 'STATISTIQUES SUR LES MEDIAS A KINSHASA')], max_length=100, verbose_name='TITRE'),
        ),
        migrations.AlterField(
            model_name='redactionprocedures',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYÉS"),
        ),
        migrations.AlterField(
            model_name='redactionprocedures',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='sonnerieelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='souffleuraspirateur',
            name='puissance_machine',
            field=models.CharField(choices=[('800W', '800W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='souffleuraspirateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='souligneur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='souris',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='split',
            name='puissance',
            field=models.CharField(choices=[('9000 BTU', '9000 BTU'), ('12000 BTU', '12000 BTU'), ('18000 BTU', '18000 BTU'), ('24000 BTU', '24000 BTU')], max_length=20, verbose_name='PUISSANCE DU SPLIT'),
        ),
        migrations.AlterField(
            model_name='split',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='spray',
            name='couleur_spray',
            field=models.CharField(choices=[('BLEU', 'BLEU'), ('NOIR', 'NOIR'), ('ROUGE', 'ROUGE'), ('JAUNE', 'JAUNE'), ('VERT', 'VERT')], max_length=100, verbose_name='COULEUR'),
        ),
        migrations.AlterField(
            model_name='spray',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='stabilisateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='standlaptop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10001-50000', '10001-50000'), ('50001-100000', '50001-100000'), ('100000<', '100000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='type_stylo',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=50, verbose_name='TYPE DE STYLO'),
        ),
        migrations.AlterField(
            model_name='stylo',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='stylofeutre',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='stylopapeterie',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='nombre_port',
            field=models.CharField(choices=[('5 PORTS', '5 PORTS'), ('8 PORTS', '8 PORTS'), ('16 PORTS', '16 PORTS'), ('24 PORTS', '24 PORTS'), ('48 PORTS', '48 PORTS')], max_length=50, verbose_name='NOMBRE DE PORTS'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='type_equipement',
            field=models.CharField(choices=[('SWITCH', 'SWITCH')], max_length=50, verbose_name="TYPE D'EQUIPEMENT"),
        ),
        migrations.AlterField(
            model_name='switch',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='switchhdmi',
            name='marque',
            field=models.CharField(choices=[('S-TEK', 'S-TEK')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='switchhdmi',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='switchkvm',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='dimension_tableau',
            field=models.CharField(choices=[('60X60 CM ', '60X60 CM '), ('50X40 CM', '50X40 CM')], max_length=20, verbose_name='DIMENSION DU TABLEAU'),
        ),
        migrations.AlterField(
            model_name='tableaublanc',
            name='dimension',
            field=models.CharField(choices=[('100x150CM', '100x150CM')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='tableaublanc',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tableplastique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tablette',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tambour',
            name='marque',
            field=models.CharField(choices=[('BROTHER', 'BROTHER'), ('CANNON', 'CANNON')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='tambour',
            name='numero',
            field=models.CharField(choices=[('DR 2125', 'DR 2125'), ('DR 2255', 'DR 2255'), ('DR 240CL', 'DR 240CL'), ('DR 261CL', 'DR 261CL'), ('DR 3215', 'DR 3215'), ('IR-1018', 'IR-1018')], max_length=100, verbose_name='NUMERO'),
        ),
        migrations.AlterField(
            model_name='tambour',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tapisdecourse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='tapissouris',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
    ]
