# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0412_auto_20180531_1415'),
    ]

    operations = [

        migrations.RenameField(
            model_name='photocopieuse',
            old_name='marque_imprimante',
            new_name='marque_photocopieuse',
        ),
        migrations.RemoveField(
            model_name='appareildemesure',
            name='unite_prix',
        ),
        migrations.RemoveField(
            model_name='coffretelectrique',
            name='encastre_sailli',
        ),
        migrations.RemoveField(
            model_name='souris',
            name='avec_fil',
        ),
        migrations.AddField(
            model_name='coffretelectrique',
            name='type_installation',
            field=models.CharField(choices=[('SAILLI', 'SAILLI'), ('ENCASTRE', 'ENCASTRE')], default=1, max_length=20, verbose_name="TYPE D'INSTALLATION"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='souris',
            name='technologie',
            field=models.CharField(choices=[('AVEC FIL', 'AVEC FIL'), ('SANS FIL', 'SANS FIL')], default=1, max_length=50, verbose_name='TECHNOLOGIE'),
            preserve_default=False,
        ),

    ]
