# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0413_auto_20180531_1458'),
    ]

    operations = [

        migrations.AlterField(
            model_name='disjoncteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcompact',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurcontacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='sensibilite',
            field=models.CharField(choices=[('30MA', '30MA'), ('300MA', '300MA')], max_length=100, verbose_name='SENSIBILITE EN MILLIAMPERE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurdifferentiel',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='intensite',
            field=models.CharField(choices=[('6-10A', '6-10A'), ('13-17A', '13-17A'), ('17-23A', '17-23A')], max_length=50, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='disjoncteurmoteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disquedescie',
            name='diametre',
            field=models.CharField(choices=[('105MM', '105MM'), ('115MM', '115MM'), ('125MM', '125MM'), ('180MM', '180MM'), ('230MM', '230MM'), ('300MM', '300MM'), ('350MM', '350MM'), ('400MM', '400MM'), ('500MM', '500MM'), ('305MM', '305MM')], max_length=100, verbose_name='DIAMETRE DU DISQUE'),
        ),
        migrations.AlterField(
            model_name='disquedescie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='distributeurelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ecouteurmicro',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ecranprojection',
            name='dimension',
            field=models.CharField(choices=[('150x150MM', '150x150MM'), ('200x200MM', '200x200MM'), ('240x240MM', '240x240MM'), ('223x120MM', '223x120MM')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='ecranprojection',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ecritoire',
            name='matiere_ecritoire',
            field=models.CharField(choices=[('BOIS', 'BOIS'), ('PLASTIQUE', 'PLASTIQUE')], max_length=100, verbose_name="MATIERE DE L'ECRITOIRE"),
        ),
        migrations.AlterField(
            model_name='ecritoire',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ecriturescenario',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='elastiques',
            name='quantite',
            field=models.CharField(choices=[('10 BOITES', '10 BOITES'), ('500GR', '500GR')], max_length=100, verbose_name='QUANTITE EN GRAMMES'),
        ),
        migrations.AlterField(
            model_name='elastiques',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='enregistreurcamerasurveillance',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='enregistreurcamerasurveillance',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='enregistreurccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='format_enseigne',
            field=models.CharField(choices=[('GRAND FORMAT', 'GRAND FORMAT'), ('PETIT FORMAT', 'PETIT FORMAT')], max_length=20, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='enseignelumineuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ensemblepoidsmuscul',
            name='poids',
            field=models.CharField(choices=[('50KG', '50KG')], max_length=100, verbose_name='POIDS'),
        ),
        migrations.AlterField(
            model_name='ensemblepoidsmuscul',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='enveloppe',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='equerre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='equerre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='equipementbluetoothportable',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='equipementcpe',
            name='marque_cpe',
            field=models.CharField(choices=[('TP-LINK', 'TP-LINK')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='equipementcpe',
            name='modele_cpe',
            field=models.CharField(choices=[('CPE210', 'CPE210'), ('WBS210', 'WBS210')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='equipementcpe',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='escortefonds',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='largeur',
            field=models.CharField(choices=[('27,5CM', '27,5CM'), ('30CM', '30CM'), ('37,5CM', '37,5CM'), ('78CM', '78CM')], max_length=20, verbose_name='LARGEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='longueur',
            field=models.CharField(choices=[('120CM', '120CM'), ('140CM', '140CM'), ('150CM', '150CM'), ('160CM', '160CM'), ('170CM', '170CM'), ('180CM', '180CM')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='materiau_armoire',
            field=models.CharField(choices=[('BOIS AGGLOMERE', 'BOIS AGGLOMERE'), ('METAL', 'METAL')], max_length=20, verbose_name='MATERIAU '),
        ),
        migrations.AlterField(
            model_name='etiquettedymo',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='etui',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='evacuationdesdechets',
            name='units',
            field=models.CharField(choices=[('USD/MOIS', 'USD/MOIS')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='evenementdemasse',
            name='type_evenement_de_masse',
            field=models.CharField(choices=[('CARAVANE MOTORISE', 'CARAVANE MOTORISE'), ('EVENEMENT MASSE', 'EVENEMENT MASSE'), ('EVENEMENT CORPORATE', 'EVENEMENT CORPORATE'), ('EVENEMENT PREMIUM', 'EVENEMENT PREMIUM')], max_length=100, verbose_name="TYPE D'EVENEMENT"),
        ),
        migrations.AlterField(
            model_name='evenementdemasse',
            name='units',
            field=models.CharField(choices=[('%', '%')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='extincteur',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='extincteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='farde',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='filbarbele',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='filplastique',
            name='section',
            field=models.CharField(choices=[('4', '4'), ('6', '6'), ('10', '10'), ('16', '16'), ('25', '25'), ('35', '35'), ('50MM2', '50MM2'), ('3X2,5MM2', '3X2,5MM2'), ('3X1,5MM2', '3X1,5MM2')], max_length=20, verbose_name='SECTION EN MILLIMETRE CARRÉ'),
        ),
        migrations.AlterField(
            model_name='filplastique',
            name='units',
            field=models.CharField(choices=[('USD/M', 'USD/M')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='filtreaeau',
            name='dimension',
            field=models.CharField(choices=[('10’’', '10’’')], max_length=100, verbose_name='DIMENSION EN POUCE'),
        ),
        migrations.AlterField(
            model_name='filtreaeau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='fixationtv',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='fixeur',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='flexible',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='flexible',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50, verbose_name='FACE A IMPRIMER'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='quantite',
            field=models.CharField(choices=[('20000<', '20000<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000'), ('1-500', '1-500')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='fontaineeau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='foreuseperceuse',
            name='type_de_perceuse',
            field=models.CharField(choices=[('FOREUSE', 'FOREUSE'), ('FOREUSE A PERCUSSION', 'FOREUSE A PERCUSSION'), ('PERFORATEUR', 'PERFORATEUR'), ('BURINEUR', 'BURINEUR'), ('PERCEUSE A PERCUSSION', 'PERCEUSE A PERCUSSION'), ('FOREUSE PERFORATEUR BURINEUR', 'FOREUSE PERFORATEUR BURINEUR'), ('PERCEUSE DIAMANT', 'PERCEUSE DIAMANT'), ('PERCEUSE FOREUSE ANGLE', 'PERCEUSE FOREUSE ANGLE'), ('PERFORAEUR BURINEUR', 'PERFORAEUR BURINEUR'), ('FRAISEUSE A LAMELLES', 'FRAISEUSE A LAMELLES'), ('FOREUSE A COLONNE', 'FOREUSE A COLONNE'), ('FOREUSE MAGNETIQUE', 'FOREUSE MAGNETIQUE'), ('MARTEAU PERFORATEUR', 'MARTEAU PERFORATEUR'), ('FOREUSE MARTEAU PERFORATEUR', 'FOREUSE MARTEAU PERFORATEUR')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='foreuseperceuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='frigo',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='frigo',
            name='volume',
            field=models.CharField(choices=[('50L', '50L'), ('105L', '105L'), ('120L', '120L'), ('50L', '50L')], max_length=100, verbose_name='VOLUME'),
        ),
        migrations.AlterField(
            model_name='fumigateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='fusible',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='gant',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='gant',
            name='type_gant',
            field=models.CharField(choices=[('ANTI CHALEUR', 'ANTI CHALEUR'), ('CHANTIER', 'CHANTIER'), ('COTON', 'COTON'), ('CUIRE', 'CUIRE'), ('PLASTIQUE', 'PLASTIQUE')], max_length=50, verbose_name='TYPE DU GANT'),
        ),
        migrations.AlterField(
            model_name='gant',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='giletkaki',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='globepoureclairage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='gomme',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='graphismeetanimation3d',
            name='units',
            field=models.CharField(choices=[('USD/SECONDE', 'USD/SECONDE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='graveur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='gravure',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='gravure',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='carburant',
            field=models.CharField(choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL')], max_length=20, verbose_name='TYPE DE CARBURANT'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='puissance_groupe',
            field=models.CharField(choices=[('720W', '720W'), ('3100W', '3100W'), ('3500W', '3500W'), ('4875W', '4875W'), ('5000W', '5000W'), ('5500W', '5500W'), ('7500W', '7500W'), ('10000W', '10000W'), ('1KVA', '1KVA'), ('10KVA', '10KVA'), ('2,5KVA', '2,5KVA'), ('4,8KVA', '4,8KVA'), ('5,5KVA', '5,5KVA'), ('3,5KVA', '3,5KVA'), ('5KVA', '5KVA'), ('2KVA', '2KVA'), ('3KVA', '3KVA'), ('6,5KVA', '6,5KVA'), ('7,5KVA', '7,5KVA'), ('12,5KVA', '12,5KVA'), ('15KVA', '15KVA'), ('20KVA', '20KVA'), ('38KVA', '38KVA'), ('27KVA', '27KVA'), ('225KVA', '225KVA'), ('30KVA', '30KVA'), ('40KVA', '40KVA'), ('60KVA', '60KVA'), ('50KVA', '50KVA'), ('100KVA', '100KVA')], max_length=20, verbose_name='PUISSANCE EN KILOVOLT-AMPERE'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='halogene',
            name='type_halogene',
            field=models.CharField(choices=[('DIRECTE', 'DIRECTE'), ('INDIRECTE', 'INDIRECTE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='halogene',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='hautparleurusb',
            name='marque_haut_parleur',
            field=models.CharField(choices=[('MAXICOM', 'MAXICOM')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='hautparleurusb',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='hebergementsiteweb',
            name='type_hebergement',
            field=models.CharField(choices=[('SITE VITRINE', 'SITE VITRINE'), ('HEBERGEMENT SITE INTERNET', 'HEBERGEMENT SITE INTERNET'), ('HEBERGEMENT MODULE ERP', 'HEBERGEMENT MODULE ERP'), ('HEBERGEMENT UTILISATEUR ERP', 'HEBERGEMENT UTILISATEUR ERP')], max_length=50, verbose_name="TYPE D'HEBERGEMENT"),
        ),
        migrations.AlterField(
            model_name='hebergementsiteweb',
            name='units',
            field=models.CharField(choices=[('USD/AN', 'USD/AN')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='jardinage',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='navetteaeroport',
            name='nombre_personnes',
            field=models.CharField(choices=[('1', '1'), ('1<', '1<')], max_length=20, verbose_name='NOMBRE DE PERSONNES'),
        ),
        migrations.AlterField(
            model_name='navetteaeroport',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name="CHOIX DE L'AMUSE GUEULE"),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_chaude',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSON CHAUDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_froide',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSON FROIDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_viennoiserie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA VIENNOISERIE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='pieces_rechange_moteur',
            field=models.CharField(choices=[('FILTRE A HUILE', 'FILTRE A HUILE'), ('FILTRE A AIR', 'FILTRE A AIR'), ('FILTRE A CARBURANT', 'FILTRE A CARBURANT'), ('FILTRE HABITACLE', 'FILTRE HABITACLE'), ('INJECTEUR', 'INJECTEUR'), ('COURROIE DIRECTION', 'COURROIE DIRECTION'), ('COURROIE DISTRIBUTION', 'COURROIE DISTRIBUTION'), ('POMPE A HUILE', 'POMPE A HUILE'), ('TURBO COMPRESSEUR', 'TURBO COMPRESSEUR'), ('SUPPORT MOTEUR', 'SUPPORT MOTEUR'), ('COURROIE COMPRESSEUR', 'COURROIE COMPRESSEUR'), ('TENDEUR DISTRIBUTION', 'TENDEUR DISTRIBUTION'), ('NEZ INJECTEUR', 'NEZ INJECTEUR'), ('FILTRE A CARBURANT  16405-01T0A', 'FILTRE A CARBURANT  16405-01T0A'), ('FILTRE A CARBURANT  16405-02N0A', 'FILTRE A CARBURANT  16405-02N0A'), ('INJECTEUR COMPLET', 'INJECTEUR COMPLET'), ('POMPE A CARBURANT', 'POMPE A CARBURANT'), ('COURROIE DE DISTRIBUTION', 'COURROIE DE DISTRIBUTION'), ('TENDEUR ALTERNATEUR', 'TENDEUR ALTERNATEUR')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='units',
            field=models.CharField(choices=[('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='poisson',
            name='type_de_poisson',
            field=models.CharField(choices=[('MUNGUSU', 'MUNGUSU'), ('MOJOMBO', 'MOJOMBO'), ('MINZANDA', 'MINZANDA'), ('MGOMGO', 'MGOMGO'), ('CAPITAINE', 'CAPITAINE'), ('MBOTO', 'MBOTO'), ('MINZANDA', 'MINZANDA'), ('NGOLO', 'NGOLO'), ('SOLE MOYENNE', 'SOLE MOYENNE'), ('GRANDE SOLE', 'GRANDE SOLE'), ('CAPITAINE MOYEN', 'CAPITAINE MOYEN'), ('GRAND CAPITAINE', 'GRAND CAPITAINE'), ('FILET DE CAPITAINE', 'FILET DE CAPITAINE'), ('PERCHE', 'PERCHE'), ('FILET DE PERCHE', 'FILET DE PERCHE'), ('MEROU', 'MEROU'), ('RAIE (MAZIBA)', 'RAIE (MAZIBA)'), ('AILE DE RAIE', 'AILE DE RAIE'), ('ROUGET', 'ROUGET'), ('SAINT PIERRE', 'SAINT PIERRE'), ('BARRACUDA', 'BARRACUDA'), ('COSSA MOYEN MOANDA', 'COSSA MOYEN MOANDA'), ('COSSA MOYEN POINTE NOIRE', 'COSSA MOYEN POINTE NOIRE'), ('COSSA ROYALE POINTE NOIRE', 'COSSA ROYALE POINTE NOIRE'), ('PETITE LANGOUSTE MOANDA', 'PETITE LANGOUSTE MOANDA'), ('LANGOUSTE MOYENNE POINTE NOIRE', 'LANGOUSTE MOYENNE POINTE NOIRE'), ('GRANDE LANGOUSTE POINTE NOIRE', 'GRANDE LANGOUSTE POINTE NOIRE'), ('PIEUVRE POINTE NOIR', 'PIEUVRE POINTE NOIR'), ('CRABE', 'CRABE'), ('CALAMARD', 'CALAMARD'), ('SECHE', 'SECHE'), ('COSSA DECORTIQUE', 'COSSA DECORTIQUE'), ('MORUE', 'MORUE'), ('CROQUETTES COSSA 10PCS', 'CROQUETTES COSSA 10PCS'), ('CROQUETTE MORUE 10PCS', 'CROQUETTE MORUE 10PCS')], max_length=50, verbose_name='TYPE DE POISSON'),
        ),
        migrations.AlterField(
            model_name='poubelleuac',
            name='matiere',
            field=models.CharField(choices=[('INOX', 'INOX'), ('PLASTIQUE', 'PLASTIQUE')], max_length=100, verbose_name='MATIERE'),
        ),
        migrations.AlterField(
            model_name='produitnettoyage',
            name='type_produit',
            field=models.CharField(choices=[('EAU DE JAVEL', 'EAU DE JAVEL'), ('BACTEROL', 'BACTEROL'), ('CREOLINE', 'CREOLINE'), ('ESPRIT DE SEL', 'ESPRIT DE SEL'), ('INSECTICIDE', 'INSECTICIDE'), ('RATICIDE', 'RATICIDE')], max_length=20, verbose_name='TYPE DE PRODUIT'),
        ),
        migrations.AlterField(
            model_name='produitnettoyage',
            name='units',
            field=models.CharField(choices=[('USD/LITRE', 'USD/LITRE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='recrutement',
            name='units',
            field=models.CharField(choices=[('% DU SALAIRE', '% DU SALAIRE'), ('% DU 1ER SALAIRE', '% DU 1ER SALAIRE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='reproductioncle',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='reservationhoteletranger',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='baffle_gratuit',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='AVEC BAFFLE GRATUIT'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='micro_gratuit',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NOM')], max_length=20, verbose_name='AVEC MICRO GRATUIT'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='retro_projecteur',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, verbose_name='AVEC RETRO PROJECTEUR'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE/MOIS', 'USD/PERSONNE/MOIS')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='serviceaccueil',
            name='periode_service',
            field=models.CharField(choices=[('JOUR', 'JOUR'), ('NUIT', 'NUIT')], max_length=20, verbose_name='PERIODE DE SERVICE'),
        ),
        migrations.AlterField(
            model_name='serviceaccueil',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='serviceagencevoyage',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='units',
            field=models.CharField(choices=[('USD/PAGE', 'USD/PAGE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='servicegardiennage',
            name='type_gardiennage',
            field=models.CharField(choices=[('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES ', 'INDUSTRIES '), ('MINES', 'MINES'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE'), ('AUTRES SERVICES', 'AUTRES SERVICES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('SECURITE RAPPROCHEE', 'SECURITE RAPPROCHEE')], max_length=100, verbose_name='TYPE DE GARDIENNAGE'),
        ),
        migrations.AlterField(
            model_name='servicegardiennage',
            name='units',
            field=models.CharField(choices=[('USD/GARDIEN/MOIS', 'USD/GARDIEN/MOIS')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='servicesplit',
            name='type_service_split',
            field=models.CharField(choices=[('INSTALLATION SPLIT', 'INSTALLATION SPLIT'), ('ENTRETIEN SPLIT', 'ENTRETIEN SPLIT')], max_length=20, verbose_name='TYPE DE SERVICE POUR SPLIT'),
        ),
        migrations.AlterField(
            model_name='servicesplit',
            name='units',
            field=models.CharField(choices=[('USD/SPLIT', 'USD/SPLIT')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='marque_smartphone',
            field=models.CharField(choices=[('HUAWEI', 'HUAWEI'), ('TECNO', 'TECNO')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='modele_smartphone',
            field=models.CharField(choices=[('K7', 'K7'), ('K9', 'K9'), ('Y5', 'Y5')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='forme',
            field=models.CharField(choices=[('EN L', 'EN L'), ('OVALE', 'OVALE'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='longueur',
            field=models.CharField(choices=[('120CM', '120CM'), ('140CM', '140CM'), ('150CM', '150CM'), ('160CM', '160CM'), ('170CM', '170CM'), ('180CM', '180CM')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='telephonemobilesimple',
            name='marque_mobile',
            field=models.CharField(choices=[('SAMSUNG ', 'SAMSUNG ')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='telephonemobilesimple',
            name='modele_mobile',
            field=models.CharField(choices=[('B110E', 'B110E')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='tvled',
            name='marque',
            field=models.CharField(choices=[('SHARP', 'SHARP'), ('SONY', 'SONY'), ('TOSHIBA', 'TOSHIBA'), ('WESTPOOL', 'WESTPOOL')], max_length=100, verbose_name='MARQUE'),
        ),
    ]
