# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0414_auto_20180531_1507'),
    ]

    operations = [

        migrations.AlterField(
            model_name='chaisebureau',
            name='type_chaise',
            field=models.CharField(choices=[('CHAISE DE BUREAU', 'CHAISE DE BUREAU'), ('CHAISE DE DIRECTION', 'CHAISE DE DIRECTION'), ('CHAISE POUR ORDINATEUR', 'CHAISE ORDINATEUR'), ('CHAISE VISITEUR', 'CHAISE VISITEUR')], max_length=20, verbose_name='TYPE DE CHAISE'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='nombre_etoile',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, verbose_name="NOMBRE D'ETOILE"),
        ),
        migrations.AlterField(
            model_name='chargeurcameraccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='intensite',
            field=models.CharField(choices=[('3,42A', '3,42A'), ('3,34A', '3,34A'), ('4,62A', '4,62A'), ('3,5A', '3,5A'), ('3,5A SMALL PIN', '3,5A SMALL PIN'), ('1,58A', '1,58A'), ('4,74A BIG PIN', '4,74A BIG PIN'), ('4,74A SMALL PIN', '4,74A SMALL PIN'), ('3,42A', '3,42A'), ('3,95A', '3,95A')], max_length=100, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='tension',
            field=models.CharField(choices=[('19V', '19V'), ('19,5V', '19,5V'), ('18,5V', '18,5V')], max_length=100, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='charniere',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chauffeeau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chemise',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='ciseau',
            name='taille',
            field=models.CharField(choices=[('22CM', '22CM')], max_length=100, verbose_name='TAILLE EN CENTIMETRE'),
        ),
        migrations.AlterField(
            model_name='ciseau',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='classeur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='type_clavier',
            field=models.CharField(choices=[('QWERTY', 'QWERTY'), ('AZERTY', 'AZERTY')], max_length=50, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clavieretsourissansfil',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='claviersansfil',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cleallen',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='dimension_clef_molette',
            field=models.CharField(choices=[('10 POUCES', '10 POUCES'), ('12 POUCES', '12 POUCES'), ('14 POUCES', '14 POUCES'), ('36 POUCES', '36 POUCES')], max_length=50, verbose_name='DIMENSION DE LA CLEF'),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='clefmolette',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clinche',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='clous',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name="CHOIX DE L'AMUSE GUEULE"),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSON NON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='coffretdeclecomplet',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coffretdivisionnaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='coffretelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coffretelectriquemodulaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coffretjeubarre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='colleliquide',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='combinaison',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='communicationdemasse',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE/JOUR', 'USD/PERSONNE/JOUR')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='communicationgraphique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='communique',
            name='units',
            field=models.CharField(choices=[('USD/COMMUNIQUE', 'USD/COMMUNIQUE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='compacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='compteurmonnaie',
            name='marque_compteur_monnaie',
            field=models.CharField(choices=[('ITC', 'ITC'), ('MAGNER', 'MAGNER')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='compteurmonnaie',
            name='model_compteur_monnaie',
            field=models.CharField(choices=[('2108', '2108'), ('MAG75', 'MAG75')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='compteurmonnaie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='conceptiongraphique',
            name='units',
            field=models.CharField(choices=[('USD/THEME', 'USD/THEME')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='conceptionpagemagazine',
            name='units',
            field=models.CharField(choices=[('USD/PAGE', 'USD/PAGE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='congelateur',
            name='type_congelateur',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('DEBOUT', 'DEBOUT'), ('AVEC COOL PACK', 'AVEC COOL PACK'), ('AVEC VITRE', 'AVEC VITRE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='congelateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='congelateur',
            name='volume',
            field=models.CharField(choices=[('150L', '150L'), ('250L', '250L'), ('350L', '350L'), ('300L', '300L'), ('550L', '550L'), ('260L', '260L'), ('400L', '400L'), ('280L', '280L'), ('320L', '320L'), ('480L', '480L'), ('185L', '185L'), ('324L', '324L'), ('130L', '130L'), ('465L', '465L'), ('500L', '500L'), ('600L', '600L'), ('110L', '110L'), ('120L', '120L'), ('170L', '170L'), ('200L', '200L'), ('450L', '450L')], max_length=100, verbose_name='VOLUME'),
        ),
        migrations.AlterField(
            model_name='connecteur',
            name='type_connecteur',
            field=models.CharField(choices=[('RJ45 CAT6 METAL', 'RJ45 CAT6 METAL'), ('RJ45 COUVERT', 'RJ45 COUVERT'), ('RJ11', 'RJ11'), ('RJ45 CAT5E', 'RJ45 CAT5E'), ('RJ45 CAT6E', 'RJ45 CAT6E'), ('COUVERTURE CABLE RJ45', 'COUVERTURE CABLE RJ45'), ('RJ45 AICO', 'RJ45 AICO'), ('RJ45 CAT6', 'RJ45 CAT6'), ('RJ45 METAL', 'RJ45 METAL'), ('RJ45 NORMA', 'RJ45 NORMA'), ('CAT6 RJ45 POUR PRISE MURALE', 'CAT6 RJ45 POUR PRISE MURALE')], max_length=100, verbose_name='TYPE DE CONNECTEUR'),
        ),
        migrations.AlterField(
            model_name='connecteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='connecteuralimentationfemmelleccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='connecteurbnc',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYES"),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=100, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='puissance',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='PUISSANCE EN KILOWATT'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='tension',
            field=models.CharField(choices=[('24V', '24V'), ('24VCC', '24VCC'), ('48V', '48V'), ('110V', '110V'), ('220V', '220V'), ('230V', '230V'), ('250V', '250V'), ('380V', '380V'), ('400V', '400V'), ('415V', '415V'), ('500V', '500V'), ('1000V', '1000V')], max_length=100, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='contacteur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='pointage_presence',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=50, verbose_name='POINTAGE DE PRESENCE'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='controleaccesetpointage',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='marque_convertisseur',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('SOLARWORLD', 'SOLARWORLD'), ('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('ERCO SOLAIRE', 'ERCO SOLAIRE'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='puissance_convertisseur',
            field=models.CharField(choices=[('300W', '300W'), ('600W', '600W'), ('800W', '800W'), ('1000W', '1000W'), ('2000W', '2000W'), ('3000W', '3000W'), ('4000W', '4000W'), ('5000W', '5000W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='tension_convertisseur',
            field=models.CharField(choices=[('2V', '2V'), ('12V', '12V'), ('12/24V', '12/24V'), ('24V', '24V'), ('48V', '48V')], max_length=20, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='correcteurliquide',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coupecarreau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='couphaieelectrique',
            name='longueur_de_coupe',
            field=models.CharField(choices=[('60CM', '60CM')], max_length=100, verbose_name='LONGUEUR DE COUPE'),
        ),
        migrations.AlterField(
            model_name='couphaieelectrique',
            name='puissance',
            field=models.CharField(choices=[('900W', '900W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='couphaieelectrique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='coupleur',
            name='type_coupleur',
            field=models.CharField(choices=[('RJ45 DOUBLE', 'RJ45 DOUBLE'), ('RJ45 SIMPLE', 'RJ45 SIMPLE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='coupleur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='courslangueetrangere',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='courslanguenationale',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='couvercleoval',
            name='taille',
            field=models.CharField(choices=[('12"', '12"'), ('14"', '14"')], max_length=100, verbose_name='TAILLE EN POUCE  '),
        ),
        migrations.AlterField(
            model_name='couverturephoto',
            name='units',
            field=models.CharField(choices=[('USD/HEURE', 'USD/HEURE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='creationsiteweb',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cyclometre',
            name='type_cyclometre',
            field=models.CharField(choices=[('NUMERIQUE', 'NUMERIQUE'), ('NORMALE', 'NORMALE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='cyclometre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='type_cylindre',
            field=models.CharField(choices=[('DGC', 'DGC'), ('ITALY', 'ITALY'), ('RENZ', 'RENZ'), ('SISLYE', 'SISLYE'), ('VACHETTE', 'VACHETTE')], max_length=50, verbose_name='TYPE DE CYLINDRE'),
        ),
        migrations.AlterField(
            model_name='cylindre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='damesauteuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='debrousailleuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='decapeurthermique',
            name='puissance',
            field=models.CharField(choices=[('1800W', '1800W')], max_length=100, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='decapeurthermique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='quantite',
            field=models.CharField(choices=[('20001<', '20001<'), ('10001-20000', '10001-20000'), ('5001-10000', '5001-10000'), ('4001-5000', '4001-5000'), ('3001-4000', '3001-4000'), ('2001-3000', '2001-3000'), ('1001-2000', '1001-2000'), ('501-1000', '501-1000')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='depliant',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='desagrafeuse',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='marque_desktop',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('FUJITSU', 'FUJITSU'), ('LENOVO', 'LENOVO'), ('SONY', 'SONY'), ('ASUS', 'ASUS'), ('APPLE', 'APPLE'), ('TOSHIBA', 'TOSHIBA')], max_length=50, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='destructeurpapier',
            name='Volume_panier_dechet',
            field=models.CharField(choices=[('23L', '23L'), ('16L', '16L'), ('31L', '31L'), ('13L', '13L'), ('3,5L', '3,5L')], max_length=100, verbose_name='VOLUME DU PANIER'),
        ),
        migrations.AlterField(
            model_name='destructeurpapier',
            name='destruction_carte_credit',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, verbose_name='DESTRUCTEUR CARTE BANCAIRE'),
        ),
        migrations.AlterField(
            model_name='destructeurpapier',
            name='destruction_cd',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, verbose_name='DESTRUCTEUR CD'),
        ),
        migrations.AlterField(
            model_name='destructeurpapier',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='detecteurincendie',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='detecteurincendie',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='marque_detecteur',
            field=models.CharField(choices=[('ABB', 'ABB'), ('GENERAL ELECTRIC', 'GENERAL ELECTRIC'), ('SCHNEIDER', 'SCHNEIDER'), ('SUPREMA', 'SUPREMA'), ('PROLINE', 'PROLINE'), ('TELEMECA', 'TELEMECA'), ('NEC', 'NEC')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='detecteurintrusion',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='diable',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='diamantcoupecarreaux',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='diffusioncontenumediatique',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='diffusionspotpublicitaire',
            name='units',
            field=models.CharField(choices=[('USD/SECONDE', 'USD/SECONDE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='disjoncteur',
            name='intensite',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('6A', '6A'), ('9A', '9A'), ('10A', '10A'), ('12A', '12A'), ('16A', '16A'), ('18A', '18A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A'), ('65A', '65A'), ('80A', '80A'), ('100A', '100A'), ('115A', '115A'), ('125A', '125A'), ('150A', '150A'), ('160A', '160A'), ('185A', '185A'), ('200A', '200A'), ('225A', '225A'), ('250A', '250A'), ('400A', '400A'), ('1000A', '1000A')], max_length=50, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='poids',
            field=models.CharField(choices=[('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 1kgs', '0 à 1kgs'), ('1,01 à 1,5kgs1', '01-1,5kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('1,51 à 2kgs', '1,51-2kgs'), ('2,01 à 2,5kgs', '2,01-2,5kgs'), ('1,01 à 1,5kgs', '1,01 à 1,5kgs'), ('2,51 à 3kgs', '2,51-3kgs'), ('1,01 à 2kgs', '1,01 à 2kgs'), ('3,01 à 3,5kgs', '3,01-3,5kgs'), ('1,51 à 2kgs', '1,51 à 2kgs'), ('3,51 à 4kgs', '3,51-4kgs'), ('4,01 à 4,5kgs', '4,01-4,5kgs'), ('2,01 à 2,5kgs', '2,01 à 2,5kgs'), ('4,51 à 5kgs', '4,51-5kgs'), ('2,01 à 3kgs', '2,01 à 3kgs'), ('5,01 à 5,5kgs', '5,01-5,5kgs'), ('2,51 à 3kgs', '2,51 à 3kgs'), ('5,51 à 6,0kgs', '5,51-6,0kgs'), ('6,01 à 6,5 kgs', '6,01-6,5 kgs'), ('6,51 à 7,0 kgs', '6,51-7,0 kgs'), ('3,01 à 3,5kgs', '3,01 à 3,5kgs'), ('3,01 à 4kgs', '3,01 à 4kgs'), ('7,01 à 7,5 kgs', '7,01-7,5 kgs'), ('3,51 à 4kgs', '3,51 à 4kgs'), ('7,51 à 8,0 kgs', '7,51- 8,0 kgs'), ('8,01 à 8,5 kgs', '8,01-8,5 kgs'), ('8,51 à 9,0 kgs', '8,51-9,0 kgs'), ('4,01 à 4,5kgs', '4,01 à 4,5kgs'), ('4,01 à 5kgs', '4,01 à 5kgs'), ('9,01 à 9,5 kgs', '9,01-9,5 kgs'), ('4,51 à 5kgs', '4,51 à 5kgs'), ('9,51 à 10 kgs', '9,51-10 kgs'), ('5,01 à 5,5kgs', '5,01 à 5,5kgs'), ('5,01 à 6kgs', '5,01 à 6kgs'), ('5,51 à 6kgs', '5,51 à 6kgs'), ('6,01 à 6,5kgs', '6,01 à 6,5kgs'), ('6,01 à 7kgs', '6,01 à 7kgs'), ('6,51 à 7kgs', '6,51 à 7kgs'), ('7,01 à 7,5kgs', '7,01 à 7,5kgs'), ('7,01 à 8 kgs', '7,01 à 8 kgs'), ('7,51 à 8kgs', '7,51 à 8kgs'), ('8,01 à 8,5kgs', '8,01 à 8,5kgs'), ('8,01 à 9kgs', '8,01 à 9kgs'), ('8,51 à 9kgs', '8,51 à 9kgs'), ('9,01, à 9,5kgs', '9,01, à 9,5kgs'), ('9,01 à 10kgs', '9,01 à 10kgs'), ('9,51 à 10kgs', '9,51 à 10kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('20,01 à 21kgs', '20,01 à 21kgs'), ('21,01 à 22kgs', '21,01 à 22kgs'), ('22,01 à 23kgs', '22,01 à 23kgs'), ('23,01 à 24kgs', '23,01 à 24kgs'), ('24,01 à 25kgs', '24,01 à 25kgs'), ('25,01 à 26kgs', '25,01 à 26kgs'), ('26,01 à 27kgs', '26,01 à 27kgs'), ('27,01 à 28kgs', '27,01 à 28kgs'), ('28,01 à 29kgs', '28,01 à 29kgs'), ('29,01 à 30kgs', '29,01 à 30kgs'), ('30,01 à 31kgs', '30,01 à 31kgs'), ('31,01 à 32kgs', '31,01 à 32kgs'), ('32,01 à 33kgs', '32,01 à 33kgs'), ('33,01 à 34kgs', '33,01 à 34kgs'), ('34,01 à 35kgs', '34,01 à 35kgs'), ('35,01 à 36kgs', '35,01 à 36kgs'), ('36,01 à 37kgs', '36,01 à 37kgs'), ('37,01 à 38kgs', '37,01 à 38kgs'), ('38,01 à 39kgs', '38,01 à 39kgs'), ('39,01 à 40kgs', '39,01 à 40kgs'), ('40,01 à 41kgs', '40,01 à 41kgs'), ('41,01 à 42kgs', '41,01 à 42kgs'), ('42,01 à 43kgs', '42,01 à 43kgs'), ('43,01 à 44kgs', '43,01 à 44kgs'), ('44,01 à 45kgs', '44,01 à 45kgs'), ('45,01 à 46kgs', '45,01 à 46kgs'), ('46,01 à 47kgs', '46,01 à 47kgs'), ('47,01 à 48kgs', '47,01 à 48kgs'), ('48,01 à 49kgs', '48,01 à 49kgs'), ('49,01 à 50kgs', '49,01 à 50kgs'), ('50,01 à 51kgs', '50,01 à 51kgs'), ('51,01 à 52kgs', '51,01 à 52kgs'), ('52,01 à 53kgs', '52,01 à 53kgs'), ('53,01 à 54kgs', '53,01 à 54kgs'), ('54,01 à 55kgs', '54,01 à 55kgs'), ('55,01 à 56kgs', '55,01 à 56kgs'), ('56,01 à 57kgs', '56,01 à 57kgs'), ('57,01 à 58kgs', '57,01 à 58kgs'), ('58,01 à 59kgs', '58,01 à 59kgs'), ('59,01 à 60kgs', '59,01 à 60kgs'), ('60,01 à 61kgs', '60,01 à 61kgs'), ('61,01 à 62kgs', '61,01 à 62kgs'), ('62,01 à 63kgs', '62,01 à 63kgs'), ('63,01 à 64kgs', '63,01 à 64kgs'), ('64,01 à 65kgs', '64,01 à 65kgs'), ('65,01 à 66kgs', '65,01 à 66kgs'), ('66,01 à 67kgs', '66,01 à 67kgs'), ('67,01 à 68kgs', '67,01 à 68kgs'), ('68,01 à 69kgs', '68,01 à 69kgs'), ('69,01 à 70kgs', '69,01 à 70kgs')], max_length=20, verbose_name='POIDS'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternationalplus70kg',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational0a20kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational0a20kgs',
            name='poids',
            field=models.CharField(choices=[('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 1kgs', '0 à 1kgs'), ('1,01 à 1,5kgs1', '01-1,5kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('1,51 à 2kgs', '1,51-2kgs'), ('2,01 à 2,5kgs', '2,01-2,5kgs'), ('1,01 à 1,5kgs', '1,01 à 1,5kgs'), ('2,51 à 3kgs', '2,51-3kgs'), ('1,01 à 2kgs', '1,01 à 2kgs'), ('3,01 à 3,5kgs', '3,01-3,5kgs'), ('1,51 à 2kgs', '1,51 à 2kgs'), ('3,51 à 4kgs', '3,51-4kgs'), ('4,01 à 4,5kgs', '4,01-4,5kgs'), ('2,01 à 2,5kgs', '2,01 à 2,5kgs'), ('4,51 à 5kgs', '4,51-5kgs'), ('2,01 à 3kgs', '2,01 à 3kgs'), ('5,01 à 5,5kgs', '5,01-5,5kgs'), ('2,51 à 3kgs', '2,51 à 3kgs'), ('5,51 à 6,0kgs', '5,51-6,0kgs'), ('6,01 à 6,5 kgs', '6,01-6,5 kgs'), ('6,51 à 7,0 kgs', '6,51-7,0 kgs'), ('3,01 à 3,5kgs', '3,01 à 3,5kgs'), ('3,01 à 4kgs', '3,01 à 4kgs'), ('7,01 à 7,5 kgs', '7,01-7,5 kgs'), ('3,51 à 4kgs', '3,51 à 4kgs'), ('7,51 à 8,0 kgs', '7,51- 8,0 kgs'), ('8,01 à 8,5 kgs', '8,01-8,5 kgs'), ('8,51 à 9,0 kgs', '8,51-9,0 kgs'), ('4,01 à 4,5kgs', '4,01 à 4,5kgs'), ('4,01 à 5kgs', '4,01 à 5kgs'), ('9,01 à 9,5 kgs', '9,01-9,5 kgs'), ('4,51 à 5kgs', '4,51 à 5kgs'), ('9,51 à 10 kgs', '9,51-10 kgs'), ('5,01 à 5,5kgs', '5,01 à 5,5kgs'), ('5,01 à 6kgs', '5,01 à 6kgs'), ('5,51 à 6kgs', '5,51 à 6kgs'), ('6,01 à 6,5kgs', '6,01 à 6,5kgs'), ('6,01 à 7kgs', '6,01 à 7kgs'), ('6,51 à 7kgs', '6,51 à 7kgs'), ('7,01 à 7,5kgs', '7,01 à 7,5kgs'), ('7,01 à 8 kgs', '7,01 à 8 kgs'), ('7,51 à 8kgs', '7,51 à 8kgs'), ('8,01 à 8,5kgs', '8,01 à 8,5kgs'), ('8,01 à 9kgs', '8,01 à 9kgs'), ('8,51 à 9kgs', '8,51 à 9kgs'), ('9,01, à 9,5kgs', '9,01, à 9,5kgs'), ('9,01 à 10kgs', '9,01 à 10kgs'), ('9,51 à 10kgs', '9,51 à 10kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('20,01 à 21kgs', '20,01 à 21kgs'), ('21,01 à 22kgs', '21,01 à 22kgs'), ('22,01 à 23kgs', '22,01 à 23kgs'), ('23,01 à 24kgs', '23,01 à 24kgs'), ('24,01 à 25kgs', '24,01 à 25kgs'), ('25,01 à 26kgs', '25,01 à 26kgs'), ('26,01 à 27kgs', '26,01 à 27kgs'), ('27,01 à 28kgs', '27,01 à 28kgs'), ('28,01 à 29kgs', '28,01 à 29kgs'), ('29,01 à 30kgs', '29,01 à 30kgs'), ('30,01 à 31kgs', '30,01 à 31kgs'), ('31,01 à 32kgs', '31,01 à 32kgs'), ('32,01 à 33kgs', '32,01 à 33kgs'), ('33,01 à 34kgs', '33,01 à 34kgs'), ('34,01 à 35kgs', '34,01 à 35kgs'), ('35,01 à 36kgs', '35,01 à 36kgs'), ('36,01 à 37kgs', '36,01 à 37kgs'), ('37,01 à 38kgs', '37,01 à 38kgs'), ('38,01 à 39kgs', '38,01 à 39kgs'), ('39,01 à 40kgs', '39,01 à 40kgs'), ('40,01 à 41kgs', '40,01 à 41kgs'), ('41,01 à 42kgs', '41,01 à 42kgs'), ('42,01 à 43kgs', '42,01 à 43kgs'), ('43,01 à 44kgs', '43,01 à 44kgs'), ('44,01 à 45kgs', '44,01 à 45kgs'), ('45,01 à 46kgs', '45,01 à 46kgs'), ('46,01 à 47kgs', '46,01 à 47kgs'), ('47,01 à 48kgs', '47,01 à 48kgs'), ('48,01 à 49kgs', '48,01 à 49kgs'), ('49,01 à 50kgs', '49,01 à 50kgs'), ('50,01 à 51kgs', '50,01 à 51kgs'), ('51,01 à 52kgs', '51,01 à 52kgs'), ('52,01 à 53kgs', '52,01 à 53kgs'), ('53,01 à 54kgs', '53,01 à 54kgs'), ('54,01 à 55kgs', '54,01 à 55kgs'), ('55,01 à 56kgs', '55,01 à 56kgs'), ('56,01 à 57kgs', '56,01 à 57kgs'), ('57,01 à 58kgs', '57,01 à 58kgs'), ('58,01 à 59kgs', '58,01 à 59kgs'), ('59,01 à 60kgs', '59,01 à 60kgs'), ('60,01 à 61kgs', '60,01 à 61kgs'), ('61,01 à 62kgs', '61,01 à 62kgs'), ('62,01 à 63kgs', '62,01 à 63kgs'), ('63,01 à 64kgs', '63,01 à 64kgs'), ('64,01 à 65kgs', '64,01 à 65kgs'), ('65,01 à 66kgs', '65,01 à 66kgs'), ('66,01 à 67kgs', '66,01 à 67kgs'), ('67,01 à 68kgs', '67,01 à 68kgs'), ('68,01 à 69kgs', '68,01 à 69kgs'), ('69,01 à 70kgs', '69,01 à 70kgs')], max_length=20, verbose_name='POIDS'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational0a20kgs',
            name='ville_de_destination',
            field=models.CharField(choices=[('BANDUNDU', 'BANDUNDU'), ('BENI', 'BENI'), ('BOENDE', 'BOENDE'), ('BOMA', 'BOMA'), ('BUKAVU', 'BUKAVU'), ('BUNIA', 'BUNIA'), ('BUTA', 'BUTA'), ('BUTEMBO', 'BUTEMBO'), ('DUNGU', 'DUNGU'), ('FUNGURUME', 'FUNGURUME'), ('GBADOLITE', 'GBADOLITE'), ('GEMENA', 'GEMENA'), ('GOMA', 'GOMA'), ('INONGO', 'INONGO'), ('ISIRO', 'ISIRO'), ('KABINDA', 'KABINDA'), ('KALEMIE', 'KALEMIE'), ('KAMINA', 'KAMINA'), ('KANANGA', 'KANANGA'), ('KASUMBALESA', 'KASUMBALESA'), ('KENGE', 'KENGE'), ('KIKWIT', 'KIKWIT'), ('KILWA', 'KILWA'), ('KIMPESE', 'KIMPESE'), ('KINDU', 'KINDU'), ('KISANGANI', 'KISANGANI'), ('KOLWEZI', 'KOLWEZI'), ('LIKASI', 'LIKASI'), ('LISALA', 'LISALA'), ('LODJA', 'LODJA'), ('LUBUMBASHI', 'LUBUMBASHI'), ('LUKALA', 'LUKALA'), ('MAHAGI', 'MAHAGI'), ('MATADI', 'MATADI'), ('MATADI', 'MATADI'), ('MBANDAKA', 'MBANDAKA'), ('MBANZA-NGUNGU', 'MBANZA-NGUNGU'), ('MBUJI MAYI', 'MBUJI MAYI'), ('MOANDA', 'MOANDA'), ('MWENE-DITU', 'MWENE-DITU'), ('TSHIKAPA', 'TSHIKAPA'), ('UVIRA', 'UVIRA')], max_length=20, verbose_name='VILLE DESTINATION'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational100kgsetplus',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational100kgsetplus',
            name='ville_de_destination',
            field=models.CharField(choices=[('BANDUNDU', 'BANDUNDU'), ('BENI', 'BENI'), ('BOENDE', 'BOENDE'), ('BOMA', 'BOMA'), ('BUKAVU', 'BUKAVU'), ('BUNIA', 'BUNIA'), ('BUTA', 'BUTA'), ('BUTEMBO', 'BUTEMBO'), ('DUNGU', 'DUNGU'), ('FUNGURUME', 'FUNGURUME'), ('GBADOLITE', 'GBADOLITE'), ('GEMENA', 'GEMENA'), ('GOMA', 'GOMA'), ('INONGO', 'INONGO'), ('ISIRO', 'ISIRO'), ('KABINDA', 'KABINDA'), ('KALEMIE', 'KALEMIE'), ('KAMINA', 'KAMINA'), ('KANANGA', 'KANANGA'), ('KASUMBALESA', 'KASUMBALESA'), ('KENGE', 'KENGE'), ('KIKWIT', 'KIKWIT'), ('KILWA', 'KILWA'), ('KIMPESE', 'KIMPESE'), ('KINDU', 'KINDU'), ('KISANGANI', 'KISANGANI'), ('KOLWEZI', 'KOLWEZI'), ('LIKASI', 'LIKASI'), ('LISALA', 'LISALA'), ('LODJA', 'LODJA'), ('LUBUMBASHI', 'LUBUMBASHI'), ('LUKALA', 'LUKALA'), ('MAHAGI', 'MAHAGI'), ('MATADI', 'MATADI'), ('MATADI', 'MATADI'), ('MBANDAKA', 'MBANDAKA'), ('MBANZA-NGUNGU', 'MBANZA-NGUNGU'), ('MBUJI MAYI', 'MBUJI MAYI'), ('MOANDA', 'MOANDA'), ('MWENE-DITU', 'MWENE-DITU'), ('TSHIKAPA', 'TSHIKAPA'), ('UVIRA', 'UVIRA')], max_length=20, verbose_name='VILLE DESTINATION'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational20kgsa99kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational20kgsa99kgs',
            name='ville_de_destination',
            field=models.CharField(choices=[('BANDUNDU', 'BANDUNDU'), ('BENI', 'BENI'), ('BOENDE', 'BOENDE'), ('BOMA', 'BOMA'), ('BUKAVU', 'BUKAVU'), ('BUNIA', 'BUNIA'), ('BUTA', 'BUTA'), ('BUTEMBO', 'BUTEMBO'), ('DUNGU', 'DUNGU'), ('FUNGURUME', 'FUNGURUME'), ('GBADOLITE', 'GBADOLITE'), ('GEMENA', 'GEMENA'), ('GOMA', 'GOMA'), ('INONGO', 'INONGO'), ('ISIRO', 'ISIRO'), ('KABINDA', 'KABINDA'), ('KALEMIE', 'KALEMIE'), ('KAMINA', 'KAMINA'), ('KANANGA', 'KANANGA'), ('KASUMBALESA', 'KASUMBALESA'), ('KENGE', 'KENGE'), ('KIKWIT', 'KIKWIT'), ('KILWA', 'KILWA'), ('KIMPESE', 'KIMPESE'), ('KINDU', 'KINDU'), ('KISANGANI', 'KISANGANI'), ('KOLWEZI', 'KOLWEZI'), ('LIKASI', 'LIKASI'), ('LISALA', 'LISALA'), ('LODJA', 'LODJA'), ('LUBUMBASHI', 'LUBUMBASHI'), ('LUKALA', 'LUKALA'), ('MAHAGI', 'MAHAGI'), ('MATADI', 'MATADI'), ('MATADI', 'MATADI'), ('MBANDAKA', 'MBANDAKA'), ('MBANZA-NGUNGU', 'MBANZA-NGUNGU'), ('MBUJI MAYI', 'MBUJI MAYI'), ('MOANDA', 'MOANDA'), ('MWENE-DITU', 'MWENE-DITU'), ('TSHIKAPA', 'TSHIKAPA'), ('UVIRA', 'UVIRA')], max_length=20, verbose_name='VILLE DESTINATION'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('A CONFIRMER', 'A CONFIRMER'), ('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('3 JOURS', '3 JOURS'), ('3 JOURS', '3 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('4 JOURS', '4 JOURS'), ('4 JOURS', '4 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('5 JOURS', '5 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('6 JOURS', '6 JOURS'), ('6 JOURS', '6 JOURS'), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('3 A 4 JOURS', '3 A 4 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('7 JOURS', '7 JOURS'), ('7 JOURS', '7 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('8 JOURS', '8 JOURS'), ('8 JOURS', '8 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('14 JOURS ', '14 JOURS '), ('14 JOURS', '14 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='poids',
            field=models.CharField(choices=[('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 0,5kgs', '0 à 0,5kgs'), ('0 à 1kgs', '0 à 1kgs'), ('1,01 à 1,5kgs1', '01-1,5kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('0,51 à 1kgs', '0,51 à 1kgs'), ('1,51 à 2kgs', '1,51-2kgs'), ('2,01 à 2,5kgs', '2,01-2,5kgs'), ('1,01 à 1,5kgs', '1,01 à 1,5kgs'), ('2,51 à 3kgs', '2,51-3kgs'), ('1,01 à 2kgs', '1,01 à 2kgs'), ('3,01 à 3,5kgs', '3,01-3,5kgs'), ('1,51 à 2kgs', '1,51 à 2kgs'), ('3,51 à 4kgs', '3,51-4kgs'), ('4,01 à 4,5kgs', '4,01-4,5kgs'), ('2,01 à 2,5kgs', '2,01 à 2,5kgs'), ('4,51 à 5kgs', '4,51-5kgs'), ('2,01 à 3kgs', '2,01 à 3kgs'), ('5,01 à 5,5kgs', '5,01-5,5kgs'), ('2,51 à 3kgs', '2,51 à 3kgs'), ('5,51 à 6,0kgs', '5,51-6,0kgs'), ('6,01 à 6,5 kgs', '6,01-6,5 kgs'), ('6,51 à 7,0 kgs', '6,51-7,0 kgs'), ('3,01 à 3,5kgs', '3,01 à 3,5kgs'), ('3,01 à 4kgs', '3,01 à 4kgs'), ('7,01 à 7,5 kgs', '7,01-7,5 kgs'), ('3,51 à 4kgs', '3,51 à 4kgs'), ('7,51 à 8,0 kgs', '7,51- 8,0 kgs'), ('8,01 à 8,5 kgs', '8,01-8,5 kgs'), ('8,51 à 9,0 kgs', '8,51-9,0 kgs'), ('4,01 à 4,5kgs', '4,01 à 4,5kgs'), ('4,01 à 5kgs', '4,01 à 5kgs'), ('9,01 à 9,5 kgs', '9,01-9,5 kgs'), ('4,51 à 5kgs', '4,51 à 5kgs'), ('9,51 à 10 kgs', '9,51-10 kgs'), ('5,01 à 5,5kgs', '5,01 à 5,5kgs'), ('5,01 à 6kgs', '5,01 à 6kgs'), ('5,51 à 6kgs', '5,51 à 6kgs'), ('6,01 à 6,5kgs', '6,01 à 6,5kgs'), ('6,01 à 7kgs', '6,01 à 7kgs'), ('6,51 à 7kgs', '6,51 à 7kgs'), ('7,01 à 7,5kgs', '7,01 à 7,5kgs'), ('7,01 à 8 kgs', '7,01 à 8 kgs'), ('7,51 à 8kgs', '7,51 à 8kgs'), ('8,01 à 8,5kgs', '8,01 à 8,5kgs'), ('8,01 à 9kgs', '8,01 à 9kgs'), ('8,51 à 9kgs', '8,51 à 9kgs'), ('9,01, à 9,5kgs', '9,01, à 9,5kgs'), ('9,01 à 10kgs', '9,01 à 10kgs'), ('9,51 à 10kgs', '9,51 à 10kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('10,01 à 11kgs', '10,01 à 11kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('11,01 à 12kgs', '11,01 à 12kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('12,01 à 13kgs', '12,01 à 13kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('13,01 à 14kgs', '13,01 à 14kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('14,01 à 15kgs', '14,01 à 15kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('15,01 à 16kgs', '15,01 à 16kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('16,01 à 17kgs', '16,01 à 17kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('17,01 à 18kgs', '17,01 à 18kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('18,01 à 19kgs', '18,01 à 19kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('19,01 à 20kgs', '19,01 à 20kgs'), ('20,01 à 21kgs', '20,01 à 21kgs'), ('21,01 à 22kgs', '21,01 à 22kgs'), ('22,01 à 23kgs', '22,01 à 23kgs'), ('23,01 à 24kgs', '23,01 à 24kgs'), ('24,01 à 25kgs', '24,01 à 25kgs'), ('25,01 à 26kgs', '25,01 à 26kgs'), ('26,01 à 27kgs', '26,01 à 27kgs'), ('27,01 à 28kgs', '27,01 à 28kgs'), ('28,01 à 29kgs', '28,01 à 29kgs'), ('29,01 à 30kgs', '29,01 à 30kgs'), ('30,01 à 31kgs', '30,01 à 31kgs'), ('31,01 à 32kgs', '31,01 à 32kgs'), ('32,01 à 33kgs', '32,01 à 33kgs'), ('33,01 à 34kgs', '33,01 à 34kgs'), ('34,01 à 35kgs', '34,01 à 35kgs'), ('35,01 à 36kgs', '35,01 à 36kgs'), ('36,01 à 37kgs', '36,01 à 37kgs'), ('37,01 à 38kgs', '37,01 à 38kgs'), ('38,01 à 39kgs', '38,01 à 39kgs'), ('39,01 à 40kgs', '39,01 à 40kgs'), ('40,01 à 41kgs', '40,01 à 41kgs'), ('41,01 à 42kgs', '41,01 à 42kgs'), ('42,01 à 43kgs', '42,01 à 43kgs'), ('43,01 à 44kgs', '43,01 à 44kgs'), ('44,01 à 45kgs', '44,01 à 45kgs'), ('45,01 à 46kgs', '45,01 à 46kgs'), ('46,01 à 47kgs', '46,01 à 47kgs'), ('47,01 à 48kgs', '47,01 à 48kgs'), ('48,01 à 49kgs', '48,01 à 49kgs'), ('49,01 à 50kgs', '49,01 à 50kgs'), ('50,01 à 51kgs', '50,01 à 51kgs'), ('51,01 à 52kgs', '51,01 à 52kgs'), ('52,01 à 53kgs', '52,01 à 53kgs'), ('53,01 à 54kgs', '53,01 à 54kgs'), ('54,01 à 55kgs', '54,01 à 55kgs'), ('55,01 à 56kgs', '55,01 à 56kgs'), ('56,01 à 57kgs', '56,01 à 57kgs'), ('57,01 à 58kgs', '57,01 à 58kgs'), ('58,01 à 59kgs', '58,01 à 59kgs'), ('59,01 à 60kgs', '59,01 à 60kgs'), ('60,01 à 61kgs', '60,01 à 61kgs'), ('61,01 à 62kgs', '61,01 à 62kgs'), ('62,01 à 63kgs', '62,01 à 63kgs'), ('63,01 à 64kgs', '63,01 à 64kgs'), ('64,01 à 65kgs', '64,01 à 65kgs'), ('65,01 à 66kgs', '65,01 à 66kgs'), ('66,01 à 67kgs', '66,01 à 67kgs'), ('67,01 à 68kgs', '67,01 à 68kgs'), ('68,01 à 69kgs', '68,01 à 69kgs'), ('69,01 à 70kgs', '69,01 à 70kgs')], max_length=20, verbose_name='POIDS'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='longueur',
            field=models.CharField(choices=[('92CM', '92CM'), ('91CM', '91CM')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='fretroutier',
            name='lieu_destination',
            field=models.CharField(choices=[('KANANGA', 'KANANGA'), ('KIKWIT', 'KIKWIT'), ('MBUJI MAYI ', 'MBUJI MAYI '), ('TSHIKAPA', 'TSHIKAPA')], max_length=20, verbose_name='LIEU DESTINATION'),
        ),
        migrations.AlterField(
            model_name='poubelleuac',
            name='volume',
            field=models.CharField(choices=[('6L', '6L'), ('8L', '8L'), ('12L', '12L'), ('20L', '20L'), ('30L', '30L')], max_length=100, verbose_name='VOLUME EN LITRE'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='longueur',
            field=models.CharField(choices=[('2.4 MTR', '2.4 MTR'), ('3.5 MTR', '3.5 MTR')], max_length=20, verbose_name='LONGUEUR'),
        ),
    ]
