# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0415_auto_20180531_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Envoicolisnational100kgsetplus',
            new_name='EnvoiColisCational100kgsEtPlus',
        ),
        migrations.AlterModelOptions(
            name='affiche',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='cachet',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='carnet',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='carteservice',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='cartevisite',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='casquette',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='depliant',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='flyer',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='gravure',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='laniere',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangecarrosserie',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangedirectionsuspension',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangeelectrique',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangeembrayage',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangefreinage',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangerefroidissement',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecederechangetransmission',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecerechangemoteur',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='piecerevisionmoteur',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='pins',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='porteclef',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='stylo',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='tshirt',
            options={'ordering': ['prix']},
        ),
        migrations.AlterModelOptions(
            name='tshirtblanc',
            options={'ordering': ['prix']},
        ),
        migrations.AlterField(
            model_name='abonnementjournal',
            name='duree_abonnement',
            field=models.CharField(choices=[('3 MOIS', '3 MOIS'), ('6 MOIS', '6 MOIS'), ('12 MOIS', '12 MOIS')], max_length=20, verbose_name="DURÉE D'ABONNEMENT"),
        ),
        migrations.AlterField(
            model_name='abonnementjournal',
            name='type_abonnement',
            field=models.CharField(choices=[('JOURNAL', 'JOURNAL')], max_length=20, verbose_name="TYPE D'ABONNEMENT"),
        ),
        migrations.AlterField(
            model_name='abonnementjournal',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='accueilaeroport',
            name='nombre_personnes',
            field=models.CharField(choices=[('1', '1'), ('1<', '1<')], max_length=20, verbose_name='NOMBRE DE PERSONNES'),
        ),
        migrations.AlterField(
            model_name='accueilaeroport',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='adaptateur',
            name='type_adaptateur',
            field=models.CharField(choices=[('ALIMENTATION CCTV CAMERA 12V', 'ALIMENTATION CCTV CAMERA 12V'), ('USB VERS PORT PARALLELE', 'USB VERS PORT PARALLELE'), ('USB VERS RJ45', 'USB VERS RJ45'), ('USB VERS PORT SERIE', 'USB VERS PORT SERIE'), ('USB VERS SON', 'USB VERS SON'), ('USB WIFI TPLINK T2U AC600', 'USB WIFI TPLINK T2U AC600'), ('USB WIRELESS TL-WN7200ND', 'USB WIRELESS TL-WN7200ND'), ('USB WIFI TPLINK TL-WN725N', 'USB WIFI TPLINK TL-WN725N'), ('1VGA VERS HDMI', 'VGA VERS HDMI'), ('WIFI POUR IMPRIMANTE', 'WIFI POUR IMPRIMANTE'), ('IHPONE 5/6 VERS HDMI AVEC ALIMENTATION', 'IHPONE 5/6 VERS HDMI AVEC ALIMENTATION'), ('DVI VERS VGA', 'DVI VERS VGA'), ('POUR ORDINATEUR', 'POUR ORDINATEUR'), ('UNIVERSEL POUR LAPTOP', 'UNIVERSEL POUR LAPTOP'), ('CARTE MEMOIRE', 'CARTE MEMOIRE'), ('USB 3.0 VERS HDMI', 'USB 3.0 VERS HDMI'), ('USB 3.0 VERS VGA', 'USB 3.0 VERS VGA'), ('HUB CHARGEUR DE SORTIE UNIVERSEL USB', 'HUB CHARGEUR DE SORTIE UNIVERSEL USB'), ('HDMI VERS 3RCA AVEC ALIMENTATON', 'HDMI VERS 3RCA AVEC ALIMENTATON'), ('HDMI VERS VGA AVEC ALIMENTATION', 'HDMI VERS VGA AVEC ALIMENTATION'), ('VGA VERS HDMI', 'VGA VERS HDMI'), ('PORT DISPLAY DVI', 'PORT DISPLAY DVI'), ('HDMI VERS VGA ', 'HDMI VERS VGA '), ('IPAD VERS HDMI', 'IPAD VERS HDMI'), ('PORT MINI DISPLAY VERS DVI', 'PORT MINI DISPLAY VERS DVI'), ('PORT MINI DISPLAY VERS HDMI', 'PORT MINI DISPLAY VERS HDMI'), ('POUR ALIMENTATION IMPRIMANTE HP', 'POUR ALIMENTATION IMPRIMANTE HP')], max_length=100, verbose_name="TYPE D'ADAPTATEUR "),
        ),
        migrations.AlterField(
            model_name='adaptateur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='adresseippublique',
            name='nombre_adresse_maximum',
            field=models.CharField(choices=[('5', '5')], max_length=20, verbose_name="NOMBRE D'IP PUBLIQUE MAXIMUM"),
        ),
        migrations.AlterField(
            model_name='adresseippublique',
            name='units',
            field=models.CharField(choices=[('USD/AN', 'USD/AN')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='antennewifi',
            name='marque_antenne',
            field=models.CharField(choices=[('TP-LINK', 'TP-LINK'), ('UBIQUITI', 'UBIQUITI')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='antennewifi',
            name='modele_antenne',
            field=models.CharField(choices=[('TL-ANT2415D', 'TL-ANT2415D'), ('TL-ANT2424B', 'TL-ANT2424B'), ('M5 NBE-M5-1', 'M5 NBE-M5-1')], max_length=100, verbose_name='MODELE '),
        ),
        migrations.AlterField(
            model_name='antennewifi',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='largeur',
            field=models.CharField(choices=[('27,5CM', '27,5CM'), ('30CM', '30CM'), ('37,5CM', '37,5CM'), ('78CM', '78CM')], max_length=50, verbose_name='LARGEUR'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='longueur',
            field=models.CharField(choices=[('40CM', '40CM')], max_length=50, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='materiau_armoire',
            field=models.CharField(choices=[('BOIS AGGLOMERE', 'BOIS AGGLOMERE'), ('METAL', 'METAL')], max_length=50, verbose_name='MATERIAU'),
        ),
        migrations.AlterField(
            model_name='assainissement',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYES"),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYES"),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='assistanceobtentionvisa',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='tranche_age',
            field=models.CharField(choices=[('0-55 ANS', '0-55 ANS'), ('55-65 ANS', '55-65 ANS'), ('65-69 ANS', '65-69 ANS')], max_length=20, verbose_name="TRANCHE D'AGE"),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='auditcontroleinterne',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYES"),
        ),
        migrations.AlterField(
            model_name='auditcontroleinterne',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='nombre_employes',
            field=models.CharField(choices=[('0-6', '0-6'), ('6-10', '6-10'), ('10–20', '10–20'), ('20–50', '20–50'), ('50–100', '50–100'), ('100 OU PLUS', '100 OU PLUS')], max_length=20, verbose_name="NOMBRE D'EMPLOYÉS"),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='type_intervention',
            field=models.CharField(choices=[('PONCTUELLE', 'PONCTUELLE'), ('CONTINUE', 'CONTINUE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='autocollantcodebar',
            name='dimension_autocollant',
            field=models.CharField(choices=[('102x76 MM', '102x76 MM'), ('50x30 MM', '50x30 MM'), ('60x30 MM', '60x30 MM')], max_length=100, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='autocollantcodebar',
            name='quantite_autocollant',
            field=models.CharField(choices=[('1500', '1500'), ('5000', '5000'), ('4000', '4000')], max_length=100, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='autocollantcodebar',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bacacourrier',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='backdrops',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='baguette',
            name='quantite_par_paquet',
            field=models.CharField(choices=[('10 BOITES', '10 BOITES'), ('500GR', '500GR')], max_length=100, verbose_name='QUANTITE PAR PAQUET'),
        ),
        migrations.AlterField(
            model_name='baguette',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='balastre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bandeadhesive',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bandedefilante',
            name='units',
            field=models.CharField(choices=[('USD/JOUR', 'USD/JOUR')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bandedesignalisation',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='frais_installation',
            field=models.CharField(choices=[('750$', '150$')], max_length=20, verbose_name="FRAIS D'INSTALLATION"),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='type_bande_passante',
            field=models.CharField(choices=[('DEDIE', 'DEDIE')], max_length=20, verbose_name='TYPE DE BANDE PASSANTE'),
        ),
        migrations.AlterField(
            model_name='bandepassante',
            name='units',
            field=models.CharField(choices=[('USD/MOIS', 'USD/MOIS')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='batondecolle',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='batterie',
            name='capacite_batterie',
            field=models.CharField(choices=[('100AH', '100AH'), ('105AH', '105AH'), ('120AH', '120AH'), ('150AH', '150AH'), ('180AH', '180AH'), ('200AH', '200AH'), ('220AH', '220AH'), ('40AH ', '40AH'), ('45AH ', '45AH'), ('60AH ', '60AH'), ('62AH ', '62AH'), ('65AH ', '65AH'), ('66AH ', '66AH'), ('70AH ', '70AH'), ('75AH ', '75AH'), ('80AH ', '80AH'), ('85AH ', '85AH'), ('85AH ', '85AH'), ('88AH ', '88AH'), ('90AH ', '90AH'), ('95AH ', '95AH')], max_length=100, verbose_name='CAPACITE EN AMPERE-HEURE'),
        ),
        migrations.AlterField(
            model_name='batteriecmos',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='batterielaptop',
            name='marque_laptop',
            field=models.CharField(choices=[('HP', 'HP')], max_length=100, verbose_name='MARQUE DU LAPTOP'),
        ),
        migrations.AlterField(
            model_name='batterielaptop',
            name='modeles_laptop',
            field=models.CharField(choices=[('530/510', '530/510'), ('6720/6730', '6720/6730'), ('DV4/DV5/DV6', 'DV4/DV5/DV6'), ('G62', 'G62'), ('NX6120', 'NX6120'), ('PROBOOK 4520/620', 'PROBOOK 4520/620')], max_length=100, verbose_name='MODELE DU LAPTOP'),
        ),
        migrations.AlterField(
            model_name='batterielaptop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='capacite',
            field=models.CharField(choices=[('100Ah', '100Ah'), ('102Ah', '102Ah'), ('200Ah', '200Ah'), ('1130Ah', '1130Ah')], max_length=20, verbose_name='CAPACITE EN AMPERE-HEURE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='tension',
            field=models.CharField(choices=[('2V', '2V'), ('12V', '12V')], max_length=20, verbose_name='TENSION EN VOLT'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='betonniere',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='blocdalimentationpourpc',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='blocnoteligne',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='blocnotememo',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='dimension',
            field=models.CharField(choices=[('80X80MM', '80X80MM'), ('100X100MM', '100X100MM'), ('150X150MM', '150X150MM'), ('200X150MM', '200X150MM')], max_length=20, verbose_name='DIMENSION'),
        ),
    ]
