# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0416_auto_20180531_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitecuisiniere',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boitedarchive',
            name='dimension_boite',
            field=models.CharField(blank=True, choices=[('80MM', '80MM'), ('100MM', '100MM'), ('150MM', '150MM')], max_length=100, null=True, verbose_name='DIMENSION'),
        ),
        migrations.AlterField(
            model_name='boitedarchive',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('4x40 MM', '4x40 MM'), ('4x25 MM', '4x25 MM')], max_length=20, verbose_name='DIMENSION EN MILLIMETRES'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=20, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boitierdisquedur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boitiersocketmural',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='botte',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bougie',
            name='marque_bougie',
            field=models.CharField(choices=[('BOSCH', 'BOSCH'), ('BERU', 'BERU'), ('TOYOTA', 'TOYOTA'), ('NJK', 'NJK')], max_length=100, verbose_name='MARQUE DE BOUGIE'),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='composition_bouillie',
            field=models.CharField(choices=[('SOYA, BLE, MAIS, RIZ ET HUILE VEGETALE', 'SOYA, BLE, MAIS, RIZ ET HUILE VEGETALE')], max_length=100, verbose_name='COMPOSITION'),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='qualite_bouillie',
            field=models.CharField(choices=[('BIO', 'BIO')], max_length=100, verbose_name='QUALITE '),
        ),
        migrations.AlterField(
            model_name='bouillie',
            name='units',
            field=models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50, verbose_name='UNITÉS'),
        ),
        migrations.AlterField(
            model_name='bouilloire',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boulonneuse',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='bouteilleencre',
            name='marque_bouteille_encre',
            field=models.CharField(choices=[('BROTHER', 'BROTHER')], max_length=100, verbose_name="MARQUE DE L'ENCRE"),
        ),
        migrations.AlterField(
            model_name='bouteilleencre',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='boxlight',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='brandingvehiculefull',
            name='units',
            field=models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='broderieecussons',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='type_tshirt',
            field=models.CharField(choices=[('ORDINAIRE', 'ORDINAIRE'), ('PREMIUM', 'PREMIUM')], max_length=100, verbose_name='TYPE DE TSHIRT'),
        ),
        migrations.AlterField(
            model_name='broderiesurtshirt',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name="CHOIX DE L'ACCOMPAGNEMENT"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSONALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE LA BOISSON NON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_dessert',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=20, verbose_name='CHOIX DU DESSERT'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name="CHOIX DE L'ENTRÉE"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_legumes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='CHOIX DES LEGUMES'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='units',
            field=models.CharField(choices=[('USD/PERSONNE', 'USD/PERSONNE')], max_length=50, verbose_name='UNITÉ'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='forme',
            field=models.CharField(choices=[('EN L', 'EN L'), ('OVALE', 'OVALE'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longueur',
            field=models.CharField(choices=[('120CM', '120CM'), ('140CM', '140CM'), ('150CM', '150CM'), ('160CM', '160CM'), ('170CM', '170CM'), ('180CM', '180CM')], max_length=20, verbose_name='LONGUEUR EN CENTIMETRE'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='materiau_bureau',
            field=models.CharField(choices=[('BOIS AGGLOMERE', 'BOIS AGGLOMERE'), ('METAL', 'METAL')], max_length=20, verbose_name='MATERIAU '),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='type_bureau',
            field=models.CharField(choices=[('DIRECTION', 'DIRECTION'), ('SIMPLE', 'SIMPLE')], max_length=20, verbose_name='TYPE DE BUREAU'),
        ),
        migrations.AlterField(
            model_name='burineur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cablecameraccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cablecoaxial',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cableenacier',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cableinformatique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cablemasse',
            name='units',
            field=models.CharField(choices=[('USD/M', 'USD/M')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cablereseau',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cablesouple',
            name='units',
            field=models.CharField(choices=[('USD/M', 'USD/M')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cachet',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='cachet',
            name='type_cachet',
            field=models.CharField(choices=[('ADMINISTRATIF', 'ADMINISTRATIF'), ('NUMERIQUE', 'NUMERIQUE')], max_length=50, verbose_name='TYPE DE CACHET'),
        ),
        migrations.AlterField(
            model_name='cachet',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITS'),
        ),
        migrations.AlterField(
            model_name='cachetdateur',
            name='type_cachet_dateur',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'SIMPLE'), ('AUTOMATIQUE', 'AUTOMATIQUE')], max_length=100, null=True, verbose_name='TYPE DE CACHET'),
        ),
        migrations.AlterField(
            model_name='cachetdateur',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cafetiere',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cahier',
            name='type_cahier',
            field=models.CharField(blank=True, choices=[('SPIRALE', 'SPIRALE'), ('CARTONE', 'CARTONE'), ('REGISTRE QUADRILLE', 'REGISTRE QUADRILLE')], max_length=100, null=True, verbose_name='TYPE DE CAHIER'),
        ),
        migrations.AlterField(
            model_name='cahier',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cahiercharges',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='calculatrice',
            name='type_calculatrice',
            field=models.CharField(blank=True, choices=[('12 CHIFFRES', '12 CHIFFRES')], max_length=100, null=True, verbose_name='TYPE DE CALCULATRICE'),
        ),
        migrations.AlterField(
            model_name='calculatrice',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='format_calendrier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='quantite',
            field=models.CharField(choices=[('1-1000', '1-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000<', '20000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='marque_camera',
            field=models.CharField(choices=[('KODAK', 'KODAK'), ('OLYMPUS', 'OLYMPUS'), ('SONY', 'SONY'), ('CLOUD CAMERA', 'CLOUD CAMERA'), ('CANON', 'CANON')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='modele_camera',
            field=models.CharField(choices=[('C-1505', 'C-1505'), ('T200', 'T200'), ('VE-180', 'VE-180'), ('DSC-T99', 'DSC-T99'), ('DSC-TX1', 'DSC-TX1'), ('HD DAY/NIGHT NC450', 'HD DAY/NIGHT NC450'), ('DIGICAM EOS 350D', 'DIGICAM EOS 350D')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cameraccd',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cameracloud',
            name='marque',
            field=models.CharField(choices=[('TP-LINK', 'TP-LINK')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='cameracloud',
            name='modele',
            field=models.CharField(choices=[('NC250', 'NC250'), ('NC220', 'NC220')], max_length=100, verbose_name='MODELE'),
        ),

    ]
