# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0417_auto_20180531_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancecomptable',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='assistancecomptable',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='assistancefiscale',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='assurancevoyage',
            name='periode',
            field=models.CharField(choices=[('1-5 JOURS', '1-5 JOURS'), ('1-7 JOURS', '1-7 JOURS'), ('6-7 JOURS', '6-7 JOURS'), ('8-10 JOURS', '8-10 JOURS'), ('8-15 JOURS', '8-15 JOURS'), ('11-15 JOURS', '11-15 JOURS'), ('16-21 JOURS', '16-21 JOURS'), ('22-30 JOURS', '22-30 JOURS'), ('31-45 JOURS', '31-45 JOURS'), ('46-60 JOURS', '46-60 JOURS'), ('61-90 JOURS', '61-90 JOURS'), ('91-180 JOURS', '91-180 JOURS')], max_length=20, verbose_name='NOMBRE DES JOURS'),
        ),
        migrations.AlterField(
            model_name='auditcontroleinterne',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='auditcontroleinterne',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='auditfinancier',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='lieu',
            field=models.CharField(blank=True, choices=[('A CONVENIR', 'A CONVENIR'), ('SUR PLACE', 'SUR PLACE')], max_length=20, null=True, verbose_name='LIEU'),
        ),
        migrations.AlterField(
            model_name='cameracloud',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cameraip',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='marque',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='modele',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='type_camion',
            field=models.CharField(choices=[('4X4', '4X4'), ('6X6', '6X6')], max_length=100, verbose_name='TYPE DE CAMION'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='type_carbonne',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE FACE', 'DOUBLE FACE')], max_length=100, null=True, verbose_name='TYPE DE CARBONNE'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='units',
            field=models.CharField(choices=[('USD/PAQUET', 'USD/PAQUET')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='format_papier',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('1/3 A4', '1/3 A4')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-10000', '1001-10000')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='carnetderecu',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='type_carte',
            field=models.CharField(choices=[('GRAPHIQUE PCI EXPRESS NVIDIA 1GO', 'GRAPHIQUE PCI EXPRESS NVIDIA 1GO'), ('GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO', 'GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO'), ('READER EXTERNAL', 'READER EXTERNAL'), ('RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND', 'RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND'), ('FIREWIRE PCI LW', 'FIREWIRE PCI LW'), ('GRAPHIQUE NVIDIA 1GB', 'GRAPHIQUE NVIDIA 1GB'), ('PCI COMBO 2 SERIAL+1PARRALE', 'PCI COMBO 2 SERIAL+1PARRALE'), ('PCI EXPRESS', 'PCI EXPRESS'), ('PCI SERIAL ATA HOST', 'PCI SERIAL ATA HOST'), ('PCI TO PCMCI', 'PCI TO PCMCI'), ('PCI ULTRA ATA', 'PCI ULTRA ATA'), ('PCMCI RJ45', 'PCMCI RJ45'), ('SON PCI', 'SON PCI'), ('CARTE MERE INTEL DG 41BL', 'CARTE MERE INTEL DG 41BL')], max_length=100, verbose_name='TYPE DE CARTE'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50, verbose_name='FACE A IMPRIMER'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('100 <', '100 <'), ('1-1000', '1-1000'), ('1000<', '1000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='face_impression',
            field=models.CharField(choices=[('RECTO', 'RECTO'), ('RECTO VERSO', 'RECTO VERSO')], max_length=50, verbose_name='FACE A IMPRIMER'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='quantite',
            field=models.CharField(choices=[('100', '100')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='cartevisite',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='cartouche',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='casqueavecmicro',
            name='marque_casque_micro',
            field=models.CharField(choices=[('LG TONE', 'LG TONE')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='casqueavecmicro',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='casquemusique',
            name='marque_casque_musique',
            field=models.CharField(choices=[('GORSUN', 'GORSUN'), ('SAMSUNG', 'SAMSUNG'), ('BEATS', 'BEATS'), ('LIGHTWAVE BIG', 'LIGHTWAVE BIG'), ('LIGHTWAVE SMALL', 'LIGHTWAVE SMALL')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='casquemusique',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='casquemusiquehautparleur',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='quantite',
            field=models.CharField(choices=[('1-100', '1-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001-10000', '5001-10000'), ('10000<', '10000<')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='casquette',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chainedesecuritepourlaptop',
            name='units',
            field=models.CharField(choices=[('USD', 'USD'), ('$/KM', '$/KM'), ('% DES DROITS ET TAXES', '% DES DROITS ET TAXES'), ('% DE LA VALEUR CIF', '% DE LA VALEUR CIF'), ('USD/SAC', 'USD/SAC'), ('USD/POSTE', 'USD/POSTE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chaisebureau',
            name='revetement',
            field=models.CharField(choices=[('CUIR', 'CUIR'), ('MAILLE', 'MAILLE'), ('TISSU ET MAILLE', 'TISSU ET MAILLE')], max_length=20, verbose_name='REVETEMENT'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='lieu',
            field=models.CharField(blank=True, choices=[('A CONVENIR', 'A CONVENIR'), ('SUR PLACE', 'SUR PLACE')], max_length=20, null=True, verbose_name='LIEU'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='courslanguenationale',
            name='langue_cours',
            field=models.CharField(choices=[('KIKONGO', 'KIKONGO'), ('LINGALA', 'LINGALA'), ('SWAHILI', 'SWAHILI'), ('TSHILUBA', 'TSHILUBA')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='envoicoliscational100kgsetplus',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternational',
            name='pays_destination',
            field=models.CharField(choices=[('ACORES', 'ACORES'), ('AFGHANISTAN', 'AFGHANISTAN'), ('AFRIQUE DU SUD', 'AFRIQUE DU SUD'), ('ALBANIE', 'ALBANIE'), ('ALGERIE', 'ALGERIE'), ('ALLEMAGNE', 'ALLEMAGNE'), ('ANDORRE', 'ANDORRE'), ('ANGLETERRE', 'ANGLETERRE'), ('ANGOLA', 'ANGOLA'), ('ANGUILLA', 'ANGUILLA'), ('ANTIGUA', 'ANTIGUA'), ('ANTIGUA-ET-BARBUDA', 'ANTIGUA-ET-BARBUDA'), ('ANTILLES NEERLANDAISES', 'ANTILLES NEERLANDAISES'), ('ARABIE SAOUDITE', 'ARABIE SAOUDITE'), ('ARGENTINE', 'ARGENTINE'), ('ARMENIE', 'ARMENIE'), ('ARUBA', 'ARUBA'), ('AUSTRALIE', 'AUSTRALIE'), ('AUTRICHE', 'AUTRICHE'), ('AZERBAIDJAN', 'AZERBAIDJAN'), ('BAHAMAS', 'BAHAMAS'), ('BAHREIN', 'BAHREIN'), ('BANGLADESH', 'BANGLADESH'), ('BARBADE', 'BARBADE'), ('BARBADES', 'BARBADES'), ('BARBUDA(ANTIGUA)', 'BARBUDA(ANTIGUA)'), ('BELGIQUE ', 'BELGIQUE '), ('BELGIQUE', 'BELGIQUE'), ('BELIZE', 'BELIZE'), ('BENIN', 'BENIN'), ('BERMUDES', 'BERMUDES'), ('BHOUTAN', 'BHOUTAN'), ('BIELORUSSIE', 'BIELORUSSIE'), ('BOLIVIE', 'BOLIVIE'), ('BONAIRE', 'BONAIRE'), ('BOSNIE à HERZEGOVINE', 'BOSNIE à HERZEGOVINE'), ('BOSNIE', 'BOSNIE'), ('BOSNIE-HERZEGOVINE', 'BOSNIE-HERZEGOVINE'), ('BOTSWANA', 'BOTSWANA'), ('BRESIL', 'BRESIL'), ('BRUNEI', 'BRUNEI'), ('BULGARIE', 'BULGARIE'), ('BURKINA FASO', 'BURKINA FASO'), ('BURUNDI', 'BURUNDI'), ('CAIMAN ILES', 'CAIMAN ILES'), ('CAÏMANS(ILES)', 'CAÏMANS(ILES)'), ('CAMBODGE', 'CAMBODGE'), ('CAMEROUN', 'CAMEROUN'), ('CANADA', 'CANADA'), ('CANARIES(ILES)', 'CANARIES(ILES)'), ('CAP VERT', 'CAP VERT'), ('CENTRAFRIQUE', 'CENTRAFRIQUE'), ('CEUTA', 'CEUTA'), ('CHANNELLE(ILES)  à  GUERNSEY', 'CHANNELLE(ILES)  à  GUERNSEY'), ('CHANNELLE(ILES)  à  JERSEY', 'CHANNELLE(ILES)  à  JERSEY'), ('CHANNELLE(ILES) - GUERNSEY', 'CHANNELLE(ILES) - GUERNSEY'), ('CHANNELLE(ILES) - JERSEY', 'CHANNELLE(ILES) - JERSEY'), ('CHILI', 'CHILI'), ('CHINE', 'CHINE'), ('CHYPRE ', 'CHYPRE '), ('CHYPRE', 'CHYPRE'), ('COLOMBIE', 'COLOMBIE'), ('COMORES', 'COMORES'), ('CONGO(BRAZZAVILLE)', 'CONGO(BRAZZAVILLE)'), ('CONGO', 'CONGO'), ('COOK ILES', 'COOK ILES'), ('COOK(ILES)', 'COOK(ILES)'), ('COREE DU NORD', 'COREE DU NORD'), ('COREE DU SUD', 'COREE DU SUD'), ('CORÉE DU SUD', 'CORÉE DU SUD'), ('COSTA RICA', 'COSTA RICA'), ('COTE D IVOIRE', 'COTE D IVOIRE'), ('CROATIE', 'CROATIE'), ('CUBA', 'CUBA'), ('CURACAO', 'CURACAO'), ('DANEMARK', 'DANEMARK'), ('DJIBOUTI', 'DJIBOUTI'), ('DOMINIQUE', 'DOMINIQUE'), ('ECOSSE', 'ECOSSE'), ('EGYPTE', 'EGYPTE'), ('EL SALVADOR', 'EL SALVADOR'), ('EMIRATS ARABE UNIS', 'EMIRATS ARABE UNIS'), ('EMIRATS ARABES UNIS', 'EMIRATS ARABES UNIS'), ('EQUATEUR', 'EQUATEUR'), ('ERITHRÉE', 'ERITHRÉE'), ('ERYTRHEE', 'ERYTRHEE'), ('ESPAGNE ', 'ESPAGNE '), ('ESPAGNE', 'ESPAGNE'), ('ESTONIE', 'ESTONIE'), ('ETATS UNIS', 'ETATS UNIS'), ('ETATS-UNIS', 'ETATS-UNIS'), ('ETHIOPIE', 'ETHIOPIE'), ('FALKSLANDS', 'FALKSLANDS'), ('FÉROÉ(ILES)', 'FÉROÉ(ILES)'), ('FIDJI', 'FIDJI'), ('FINLANDE', 'FINLANDE'), ('FRANCE ', 'FRANCE '), ('FRANCE', 'FRANCE'), ('GABON', 'GABON'), ('GAMBIE', 'GAMBIE'), ('GAZA (WEST BANK)', 'GAZA (WEST BANK)'), ('GEORGIE', 'GEORGIE'), ('GÉORGIE', 'GÉORGIE'), ('GHANA', 'GHANA'), ('GIBRALTAR', 'GIBRALTAR'), ('GRECE', 'GRECE'), ('GRENADE', 'GRENADE'), ('GROENLAND', 'GROENLAND'), ('GUADELOUPE', 'GUADELOUPE'), ('GUAM (ILE)', 'GUAM (ILE)'), ('GUAM', 'GUAM'), ('GUATEMALA', 'GUATEMALA'), ('GUERNESEY', 'GUERNESEY'), ('GUIANA', 'GUIANA'), ('GUINEE BISSAU', 'GUINEE BISSAU'), ('GUINÉE BISSAU', 'GUINÉE BISSAU'), ('GUINEE EQUATORIALE', 'GUINEE EQUATORIALE'), ('GUINÉE EQUATORIALE', 'GUINÉE EQUATORIALE'), ('GUINEE FRANCAISE', 'GUINEE FRANCAISE'), ('GUINEE', 'GUINEE'), ('GUINÉE', 'GUINÉE'), ('GUYANE FRANÇAISE', 'GUYANE FRANÇAISE'), ('GUYANE', 'GUYANE'), ('HAITI', 'HAITI'), ('HAWAI', 'HAWAI'), ('HONDURAS', 'HONDURAS'), ('HONG KONG', 'HONG KONG'), ('HONGRIE', 'HONGRIE'), ('ILE DE MAN', 'ILE DE MAN'), ('ILE MAURICE', 'ILE MAURICE'), ('ILES CANARIES', 'ILES CANARIES'), ('ILES FEROE', 'ILES FEROE'), ('ILES MARSHALL', 'ILES MARSHALL'), ('ILES TURQUES ET CAICOS', 'ILES TURQUES ET CAICOS'), ('ILES VIERGES  à  GB', 'ILES VIERGES  à  GB'), ('ILES VIERGES  à  USA', 'ILES VIERGES  à  USA'), ('ILES VIERGES - GB', 'ILES VIERGES - GB'), ('ILES VIERGES - USA', 'ILES VIERGES - USA'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILLE MAURICE', 'ILLE MAURICE'), ('INDE', 'INDE'), ('INDONESIE', 'INDONESIE'), ('IRAK', 'IRAK'), ('IRAN', 'IRAN'), ('IRLANDE ', 'IRLANDE '), ('IRLANDE DU NORD', 'IRLANDE DU NORD'), ('IRLANDE', 'IRLANDE'), ('ISLANDE', 'ISLANDE'), ('ISRAEL', 'ISRAEL'), ('ITALIE ', 'ITALIE '), ('ITALIE', 'ITALIE'), ('JAMAIQUE', 'JAMAIQUE'), ('JAPON', 'JAPON'), ('JERSEY', 'JERSEY'), ('JORDANIE', 'JORDANIE'), ('KAZAKHSTAN', 'KAZAKHSTAN'), ('KENYA', 'KENYA'), ('KIRGHIZISTAN', 'KIRGHIZISTAN'), ('KIRIBATI', 'KIRIBATI'), ('KOSOVO', 'KOSOVO'), ('KOSRAE(MICRONÉSIE)', 'KOSRAE(MICRONÉSIE)'), ('KOWEIT', 'KOWEIT'), ('KYRGYZSTAN', 'KYRGYZSTAN'), ('LAOS', 'LAOS'), ('LESOTHO', 'LESOTHO'), ('LETTONIE', 'LETTONIE'), ('LIBAN', 'LIBAN'), ('LIBERIA', 'LIBERIA'), ('LIBYE', 'LIBYE'), ('LIECHTENSTEIN', 'LIECHTENSTEIN'), ('LITUANIE', 'LITUANIE'), ('LUXEMBOURG', 'LUXEMBOURG'), ('LYBIE', 'LYBIE'), ('MACAO', 'MACAO'), ('MACEDOINE', 'MACEDOINE'), ('MADAGASCAR', 'MADAGASCAR'), ('MADEIRE', 'MADEIRE'), ('MADERE', 'MADERE'), ('MALAISIE', 'MALAISIE'), ('MALAWI', 'MALAWI'), ('MALDIVES', 'MALDIVES'), ('MALI', 'MALI'), ('MALTE', 'MALTE'), ('MARIANNE DU NORD(ILES)', 'MARIANNE DU NORD(ILES)'), ('MAROC', 'MAROC'), ('MARTINIQUE', 'MARTINIQUE'), ('MAURITANIE', 'MAURITANIE'), ('MAYOTTE', 'MAYOTTE'), ('MELILLA', 'MELILLA'), ('MEXIQUE', 'MEXIQUE'), ('MICRONESIE', 'MICRONESIE'), ('MOLDAVIE', 'MOLDAVIE'), ('MONACO', 'MONACO'), ('MONGOLIE', 'MONGOLIE'), ('MONSERRAT', 'MONSERRAT'), ('MONTENEGRO', 'MONTENEGRO'), ('MONTSERRAT', 'MONTSERRAT'), ('MOZAMBIQUE', 'MOZAMBIQUE'), ('MYANMAR', 'MYANMAR'), ('NAMIBIE', 'NAMIBIE'), ('NAURU', 'NAURU'), ('NEPAL', 'NEPAL'), ('NEVIS(ST KITTS)', 'NEVIS(ST KITTS)'), ('NEVIS', 'NEVIS'), ('NICARAGUA', 'NICARAGUA'), ('NIGER', 'NIGER'), ('NIGERIA', 'NIGERIA'), ('NIUE ILE', 'NIUE ILE'), ('NORVEGE', 'NORVEGE'), ('NOUVELLE CALEDONIE', 'NOUVELLE CALEDONIE'), ('NOUVELLE CALÉDONIE', 'NOUVELLE CALÉDONIE'), ('NOUVELLE ZELANDE', 'NOUVELLE ZELANDE'), ('OMAN', 'OMAN'), ('OUGANDA', 'OUGANDA'), ('OUZBEKISTAN', 'OUZBEKISTAN'), ('PAKISTAN', 'PAKISTAN'), ('PALAOS', 'PALAOS'), ('PANAMA', 'PANAMA'), ('PAPOUASIE NOUVELLE GUINÉE', 'PAPOUASIE NOUVELLE GUINÉE'), ('PAPOUASIE', 'PAPOUASIE'), ('PARAGUAY', 'PARAGUAY'), ('PAYS DE GALLES', 'PAYS DE GALLES'), ('PAYS-BAS', 'PAYS-BAS'), ('PEROU', 'PEROU'), ('PHILIPPINES', 'PHILIPPINES'), ('POLOGNE', 'POLOGNE'), ('POLYNÉSIE FRANÇAISE', 'POLYNÉSIE FRANÇAISE'), ('POLYNESIE', 'POLYNESIE'), ('PONAPE', 'PONAPE'), ('PORTO RICO', 'PORTO RICO'), ('PORTORICO', 'PORTORICO'), ('PORTUGAL', 'PORTUGAL'), ('QATAR', 'QATAR'), ('QUATAR', 'QUATAR'), ('REPUBLIQUE DIMINICAINE', 'REPUBLIQUE DIMINICAINE'), ('RÉPUBLIQUE DOMINICAINE', 'RÉPUBLIQUE DOMINICAINE'), ('RÉPUBLIQUE TCHÈQUE', 'RÉPUBLIQUE TCHÈQUE'), ('REUNION', 'REUNION'), ('RÉUNION', 'RÉUNION'), ('ROTA', 'ROTA'), ('ROUMANIE', 'ROUMANIE'), ('ROYAUME-UNI', 'ROYAUME-UNI'), ('RUSSIE', 'RUSSIE'), ('RWANDA', 'RWANDA'), ('SABA', 'SABA'), ('SAINT BARTH', 'SAINT BARTH'), ('SAINT BARTHELEMY', 'SAINT BARTHELEMY'), ('SAINT CHRISTOPHE(ST. KITTS)', 'SAINT CHRISTOPHE(ST. KITTS)'), ('SAINT JEAN', 'SAINT JEAN'), ('SAINT KITTS', 'SAINT KITTS'), ('SAINT MAARTEN', 'SAINT MAARTEN'), ('SAINT MARIN', 'SAINT MARIN'), ('SAINT MARTIN', 'SAINT MARTIN'), ('SAINT PIERRE', 'SAINT PIERRE'), ('SAINT THOMAS', 'SAINT THOMAS'), ('SAINT VINCENT ET LES GRENADES', 'SAINT VINCENT ET LES GRENADES'), ('SAINT VINCENT', 'SAINT VINCENT'), ('SAINTE LUCIE', 'SAINTE LUCIE'), ('SAIPAN', 'SAIPAN'), ('SAMOA  à  USA', 'SAMOA  à  USA'), ('SAMOA - USA', 'SAMOA - USA'), ('SAMOA ILES', 'SAMOA ILES'), ('SAN MARIN', 'SAN MARIN'), ('SENEGAL', 'SENEGAL'), ('SERBIE', 'SERBIE'), ('SEYCHELLES', 'SEYCHELLES'), ('SIERRA LEONE', 'SIERRA LEONE'), ('SINGAPOUR', 'SINGAPOUR'), ('SLOVAQUIE', 'SLOVAQUIE'), ('SLOVENIE', 'SLOVENIE'), ('SRI LANKA', 'SRI LANKA'), ('SUEDE', 'SUEDE'), ('SUISSE', 'SUISSE'), ('SURINAM', 'SURINAM'), ('SURINAME', 'SURINAME'), ('SWAZILAND', 'SWAZILAND'), ('SYRIE', 'SYRIE'), ('TADJIKISTAN', 'TADJIKISTAN'), ('TAHITI', 'TAHITI'), ('TAIWAN', 'TAIWAN'), ('TANZANIE', 'TANZANIE'), ('TCHAD', 'TCHAD'), ('THAILAND', 'THAILAND'), ('THAILANDE', 'THAILANDE'), ('TIMOR ORIENTAL', 'TIMOR ORIENTAL'), ('TINIAN', 'TINIAN'), ('TOGO', 'TOGO'), ('TONGA', 'TONGA'), ('TORTOLA', 'TORTOLA'), ('TRINITE ET TOBAGO', 'TRINITE ET TOBAGO'), ('TRINITÉ ET TOBAGO', 'TRINITÉ ET TOBAGO'), ('TRUK', 'TRUK'), ('TUNISIE', 'TUNISIE'), ('TURKMENISTAN', 'TURKMENISTAN'), ('TURQUIE', 'TURQUIE'), ('TUVALU', 'TUVALU'), ('UKRAINE', 'UKRAINE'), ('UNION(ILE)', 'UNION(ILE)'), ('URUGUAY', 'URUGUAY'), ('VANUATU', 'VANUATU'), ('VATICAN CITE', 'VATICAN CITE'), ('VENEZUELA', 'VENEZUELA'), ('VIERGE GORDA(ILES VIERGES BRITANNIQUES)', 'VIERGE GORDA(ILES VIERGES BRITANNIQUES)'), ('VIETNAM', 'VIETNAM'), ('WALLIS ET FUTUNA', 'WALLIS ET FUTUNA'), ('YAP', 'YAP'), ('YEMEN', 'YEMEN'), ('ZAMBIE', 'ZAMBIE'), ('ZIMBABWE', 'ZIMBABWE')], max_length=50, verbose_name='PAYS DESTINATION'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternationalplus70kg',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisinternationalplus70kg',
            name='pays_destination',
            field=models.CharField(choices=[('ACORES', 'ACORES'), ('AFGHANISTAN', 'AFGHANISTAN'), ('AFRIQUE DU SUD', 'AFRIQUE DU SUD'), ('ALBANIE', 'ALBANIE'), ('ALGERIE', 'ALGERIE'), ('ALLEMAGNE', 'ALLEMAGNE'), ('ANDORRE', 'ANDORRE'), ('ANGLETERRE', 'ANGLETERRE'), ('ANGOLA', 'ANGOLA'), ('ANGUILLA', 'ANGUILLA'), ('ANTIGUA', 'ANTIGUA'), ('ANTIGUA-ET-BARBUDA', 'ANTIGUA-ET-BARBUDA'), ('ANTILLES NEERLANDAISES', 'ANTILLES NEERLANDAISES'), ('ARABIE SAOUDITE', 'ARABIE SAOUDITE'), ('ARGENTINE', 'ARGENTINE'), ('ARMENIE', 'ARMENIE'), ('ARUBA', 'ARUBA'), ('AUSTRALIE', 'AUSTRALIE'), ('AUTRICHE', 'AUTRICHE'), ('AZERBAIDJAN', 'AZERBAIDJAN'), ('BAHAMAS', 'BAHAMAS'), ('BAHREIN', 'BAHREIN'), ('BANGLADESH', 'BANGLADESH'), ('BARBADE', 'BARBADE'), ('BARBADES', 'BARBADES'), ('BARBUDA(ANTIGUA)', 'BARBUDA(ANTIGUA)'), ('BELGIQUE ', 'BELGIQUE '), ('BELGIQUE', 'BELGIQUE'), ('BELIZE', 'BELIZE'), ('BENIN', 'BENIN'), ('BERMUDES', 'BERMUDES'), ('BHOUTAN', 'BHOUTAN'), ('BIELORUSSIE', 'BIELORUSSIE'), ('BOLIVIE', 'BOLIVIE'), ('BONAIRE', 'BONAIRE'), ('BOSNIE à HERZEGOVINE', 'BOSNIE à HERZEGOVINE'), ('BOSNIE', 'BOSNIE'), ('BOSNIE-HERZEGOVINE', 'BOSNIE-HERZEGOVINE'), ('BOTSWANA', 'BOTSWANA'), ('BRESIL', 'BRESIL'), ('BRUNEI', 'BRUNEI'), ('BULGARIE', 'BULGARIE'), ('BURKINA FASO', 'BURKINA FASO'), ('BURUNDI', 'BURUNDI'), ('CAIMAN ILES', 'CAIMAN ILES'), ('CAÏMANS(ILES)', 'CAÏMANS(ILES)'), ('CAMBODGE', 'CAMBODGE'), ('CAMEROUN', 'CAMEROUN'), ('CANADA', 'CANADA'), ('CANARIES(ILES)', 'CANARIES(ILES)'), ('CAP VERT', 'CAP VERT'), ('CENTRAFRIQUE', 'CENTRAFRIQUE'), ('CEUTA', 'CEUTA'), ('CHANNELLE(ILES)  à  GUERNSEY', 'CHANNELLE(ILES)  à  GUERNSEY'), ('CHANNELLE(ILES)  à  JERSEY', 'CHANNELLE(ILES)  à  JERSEY'), ('CHANNELLE(ILES) - GUERNSEY', 'CHANNELLE(ILES) - GUERNSEY'), ('CHANNELLE(ILES) - JERSEY', 'CHANNELLE(ILES) - JERSEY'), ('CHILI', 'CHILI'), ('CHINE', 'CHINE'), ('CHYPRE ', 'CHYPRE '), ('CHYPRE', 'CHYPRE'), ('COLOMBIE', 'COLOMBIE'), ('COMORES', 'COMORES'), ('CONGO(BRAZZAVILLE)', 'CONGO(BRAZZAVILLE)'), ('CONGO', 'CONGO'), ('COOK ILES', 'COOK ILES'), ('COOK(ILES)', 'COOK(ILES)'), ('COREE DU NORD', 'COREE DU NORD'), ('COREE DU SUD', 'COREE DU SUD'), ('CORÉE DU SUD', 'CORÉE DU SUD'), ('COSTA RICA', 'COSTA RICA'), ('COTE D IVOIRE', 'COTE D IVOIRE'), ('CROATIE', 'CROATIE'), ('CUBA', 'CUBA'), ('CURACAO', 'CURACAO'), ('DANEMARK', 'DANEMARK'), ('DJIBOUTI', 'DJIBOUTI'), ('DOMINIQUE', 'DOMINIQUE'), ('ECOSSE', 'ECOSSE'), ('EGYPTE', 'EGYPTE'), ('EL SALVADOR', 'EL SALVADOR'), ('EMIRATS ARABE UNIS', 'EMIRATS ARABE UNIS'), ('EMIRATS ARABES UNIS', 'EMIRATS ARABES UNIS'), ('EQUATEUR', 'EQUATEUR'), ('ERITHRÉE', 'ERITHRÉE'), ('ERYTRHEE', 'ERYTRHEE'), ('ESPAGNE ', 'ESPAGNE '), ('ESPAGNE', 'ESPAGNE'), ('ESTONIE', 'ESTONIE'), ('ETATS UNIS', 'ETATS UNIS'), ('ETATS-UNIS', 'ETATS-UNIS'), ('ETHIOPIE', 'ETHIOPIE'), ('FALKSLANDS', 'FALKSLANDS'), ('FÉROÉ(ILES)', 'FÉROÉ(ILES)'), ('FIDJI', 'FIDJI'), ('FINLANDE', 'FINLANDE'), ('FRANCE ', 'FRANCE '), ('FRANCE', 'FRANCE'), ('GABON', 'GABON'), ('GAMBIE', 'GAMBIE'), ('GAZA (WEST BANK)', 'GAZA (WEST BANK)'), ('GEORGIE', 'GEORGIE'), ('GÉORGIE', 'GÉORGIE'), ('GHANA', 'GHANA'), ('GIBRALTAR', 'GIBRALTAR'), ('GRECE', 'GRECE'), ('GRENADE', 'GRENADE'), ('GROENLAND', 'GROENLAND'), ('GUADELOUPE', 'GUADELOUPE'), ('GUAM (ILE)', 'GUAM (ILE)'), ('GUAM', 'GUAM'), ('GUATEMALA', 'GUATEMALA'), ('GUERNESEY', 'GUERNESEY'), ('GUIANA', 'GUIANA'), ('GUINEE BISSAU', 'GUINEE BISSAU'), ('GUINÉE BISSAU', 'GUINÉE BISSAU'), ('GUINEE EQUATORIALE', 'GUINEE EQUATORIALE'), ('GUINÉE EQUATORIALE', 'GUINÉE EQUATORIALE'), ('GUINEE FRANCAISE', 'GUINEE FRANCAISE'), ('GUINEE', 'GUINEE'), ('GUINÉE', 'GUINÉE'), ('GUYANE FRANÇAISE', 'GUYANE FRANÇAISE'), ('GUYANE', 'GUYANE'), ('HAITI', 'HAITI'), ('HAWAI', 'HAWAI'), ('HONDURAS', 'HONDURAS'), ('HONG KONG', 'HONG KONG'), ('HONGRIE', 'HONGRIE'), ('ILE DE MAN', 'ILE DE MAN'), ('ILE MAURICE', 'ILE MAURICE'), ('ILES CANARIES', 'ILES CANARIES'), ('ILES FEROE', 'ILES FEROE'), ('ILES MARSHALL', 'ILES MARSHALL'), ('ILES TURQUES ET CAICOS', 'ILES TURQUES ET CAICOS'), ('ILES VIERGES  à  GB', 'ILES VIERGES  à  GB'), ('ILES VIERGES  à  USA', 'ILES VIERGES  à  USA'), ('ILES VIERGES - GB', 'ILES VIERGES - GB'), ('ILES VIERGES - USA', 'ILES VIERGES - USA'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILLE MAURICE', 'ILLE MAURICE'), ('INDE', 'INDE'), ('INDONESIE', 'INDONESIE'), ('IRAK', 'IRAK'), ('IRAN', 'IRAN'), ('IRLANDE ', 'IRLANDE '), ('IRLANDE DU NORD', 'IRLANDE DU NORD'), ('IRLANDE', 'IRLANDE'), ('ISLANDE', 'ISLANDE'), ('ISRAEL', 'ISRAEL'), ('ITALIE ', 'ITALIE '), ('ITALIE', 'ITALIE'), ('JAMAIQUE', 'JAMAIQUE'), ('JAPON', 'JAPON'), ('JERSEY', 'JERSEY'), ('JORDANIE', 'JORDANIE'), ('KAZAKHSTAN', 'KAZAKHSTAN'), ('KENYA', 'KENYA'), ('KIRGHIZISTAN', 'KIRGHIZISTAN'), ('KIRIBATI', 'KIRIBATI'), ('KOSOVO', 'KOSOVO'), ('KOSRAE(MICRONÉSIE)', 'KOSRAE(MICRONÉSIE)'), ('KOWEIT', 'KOWEIT'), ('KYRGYZSTAN', 'KYRGYZSTAN'), ('LAOS', 'LAOS'), ('LESOTHO', 'LESOTHO'), ('LETTONIE', 'LETTONIE'), ('LIBAN', 'LIBAN'), ('LIBERIA', 'LIBERIA'), ('LIBYE', 'LIBYE'), ('LIECHTENSTEIN', 'LIECHTENSTEIN'), ('LITUANIE', 'LITUANIE'), ('LUXEMBOURG', 'LUXEMBOURG'), ('LYBIE', 'LYBIE'), ('MACAO', 'MACAO'), ('MACEDOINE', 'MACEDOINE'), ('MADAGASCAR', 'MADAGASCAR'), ('MADEIRE', 'MADEIRE'), ('MADERE', 'MADERE'), ('MALAISIE', 'MALAISIE'), ('MALAWI', 'MALAWI'), ('MALDIVES', 'MALDIVES'), ('MALI', 'MALI'), ('MALTE', 'MALTE'), ('MARIANNE DU NORD(ILES)', 'MARIANNE DU NORD(ILES)'), ('MAROC', 'MAROC'), ('MARTINIQUE', 'MARTINIQUE'), ('MAURITANIE', 'MAURITANIE'), ('MAYOTTE', 'MAYOTTE'), ('MELILLA', 'MELILLA'), ('MEXIQUE', 'MEXIQUE'), ('MICRONESIE', 'MICRONESIE'), ('MOLDAVIE', 'MOLDAVIE'), ('MONACO', 'MONACO'), ('MONGOLIE', 'MONGOLIE'), ('MONSERRAT', 'MONSERRAT'), ('MONTENEGRO', 'MONTENEGRO'), ('MONTSERRAT', 'MONTSERRAT'), ('MOZAMBIQUE', 'MOZAMBIQUE'), ('MYANMAR', 'MYANMAR'), ('NAMIBIE', 'NAMIBIE'), ('NAURU', 'NAURU'), ('NEPAL', 'NEPAL'), ('NEVIS(ST KITTS)', 'NEVIS(ST KITTS)'), ('NEVIS', 'NEVIS'), ('NICARAGUA', 'NICARAGUA'), ('NIGER', 'NIGER'), ('NIGERIA', 'NIGERIA'), ('NIUE ILE', 'NIUE ILE'), ('NORVEGE', 'NORVEGE'), ('NOUVELLE CALEDONIE', 'NOUVELLE CALEDONIE'), ('NOUVELLE CALÉDONIE', 'NOUVELLE CALÉDONIE'), ('NOUVELLE ZELANDE', 'NOUVELLE ZELANDE'), ('OMAN', 'OMAN'), ('OUGANDA', 'OUGANDA'), ('OUZBEKISTAN', 'OUZBEKISTAN'), ('PAKISTAN', 'PAKISTAN'), ('PALAOS', 'PALAOS'), ('PANAMA', 'PANAMA'), ('PAPOUASIE NOUVELLE GUINÉE', 'PAPOUASIE NOUVELLE GUINÉE'), ('PAPOUASIE', 'PAPOUASIE'), ('PARAGUAY', 'PARAGUAY'), ('PAYS DE GALLES', 'PAYS DE GALLES'), ('PAYS-BAS', 'PAYS-BAS'), ('PEROU', 'PEROU'), ('PHILIPPINES', 'PHILIPPINES'), ('POLOGNE', 'POLOGNE'), ('POLYNÉSIE FRANÇAISE', 'POLYNÉSIE FRANÇAISE'), ('POLYNESIE', 'POLYNESIE'), ('PONAPE', 'PONAPE'), ('PORTO RICO', 'PORTO RICO'), ('PORTORICO', 'PORTORICO'), ('PORTUGAL', 'PORTUGAL'), ('QATAR', 'QATAR'), ('QUATAR', 'QUATAR'), ('REPUBLIQUE DIMINICAINE', 'REPUBLIQUE DIMINICAINE'), ('RÉPUBLIQUE DOMINICAINE', 'RÉPUBLIQUE DOMINICAINE'), ('RÉPUBLIQUE TCHÈQUE', 'RÉPUBLIQUE TCHÈQUE'), ('REUNION', 'REUNION'), ('RÉUNION', 'RÉUNION'), ('ROTA', 'ROTA'), ('ROUMANIE', 'ROUMANIE'), ('ROYAUME-UNI', 'ROYAUME-UNI'), ('RUSSIE', 'RUSSIE'), ('RWANDA', 'RWANDA'), ('SABA', 'SABA'), ('SAINT BARTH', 'SAINT BARTH'), ('SAINT BARTHELEMY', 'SAINT BARTHELEMY'), ('SAINT CHRISTOPHE(ST. KITTS)', 'SAINT CHRISTOPHE(ST. KITTS)'), ('SAINT JEAN', 'SAINT JEAN'), ('SAINT KITTS', 'SAINT KITTS'), ('SAINT MAARTEN', 'SAINT MAARTEN'), ('SAINT MARIN', 'SAINT MARIN'), ('SAINT MARTIN', 'SAINT MARTIN'), ('SAINT PIERRE', 'SAINT PIERRE'), ('SAINT THOMAS', 'SAINT THOMAS'), ('SAINT VINCENT ET LES GRENADES', 'SAINT VINCENT ET LES GRENADES'), ('SAINT VINCENT', 'SAINT VINCENT'), ('SAINTE LUCIE', 'SAINTE LUCIE'), ('SAIPAN', 'SAIPAN'), ('SAMOA  à  USA', 'SAMOA  à  USA'), ('SAMOA - USA', 'SAMOA - USA'), ('SAMOA ILES', 'SAMOA ILES'), ('SAN MARIN', 'SAN MARIN'), ('SENEGAL', 'SENEGAL'), ('SERBIE', 'SERBIE'), ('SEYCHELLES', 'SEYCHELLES'), ('SIERRA LEONE', 'SIERRA LEONE'), ('SINGAPOUR', 'SINGAPOUR'), ('SLOVAQUIE', 'SLOVAQUIE'), ('SLOVENIE', 'SLOVENIE'), ('SRI LANKA', 'SRI LANKA'), ('SUEDE', 'SUEDE'), ('SUISSE', 'SUISSE'), ('SURINAM', 'SURINAM'), ('SURINAME', 'SURINAME'), ('SWAZILAND', 'SWAZILAND'), ('SYRIE', 'SYRIE'), ('TADJIKISTAN', 'TADJIKISTAN'), ('TAHITI', 'TAHITI'), ('TAIWAN', 'TAIWAN'), ('TANZANIE', 'TANZANIE'), ('TCHAD', 'TCHAD'), ('THAILAND', 'THAILAND'), ('THAILANDE', 'THAILANDE'), ('TIMOR ORIENTAL', 'TIMOR ORIENTAL'), ('TINIAN', 'TINIAN'), ('TOGO', 'TOGO'), ('TONGA', 'TONGA'), ('TORTOLA', 'TORTOLA'), ('TRINITE ET TOBAGO', 'TRINITE ET TOBAGO'), ('TRINITÉ ET TOBAGO', 'TRINITÉ ET TOBAGO'), ('TRUK', 'TRUK'), ('TUNISIE', 'TUNISIE'), ('TURKMENISTAN', 'TURKMENISTAN'), ('TURQUIE', 'TURQUIE'), ('TUVALU', 'TUVALU'), ('UKRAINE', 'UKRAINE'), ('UNION(ILE)', 'UNION(ILE)'), ('URUGUAY', 'URUGUAY'), ('VANUATU', 'VANUATU'), ('VATICAN CITE', 'VATICAN CITE'), ('VENEZUELA', 'VENEZUELA'), ('VIERGE GORDA(ILES VIERGES BRITANNIQUES)', 'VIERGE GORDA(ILES VIERGES BRITANNIQUES)'), ('VIETNAM', 'VIETNAM'), ('WALLIS ET FUTUNA', 'WALLIS ET FUTUNA'), ('YAP', 'YAP'), ('YEMEN', 'YEMEN'), ('ZAMBIE', 'ZAMBIE'), ('ZIMBABWE', 'ZIMBABWE')], max_length=50, verbose_name='PAYS DESTINATION'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational0a20kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicolisnational20kgsa99kgs',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='delai_de_livraison',
            field=models.CharField(choices=[('1 JOUR', '1 JOUR'), ('2 JOURS', '2 JOURS'), ('3 JOURS', '3 JOURS'), ('4 JOURS', '4 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('7 JOURS', '7 JOURS'), ('8 JOURS', '8 JOURS'), ('9 JOURS', '9 JOURS'), ('10 JOURS', '10 JOURS'), ('11 JOURS', '11 JOURS'), ('14 JOURS', '14 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('3 A 4 JOURS', '3 A 4 JOURS'), ('2 A 3 JOURS', '2 A 3 JOURS'), ('5 A 6 JOURS', '5 A 6 JOURS'), ('4 A 5 JOURS', '4 A 5 JOURS'), ('3 A 5 JOURS', '3 A 5 JOURS'), ('6 A 8 JOURS', '6 A 8 JOURS'), ('1 A 2 JOURS', '1 A 2 JOURS'), ('1 A 3 JOURS', '1 A 3 JOURS'), ('2 A 4 JOURS', '2 A 4 JOURS'), ('4 JOURS', '4 JOURS'), ('2 JOURS', '2 JOURS'), ('6 à 8 JOURS', '6 à 8 JOURS'), ('3 à 4 JOURS', '3 à 4 JOURS'), ('1 à 2 JOURS', '1 à 2 JOURS'), ('3 JOURS', '3 JOURS'), ('2 à 3 JOURS', '2 à 3 JOURS'), ('5 JOURS', '5 JOURS'), ('6 JOURS', '6 JOURS'), ('A CONFIRMER', 'A CONFIRMER'), ('4 à 5 JOURS', '4 à 5 JOURS'), ('1 à 3 JOURS', '1 à 3 JOURS'), ('2 à 4 JOURS', '2 à 4 JOURS'), ('8 JOURS', '8 JOURS'), ('2à3 JOURS', '2à3 JOURS'), ('4à5 JOURS', '4à5 JOURS'), ('3à4 JOURS', '3à4 JOURS'), ('7 JOURS', '7 JOURS'), ('14 JOURS ', '14 JOURS '), ('3 A 4 JOURS ', '3 A 4 JOURS '), ('1 JOURS', '1 JOURS')], max_length=20, verbose_name='DELAI LIVRAISON'),
        ),
        migrations.AlterField(
            model_name='envoicourrierinternational',
            name='pays_destination',
            field=models.CharField(choices=[('ACORES', 'ACORES'), ('AFGHANISTAN', 'AFGHANISTAN'), ('AFRIQUE DU SUD', 'AFRIQUE DU SUD'), ('ALBANIE', 'ALBANIE'), ('ALGERIE', 'ALGERIE'), ('ALLEMAGNE', 'ALLEMAGNE'), ('ANDORRE', 'ANDORRE'), ('ANGLETERRE', 'ANGLETERRE'), ('ANGOLA', 'ANGOLA'), ('ANGUILLA', 'ANGUILLA'), ('ANTIGUA', 'ANTIGUA'), ('ANTIGUA-ET-BARBUDA', 'ANTIGUA-ET-BARBUDA'), ('ANTILLES NEERLANDAISES', 'ANTILLES NEERLANDAISES'), ('ARABIE SAOUDITE', 'ARABIE SAOUDITE'), ('ARGENTINE', 'ARGENTINE'), ('ARMENIE', 'ARMENIE'), ('ARUBA', 'ARUBA'), ('AUSTRALIE', 'AUSTRALIE'), ('AUTRICHE', 'AUTRICHE'), ('AZERBAIDJAN', 'AZERBAIDJAN'), ('BAHAMAS', 'BAHAMAS'), ('BAHREIN', 'BAHREIN'), ('BANGLADESH', 'BANGLADESH'), ('BARBADE', 'BARBADE'), ('BARBADES', 'BARBADES'), ('BARBUDA(ANTIGUA)', 'BARBUDA(ANTIGUA)'), ('BELGIQUE ', 'BELGIQUE '), ('BELGIQUE', 'BELGIQUE'), ('BELIZE', 'BELIZE'), ('BENIN', 'BENIN'), ('BERMUDES', 'BERMUDES'), ('BHOUTAN', 'BHOUTAN'), ('BIELORUSSIE', 'BIELORUSSIE'), ('BOLIVIE', 'BOLIVIE'), ('BONAIRE', 'BONAIRE'), ('BOSNIE à HERZEGOVINE', 'BOSNIE à HERZEGOVINE'), ('BOSNIE', 'BOSNIE'), ('BOSNIE-HERZEGOVINE', 'BOSNIE-HERZEGOVINE'), ('BOTSWANA', 'BOTSWANA'), ('BRESIL', 'BRESIL'), ('BRUNEI', 'BRUNEI'), ('BULGARIE', 'BULGARIE'), ('BURKINA FASO', 'BURKINA FASO'), ('BURUNDI', 'BURUNDI'), ('CAIMAN ILES', 'CAIMAN ILES'), ('CAÏMANS(ILES)', 'CAÏMANS(ILES)'), ('CAMBODGE', 'CAMBODGE'), ('CAMEROUN', 'CAMEROUN'), ('CANADA', 'CANADA'), ('CANARIES(ILES)', 'CANARIES(ILES)'), ('CAP VERT', 'CAP VERT'), ('CENTRAFRIQUE', 'CENTRAFRIQUE'), ('CEUTA', 'CEUTA'), ('CHANNELLE(ILES)  à  GUERNSEY', 'CHANNELLE(ILES)  à  GUERNSEY'), ('CHANNELLE(ILES)  à  JERSEY', 'CHANNELLE(ILES)  à  JERSEY'), ('CHANNELLE(ILES) - GUERNSEY', 'CHANNELLE(ILES) - GUERNSEY'), ('CHANNELLE(ILES) - JERSEY', 'CHANNELLE(ILES) - JERSEY'), ('CHILI', 'CHILI'), ('CHINE', 'CHINE'), ('CHYPRE ', 'CHYPRE '), ('CHYPRE', 'CHYPRE'), ('COLOMBIE', 'COLOMBIE'), ('COMORES', 'COMORES'), ('CONGO(BRAZZAVILLE)', 'CONGO(BRAZZAVILLE)'), ('CONGO', 'CONGO'), ('COOK ILES', 'COOK ILES'), ('COOK(ILES)', 'COOK(ILES)'), ('COREE DU NORD', 'COREE DU NORD'), ('COREE DU SUD', 'COREE DU SUD'), ('CORÉE DU SUD', 'CORÉE DU SUD'), ('COSTA RICA', 'COSTA RICA'), ('COTE D IVOIRE', 'COTE D IVOIRE'), ('CROATIE', 'CROATIE'), ('CUBA', 'CUBA'), ('CURACAO', 'CURACAO'), ('DANEMARK', 'DANEMARK'), ('DJIBOUTI', 'DJIBOUTI'), ('DOMINIQUE', 'DOMINIQUE'), ('ECOSSE', 'ECOSSE'), ('EGYPTE', 'EGYPTE'), ('EL SALVADOR', 'EL SALVADOR'), ('EMIRATS ARABE UNIS', 'EMIRATS ARABE UNIS'), ('EMIRATS ARABES UNIS', 'EMIRATS ARABES UNIS'), ('EQUATEUR', 'EQUATEUR'), ('ERITHRÉE', 'ERITHRÉE'), ('ERYTRHEE', 'ERYTRHEE'), ('ESPAGNE ', 'ESPAGNE '), ('ESPAGNE', 'ESPAGNE'), ('ESTONIE', 'ESTONIE'), ('ETATS UNIS', 'ETATS UNIS'), ('ETATS-UNIS', 'ETATS-UNIS'), ('ETHIOPIE', 'ETHIOPIE'), ('FALKSLANDS', 'FALKSLANDS'), ('FÉROÉ(ILES)', 'FÉROÉ(ILES)'), ('FIDJI', 'FIDJI'), ('FINLANDE', 'FINLANDE'), ('FRANCE ', 'FRANCE '), ('FRANCE', 'FRANCE'), ('GABON', 'GABON'), ('GAMBIE', 'GAMBIE'), ('GAZA (WEST BANK)', 'GAZA (WEST BANK)'), ('GEORGIE', 'GEORGIE'), ('GÉORGIE', 'GÉORGIE'), ('GHANA', 'GHANA'), ('GIBRALTAR', 'GIBRALTAR'), ('GRECE', 'GRECE'), ('GRENADE', 'GRENADE'), ('GROENLAND', 'GROENLAND'), ('GUADELOUPE', 'GUADELOUPE'), ('GUAM (ILE)', 'GUAM (ILE)'), ('GUAM', 'GUAM'), ('GUATEMALA', 'GUATEMALA'), ('GUERNESEY', 'GUERNESEY'), ('GUIANA', 'GUIANA'), ('GUINEE BISSAU', 'GUINEE BISSAU'), ('GUINÉE BISSAU', 'GUINÉE BISSAU'), ('GUINEE EQUATORIALE', 'GUINEE EQUATORIALE'), ('GUINÉE EQUATORIALE', 'GUINÉE EQUATORIALE'), ('GUINEE FRANCAISE', 'GUINEE FRANCAISE'), ('GUINEE', 'GUINEE'), ('GUINÉE', 'GUINÉE'), ('GUYANE FRANÇAISE', 'GUYANE FRANÇAISE'), ('GUYANE', 'GUYANE'), ('HAITI', 'HAITI'), ('HAWAI', 'HAWAI'), ('HONDURAS', 'HONDURAS'), ('HONG KONG', 'HONG KONG'), ('HONGRIE', 'HONGRIE'), ('ILE DE MAN', 'ILE DE MAN'), ('ILE MAURICE', 'ILE MAURICE'), ('ILES CANARIES', 'ILES CANARIES'), ('ILES FEROE', 'ILES FEROE'), ('ILES MARSHALL', 'ILES MARSHALL'), ('ILES TURQUES ET CAICOS', 'ILES TURQUES ET CAICOS'), ('ILES VIERGES  à  GB', 'ILES VIERGES  à  GB'), ('ILES VIERGES  à  USA', 'ILES VIERGES  à  USA'), ('ILES VIERGES - GB', 'ILES VIERGES - GB'), ('ILES VIERGES - USA', 'ILES VIERGES - USA'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-GB', 'ILES VIERGES-GB'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILES VIERGES-USA', 'ILES VIERGES-USA'), ('ILLE MAURICE', 'ILLE MAURICE'), ('INDE', 'INDE'), ('INDONESIE', 'INDONESIE'), ('IRAK', 'IRAK'), ('IRAN', 'IRAN'), ('IRLANDE ', 'IRLANDE '), ('IRLANDE DU NORD', 'IRLANDE DU NORD'), ('IRLANDE', 'IRLANDE'), ('ISLANDE', 'ISLANDE'), ('ISRAEL', 'ISRAEL'), ('ITALIE ', 'ITALIE '), ('ITALIE', 'ITALIE'), ('JAMAIQUE', 'JAMAIQUE'), ('JAPON', 'JAPON'), ('JERSEY', 'JERSEY'), ('JORDANIE', 'JORDANIE'), ('KAZAKHSTAN', 'KAZAKHSTAN'), ('KENYA', 'KENYA'), ('KIRGHIZISTAN', 'KIRGHIZISTAN'), ('KIRIBATI', 'KIRIBATI'), ('KOSOVO', 'KOSOVO'), ('KOSRAE(MICRONÉSIE)', 'KOSRAE(MICRONÉSIE)'), ('KOWEIT', 'KOWEIT'), ('KYRGYZSTAN', 'KYRGYZSTAN'), ('LAOS', 'LAOS'), ('LESOTHO', 'LESOTHO'), ('LETTONIE', 'LETTONIE'), ('LIBAN', 'LIBAN'), ('LIBERIA', 'LIBERIA'), ('LIBYE', 'LIBYE'), ('LIECHTENSTEIN', 'LIECHTENSTEIN'), ('LITUANIE', 'LITUANIE'), ('LUXEMBOURG', 'LUXEMBOURG'), ('LYBIE', 'LYBIE'), ('MACAO', 'MACAO'), ('MACEDOINE', 'MACEDOINE'), ('MADAGASCAR', 'MADAGASCAR'), ('MADEIRE', 'MADEIRE'), ('MADERE', 'MADERE'), ('MALAISIE', 'MALAISIE'), ('MALAWI', 'MALAWI'), ('MALDIVES', 'MALDIVES'), ('MALI', 'MALI'), ('MALTE', 'MALTE'), ('MARIANNE DU NORD(ILES)', 'MARIANNE DU NORD(ILES)'), ('MAROC', 'MAROC'), ('MARTINIQUE', 'MARTINIQUE'), ('MAURITANIE', 'MAURITANIE'), ('MAYOTTE', 'MAYOTTE'), ('MELILLA', 'MELILLA'), ('MEXIQUE', 'MEXIQUE'), ('MICRONESIE', 'MICRONESIE'), ('MOLDAVIE', 'MOLDAVIE'), ('MONACO', 'MONACO'), ('MONGOLIE', 'MONGOLIE'), ('MONSERRAT', 'MONSERRAT'), ('MONTENEGRO', 'MONTENEGRO'), ('MONTSERRAT', 'MONTSERRAT'), ('MOZAMBIQUE', 'MOZAMBIQUE'), ('MYANMAR', 'MYANMAR'), ('NAMIBIE', 'NAMIBIE'), ('NAURU', 'NAURU'), ('NEPAL', 'NEPAL'), ('NEVIS(ST KITTS)', 'NEVIS(ST KITTS)'), ('NEVIS', 'NEVIS'), ('NICARAGUA', 'NICARAGUA'), ('NIGER', 'NIGER'), ('NIGERIA', 'NIGERIA'), ('NIUE ILE', 'NIUE ILE'), ('NORVEGE', 'NORVEGE'), ('NOUVELLE CALEDONIE', 'NOUVELLE CALEDONIE'), ('NOUVELLE CALÉDONIE', 'NOUVELLE CALÉDONIE'), ('NOUVELLE ZELANDE', 'NOUVELLE ZELANDE'), ('OMAN', 'OMAN'), ('OUGANDA', 'OUGANDA'), ('OUZBEKISTAN', 'OUZBEKISTAN'), ('PAKISTAN', 'PAKISTAN'), ('PALAOS', 'PALAOS'), ('PANAMA', 'PANAMA'), ('PAPOUASIE NOUVELLE GUINÉE', 'PAPOUASIE NOUVELLE GUINÉE'), ('PAPOUASIE', 'PAPOUASIE'), ('PARAGUAY', 'PARAGUAY'), ('PAYS DE GALLES', 'PAYS DE GALLES'), ('PAYS-BAS', 'PAYS-BAS'), ('PEROU', 'PEROU'), ('PHILIPPINES', 'PHILIPPINES'), ('POLOGNE', 'POLOGNE'), ('POLYNÉSIE FRANÇAISE', 'POLYNÉSIE FRANÇAISE'), ('POLYNESIE', 'POLYNESIE'), ('PONAPE', 'PONAPE'), ('PORTO RICO', 'PORTO RICO'), ('PORTORICO', 'PORTORICO'), ('PORTUGAL', 'PORTUGAL'), ('QATAR', 'QATAR'), ('QUATAR', 'QUATAR'), ('REPUBLIQUE DIMINICAINE', 'REPUBLIQUE DIMINICAINE'), ('RÉPUBLIQUE DOMINICAINE', 'RÉPUBLIQUE DOMINICAINE'), ('RÉPUBLIQUE TCHÈQUE', 'RÉPUBLIQUE TCHÈQUE'), ('REUNION', 'REUNION'), ('RÉUNION', 'RÉUNION'), ('ROTA', 'ROTA'), ('ROUMANIE', 'ROUMANIE'), ('ROYAUME-UNI', 'ROYAUME-UNI'), ('RUSSIE', 'RUSSIE'), ('RWANDA', 'RWANDA'), ('SABA', 'SABA'), ('SAINT BARTH', 'SAINT BARTH'), ('SAINT BARTHELEMY', 'SAINT BARTHELEMY'), ('SAINT CHRISTOPHE(ST. KITTS)', 'SAINT CHRISTOPHE(ST. KITTS)'), ('SAINT JEAN', 'SAINT JEAN'), ('SAINT KITTS', 'SAINT KITTS'), ('SAINT MAARTEN', 'SAINT MAARTEN'), ('SAINT MARIN', 'SAINT MARIN'), ('SAINT MARTIN', 'SAINT MARTIN'), ('SAINT PIERRE', 'SAINT PIERRE'), ('SAINT THOMAS', 'SAINT THOMAS'), ('SAINT VINCENT ET LES GRENADES', 'SAINT VINCENT ET LES GRENADES'), ('SAINT VINCENT', 'SAINT VINCENT'), ('SAINTE LUCIE', 'SAINTE LUCIE'), ('SAIPAN', 'SAIPAN'), ('SAMOA  à  USA', 'SAMOA  à  USA'), ('SAMOA - USA', 'SAMOA - USA'), ('SAMOA ILES', 'SAMOA ILES'), ('SAN MARIN', 'SAN MARIN'), ('SENEGAL', 'SENEGAL'), ('SERBIE', 'SERBIE'), ('SEYCHELLES', 'SEYCHELLES'), ('SIERRA LEONE', 'SIERRA LEONE'), ('SINGAPOUR', 'SINGAPOUR'), ('SLOVAQUIE', 'SLOVAQUIE'), ('SLOVENIE', 'SLOVENIE'), ('SRI LANKA', 'SRI LANKA'), ('SUEDE', 'SUEDE'), ('SUISSE', 'SUISSE'), ('SURINAM', 'SURINAM'), ('SURINAME', 'SURINAME'), ('SWAZILAND', 'SWAZILAND'), ('SYRIE', 'SYRIE'), ('TADJIKISTAN', 'TADJIKISTAN'), ('TAHITI', 'TAHITI'), ('TAIWAN', 'TAIWAN'), ('TANZANIE', 'TANZANIE'), ('TCHAD', 'TCHAD'), ('THAILAND', 'THAILAND'), ('THAILANDE', 'THAILANDE'), ('TIMOR ORIENTAL', 'TIMOR ORIENTAL'), ('TINIAN', 'TINIAN'), ('TOGO', 'TOGO'), ('TONGA', 'TONGA'), ('TORTOLA', 'TORTOLA'), ('TRINITE ET TOBAGO', 'TRINITE ET TOBAGO'), ('TRINITÉ ET TOBAGO', 'TRINITÉ ET TOBAGO'), ('TRUK', 'TRUK'), ('TUNISIE', 'TUNISIE'), ('TURKMENISTAN', 'TURKMENISTAN'), ('TURQUIE', 'TURQUIE'), ('TUVALU', 'TUVALU'), ('UKRAINE', 'UKRAINE'), ('UNION(ILE)', 'UNION(ILE)'), ('URUGUAY', 'URUGUAY'), ('VANUATU', 'VANUATU'), ('VATICAN CITE', 'VATICAN CITE'), ('VENEZUELA', 'VENEZUELA'), ('VIERGE GORDA(ILES VIERGES BRITANNIQUES)', 'VIERGE GORDA(ILES VIERGES BRITANNIQUES)'), ('VIETNAM', 'VIETNAM'), ('WALLIS ET FUTUNA', 'WALLIS ET FUTUNA'), ('YAP', 'YAP'), ('YEMEN', 'YEMEN'), ('ZAMBIE', 'ZAMBIE'), ('ZIMBABWE', 'ZIMBABWE')], max_length=50, verbose_name='PAYS DESTINATION'),
        ),
        migrations.AlterField(
            model_name='interpretariat',
            name='langue_interpretariat',
            field=models.CharField(choices=[('ALLEMAND-FRANCAIS', 'ALLEMAND-FRANCAIS'), ('ANGLAIS-FRANCAIS', 'ANGLAIS-FRANCAIS'), ('ESPAGNOL-FRANCAIS', 'ESPAGNOL-FRANCAIS'), ('KIKONGO-ANGLAIS', 'KIKONGO-ANGLAIS'), ('KIKONGO-FRANCAIS', 'KIKONGO-FRANCAIS'), ('LINGALA-ANGLAIS', 'LINGALA-ANGLAIS'), ('LINGALA-FRANCAIS', 'LINGALA-FRANCAIS'), ('PORTUGAIS-FRANCAIS', 'PORTUGAIS-FRANCAIS'), ('SWAHILI-ANGLAIS', 'SWAHILI-ANGLAIS'), ('SWAHILI-FRANCAIS', 'SWAHILI-FRANCAIS'), ('TSHILUBA-ANGLAIS', 'TSHILUBA-ANGLAIS'), ('TSHILUBA-FRANCAIS', 'TSHILUBA-FRANCAIS')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='lieu',
            field=models.CharField(blank=True, choices=[('A CONVENIR', 'A CONVENIR'), ('SUR PLACE', 'SUR PLACE')], max_length=20, null=True, verbose_name='LIEU'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='classe_therapeutique',
            field=models.CharField(choices=[('ALLERGOLIGIE', 'ALLERGOLIGIE'), ('ANTIHELMINTHIQUES', 'ANTIHELMINTHIQUES'), ('ANTI-INFLAMMATOIRE ET ANTALGIQUES', 'ANTI-INFLAMMATOIRE ET ANTALGIQUES'), ('ANTISPASMODIQUE ET ANTIFLATULENCE', 'ANTISPASMODIQUE ET ANTIFLATULENCE'), ('BRONCHOPNEUMONIE', 'BRONCHOPNEUMONIE'), ('DERMATOLOGIE', 'DERMATOLOGIE'), ('GASTRO-ENTEROLOGIE', 'GASTRO-ENTEROLOGIE'), ('INFECTIOLOGIE', 'INFECTIOLOGIE')], max_length=50, verbose_name='CLASSE THERAPEUTIQUE'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='dosage',
            field=models.CharField(choices=[('5MG/2MG/8MG', '2MG/5MG/8MG'), ('10G', '10G'), ('10MG', '10MG'), ('10ML', '10ML'), ('20MG', '20MG'), ('50G', '50G'), ('60ML', '60ML'), ('100MG', '100MG'), ('100ML', '100ML'), ('250MG', '250MG'), ('400MG', '400MG'), ('500MG', '500MG')], max_length=50, verbose_name='DOSAGE'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='presentation',
            field=models.CharField(choices=[('AMPOULE', 'AMPOULE'), ('COMPRIME', 'COMPRIME'), ('CREME ANTI-INFLAMMATOIRE', 'CREME ANTI-INFLAMMATOIRE'), ('CREME DERMIQUE', 'CREME DERMIQUE'), ('GELULES', 'GELULES'), ('GOUTTES', 'GOUTTES'), ('SIROP', 'SIROP'), ('SUSPENSION LIQUIDE', 'SUSPENSION LIQUIDE')], max_length=50, verbose_name='PRESENTATION'),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='produit',
            field=models.CharField(choices=[('BLUMOX', 'BLUMOX'), ('CEBRAN 500', 'CEBRAN 500'), ('EKON-DT', 'EKON-DT'), ('MEFTAL 500', 'MEFTAL 500'), ('MEFTAL FORTE CREME', 'MEFTAL FORTE CREME'), ('MEFTAL FORTE', 'MEFTAL FORTE'), ('MEFTAL P SUSP', 'MEFTAL P SUSP'), ('MEFTAL P', 'MEFTAL P'), ('MEFTAL SPAS DROPS', 'MEFTAL SPAS DROPS'), ('MEFTAL SPAS INJ', 'MEFTAL SPAS INJ'), ('MEFTAL SPAS', 'MEFTAL SPAS'), ('OMEPREN 20', 'OMEPREN 20'), ('SONADERM', 'SONADERM'), ('TUSQ-DX CES', 'TUSQ-DX CES'), ('TUSQ-DX SIROP', 'TUSQ-DX SIROP'), ('TUSQ-X SIROP', 'TUSQ-X SIROP'), ('WOMIBAN', 'WOMIBAN')], max_length=50, verbose_name='PRODUIT'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(choices=[('LES PRINCIPALES PREOCCUPATIOS DES CONGOLAIS', 'LES PRINCIPALES PREOCCUPATIONS DES CONGOLAIS'), ('STATISTIQUES SUR LES MEDIAS A KINSHASA', 'STATISTIQUES SUR LES MEDIAS A KINSHASA')], max_length=100, verbose_name='TITRE'),
        ),
        migrations.AlterField(
            model_name='redactionprocedures',
            name='secteur',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES', 'INDUSTRIES'), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='SECTEUR '),
        ),
        migrations.AlterField(
            model_name='redactionprocedures',
            name='type_intervention',
            field=models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('PONCTUELLE', 'PONCTUELLE')], max_length=20, verbose_name="TYPE D'INTERVENTION"),
        ),
        migrations.AlterField(
            model_name='reproductioncle',
            name='type_de_reproduction',
            field=models.CharField(choices=[('DOUBLURE CLE SIMPLE', 'DOUBLURE POUR CLE SIMPLE'), ('DOUBLURE CONTACT VEHICULE', 'DOUBLURE POUR CONTACT VEHICULE'), ('REPRODUCTION CLE MEMOIRE VEHICULE', 'REPRODUCTION DE CLE MEMOIRE VEHICULE')], max_length=100, verbose_name='TYPE DE REPRODUCTION'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='avenue',
            field=models.CharField(choices=[('COLONNEL EBEYA', 'COLONNEL EBEYA'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('SENEGALAIS', 'SENEGALAIS')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='commune',
            field=models.CharField(choices=[('BANDALUNGWA', 'BANDALUNGWA'), ('GOMBE', 'GOMBE'), ('KASAVUBU', 'KASAVUBU'), ('LIMETE', 'LIMETE')], max_length=20, verbose_name='COMMUNE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='superficie',
            field=models.CharField(choices=[('71,5 M2', '71,5 M2'), ('72 M2', '72 M2'), ('140 M2', '140 M2')], max_length=20, verbose_name='SUPERFICIE'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='avenue',
            field=models.CharField(choices=[('COLONNEL EBEYA', 'COLONNEL EBEYA'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('SENEGALAIS', 'SENEGALAIS')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='commune',
            field=models.CharField(choices=[('BANDALUNGWA', 'BANDALUNGWA'), ('GOMBE', 'GOMBE'), ('KASAVUBU', 'KASAVUBU'), ('LIMETE', 'LIMETE')], max_length=20, verbose_name='COMMUNE'),
        ),
        migrations.AlterField(
            model_name='servicedetraduction',
            name='langue',
            field=models.CharField(choices=[('ALLEMAND-FRANCAIS', 'ALLEMAND-FRANCAIS'), ('ANGLAIS-FRANCAIS', 'ANGLAIS-FRANCAIS'), ('ANGLAIS-LINGALA', 'ANGLAIS-LINGALA'), ('ESPAGNOL-FRANCAIS', 'ESPAGNOL-FRANCAIS'), ('KIKONGO-ANGLAIS', 'KIKONGO-ANGLAIS'), ('KIKONGO-FRANCAIS', 'KIKONGO-FRANCAIS'), ('LINGALA-ANGLAIS', 'LINGALA-ANGLAIS'), ('LINGALA-FRANCAIS', 'LINGALA-FRANCAIS'), ('PORTUGAIS-FRANCAIS', 'PORTUGAIS-FRANCAIS'), ('SWAHILI-ANGLAIS', 'SWAHILI-ANGLAIS'), ('SWAHILI-FRANCAIS', 'SWAHILI-FRANCAIS'), ('TSHILUBA-ANGLAIS', 'TSHILUBA-ANGLAIS'), ('TSHILUBA-FRANCAIS', 'TSHILUBA-FRANCAIS')], max_length=20, verbose_name='LANGUE'),
        ),
        migrations.AlterField(
            model_name='servicegardiennage',
            name='type_gardiennage',
            field=models.CharField(choices=[('AUTRES SERVICES', 'AUTRES SERVICES'), ('BATIMENTS ET TRAVAUX PUBLIC', 'BATIMENTS ET TRAVAUX PUBLIC'), ('BRASSERIES ET AGROALIMENTAIRE', 'BRASSERIES ET AGROALIMENTAIRE'), ('DISTRIBUTION ET COMMERCE', 'DISTRIBUTION ET COMMERCE'), ('ENERGIE ET HYDROCARBURES', 'ENERGIE ET HYDROCARBURES'), ('ETABLISSEMENT PUBLIC', 'ETABLISSEMENT PUBLIC'), ('FINANCE ET BANQUES', 'FINANCE ET BANQUES'), ('INDUSTRIES ', 'INDUSTRIES '), ('MINES', 'MINES'), ('ORGANISME INTERNATIONAL', 'ORGANISME INTERNATIONAL'), ('REPRESENTATION DIPLOMATIQUE', 'REPRESENTATION DIPLOMATIQUE'), ('SECURITE RAPPROCHEE', 'SECURITE RAPPROCHEE'), ('TELECOMMUNICATIONS ET TIC', 'TELECOMMUNICATIONS ET TIC'), ('TRANSPORTS ET LOGISTIQUE', 'TRANSPORTS ET LOGISTIQUE')], max_length=100, verbose_name='TYPE DE GARDIENNAGE'),
        ),
        migrations.AlterField(
            model_name='servicesplit',
            name='type_service_split',
            field=models.CharField(choices=[('INSTALLATION SPLIT', 'INSTALLATION DES SPLIT'), ('ENTRETIEN SPLIT', 'ENTRETIEN DES SPLIT')], max_length=20, verbose_name='TYPE DE SERVICE POUR SPLIT'),
        ),
        migrations.AlterField(
            model_name='tvled',
            name='taille_ecran',
            field=models.CharField(choices=[('19"', '19"'), ('22"', '22"'), ('24"', '24"'), ('32"', '32"'), ('40"', '40"'), ('43"', '43"'), ('49"', '49"'), ('55"', '55"'), ('65"', '65"'), ('80"', '80"')], max_length=100, verbose_name="TAILLE DE L'ECRAN"),
        ),
    ]
