# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0419_auto_20180531_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptateur',
            name='type_adaptateur',
            field=models.CharField(choices=[('VGA VERS HDMI', 'VGA VERS HDMI'), ('ALIMENTATION CCTV CAMERA 12V', 'ALIMENTATION CCTV CAMERA 12V'), ('CARTE MEMOIRE', 'CARTE MEMOIRE'), ('DVI VERS VGA', 'DVI VERS VGA'), ('HDMI VERS 3RCA AVEC ALIMENTATON', 'HDMI VERS 3RCA AVEC ALIMENTATON'), ('HDMI VERS VGA ', 'HDMI VERS VGA '), ('HDMI VERS VGA AVEC ALIMENTATION', 'HDMI VERS VGA AVEC ALIMENTATION'), ('HUB CHARGEUR DE SORTIE UNIVERSEL USB', 'HUB CHARGEUR DE SORTIE UNIVERSEL USB'), ('IHPONE 5/6 VERS HDMI AVEC ALIMENTATION', 'IHPONE 5/6 VERS HDMI AVEC ALIMENTATION'), ('IPAD VERS HDMI', 'IPAD VERS HDMI'), ('PORT DISPLAY DVI', 'PORT DISPLAY DVI'), ('PORT MINI DISPLAY VERS DVI', 'PORT MINI DISPLAY VERS DVI'), ('PORT MINI DISPLAY VERS HDMI', 'PORT MINI DISPLAY VERS HDMI'), ('POUR ALIMENTATION IMPRIMANTE HP', 'POUR ALIMENTATION IMPRIMANTE HP'), ('POUR ORDINATEUR', 'POUR ORDINATEUR'), ('UNIVERSEL POUR LAPTOP', 'UNIVERSEL POUR LAPTOP'), ('USB 3.0 VERS HDMI', 'USB 3.0 VERS HDMI'), ('USB 3.0 VERS VGA', 'USB 3.0 VERS VGA'), ('USB VERS PORT PARALLELE', 'USB VERS PORT PARALLELE'), ('USB VERS PORT SERIE', 'USB VERS PORT SERIE'), ('USB VERS RJ45', 'USB VERS RJ45'), ('USB VERS SON', 'USB VERS SON'), ('USB WIFI TPLINK T2U AC600', 'USB WIFI TPLINK T2U AC600'), ('USB WIFI TPLINK TL-WN725N', 'USB WIFI TPLINK TL-WN725N'), ('USB WIRELESS TL-WN7200ND', 'USB WIRELESS TL-WN7200ND'), ('VGA VERS HDMI', 'VGA VERS HDMI'), ('WIFI POUR IMPRIMANTE', 'WIFI POUR IMPRIMANTE')], max_length=100, verbose_name="TYPE D'ADAPTATEUR "),
        ),
        migrations.AlterField(
            model_name='antennewifi',
            name='modele_antenne',
            field=models.CharField(choices=[('M5 NBE-M5-1', 'M5 NBE-M5-1'), ('TL-ANT2415D', 'TL-ANT2415D'), ('TL-ANT2424B', 'TL-ANT2424B')], max_length=100, verbose_name='MODELE '),
        ),
        migrations.AlterField(
            model_name='autocollantcodebar',
            name='quantite_autocollant',
            field=models.CharField(choices=[('1500', '1500'), ('4000', '4000'), ('5000', '5000')], max_length=100, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='boitierdisquedur',
            name='type_disque_dur',
            field=models.CharField(choices=[('IDE', 'IDE'), ('SATA', 'SATA')], max_length=100, verbose_name='TYPE DE DISQUE'),
        ),
        migrations.AlterField(
            model_name='cableinformatique',
            name='type_cable',
            field=models.CharField(choices=[('BAFFLE', 'BAFFLE'), ('CAT 6', 'CAT 6'), ('COAXIAL', 'COAXIAL'), ('FIREWARE', 'FIREWARE'), ('HDMI', 'HDMI'), ('MAC THUNDER', 'MAC THUNDER'), ('MICRO', 'MICRO'), ('OPTICAL', 'OPTICAL'), ('SON (1*1)', 'SON (1*1)'), ('VGA', 'VGA')], max_length=50, verbose_name='TYPE DE CABLE'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='type_carte',
            field=models.CharField(choices=[('CARTE MERE INTEL DG 41BL', 'CARTE MERE INTEL DG 41BL'), ('FIREWIRE PCI LW', 'FIREWIRE PCI LW'), ('GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO', 'GRAPHICS ZOTAC PCI EXPRESS NVIDIA 2GO'), ('GRAPHIQUE NVIDIA 1GB', 'GRAPHIQUE NVIDIA 1GB'), ('GRAPHIQUE PCI EXPRESS NVIDIA 1GO', 'GRAPHIQUE PCI EXPRESS NVIDIA 1GO'), ('PCI COMBO 2 SERIAL+1PARRALE', 'PCI COMBO 2 SERIAL+1PARRALE'), ('PCI EXPRESS', 'PCI EXPRESS'), ('PCI SERIAL ATA HOST', 'PCI SERIAL ATA HOST'), ('PCI TO PCMCI', 'PCI TO PCMCI'), ('PCI ULTRA ATA', 'PCI ULTRA ATA'), ('PCMCI RJ45', 'PCMCI RJ45'), ('READER EXTERNAL', 'READER EXTERNAL'), ('RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND', 'RESEAU SANS FIL PCI EXPRESS TPLINK TL781ND'), ('SON PCI', 'SON PCI')], max_length=100, verbose_name='TYPE DE CARTE'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='intensite',
            field=models.CharField(choices=[('1,58A', '1,58A'), ('3,34A', '3,34A'), ('3,42A', '3,42A'), ('3,42A', '3,42A'), ('3,5A SMALL PIN', '3,5A SMALL PIN'), ('3,5A', '3,5A'), ('3,95A', '3,95A'), ('4,62A', '4,62A'), ('4,74A BIG PIN', '4,74A BIG PIN'), ('4,74A SMALL PIN', '4,74A SMALL PIN')], max_length=100, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='marque_appareil',
            field=models.CharField(choices=[('ACER', 'ACER'), ('DELL', 'DELL'), ('HP', 'HP'), ('SELPHY CP910', 'SELPHY CP910'), ('TOSHIBA', 'TOSHIBA'), ('UNIVERSEL', 'UNIVERSEL')], max_length=100, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='chargeurlaptop',
            name='tension',
            field=models.CharField(choices=[('18,5V', '18,5V'), ('19V', '19V'), ('19,5V', '19,5V')], max_length=100, verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='type_clavier',
            field=models.CharField(choices=[('AZERTY', 'AZERTY'), ('QWERTY', 'QWERTY')], max_length=50, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='connecteur',
            name='type_connecteur',
            field=models.CharField(choices=[('CAT6 RJ45 POUR PRISE MURALE', 'CAT6 RJ45 POUR PRISE MURALE'), ('COUVERTURE CABLE RJ45', 'COUVERTURE CABLE RJ45'), ('RJ11', 'RJ11'), ('RJ45 AICO', 'RJ45 AICO'), ('RJ45 CAT5E', 'RJ45 CAT5E'), ('RJ45 CAT6 METAL', 'RJ45 CAT6 METAL'), ('RJ45 CAT6', 'RJ45 CAT6'), ('RJ45 CAT6E', 'RJ45 CAT6E'), ('RJ45 COUVERT', 'RJ45 COUVERT'), ('RJ45 METAL', 'RJ45 METAL'), ('RJ45 NORMA', 'RJ45 NORMA')], max_length=100, verbose_name='TYPE DE CONNECTEUR'),
        ),
        migrations.AlterField(
            model_name='creationsiteweb',
            name='type_site_web',
            field=models.CharField(choices=[('E-COMMERCE', 'SITE E-COMMERCE'), ('SITE AVEC APPLICATION', 'SITE AVEC APPLICATION'), ('SITE VITRINE', 'SITE VITRINE')], max_length=100, verbose_name='TYPE DE SITE'),
        ),
        migrations.AlterField(
            model_name='hebergementsiteweb',
            name='type_hebergement',
            field=models.CharField(choices=[('HEBERGEMENT SITE INTERNET', 'HEBERGEMENT SITE INTERNET'), ('HEBERGEMENT MODULE ERP', 'HEBERGEMENT MODULE ERP'), ('HEBERGEMENT UTILISATEUR ERP', 'HEBERGEMENT UTILISATEUR ERP')], max_length=50, verbose_name="TYPE D'HEBERGEMENT"),
        ),
        migrations.AlterField(
            model_name='memoireram',
            name='type_ordinateur',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP')], max_length=100, verbose_name="TYPE D'ORDINATEUR"),
        ),
        migrations.AlterField(
            model_name='patchcord',
            name='longueur',
            field=models.CharField(choices=[('0,3M ', '0,3M '), ('1M', '1M'), ('3M', '3M'), ('15M', '15M')], max_length=100, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='nombre_port',
            field=models.CharField(choices=[('24 PORTS', '24 PORTS'), ('48 PORTS', '48 PORTS')], max_length=100, verbose_name='NOMBRE DE PORT'),
        ),
        migrations.AlterField(
            model_name='produitdederatisation',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('BACTEROL', 'BACTEROL'), ('CREOLINE', 'CREOLINE'), ('EAU DE JAVEL', 'EAU DE JAVEL'), ('ESPRIT DE SEL', 'ESPRIT DE SEL'), ('INSECTICIDE', 'INSECTICIDE'), ('RATICIDE', 'RATICIDE')], max_length=100, null=True, verbose_name='TYPE DE PRODUIT'),
        ),
        migrations.AlterField(
            model_name='produitdenettoyage',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('BACTEROL', 'BACTEROL'), ('CREOLINE', 'CREOLINE'), ('EAU DE JAVEL', 'EAU DE JAVEL'), ('ESPRIT DE SEL', 'ESPRIT DE SEL'), ('INSECTICIDE', 'INSECTICIDE'), ('RATICIDE', 'RATICIDE')], max_length=100, null=True, verbose_name='TYPE DE PRODUIT'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='avec_fan',
            field=models.CharField(choices=[('DOUBLE', 'DOUBLE'), ('OUI', 'OUI'), ('NON', 'NON')], max_length=100, verbose_name='RACK AVEC FAN'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='nombre_unites',
            field=models.CharField(choices=[('6U', '6U'), ('9U', '9U'), ('12U', '12U'), ('15U', '15U'), ('18U', '18U'), ('22U', '22U'), ('27U', '27U'), ('32U', '32U'), ('37U', '37U'), ('42U', '42U')], max_length=100, verbose_name='UNITE'),
        ),
    ]
