# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0421_auto_20180531_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brique',
            name='largeur',
            field=models.CharField(choices=[('220MM', '220MM'), ('140MM', '140MM')], max_length=20, verbose_name='LARGEUR'),
        ),
        migrations.AlterField(
            model_name='locationdepot',
            name='avenue',
            field=models.CharField(choices=[('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL')], max_length=100, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='locationdepot',
            name='plage_surface',
            field=models.CharField(choices=[('<50M²', '<50M2'), ('50M²-100M²', '50M2-100M2'), ('100M²-150M²', '100M2-150M2'), ('150M²-200M²', '150M2-200M2'), ('>200M²', '>200M2')], max_length=100, verbose_name='PLAGE DE SURFACE'),
        ),
        migrations.AlterField(
            model_name='locationdepot',
            name='surface',
            field=models.CharField(choices=[('180M2', '180M2')], max_length=100, verbose_name='SURFACE'),
        ),
        migrations.AlterField(
            model_name='peinture',
            name='composition',
            field=models.CharField(choices=[('EMAIL CELLULOSIQUE', 'EMAIL CELLULOSIQUE'), ('EMAIL', 'EMAIL'), ('LATEX ACRYLIQUE', 'LATEX ACRYLIQUE'), ('LATEX', 'LATEX')], max_length=20, verbose_name='COMPOSITION'),
        ),
        migrations.AlterField(
            model_name='peinture',
            name='teinte',
            field=models.CharField(choices=[('AUCUNE TEINTE', 'AUCUNE TEINTE'), ('CLAIR', 'CLAIR'), ('MAT', 'MAT'), ('PASTEL', 'PASTEL'), ('SATIN', 'SATIN'), ('VIF', 'VIF')], max_length=20, verbose_name='TEINTE'),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='domaine_application',
            field=models.CharField(choices=[('APPRET MUR', 'APPRET MUR'), ('BOUCHE TROIS', 'BOUCHE TROIS'), ('MENUISERIE', 'MENUISERIE'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('PROTECTION BOIS', 'PROTECTION BOIS'), ('PROTECTION METAL', 'PROTECTION METAL'), ('PROTECTION METAL', 'PROTECTION METAL'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM')], max_length=50, verbose_name="DOMAINE D'APPLICATION"),
        ),
        migrations.AlterField(
            model_name='peinturespeciale',
            name='type_produit',
            field=models.CharField(choices=[('ANTIROUILLE FER', 'ANTIROUILLE FER'), ('ANTIROUILLE PLOMB', 'ANTIROUILLE PLOMB'), ('BOUCHE PORS', 'BOUCHE PORS'), ('CHROMATE DE ZINC', 'CHROMATE DE ZINC'), ('GALVA', 'GALVA'), ('MASTIC', 'MASTIC'), ('MENUICOL', 'MENUICOL'), ('PEINTURE AU LARO', 'PEINTURE AU LARO'), ('PEINTURE PISCINE', 'PEINTURE PISCINE'), ('PRIMER SURFACER', 'PRIMER SURFACER'), ('RUSTINE D’ALUMINIUM', 'RUSTINE D’ALUMINIUM'), ('SATIN', 'SATIN'), ('VERNIS INT&EXT', 'VERNIS INT&EXT'), ('VERNIS NOIR', 'VERNIS NOIR')], max_length=50, verbose_name=' TYPE DE PRODUIT'),
        ),
    ]
