# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0423_auto_20180531_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecerechangemoteur',
            name='pieces_rechange_moteur',
            field=models.CharField(choices=[('COURROIE COMPRESSEUR', 'COURROIE COMPRESSEUR'), ('COURROIE DE DISTRIBUTION', 'COURROIE DE DISTRIBUTION'), ('COURROIE DIRECTION', 'COURROIE DIRECTION'), ('COURROIE DISTRIBUTION', 'COURROIE DISTRIBUTION'), ('FILTRE A AIR', 'FILTRE A AIR'), ('FILTRE A CARBURANT  16405-01T0A', 'FILTRE A CARBURANT  16405-01T0A'), ('FILTRE A CARBURANT  16405-02N0A', 'FILTRE A CARBURANT  16405-02N0A'), ('FILTRE A CARBURANT', 'FILTRE A CARBURANT'), ('FILTRE A HUILE', 'FILTRE A HUILE'), ('FILTRE HABITACLE', 'FILTRE HABITACLE'), ('INJECTEUR COMPLET', 'INJECTEUR COMPLET'), ('INJECTEUR', 'INJECTEUR'), ('NEZ INJECTEUR', 'NEZ INJECTEUR'), ('POMPE A CARBURANT', 'POMPE A CARBURANT'), ('POMPE A HUILE', 'POMPE A HUILE'), ('SUPPORT MOTEUR', 'SUPPORT MOTEUR'), ('TENDEUR ALTERNATEUR', 'TENDEUR ALTERNATEUR'), ('TENDEUR DISTRIBUTION', 'TENDEUR DISTRIBUTION'), ('TURBO COMPRESSEUR', 'TURBO COMPRESSEUR'), ('COURROIE POMPE ALERTE', 'COURROIE POMPE ALERTE')], max_length=50, verbose_name='TYPE DE PIECE'),
        ),
        migrations.AlterField(
            model_name='semence',
            name='variete',
            field=models.CharField(blank=True, choices=[('NERICA', 'NERICA'), ('NERICA 17', 'NERICA 17'), ('NERICA 18', 'NERICA 18'), ('JASMIN', 'JASMIN'), ('SIPI', 'SIPI'), ('IB', 'IB'), ('CARGO', 'CARGO'), ('BABUNGO', 'BABUNGO')], max_length=100, null=True, verbose_name='VARIETE'),
        ),
    ]
