# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0426_auto_20180604_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoireshydrophore',
            name='type_accessoires_hydrophore',
            field=models.CharField(choices=[('BOUGIE DE FILTRE', 'BOUGIE DE FILTRE'), ('MANOMETRE', 'MANOMETRE'), ('PRESSOSTAT', 'PRESSOSTAT'), ('PRESSURE CONTROL', 'PRESSURE CONTROL'), ('TE', 'TE')], max_length=20, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='capacite',
            field=models.CharField(choices=[('100AH', '100AH'), ('102AH', '102AH'), ('200AH', '200AH'), ('1130AH', '1130AH')], max_length=20, verbose_name='CAPACITE EN AMPERE-HEURE'),
        ),
        migrations.AlterField(
            model_name='boitederivation',
            name='dimension',
            field=models.CharField(choices=[('60X60X25MM', '60X60X25MM'), ('65X65X45MM', '65X65X45MM'), ('80X80X30MM', '80X80X30MM'), ('105X105X42MM', '105X105X42MM'), ('130X130X30MM', '130X130X30MM'), ('160X100X45MM', '160X100X45MM'), ('220X160X45MM', '220X160X45MM'), ('105X105X55MM', '105X105X55MM'), ('175X150X80MM', '175X150X80MM'), ('225X175X100MM', '225X175X100MM'), ('275X225X120MM', '275X225X120MM')], max_length=20, verbose_name='DIMENSION EN MILLIMETRES'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_accompagnement',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name="CHOIX D'ACCOMPAGNEMENT"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSONALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON NON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_entree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=20, verbose_name="CHOIX D'ENTRÉE"),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='choix_plats',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('8', '8')], max_length=20, verbose_name='CHOIX DES PLATS'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='modele',
            field=models.CharField(choices=[('26-28', '26-28'), ('26-36', '26-36')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='units',
            field=models.CharField(choices=[('USD/PIECE', 'USD/PIECE'), ('USD/PCE', 'USD/PCE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='chaisebureau',
            name='revetement',
            field=models.CharField(choices=[('CUIR', 'CUIR'), ('MAILLE', 'MAILLE'), ('TISSU ET MAILLE', 'TISSU ET MAILLE')], max_length=50, verbose_name='REVETEMENT'),
        ),
        migrations.AlterField(
            model_name='chaisebureau',
            name='type_chaise',
            field=models.CharField(choices=[('CHAISE DE BUREAU', 'CHAISE DE BUREAU'), ('CHAISE DE DIRECTION', 'CHAISE DE DIRECTION'), ('CHAISE VISITEUR', 'CHAISE VISITEUR')], max_length=50, verbose_name='TYPE DE CHAISE'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='avenue',
            field=models.CharField(choices=[('COLONEL EBEYA', 'COLONEL EBEYA'), ('KASAI', 'KASAI'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('SENEGALAIS', 'SENEGALAIS'), ('OUGANDA', 'OUGANDA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name="CHOIX D'AMUSE GUEULE"),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='choix_boisson_non_alcoolisee',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON NON ALCOOLISÉE'),
        ),
        migrations.AlterField(
            model_name='communicationdemasse',
            name='type_communication_de_masse',
            field=models.CharField(choices=[('DISTRIBUTION DE FLYERS', 'DISTRIBUTION DE FLYERS'), ('ACTIVATION', 'ACTIVATION')], max_length=100, verbose_name='TYPE DE COMMUNICATION DE MASSE'),
        ),
        migrations.AlterField(
            model_name='compresseur',
            name='capacite_compresseur',
            field=models.CharField(choices=[('6 LITRES', '6 LITRES'), ('24 LITRES', '24 LITRES'), ('50 LITRES', '50 LITRES'), ('100 LITRES', '100 LITRES'), ('150 LITRES', '150 LITRES'), ('200 LITRES', '200 LITRES'), ('300 LITRES', '300 LITRES'), ('500 LITRES', '500 LITRES'), ('1000 LITRES', '1000 LITRES')], max_length=20, verbose_name='CAPACITE EN LITRE'),
        ),
        migrations.AlterField(
            model_name='compresseurair',
            name='capacite_compresseur',
            field=models.CharField(choices=[('6 LITRES', '6 LITRES'), ('24 LITRES', '24 LITRES'), ('50 LITRES', '50 LITRES'), ('100 LITRES', '100 LITRES'), ('150 LITRES', '150 LITRES'), ('200 LITRES', '200 LITRES'), ('300 LITRES', '300 LITRES'), ('500 LITRES', '500 LITRES'), ('1000 LITRES', '1000 LITRES')], max_length=100, verbose_name='CAPACITE'),
        ),
        migrations.AlterField(
            model_name='huile',
            name='base',
            field=models.CharField(choices=[('TOURNESOL', 'TOURNESOL')], max_length=100, verbose_name='PRODUIT DE BASE'),
        ),
        migrations.AlterField(
            model_name='integrationcustomisationstandard',
            name='units',
            field=models.CharField(choices=[('USD/MODULE', 'USD/MODULE')], max_length=50, verbose_name='UNITE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_amuse_gueule',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=20, verbose_name="CHOIX D'AMUSE GUEULE"),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_chaude',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON CHAUDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_boisson_froide',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE BOISSON FROIDE'),
        ),
        migrations.AlterField(
            model_name='pausecafe',
            name='choix_viennoiserie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, verbose_name='CHOIX DE VIENNOISERIE'),
        ),
        migrations.AlterField(
            model_name='poulet',
            name='type_de_poulet',
            field=models.CharField(choices=[('POULET FRAIS', 'POULET FRAIS')], max_length=50, verbose_name='TYPE DE POULET'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='avenue',
            field=models.CharField(choices=[('COLONNEL EBEYA', 'COLONNEL EBEYA'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('SENEGALAIS', 'SENEGALAIS'), ('OUGANDA', 'OUGANDA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='PRIX'),
        ),
        migrations.AlterField(
            model_name='salleconference',
            name='superficie',
            field=models.CharField(choices=[('28 M2', '28 M2'), ('50 M2', '50 M2'), ('65 M2', '65 M2'), ('66 M2', '66 M2'), ('71,5 M2', '71,5 M2'), ('72 M2', '72 M2'), ('140 M2', '140 M2'), ('146 M2', '146 M2'), ('435 M2', '435 M2')], max_length=20, verbose_name='SUPERFICIE'),
        ),
        migrations.AlterField(
            model_name='siphon',
            name='type_sanitaire',
            field=models.CharField(choices=[('BAIGNOIRE', 'BAIGNOIRE'), ('EVIER', 'EVIER'), ('LAVABO', 'LAVABO'), ('SOL', 'SOL')], max_length=20, verbose_name="TYPE D'INSTALLATION"),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='longueur',
            field=models.CharField(choices=[('2.4 M', '2.4 M'), ('3.5 M', '3.5 M')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='tondeuse',
            name='type_tondeuse',
            field=models.CharField(choices=[('THERMIQUE', 'THERMIQUE'), ('ELECTRIQUE', 'ELECTRIQUE')], max_length=100, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='tourteau',
            name='base',
            field=models.CharField(choices=[('TOURNESOL', 'TOURNESOL')], max_length=100, verbose_name='PRODUIT DE BASE'),
        ),
    ]
