# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180118_1155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0427_auto_20180604_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenemententiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('type_evenement_de_masse', models.CharField(choices=[('CARAVANE MOTORISE', 'CARAVANE MOTORISE'), ('EVENEMENT DE MASSE', 'EVENEMENT DE MASSE'), ('EVENEMENT CORPORATE', 'EVENEMENT CORPORATE'), ('EVENEMENT PREMIUM', 'EVENEMENT PREMIUM')], max_length=100, verbose_name="TYPE D'EVENEMENT")),
                ('minimum_payable', models.CharField(blank=True, choices=[('1000 USD', '1000 USD')], max_length=20, null=True, verbose_name='MINIMUM PAYABLE')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('%', '%')], max_length=50, verbose_name='UNITE')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='evenementdemasse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='evenementdemasse',
            name='vendeur',
        ),
        migrations.AlterField(
            model_name='carteservice',
            name='quantite',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-100', '10-100'), ('100-1000', '100-1000'), ('1000 <', '1000 <')], max_length=50, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='sallegym',
            name='avenue',
            field=models.CharField(choices=[('COLONNEL EBEYA', 'COLONNEL EBEYA'), ('KASAVUBU', 'KASAVUBU'), ('LUAMBO MAKIADI', 'LUAMBO MAKIADI'), ('SENEGALAIS', 'SENEGALAIS'), ('OUGANDA', 'OUGANDA')], max_length=20, verbose_name='AVENUE'),
        ),
        migrations.DeleteModel(
            name='EvenementDeMasse',
        ),
    ]
