# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20180118_1155'),
        ('product', '0428_auto_20180604_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='NettoyageDeChaise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='PRODUIT')),
                ('is_active', models.BooleanField()),
                ('revetement', models.CharField(choices=[('TISSUS', 'TISSUS'), ('CUIR', 'CUIR')], max_length=100, verbose_name='REVETEMENT DES CHAISES')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRIX')),
                ('units', models.CharField(choices=[('USD/M2', 'USD/M2')], max_length=50, verbose_name='UNITÉ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='assainissement',
            name='detail_assainissement',
        ),
        migrations.AddField(
            model_name='assainissement',
            name='specifications',
            field=models.CharField(choices=[('NON APPLICABLE', 'NON APPLICABLE'), ('VITRE', 'VITRE'), ('ALUCOBONDE', 'ALUCOBONDE'), ('PEINTURE', 'PEINTURE'), ('CARRELAGE', 'CARRELAGE'), ('GRANITO QUARTZ', 'GRANITO QUARTZ'), ('GRATTAGE', 'GRATTAGE'), ('VITRE', 'VITRE')], default=1, max_length=100, verbose_name='SPECIFICATION'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='format_calendrier',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A3+', 'A3+')], max_length=50, verbose_name='FORMAT'),
        ),
        migrations.AlterField(
            model_name='evenemententiel',
            name='type_evenement_de_masse',
            field=models.CharField(choices=[('CARAVANE MOTORISÉ', 'CARAVANE MOTORISÉ'), ('EVENEMENT DE MASSE', 'EVENEMENT DE MASSE'), ('EVENEMENT CORPORATE', 'EVENEMENT CORPORATE'), ('EVENEMENT PREMIUM', 'EVENEMENT PREMIUM')], max_length=100, verbose_name="TYPE D'EVENEMENT"),
        ),
        migrations.AlterField(
            model_name='evenemententiel',
            name='units',
            field=models.CharField(choices=[('% DU DEVIS', '% DU DEVIS')], max_length=50, verbose_name='UNITE'),
        ),
    ]
