# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0429_auto_20180604_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farine',
            name='produit_de_base',
            field=models.CharField(choices=[('MANIOC', 'MANIOC'), ('TAPIOCA', 'TAPIOCA')], max_length=100, verbose_name='PRODUIT DE BASE'),
        ),
        migrations.AlterField(
            model_name='nettoyagedechaise',
            name='units',
            field=models.CharField(choices=[('USD/CHAISE', 'USD/CHAISE')], max_length=50, verbose_name='UNITÉ'),
        ),
    ]
