# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0430_auto_20180604_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armoire',
            name='hauteur',
            field=models.CharField(choices=[('157CM', '157CM')], max_length=50, verbose_name='HAUTEUR'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL')], max_length=50, verbose_name='MATERIAU'),
        ),
        migrations.AlterField(
            model_name='assainissement',
            name='type_assainissement',
            field=models.CharField(choices=[('DESINSECTISATION', 'DESINSECTISATION'), ('DERATISATION', 'DERATISATION'), ('NETTOYAGE', 'NETTOYAGE'), ('NETTOYAGE APRES CHANTIER', 'NETTOYAGE APRES CHANTIER'), ('DESINFECTION', 'DESINFECTION'), ('NETTOYAGE BUREAUX', 'NETTOYAGE DE BUREAUX'), ('FAÇADE IMMEUBLE', 'FAÇADE IMMEUBLE'), ('PARQUET EN BOIS', 'PARQUET EN BOIS'), ('GRANITO', 'GRANITO'), ('TAPIS', 'TAPIS')], max_length=100, verbose_name="TYPE D'ASSAINISSEMENT"),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='forme',
            field=models.CharField(choices=[('EN L', 'EN L'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longueur',
            field=models.CharField(choices=[('120CM', '120CM'), ('140CM', '140CM'), ('150CM', '150CM'), ('160CM', '160CM'), ('170CM', '170CM'), ('180CM', '180CM')], max_length=20, verbose_name='LONGUEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='hauteur',
            field=models.CharField(choices=[('198CM', '198CM'), ('200CM', '200CM')], max_length=20, verbose_name='HAUTEUR'),
        ),
        migrations.AlterField(
            model_name='etagere',
            name='materiau_armoire',
            field=models.CharField(choices=[('METAL', 'METAL')], max_length=20, verbose_name='MATERIAU '),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='modele',
            field=models.CharField(choices=[('ALLEX', 'ALLEX'), ('CAMRY', 'CAMRY'), ('COROLLA', 'COROLLA'), ('HIACE', 'HIACE'), ('HILUX DOUBLE CABINE', 'HILUX DOUBLE CABINE'), ('LAND CRUISER', 'LAND CRUISER'), ('LAND CRUISER RUNNER', 'LAND CRUISER RUNNER'), ('NOAH', 'NOAH'), ('PRADO', 'PRADO'), ('RAV4', 'RAV4'), ('YARIS', 'YARIS')], max_length=100, verbose_name='MODELE DU VEHICULE'),
        ),
        migrations.AlterField(
            model_name='locationvehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'VOITURE'), ('JEEP', 'JEEP'), ('MINIBUS', 'MINIBUS')], max_length=20, verbose_name='TYPE DE VEHICULE'),
        ),
        migrations.AlterField(
            model_name='moteur',
            name='modele',
            field=models.CharField(blank=True, choices=[('26-28', '26-28'), ('26-36', '26-36'), ('33-330', '33-330'), ('ACTROS', 'ACTROS')], max_length=100, null=True, verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='modele_moto',
            field=models.CharField(choices=[('APACHE', 'APACHE'), ('STAR HLX', 'STAR HLX'), ('ZT', 'ZT')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='motodeuxroues',
            name='puissance_moteur',
            field=models.CharField(choices=[('100CC', '100CC'), ('125CC', '125CC'), ('160CC', '160CC'), ('180CC', '180CC')], max_length=100, verbose_name='PUISSANCE DU MOTEUR'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='modele_moto',
            field=models.CharField(choices=[('KING DELUXE', 'KING DELUXE')], max_length=100, verbose_name='MODELE'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='puissance_moteur',
            field=models.CharField(choices=[('200CC', '200CC')], max_length=100, verbose_name='PUISSANCE DU MOTEUR'),
        ),
        migrations.AlterField(
            model_name='mototroisroues',
            name='type_demarrage',
            field=models.CharField(choices=[('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE')], max_length=100, verbose_name='TYPE DE DEMARRAGE'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='forme',
            field=models.CharField(choices=[('OVALE', 'OVALE'), ('RECTANGULAIRE', 'RECTANGULAIRE')], max_length=20, verbose_name='FORME'),
        ),
        migrations.AlterField(
            model_name='tablereunion',
            name='longueur',
            field=models.CharField(choices=[('2,4 M', '2,4 M'), ('3,5 M', '3,5 M')], max_length=20, verbose_name='LONGUEUR'),
        ),
    ]
