# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0434_blanchisserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanchisserie',
            name='units',
            field=models.CharField(choices=[('USD/KG', 'USD/KG')], max_length=50, verbose_name='UNITÉ'),
        ),
    ]
