# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0435_auto_20180606_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparentareliure',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
    ]
