# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0437_auto_20180606_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punaise',
            name='contenant',
            field=models.CharField(choices=[('BOITE', 'BOITE')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='stylopapeterie',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
    ]
