# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0438_auto_20180606_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baguette',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('100/PAQUET', '100/PAQUET'), ('BOITE', 'BOITE'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='carbonne',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='elastiques',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='enveloppe',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='etui',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='intercalaire',
            name='contenant',
            field=models.CharField(choices=[('JEUX', 'JEUX')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='marqueur',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='papier',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET'), ('RAME', 'RAME')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='contenant',
            field=models.CharField(choices=[('CARNET', 'CARNET')], max_length=100, verbose_name='CONTENANT'),
        ),
        migrations.AlterField(
            model_name='roseareliure',
            name='contenant',
            field=models.CharField(choices=[('PAQUET', 'PAQUET')], max_length=100, verbose_name='CONTENANT'),
        ),
    ]
