# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0439_auto_20180606_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampoulesolaire',
            name='puissance',
            field=models.CharField(choices=[('3W', '3W'), ('5W', '5W'), ('10W', '10W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='batteriesolaire',
            name='marque',
            field=models.CharField(choices=[('EXCIS', 'EXCIS'), ('MONBAT', 'MONBAT'), ('CNBINDUSTRIALPOWER', 'CNBINDUSTRIALPOWER'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='convertisseur',
            name='marque_convertisseur',
            field=models.CharField(choices=[('WESTECH', 'WESTECH'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='puissance',
            field=models.CharField(choices=[('50W', '50W'), ('80W', '80W'), ('100W', '100W'), ('150W', '150W'), ('180W', '180W'), ('190W', '190W'), ('250W', '250W'), ('300W', '300W')], max_length=20, verbose_name='PUISSANCE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='intensite',
            field=models.CharField(choices=[('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('45A', '45A'), ('50A', '50A'), ('60A', '60A'), ('80A', '80A'), ('85A', '85A')], max_length=20, verbose_name='INTENSITE'),
        ),
        migrations.AlterField(
            model_name='regulateur',
            name='marque',
            field=models.CharField(choices=[('WESTECH', 'WESTECH'), ('EPSOLAR', 'EPSOLAR'), ('VICTRON ENERGY', 'VICTRON ENERGY'), ('REOO INDUSTRY', 'REOO INDUSTRY')], max_length=20, verbose_name='MARQUE'),
        ),
    ]
