# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0440_auto_20180606_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='duree_vie',
            field=models.CharField(choices=[('20 ANS', '20 ANS')], max_length=20, verbose_name='DUREE DE VIE'),
        ),
        migrations.AlterField(
            model_name='panneauxsolaire',
            name='garantie',
            field=models.CharField(choices=[('5 ANS', '5 ANS')], max_length=20, verbose_name='GARANTIE'),
        ),
    ]
