# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessprofile_travaux_realises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='annee_existence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Année de création'),
        ),
    ]
