UNITE = (
        ('USD', 'US$'),
        ('EUROS', 'EUROS'),
        ('USD/JOUR','USD/JOUR'),
        ('USD/PAGE','USD/PAGE'),
        ('USD/M2','USD/M2'),
        ('USD/MOIS','USD/MOIS'),
        ('USD/PIECE','USD/PIECE'),
        ('USD','USD'),
        ('USD/M','USD/M'),
        ('USD/KG','USD/KG'),
        ('USD/PERSONNE','USD/PERSONNE'),
        ('USD/GARDIEN/MOIS','USD/GARDIEN/MOIS'),
        ('USD/LITRE','USD/LITRE'),
        ('USD/SPLIT','USD/SPLIT'),
        ('%','%'),
        ('% DU SALAIRE','% DU SALAIRE'),
        ('% DU 1ER SALAIRE','% DU 1ER SALAIRE'),
        ('% DES FONDS TRANSPORTES','% DES FONDS TRANSPORTES'),
        ('USD/PERSONNE/JOUR','USD/PERSONNE/JOUR'),
        ('USD/THEME','USD/THEME'),
        ('USD/KG','USD/KG'),
        ('USD/AN','USD/AN'),
        ('USD/HEURE','USD/HEURE'),
        ('USD/MODULE','USD/MODULE'),
        ('USD/KG OU L','USD/KG OU L'),
        ('% DU DEVIS','% DU DEVIS'),
        ('USD/PERSONNE/MOIS','USD/PERSONNE/MOIS'),
        ('USD/TONNE','USD/TONNE'),
        ('USD/SECONDE','USD/SECONDE'),
        ('USD/M²','USD/M²'),
        ('USD/BOITE','USD/BOITE'),
        ('USD/PAQUET','USD/PAQUET'),
        ('USD/JEU','USD/JEU'),
        ('USD/CONTENANT','USD/CONTENANT'),
        ('USD/CARNET','USD/CARNET'),

    )