POIDS = (
		('50KG','50KG'),

	)

ETENDUE = (
		('1HECTARE','1HECTARE'),

	)

VARIETE = (

		('NERICA','NERICA'),
		('NERICA 17','NERICA 17'),
		('NERICA 18','NERICA 18'),
		('JASMIN','JASMIN'),
		('SIPI','SIPI'),
		('IB','IB'),
        ('CARGO','CARGO'),
        ('BABUNGO','BABUNGO'),


	)

QUANTITE= (
		('25KG','25KG'),

	)

TYPE_RIZ= (
		('DECORTIQUE','DECORTIQUE'),
		('NON DECORTIQUE','NON DECORTIQUE'),

	)
QUALITE_RIZ= (
		('BIO','BIO'),

	)

QUALITE_BOUILLIE= (
		('BIO','BIO'),

	)


COMPOSITION_BOUILLIE= (
		('SOYA, BLE, MAIS, RIZ ET HUILE VEGETALE','SOYA, BLE, MAIS, RIZ ET HUILE VEGETALE'),

	)
PRODUIT_AGRICOLE = (

		('TOURNESOL', 'TOURNESOL'),
        ('MAIS', 'MAIS'),
        ('HARICOT', 'HARICOT'),
        ('RIZ', 'RIZ'),
        ('SOJA', 'SOJA'),

	)




POIDS = (

		('1KG', '1KG'),
        ('5KG', '5KG'),
        ('10KG', '10KG'),
        ('25KG', '25KG'),

	)

LONGUEUR = (

		('2500M', '2500M'),

	)

BASE = (

		('TOURNESOL', 'TOURNESOL'),
		('TAPIOCA', 'TAPIOCA'),

	)

TYPE_LEGUME= (
		('AUBERGINES','AUBERGINES'),
		('GOMBO','GOMBO'),
		('TOMATES','TOMATES'),

	)
TYPE_POULET= (
	    ('BLANC DE POULET','BLANC DE POULET'),
		('POULET FRAIS','POULET FRAIS'),
		('POULE FUME','POULE FUME'),


	)
TYPE_POISSON= (

		('CAPITAINE','CAPITAINE'),
		('MBOTO','MBOTO'),
		('MUNGUSU','MUNGUSU'),
		('MOJOMBO','MOJOMBO'),
		('MINZANDA','MINZANDA'),
		('NGOLO','NGOLO'),
		('MGOMGO','MGOMGO'),
		('CAPITAINE','CAPITAINE'),
		('MBOTO','MBOTO'),
		('MUNGUSU','MUNGUSU'),
		('MOJOMBO','MOJOMBO'),
		('MINZANDA','MINZANDA'),
		('NGOLO','NGOLO'),
		('MGOMGO','MGOMGO'),
		('SOLE MOYENNE','SOLE MOYENNE'),
		('GRANDE SOLE','GRANDE SOLE'),
		('CAPITAINE MOYEN','CAPITAINE MOYEN'),
		('GRAND CAPITAINE','GRAND CAPITAINE'),
		('FILET DE CAPITAINE','FILET DE CAPITAINE'),
		('PERCHE','PERCHE'),
		('FILET DE PERCHE','FILET DE PERCHE'),
		('MEROU','MEROU'),
		('RAIE (MAZIBA)','RAIE (MAZIBA)'),
		('AILE DE RAIE','AILE DE RAIE'),
		('ROUGET','ROUGET'),
		('SAINT PIERRE','SAINT PIERRE'),
		('BARRACUDA','BARRACUDA'),
		('COSSA MOYEN MOANDA','COSSA MOYEN MOANDA'),
		('COSSA MOYEN POINTE NOIRE','COSSA MOYEN POINTE NOIRE'),
		('COSSA ROYALE POINTE NOIRE','COSSA ROYALE POINTE NOIRE'),
		('PETITE LANGOUSTE MOANDA','PETITE LANGOUSTE MOANDA'),
		('LANGOUSTE MOYENNE POINTE NOIRE','LANGOUSTE MOYENNE POINTE NOIRE'),
		('GRANDE LANGOUSTE POINTE NOIRE','GRANDE LANGOUSTE POINTE NOIRE'),
		('PIEUVRE POINTE NOIR','PIEUVRE POINTE NOIR'),
		('CRABE','CRABE'),
		('CALAMARD','CALAMARD'),
		('SECHE','SECHE'),
		('COSSA DECORTIQUE','COSSA DECORTIQUE'),
		('MORUE','MORUE'),
		('CROQUETTES POISSON 10PCS','CROQUETTES POISSON 10PCS'),
		('CROQUETTES COSSA 10PCS','CROQUETTES COSSA 10PCS'),
		('CROQUETTE MORUE 10PCS','CROQUETTE MORUE 10PCS'),


	)


CONDITIONNEMENT_JUS= (
		('POT PLASTIQUE DE 25CL AVEC PAILLE','POT PLASTIQUE DE 25CL AVEC PAILLE'),
		('BOUTEILLE VERRE 25 CL','BOUTEILLE VERRE 25 CL'),
		('BOUTEILLE PLASTIQUE 33CL','BOUTEILLE PLASTIQUE 33CL'),
		('BOUTEILLE VERRE 50CL','BOUTEILLE VERRE 50CL'),
		('BIDON PLASTIQUE 2,5L','BIDON PLASTIQUE 2,5L'),
		('BIDON PLASTIQUE 5L','BIDON PLASTIQUE 5L'),

	)

TYPE_FRUIT= (


		('ANANAS','ANANAS'),
		('BANANE DE TABLE GRANDE','BANANE DE TABLE GRANDE'),
		('BANANE DE TABLE PETITE (KINSHASA)','BANANE DE TABLE PETITE (KINSHASA)'),
		('BANANE DE TABLE PETITE (KIVU)','BANANE DE TABLE PETITE (KIVU)'),
		('BANANE PLANTAIN','BANANE PLANTAIN'),
		('BISAMOUNIAOU (KIVU)','BISAMOUNIAOU (KIVU)'),
		('CITRON VERT ','CITRON VERT '),
		('COROSSOL','COROSSOL'),
		('GOYAVE (KIVU)','GOYAVE (KIVU)'),
		('GOYAVE (KINSHASA)','GOYAVE (KINSHASA)'),
		('MANGOUSTAN','MANGOUSTAN'),
		('MARACUJA JAUNE (KINSHASA)','MARACUJA JAUNE (KINSHASA)'),
		('MARACUJA NOIR (KIVU)','MARACUJA NOIR (KIVU)'),
		('MIZABIBU (KIVU)','MIZABIBU (KIVU)'),
		('NOIX DE COCO','NOIX DE COCO'),
		('ORANGE (IMPORT)','ORANGE (IMPORT)'),
		('ORANGE LOCALE','ORANGE LOCALE'),
		('PAMPLEMOUSSE JAUNE','PAMPLEMOUSSE JAUNE'),
		('PAMPLEMOUSSE ROSE','PAMPLEMOUSSE ROSE'),
		('PAPAYE','PAPAYE'),
		('PASTEQUE','PASTEQUE'),
		('PHYSALIS DU KIVU','PHYSALIS DU KIVU'),
		('RAMBOUTAN (LITCHI POILU)','RAMBOUTAN (LITCHI POILU)'),
		('TOMARILLO (PRUNE DU KIVU)','TOMARILLO (PRUNE DU KIVU)'),


	)

TYPE_MORCEAU= (


		('BLANQUETTE DE VEAU','BLANQUETTE DE VEAU'),
		('COTES DE VEAU','COTES DE VEAU'),
		('ESCALOPE DE VEAU','ESCALOPE DE VEAU'),
		('FOIE DE VEAU','FOIE DE VEAU'),
		('JARRET DE VEAU','JARRET DE VEAU'),
		('ROTIS DE VEAU','ROTIS DE VEAU'),
		('BLANC DE POULET','BLANC DE POULET'),
		('POULET FRAIS','POULET FRAIS'),
		('POULE FUME','POULE FUME'),
		('ŒUFS DE FERME BIO','ŒUFS DE FERME BIO'),
		('CARRE AGNEAU','CARRE AGNEAU'),
		('COLIER AGNEAU','COLIER AGNEAU'),
		('COTES AGNEAU','COTES AGNEAU'),
		('EPAULE','EPAULE'),
		('GIGOT','GIGOT'),
		('PLATTE COTE','PLATTE COTE'),
		('POITRINE','POITRINE'),
		('CHEVRE ENTIERE','CHEVRE ENTIERE'),
		('CUISSE DE CHEVRE','CUISSE DE CHEVRE'),
		('BACON','BACON'),
		('BILTONG','BILTONG'),
		('BOUDIN BLANC','BOUDIN BLANC'),
		('BOUDIN NOIR','BOUDIN NOIR'),
		('COTE DE POR FUME','COTE DE POR FUME'),
		('JAMBON CUIT','JAMBON CUIT'),
		('JAMBONNEAU FUME','JAMBONNEAU FUME'),
		('LARD FUME','LARD FUME'),
		('MERGUEZ','MERGUEZ'),
		('PATE DE FOIE','PATE DE FOIE'),
		('SALAMI ET COLLIER ARDENE','SALAMI ET COLLIER ARDENE'),
		('SAUCISSE AU FROMAGE','SAUCISSE AU FROMAGE'),
		('SAUCISSE FRAICHE','SAUCISSE FRAICHE'),
		('SAUCISSE PILI OU SANS PILI','SAUCISSE PILI OU SANS PILI'),
		('SAUCISSON DE JAMBO','SAUCISSON DE JAMBO'),
		('SAUCISSON DE PARIS','SAUCISSON DE PARIS'),

	)
TYPE_MORCEAU_BOEUF= (
		('BOUILLI','BOUILLI'),
		('CARBONNADE','CARBONNADE'),
		('ENTRECOTE A OS','ENTRECOTE A OS'),
		('ENTRECOTE SANS OS','ENTRECOTE SANS OS'),
		('FILET PUR','FILET PUR'),
		('HACHE DE BŒUF','HACHE DE BŒUF'),
		('JARRET (OSSO BUCO)','JARRET (OSSO BUCO)'),
		('PREGOS','PREGOS'),
		('PREGO (MARINE)','PREGO (MARINE)'),
		('QUEU DE BŒUF','QUEU DE BŒUF'),
		('ROTI 1ER CHOIX','ROTI 1ER CHOIX'),
		('STEAK','STEAK'),
		('TACHE NOIR','TACHE NOIR'),
	)
TYPE_MORCEAU_PORC= (
		('BIFANA','BIFANA'),
		('BIFANA (MARINE)','BIFANA (MARINE)'),
		('CARRE DE PORC','CARRE DE PORC'),
		('COTELETTE DE PORC','COTELETTE DE PORC'),
		('ECHINE','ECHINE'),
		('FILET MIGNON','FILET MIGNON'),
		('HACHE DE PORC','HACHE DE PORC'),
		('JAMBONNEAU FRAIS','JAMBONNEAU FRAIS'),
		('ROTI DE PORC','ROTI DE PORC'),
		('SAINDOUX','SAINDOUX'),
	)
TYPE_DE_CONDITIONNEMENT= (
		('EMBALLAGE SOUS VIDE','EMBALLAGE SOUS VIDE'),
	)

TYPE_LEGUME= (

		('ARTICHAUX DU KIVU','ARTICHAUX DU KIVU'),
		('AUBERGINE','AUBERGINE'),
		('AVOCAT','AUBERGINE'),
		('BETTERAVE DU KIVU','BETTERAVE DU KIVU'),
		('BROCOLIS','BROCOLIS'),
		('CAROTTE','CAROTTE'),
		('CAROTTE (GOMA)','CAROTTE (GOMA)'),
		('CELERI','CELERI'),
		('CHOUX FLEUR DU KIVU','CHOUX FLEUR DU KIVU'),
		('CHOUX POMME','CHOUX POMME'),
		('CONCOMBRE','CONCOMBRE'),
		('COURGE','COURGE'),
		('COURGETTES','COURGETTES'),
		('EPINARD','EPINARD'),
		('HARICOT','HARICOT'),
		('HARICOT GOMA 1ER CHOIX','HARICOT GOMA 1ER CHOIX'),
		('HARICO PRINCESSE','HARICO PRINCESSE'),
		('LAITUE','LAITUE'),
		('NAVET','NAVET'),
		('OIGNON BLANC','OIGNON BLANC'),
		('OIGNON BLANC (GOMA)','OIGNON BLANC (GOMA)'),
		('OIGNON ROUGE','OIGNON ROUGE'),
		('OIGNON ROUGE(GOMA)','OIGNON ROUGE(GOMA)'),
		('PATATE DOUCE','PATATE DOUCE'),
		('PETITS POIDS DU KIVU','PETITS POIDS DU KIVU'),
		('POIVRON VERT','POIVRON VERT'),
		('POMME DE TERRE(RSA) ','POMME DE TERRE(RSA)'),
		('POMME DE TERRE(GOMA) ','POMME DE TERRE(GOMA) '),
		('POMME DE TERRE(LOCAL) ','POMME DE TERRE(LOCAL)'),
		('RADIS DU KIVU','RADIS DU KIVU'),
		('RHUBARBE DU KIVU','RHUBARBE DU KIVU'),
		('TOMATE','TOMATE'),
		('GOMBO','GOMBO'),
		('HARICOT (GOMA)','HARICOT (GOMA)'),

	)
TYPE_CONDIMENT=(
		('AIL','AIL'),
		('BASILIC','BASILIC'),
		('CORIANDRE','CORIANDRE'),
		('GINGEMBRE','GINGEMBRE'),
		('MENTHE','MENTHE'),
		('PERSIL','PERSIL'),
		('CAFE DU KIVU (GRAIN OU MOULU)','CAFE DU KIVU (GRAIN OU MOULU)'),


	)

POIDS_PAR_SAC=(
		('100 KG','100 KG'),

	)

CONTENANT_GINGEMBRE= (

		('SACHET DE 1,5Kg','SACHET DE 1,5Kg'),


	)

CONTENANT_AMARANTE= (

		('BOTTE','BOTTE'),


	)

TYPE_LEGUME= (

		('PONDU','PONDU'),


	)



CONTENANT_PONDU= (

		('SACHET DE 250G','SACHET DE 250G'),
		('SACHET DE 500G','SACHET DE 500G'),
		('SACHET DE 1KG','SACHET DE 1KG'),


	)
CONTENANT_FARINE= (

		('SAC DE 5KG','SAC DE 5KG'),
		('SAC DE 10KG','SAC DE 10KG'),
		('SAC DE 20KG','SAC DE 20KG'),

	)
PRODUIT_BASE= (

		('MANIOC','MANIOC'),


	)
CONTENANT_MAIS= (

		('SAC DE 60KG','SAC DE 60KG'),
		('SAC DE 100KG','SAC DE 100KG'),

	)
VARIETE= (

		('JAUNE','JAUNE'),

	)
CONTENANT_MANIOC= (

		('SAC DE 100KG','SAC DE 100KG'),

	)
CONTENANT_ARACHIDE= (

		('SAC DE 50KG','SAC DE 50KG'),

	)
CARACTERISTIQUE_ARACHIDE= (

		('DECORTIQUE','DECORTIQUE'),

	)
PRODUIT_BASE_SEMOULE= (

		('MAIS','MAIS'),
		('SOJA','SOJA'),

	)
CONTENANT_SEMOULE= (

		('SAC DE 10KG','SAC DE 10KG'),
		('SAC DE 25KG','SAC DE 25KG'),
		('SAC DE 1KG','SAC DE 1KG'),


	)
