PIECE_RECHANGE_MODELE = (
		('D-MAX TFR54','D-MAX TFR54'),
        ('D-MAX TFR85','D-MAX TFR85'),
        ('L300','L300'),
        ('PATROL Y61','PATROL Y61'),
        ('HILUX','HILUX'),
        ('LAND CRUISER PRADO','LAND CRUISER PRADO'),
	)
PIECE_RECHANGE_MARQUE = (
		('ISUZU','ISUZU'),
		('MITSUBISHI','MITSUBISHI'),
        ('NISSAN','NISSAN'),
        ('TOYOTA','TOYOTA'),

	)



PIECE_DIRECTION_SUSPENSION = (
		('ROTULE DE DIRECTION EXTERIEURE GAUCHE','ROTULE DE DIRECTION EXTERIEURE GAUCHE'),
		('ROTULE DE DIRECTION EXTERIEURE DROIT','ROTULE DE DIRECTION EXTERIEURE DROIT'),
		('ROTULE DE DIRECTION INFERIEUR GAUCHE','ROTULE DE DIRECTION INFERIEUR GAUCHE'),
		('ROTULE DE DIRECTION INFERIEUR DROIT','ROTULE DE DIRECTION INFERIEUR DROIT'),
		('ROTULE DE SUSPENSION INFERIEURE GAUCHE','ROTULE DE SUSPENSION INFERIEURE GAUCHE'),
		('ROTULE DE SUSPENSION INFERIEURE DROITE','ROTULE DE SUSPENSION INFERIEURE DROITE'),
		('ROTULE DE SUSPENSION SUPERIEURE GAUCHE','ROTULE DE SUSPENSION SUPERIEURE GAUCHE'),
		('ROTULE DE SUSPENSION SUPERIEURE DROITE','ROTULE DE SUSPENSION SUPERIEURE DROITE'),
		('BRAS DE SUSPENSION INFERIEURE GAUCHE','BRAS DE SUSPENSION INFERIEURE GAUCHE'),
		('BRAS DE SUSPENSION INFERIEURE DROITE','BRAS DE SUSPENSION INFERIEURE DROITE'),
		('BRAS DE SUSPENSION SUPERIEUR GAUCHE','BRAS DE SUSPENSION SUPERIEUR GAUCHE'),
		('BRAS DE SUSPENSION SUPERIEUR DROITE','BRAS DE SUSPENSION SUPERIEUR DROITE'),
		('BIELLETTE STABILISATRICE AVANT GAUCHE','BIELLETTE STABILISATRICE AVANT GAUCHE'),
		('BIELLETTE STABILISATRICE AVANT DROITE','BIELLETTE STABILISATRICE AVANT DROITE'),
		('SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1','SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1'),
		('SILEMBLOC BRAS DE SUSPENSION SUPERIEURE','SILEMBLOC BRAS DE SUSPENSION SUPERIEURE'),
		('SILEMBLOC BRAS DE STABILISATION AV','SILEMBLOC BRAS DE STABILISATION AV'),
		('AMORTISSEUR AVANT GAUCHE','AMORTISSEUR AVANT GAUCHE'),
		('AMORTISSEUR AVANT DROIT','AMORTISSEUR AVANT DROIT'),
		('AMORTISSEUR ARRIERE GAUCHE','AMORTISSEUR ARRIERE GAUCHE'),
		('AMORTISSEUR ARRIERE DROIT','AMORTISSEUR ARRIERE DROIT'),
		('LAME MAITRESSE','LAME MAITRESSE'),
		('SILEMBLOC LAME INFERIEURE','SILEMBLOC LAME INFERIEURE'),
		('SILEMBLOC LAME SUPERIEURE','SILEMBLOC LAME SUPERIEURE'),
		('CREMAILLEUR DE DIRECTION','CREMAILLEUR DE DIRECTION'),
		('POMPE DE DIRECTION','POMPE DE DIRECTION'),
		('AMORTISSEUR DE DIRECTION','AMORTISSEUR DE DIRECTION'),
		('SILEMBLOC BARRE STABILISATRICE ARRIERE','SILEMBLOC BARRE STABILISATRICE ARRIERE'),
		('SILEMBLOC BARRE STABILISATRICE AVANT','SILEMBLOC BARRE STABILISATRICE AVANT'),
		('BIELLETTE STABILISATRICE ARRIERE GAUCHE','BIELLETTE STABILISATRICE ARRIERE GAUCHE'),
		('BIELLETTE STABILISATRICE ARRIERE DROITE','BIELLETTE STABILISATRICE ARRIERE DROITE'),
        ('BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE','BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE'),
        ('SILEMBLOC BARRE STABILISATRICE AV','SILEMBLOC BARRE STABILISATRICE AV'),
        ('BRAS DE SUSPENSION SUPERIEURE GAUCHE','BRAS DE SUSPENSION SUPERIEURE GAUCHE'),
        ('BRAS DE SUSPENSION SUPERIEURE DROITE','BRAS DE SUSPENSION SUPERIEURE DROITE'),
        ('SOUFFLET DE DIRECTION','SOUFFLET DE DIRECTION'),
        ('ROTULE DE DIRECTION INFERIEURE GAUCHE','ROTULE DE DIRECTION INFERIEURE GAUCHE'),
        ('ROTULE DE DIRECTION INFERIEURE DROITE','ROTULE DE DIRECTION INFERIEURE DROITE'),
        ('ROTULE DE DIRECTION EXTERIEURE GAUCHE','ROTULE DE DIRECTION EXTERIEURE GAUCHE'),
        ('ROTULE DE DIRECTION EXTERIEURE DROITE','ROTULE DE DIRECTION EXTERIEURE DROITE'),
        ('DEMARREUR','DEMARREUR'),
        ('SILEMBLOC BARRE STABILISATRICE AV 48815-60180','SILEMBLOC BARRE STABILISATRICE AV 48815-60180'),
        ('SILEMBLOC BARRE STABILISATRICE AV 48632-60020','SILEMBLOC BARRE STABILISATRICE AV 48632-60020'),
        ('SILEMBLOC BRAS DE SUSPENSION SUPERIEUR','SILEMBLOC BRAS DE SUSPENSION SUPERIEUR'),
	)
PIECE_RECHANGE_CARROSSERIE = (
		('PHARE AVANT GAUCHE','PHARE AVANT GAUCHE'),
		('PHARE AVANT DROIT','PHARE AVANT DROIT'),
		('FEU ARRIERE GAUCHE','FEU ARRIERE GAUCHE'),
		('FEU ARRIERE DROIT','FEU ARRIERE DROIT'),
		('BALAI ESSUIE GLACE AVANT','BALAI ESSUIE GLACE AVANT'),
		('RETROVISEUR GAUCHE','RETROVISEUR GAUCHE'),
		('RETROVISEUR DROIT','RETROVISEUR DROIT'),


	)


PIECE_RECHANGE_ELECTRIQUE = (
		('DEMARREUR','DEMARREUR'),
		('ALTERNATEUR','ALTERNATEUR'),
		('POMPE A VIDE ALTERNATEUR','POMPE A VIDE ALTERNATEUR'),
        ('CONTACTEUR PRESSION HUILE','CONTACTEUR PRESSION HUILE'),
        ('INTERRUPTEUR DE TEMPERATURE','INTERRUPTEUR DE TEMPERATURE'),
        ('RELAI DE DEMARRAGE','RELAI DE DEMARRAGE'),
        ('CONTACTEUR DE PRESSION D’HUILE','CONTACTEUR DE PRESSION D’HUILE'),

	)
PIECE_RECHANGE_EMBRAYAGE = (
		('DISQUE EMBRAYAGE','DISQUE EMBRAYAGE'),
		('PLATEAU EMBRAYAGE','PLATEAU EMBRAYAGE'),
		('BUTEE EMBRAYAGE','BUTEE EMBRAYAGE'),
		('CYLINDRE RECEPTEUR','CYLINDRE RECEPTEUR'),
		('CYLINDRE EMETTEUR','CYLINDRE EMETTEUR'),
        ('KIT DE REPARATION CYLINDRE EMETTEUR','KIT DE REPARATION CYLINDRE EMETTEUR'),
        ('KIT DE REPARATION CYLINDRE RECEPTEUR','KIT DE REPARATION CYLINDRE RECEPTEUR'),
	)
PIECE_RECHANGE_FREINAGE = (
		('PLAQUETTE DE FREIN AVANT','PLAQUETTE DE FREIN AVANT'),
		('PLAQUETTE/MACHOIRE DE FREIN ARRIERE','PLAQUETTE/MACHOIRE DE FREIN ARRIERE'),
		('DISQUE DE FREIN AVANT','DISQUE DE FREIN AVANT'),
		('DISQUE/TAMBOUR DE FREIN ARRIERE','DISQUE/TAMBOUR DE FREIN ARRIERE'),
		('CYLINDRE DE ROUE ARRIERE DROITE','CYLINDRE DE ROUE ARRIERE DROITE'),
		('CYLINDRE DE ROUE ARRIERE GAUCHE','CYLINDRE DE ROUE ARRIERE GAUCHE'),
		('MAITRE CYLINDRE DE FREIN','MAITRE CYLINDRE DE FREIN'),
	)
TYPE_PIECE_REFROIDISSEMENT = (
		('POMPE A EAU','POMPE A EAU'),
		('THERMOSTAT','THERMOSTAT'),
		('COURROIE ALTERNATEUR','COURROIE ALTERNATEUR'),
		('RADIATEUR','RADIATEUR'),
		('BOUCHON RADIATEUR','BOUCHON RADIATEUR'),
		('ACCOUPLEMENT HYDRAULIQUE','ACCOUPLEMENT HYDRAULIQUE'),
		('VENTILATEUR','VENTILATEUR'),
	)
PIECE_RECHANGE_MOTEUR = (
		('FILTRE A HUILE','FILTRE A HUILE'),
		('FILTRE A AIR','FILTRE A AIR'),
		('FILTRE A CARBURANT','FILTRE A CARBURANT'),
		('FILTRE HABITACLE','FILTRE HABITACLE'),
		('BOUGIE','BOUGIE'),
		('INJECTEUR','INJECTEUR'),
		('COURROIE DIRECTION','COURROIE DIRECTION'),
		('COURROIE DISTRIBUTION','COURROIE DISTRIBUTION'),
		('POMPE A HUILE','POMPE A HUILE'),
		('TURBO COMPRESSEUR','TURBO COMPRESSEUR'),
		('SUPPORT MOTEUR','SUPPORT MOTEUR'),
		('COURROIE COMPRESSEUR','COURROIE COMPRESSEUR'),
		('TENDEUR DISTRIBUTION','TENDEUR DISTRIBUTION'),
		('NEZ INJECTEUR','NEZ INJECTEUR'),
		('FILTRE A CARBURANT  16405-01T0A','FILTRE A CARBURANT  16405-01T0A'),
		('FILTRE A CARBURANT  16405-02N0A','FILTRE A CARBURANT  16405-02N0A'),
		('INJECTEUR COMPLET','INJECTEUR COMPLET'),
        ('POMPE A CARBURANT','POMPE A CARBURANT'),
        ('COURROIE DE DISTRIBUTION','COURROIE DE DISTRIBUTION'),
        ('TENDEUR ALTERNATEUR','TENDEUR ALTERNATEUR'),


	)
PIECE_RECHANGE_TRANSMISSION = (
		('KIT ROULEMENT DE ROUE AVANT DROIT','KIT ROULEMENT DE ROUE AVANT DROIT'),
		('KIT ROULEMENT DE ROUE AVANT GAUCHE','KIT ROULEMENT DE ROUE AVANT GAUCHE'),
		('GOUJON DE ROUE AVANT','GOUJON DE ROUE AVANT'),
		('CROISILLON','CROISILLON'),
		('CROISILLON 1','CROISILLON 1'),
        ('SOUFFLET DE TRANSMISSION','SOUFFLET DE TRANSMISSION'),
        ('KIT DE ROULEMENT ROUE ARRIERE','KIT DE ROULEMENT ROUE ARRIERE'),
        ('PALIER DE TRANSMISSION','PALIER DE TRANSMISSION'),
        ('ECROU DE ROUE ARRIERE','ECROU DE ROUE ARRIERE'),
        ('GOUJON DE ROUE ARRIERE','GOUJON DE ROUE ARRIERE'),
        ('KIT DE ROULEMENT ROUE AVANT DROITE','KIT DE ROULEMENT ROUE AVANT DROITE'),
        ('KIT DE ROULEMENT ROUE AVANT GAUCHE','KIT DE ROULEMENT ROUE AVANT GAUCHE'),
        ('MOYEU AVANT GAUCHE','MOYEU AVANT GAUCHE'),
        ('ECROU DE ROUE AVANT','ECROU DE ROUE AVANT'),


	)
PIECE_REVISION_MOTEUR = (
		('POCHETTE DE JOINT','POCHETTE DE JOINT'),
		('JOINT DE CULASSE','JOINT DE CULASSE'),
		('SEGMENTS','SEGMENTS'),
		('BOURRAGE MOTEUR BOUR04403','BOURRAGE MOTEUR BOUR04403'),
		('RETIENT HUILE','RETIENT HUILE'),
		('COUSSINET PALIER','COUSSINET PALIER'),
		('COUSSINET BIELLE','COUSSINET BIELLE'),
		('BOURRAGE MOTEUR ','BOURRAGE MOTEUR '),
		('CHEMISE(JEU DE 4 PCES)','CHEMISE(JEU DE 4 PCES)'),
        ('PISTON(SANS SEGMENT)','PISTON(SANS SEGMENT)'),
        ('CHEMISE (JEU DE 4 PIECES)','CHEMISE (JEU DE 4 PIECES)'),
        ('PISTON (SANS SEGMENT)','PISTON (SANS SEGMENT)'),
        ('ROULEMENT MOYEU ARRIERE','ROULEMENT MOYEU ARRIERE'),
        ('GOUJON DE ROUE ARRIERE','GOUJON DE ROUE ARRIERE'),
        ('CROISILLON 2','CROISILLON 2'),
        ('CROISILLON 1','CROISILLON 1'),
        ('BOURRAGE MOTEUR','BOURRAGE MOTEUR'),
        ('BIELLE MOTEUR','BIELLE MOTEUR'),
        ('COUSSINET LATERAL','COUSSINET LATERAL'),


	)

ANNEE_DEBUT_FABRICATION_VEHICULE = (
		('2002','2002'),
		('2003','2003'),
		('2004','2004'),
		('2005','2005'),
		('2006','2006'),
		('2007','2007'),
		('2008','2008'),
		('2009','2009'),
		('2010','2010'),
		('2011','2011'),
		('2012','2012'),
		('2013','2013'),
		('2014','2014'),
		('2015','2015'),
		('2016','2016'),
		('2017','2017'),
	)

ANNEE_FIN_FABRICATION_VEHICULE = (
		('2002','2002'),
		('2003','2003'),
		('2004','2004'),
		('2005','2005'),
		('2006','2006'),
		('2007','2007'),
		('2008','2008'),
		('2009','2009'),
		('2010','2010'),
		('2011','2011'),
		('2012','2012'),
		('2013','2013'),
		('2014','2014'),
		('2015','2015'),
		('2016','2016'),
		('2017','2017'),

	)

TYPE_VEHICULE = (
		('VOITURE','VOITURE'),
		('JEEP','JEEP'),
		('MINIBUS','MINIBUS'),
		('BUS', 'BUS'),

	)
TYPE_CAMION = (
		('4X4','4X4'),
		('6X6','6X6'),

	)



MODELE = (
		('PATROL V8-SE','PATROL V8-SE'),
		('PATROL PICK UP SIMPLE CABINE','PATROL PICK UP SIMPLE CABINE'),
		('PATROL 10 PLACE ','PATROL 10 PLACE '),
		('NAVARA PICK UP ','NAVARA PICK UP '),
		('HARDBODY','HARDBODY'),
		('URVAN','URVAN'),
		('CIVILIAN','CIVILIAN'),
		('QUASHKA','QUASHKA'),
		('JUKE','JUKE'),
		('PATHFINDER','PATHFINDER'),
		('SENTRA','SENTRA'),
		('ALMERA','ALMERA'),
		('SUNNY','SUNNY'),
		('X TRAIL 2X4','X TRAIL 2X4'),
		('X TRAIL 4X4','X TRAIL 4X4'),
		('GRANDTIGER PICK UP','GRANDTIGER PICK UP'),
		('TERRALORD LUXURY','TERRALORD LUXURY'),
		('Z100','Z100'),
		('GRAND TIGER SUV','GRAND TIGER SUV'),
		('26-28','26-28'),
		('26-36','26-36'),
		('33-330','33-330'),
		('ACTROS','ACTROS'),
		('LAND CRUISER RUNNER','LAND CRUISER RUNNER'),
		('LAND CRUISER','LAND CRUISER'),
		('NOAH','NOAH'),
		('ALLEX','ALLEX'),
		('YARIS','YARIS'),
		('HILUX DOUBLE CABINE','HILUX DOUBLE CABINE'),
		('COROLLA','COROLLA'),
		('CAMRY','CAMRY'),
		('RAV4','RAV4'),
		('PRADO','PRADO'),
		('HIACE','HIACE'),


	)


NOMBRE_PIED = (
		('20','20'),
		('40','40'),
		('2X20','2X20'),

	)
MARQUE_VOITURE = (

		('MERCEDES', 'MERCEDES'),
        ('NISSAN', 'NISSAN'),
        ('TOYOTA', 'TOYOTA'),
        ('ZOTYE', 'ZOTYE'),
        ('ZX AUTO', 'ZX AUTO'),
        ('MAN', 'MAN'),
        ('IVECO', 'IVECO'),

	)

MODELE_VOITURE = (

		('PATROL V8-SE', 'PATROL V8-SE'),
        ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'),
        ('PATROL 10 PLACE', 'PATROL 10 PLACE'),
        ('NAVARA PICK UP', 'NAVARA PICK UP'),
        ('HARDBODY', 'HARDBODY'),
        ('URVAN', 'URVAN'),
        ('CIVILIAN', 'CIVILIAN'),
        ('QUASHKAI', 'QUASHKAI'),
        ('JUKE', 'JUKE'),
        ('PATHFINDER', 'PATHFINDER'),
        ('SENTRA', 'SENTRA'),
        ('ALMERA', 'ALMERA'),
        ('SUNNY', 'SUNNY'),
        ('X TRAIL 2X4', 'X TRAIL 2X4'),
        ('X TRAIL 4X4', 'X TRAIL 4X4'),
        ('GRANDTIGER  PICK UP', 'GRANDTIGER  PICK UP'),
        ('TERRALORD LUXURY', 'TERRALORD LUXURY'),
        ('Z100', 'Z100'),
        ('GRAND TIGER SUV', 'GRAND TIGER SUV'),
        ('SPRINTER 313 CDI ','SPRINTER 313 CDI '),
		('SPRINTER 209','SPRINTER 209'),
	)

ETAT_VOITURE = (

		('NEUF', 'NEUF'),
		('OCCASION', 'OCCASION'),

	)
TYPE_USAGE = (

		('USAGE COMMERCIAL', 'USAGE COMMERCIAL'),
        ('USAGE PERSONNEL', 'USAGE PERSONNEL'),

	)

MARQUE_MOTO = (

		('TVS', 'TVS'),

	)

MODELE_MOTO = (

		('STAR HLX', 'STAR HLX'),
        ('ZT', 'ZT'),
        ('APACHE', 'APACHE'),
        ('KING DELUXE', 'KING DELUXE'),

	)

ETAT_MOTO = (

		('NEUF', 'NEUF'),
		('OCCASION', 'OCCASION'),

	)

PUISSANCE_MOTEUR = (

		('100CC', '100CC'),
		('125CC', '125CC'),
		('160CC', '160CC'),
		('180CC', '180CC'),
		('200CC', '200CC'),

	)

TYPE_DEMARRAGE = (

		('DEMARRAGE AU KICK', 'DEMARRAGE AU KICK'),
		('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE'),

	)
NOMBRE_CYLINDRE = (

		('6', '6'),
		('8', '8'),
		('10', '10'),

	)


MARQUE_BOUGIE = (

		('BOSCH', 'BOSCH'),
		('BERU', 'BERU'),
		('TOYOTA', 'TOYOTA'),
		('NJK', 'NJK'),

	)

ORDINAIRE_PLATINE = (

		('ORDINAIRE', 'ORDINAIRE'),
		('PLATINE', 'PLATINE'),

	)

NOMBRE_ELECTRODE = (

		('1', '1'),
		('2', '2'),
		('3', '3'),

	)


MARQUE_PNEU = (

		('GT RADIAL', 'GT RADIAL'),

	)


DIMENSION_PNEU = (

		('155/70R13','155/70R13'),
    ('165/70R13','165/70R13'),
    ('175/70R13','175/70R13'),
    ('185/70R13','185/70R13'),
    ('225/70R14','225/70R14'),
    ('165/65R14','165/65R14'),
    ('175/70R14','175/70R14'),
    ('175/70R15','175/70R15'),
    ('185/65R14','185/65R14'),
    ('185/70R14','185/70R14'),
    ('185/65R15','185/65R15'),
    ('195/70R14','195/70R14'),
    ('195/70R15','195/70R15'),
    ('185R14C','185R14C'),
    ('195R14C','195R14C'),
    ('145R12','145R12'),
    ('195/65R15','195/65R15'),
    ('215R14C','215R14C'),
    ('195/75R15C','195/75R15C'),
    ('205/55R16','205/55R16'),
    ('225/70R15','225/70R15'),
    ('205R14C','205R14C'),
    ('235/70R15','235/70R15'),
    ('195R15C','195R15C'),
    ('205/65R15','205/65R15'),
    ('205R15','205R15'),
    ('215R15','215R15'),
    ('225/70R15','225/70R15'),
    ('205/70R15C','205/70R15C'),
    ('215/65R16','215/65R16'),
    ('215/70R16','215/70R16'),
    ('215/80R15','215/80R15'),
    ('235/75R15','235/75R15'),
    ('205R16','205R16'),
    ('235/60R16','235/60R16'),
    ('225/70R16','225/70R16'),
    ('225/75R16','225/75R16'),
    ('235/70R16','235/70R16'),
    ('205/80R16','205/80R16'),
    ('265/70R15','265/70R15'),
    ('245/70R16','245/70R16'),
    ('245/75R16','245/75R16'),
    ('225/70R17','225/70R17'),
    ('225/60R17','225/60R17'),
    ('225/65R17','225/65R17'),
    ('235/65R17','235/65R17'),
    ('235/70R17','235/70R17'),
    ('255/55R17','255/55R17'),
    ('245/65R17','245/65R17'),
    ('245/70R17','245/70R17'),
    ('255/70R16','255/70R16'),
    ('650R16','650R16'),
    ('265/70R16','265/70R16'),
    ('255/55R18','255/55R18'),
    ('265/70R17','265/70R17'),
    ('275/60R17','275/60R17'),
    ('275/75R16','275/75R16'),
    ('750R16 LT','750R16 LT'),
    ('275/65R17','275/65R17'),
    ('825R16','825R16'),
    ('245/70R18','245/70R18'),
    ('235/70R18','235/70R18'),
    ('265/60R18','265/60R18'),
    ('1200R20','1200R20'),
    ('315/80R20','315/80R20'),
    ('315R20','315R20'),
    ('900R22.5','900R22.5'),
    ('1100R20','1100R20'),
    ('1100R22.5','1100R22.5'),
    ('1200R22.5','1200R22.5'),
    ('295/80R22.5','295/80R22.5'),
    ('900R20','900R20'),
    ('1400R20','1400R20'),
    ('1400R22.5','1400R22.5'),


	)



MARQUE_BATTERIE = (

		('TUDOR', 'TUDOR'),
		('LARGESTAR', 'LARGESTAR'),
		('AK', 'AK'),

	)


CAPACITE_BATTERIE = (

		('100AH','100AH'),
        ('105AH','105AH'),
        ('120AH','120AH'),
        ('150AH','150AH'),
        ('180AH','180AH'),
        ('200AH','200AH'),
        ('220AH','220AH'),
        ('40AH ','40AH'),
        ('45AH ','45AH'),
        ('60AH ','60AH'),
        ('62AH ','62AH'),
        ('65AH ','65AH'),
        ('66AH ','66AH'),
        ('70AH ','70AH'),
        ('75AH ','75AH'),
        ('80AH ','80AH'),
        ('85AH ','85AH'),
        ('85AH ','85AH'),
        ('88AH ','88AH'),
        ('90AH ','90AH'),
        ('95AH ','95AH'),


	)



GARANTIE_BATTERIE = (

		('3 MOIS', '3 MOIS'),

	)


ENTRETIEN_BATTERIE = (

		('AVEC ENTRETIEN', 'AVEC ENTRETIEN'),
		('SANS ENTRETIEN', 'SANS ENTRETIEN'),

	)



FORME_BATTERIE = (

		('N', 'N'),
		('NL', 'NL'),
		('DIN', 'DIN'),

	)



FORMAT_BATTERIE = (

		('STANDARD', 'STANDARD'),
		('PETIT FORMAT', 'PETIT FORMAT'),

	)