PIECE_RECHANGE_MODELE = (
		('D-MAX TFR54','D-MAX TFR54'),
        ('D-MAX TFR85','D-MAX TFR85'),
        ('L300','L300'),
        ('PATROL Y61','PATROL Y61'),
        ('HILUX','HILUX'),
        ('LAND CRUISER PRADO','LAND CRUISER PRADO'),
	)
PIECE_RECHANGE_MARQUE = (
		('ISUZU','ISUZU'),
		('MITSUBISHI','MITSUBISHI'),
        ('NISSAN','NISSAN'),
        ('TOYOTA','TOYOTA'),

	)



PIECE_DIRECTION_SUSPENSION = (
		('AMORTISSEUR ARRIERE DROIT','AMORTISSEUR ARRIERE DROIT'),
		('AMORTISSEUR ARRIERE GAUCHE','AMORTISSEUR ARRIERE GAUCHE'),
		('AMORTISSEUR AVANT DROIT','AMORTISSEUR AVANT DROIT'),
		('AMORTISSEUR AVANT GAUCHE','AMORTISSEUR AVANT GAUCHE'),
		('AMORTISSEUR DE DIRECTION','AMORTISSEUR DE DIRECTION'),
		('BIELLETTE STABILISATRICE ARRIERE DROITE','BIELLETTE STABILISATRICE ARRIERE DROITE'),
		('BIELLETTE STABILISATRICE ARRIERE GAUCHE','BIELLETTE STABILISATRICE ARRIERE GAUCHE'),
		('BIELLETTE STABILISATRICE AVANT DROITE','BIELLETTE STABILISATRICE AVANT DROITE'),
        ('BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE','BIELLETTE STABILISATRICE AVANT GAUCHE + DROITE'),
		('BIELLETTE STABILISATRICE AVANT GAUCHE','BIELLETTE STABILISATRICE AVANT GAUCHE'),
		('BRAS DE SUSPENSION INFERIEURE DROITE','BRAS DE SUSPENSION INFERIEURE DROITE'),
		('BRAS DE SUSPENSION INFERIEURE GAUCHE','BRAS DE SUSPENSION INFERIEURE GAUCHE'),
		('BRAS DE SUSPENSION SUPERIEUR DROITE','BRAS DE SUSPENSION SUPERIEUR DROITE'),
		('BRAS DE SUSPENSION SUPERIEUR GAUCHE','BRAS DE SUSPENSION SUPERIEUR GAUCHE'),
        ('BRAS DE SUSPENSION SUPERIEURE DROITE','BRAS DE SUSPENSION SUPERIEURE DROITE'),
        ('BRAS DE SUSPENSION SUPERIEURE GAUCHE','BRAS DE SUSPENSION SUPERIEURE GAUCHE'),
		('CREMAILLEUR DE DIRECTION','CREMAILLEUR DE DIRECTION'),
        ('DEMARREUR','DEMARREUR'),
		('LAME MAITRESSE','LAME MAITRESSE'),
		('POMPE DE DIRECTION','POMPE DE DIRECTION'),
		('ROTULE DE DIRECTION EXTERIEURE DROIT','ROTULE DE DIRECTION EXTERIEURE DROIT'),
        ('ROTULE DE DIRECTION EXTERIEURE DROITE','ROTULE DE DIRECTION EXTERIEURE DROITE'),
		('ROTULE DE DIRECTION EXTERIEURE GAUCHE','ROTULE DE DIRECTION EXTERIEURE GAUCHE'),
        ('ROTULE DE DIRECTION EXTERIEURE GAUCHE','ROTULE DE DIRECTION EXTERIEURE GAUCHE'),
		('ROTULE DE DIRECTION INFERIEUR DROIT','ROTULE DE DIRECTION INFERIEUR DROIT'),
		('ROTULE DE DIRECTION INFERIEUR GAUCHE','ROTULE DE DIRECTION INFERIEUR GAUCHE'),
        ('ROTULE DE DIRECTION INFERIEURE DROITE','ROTULE DE DIRECTION INFERIEURE DROITE'),
        ('ROTULE DE DIRECTION INFERIEURE GAUCHE','ROTULE DE DIRECTION INFERIEURE GAUCHE'),
		('ROTULE DE SUSPENSION INFERIEURE DROITE','ROTULE DE SUSPENSION INFERIEURE DROITE'),
		('ROTULE DE SUSPENSION INFERIEURE GAUCHE','ROTULE DE SUSPENSION INFERIEURE GAUCHE'),
		('ROTULE DE SUSPENSION SUPERIEURE DROITE','ROTULE DE SUSPENSION SUPERIEURE DROITE'),
		('ROTULE DE SUSPENSION SUPERIEURE GAUCHE','ROTULE DE SUSPENSION SUPERIEURE GAUCHE'),
		('SILEMBLOC BARRE STABILISATRICE ARRIERE','SILEMBLOC BARRE STABILISATRICE ARRIERE'),
        ('SILEMBLOC BARRE STABILISATRICE AV 48632-60020','SILEMBLOC BARRE STABILISATRICE AV 48632-60020'),
        ('SILEMBLOC BARRE STABILISATRICE AV 48815-60180','SILEMBLOC BARRE STABILISATRICE AV 48815-60180'),
        ('SILEMBLOC BARRE STABILISATRICE AV','SILEMBLOC BARRE STABILISATRICE AV'),
		('SILEMBLOC BARRE STABILISATRICE AVANT','SILEMBLOC BARRE STABILISATRICE AVANT'),
		('SILEMBLOC BRAS DE STABILISATION AV','SILEMBLOC BRAS DE STABILISATION AV'),
		('SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1','SILEMBLOC BRAS DE SUSPENSION INFERIEUR 1'),
        ('SILEMBLOC BRAS DE SUSPENSION SUPERIEUR','SILEMBLOC BRAS DE SUSPENSION SUPERIEUR'),
		('SILEMBLOC BRAS DE SUSPENSION SUPERIEURE','SILEMBLOC BRAS DE SUSPENSION SUPERIEURE'),
		('SILEMBLOC LAME INFERIEURE','SILEMBLOC LAME INFERIEURE'),
		('SILEMBLOC LAME SUPERIEURE','SILEMBLOC LAME SUPERIEURE'),
        ('SOUFFLET DE DIRECTION','SOUFFLET DE DIRECTION'),
	)
PIECE_RECHANGE_CARROSSERIE = (
		('BALAI ESSUIE GLACE AVANT','BALAI ESSUIE GLACE AVANT'),
		('FEU ARRIERE DROIT','FEU ARRIERE DROIT'),
		('FEU ARRIERE GAUCHE','FEU ARRIERE GAUCHE'),
		('PHARE AVANT DROIT','PHARE AVANT DROIT'),
		('PHARE AVANT GAUCHE','PHARE AVANT GAUCHE'),
		('RETROVISEUR DROIT','RETROVISEUR DROIT'),
		('RETROVISEUR GAUCHE','RETROVISEUR GAUCHE'),


	)


PIECE_RECHANGE_ELECTRIQUE = (
		('ALTERNATEUR','ALTERNATEUR'),
        ('CONTACTEUR DE PRESSION D’HUILE','CONTACTEUR DE PRESSION D’HUILE'),
        ('CONTACTEUR PRESSION HUILE','CONTACTEUR PRESSION HUILE'),
		('DEMARREUR','DEMARREUR'),
        ('INTERRUPTEUR DE TEMPERATURE','INTERRUPTEUR DE TEMPERATURE'),
		('POMPE A VIDE ALTERNATEUR','POMPE A VIDE ALTERNATEUR'),
        ('RELAI DE DEMARRAGE','RELAI DE DEMARRAGE'),

	)
PIECE_RECHANGE_EMBRAYAGE = (
		('BUTEE EMBRAYAGE','BUTEE EMBRAYAGE'),
		('CYLINDRE EMETTEUR','CYLINDRE EMETTEUR'),
		('CYLINDRE RECEPTEUR','CYLINDRE RECEPTEUR'),
		('DISQUE EMBRAYAGE','DISQUE EMBRAYAGE'),
        ('KIT DE REPARATION CYLINDRE EMETTEUR','KIT DE REPARATION CYLINDRE EMETTEUR'),
        ('KIT DE REPARATION CYLINDRE RECEPTEUR','KIT DE REPARATION CYLINDRE RECEPTEUR'),
		('PLATEAU EMBRAYAGE','PLATEAU EMBRAYAGE'),
	)
PIECE_RECHANGE_FREINAGE = (
		('CYLINDRE DE ROUE ARRIERE DROITE','CYLINDRE DE ROUE ARRIERE DROITE'),
		('CYLINDRE DE ROUE ARRIERE GAUCHE','CYLINDRE DE ROUE ARRIERE GAUCHE'),
		('DISQUE DE FREIN AVANT','DISQUE DE FREIN AVANT'),
		('DISQUE/TAMBOUR DE FREIN ARRIERE','DISQUE/TAMBOUR DE FREIN ARRIERE'),
		('MAITRE CYLINDRE DE FREIN','MAITRE CYLINDRE DE FREIN'),
		('PLAQUETTE DE FREIN AVANT','PLAQUETTE DE FREIN AVANT'),
		('PLAQUETTE/MACHOIRE DE FREIN ARRIERE','PLAQUETTE/MACHOIRE DE FREIN ARRIERE'),
	)
TYPE_PIECE_REFROIDISSEMENT = (
		('ACCOUPLEMENT HYDRAULIQUE','ACCOUPLEMENT HYDRAULIQUE'),
		('BOUCHON RADIATEUR','BOUCHON RADIATEUR'),
		('COURROIE ALTERNATEUR','COURROIE ALTERNATEUR'),
		('POMPE A EAU','POMPE A EAU'),
		('RADIATEUR','RADIATEUR'),
		('THERMOSTAT','THERMOSTAT'),
		('VENTILATEUR','VENTILATEUR'),
	)
PIECE_RECHANGE_MOTEUR = (
		('COURROIE COMPRESSEUR','COURROIE COMPRESSEUR'),
        ('COURROIE DE DISTRIBUTION','COURROIE DE DISTRIBUTION'),
		('COURROIE DIRECTION','COURROIE DIRECTION'),
		('COURROIE DISTRIBUTION','COURROIE DISTRIBUTION'),
		('FILTRE A AIR','FILTRE A AIR'),
		('FILTRE A CARBURANT  16405-01T0A','FILTRE A CARBURANT  16405-01T0A'),
		('FILTRE A CARBURANT  16405-02N0A','FILTRE A CARBURANT  16405-02N0A'),
		('FILTRE A CARBURANT','FILTRE A CARBURANT'),
		('FILTRE A HUILE','FILTRE A HUILE'),
		('FILTRE HABITACLE','FILTRE HABITACLE'),
		('INJECTEUR COMPLET','INJECTEUR COMPLET'),
		('INJECTEUR','INJECTEUR'),
		('NEZ INJECTEUR','NEZ INJECTEUR'),
        ('POMPE A CARBURANT','POMPE A CARBURANT'),
		('POMPE A HUILE','POMPE A HUILE'),
		('SUPPORT MOTEUR','SUPPORT MOTEUR'),
        ('TENDEUR ALTERNATEUR','TENDEUR ALTERNATEUR'),
		('TENDEUR DISTRIBUTION','TENDEUR DISTRIBUTION'),
		('TURBO COMPRESSEUR','TURBO COMPRESSEUR'),
		('COURROIE POMPE ALERTE','COURROIE POMPE ALERTE'),


	)
PIECE_RECHANGE_TRANSMISSION = (

		('CROISILLON 1','CROISILLON 1'),
		('CROISILLON','CROISILLON'),
        ('ECROU DE ROUE ARRIERE','ECROU DE ROUE ARRIERE'),
        ('ECROU DE ROUE AVANT','ECROU DE ROUE AVANT'),
        ('GOUJON DE ROUE ARRIERE','GOUJON DE ROUE ARRIERE'),
		('GOUJON DE ROUE AVANT','GOUJON DE ROUE AVANT'),
        ('KIT DE ROULEMENT ROUE ARRIERE','KIT DE ROULEMENT ROUE ARRIERE'),
        ('KIT DE ROULEMENT ROUE AVANT DROITE','KIT DE ROULEMENT ROUE AVANT DROITE'),
        ('KIT DE ROULEMENT ROUE AVANT GAUCHE','KIT DE ROULEMENT ROUE AVANT GAUCHE'),
		('KIT ROULEMENT DE ROUE AVANT DROIT','KIT ROULEMENT DE ROUE AVANT DROIT'),
		('KIT ROULEMENT DE ROUE AVANT GAUCHE','KIT ROULEMENT DE ROUE AVANT GAUCHE'),
        ('MOYEU AVANT GAUCHE','MOYEU AVANT GAUCHE'),
        ('PALIER DE TRANSMISSION','PALIER DE TRANSMISSION'),
        ('SOUFFLET DE TRANSMISSION','SOUFFLET DE TRANSMISSION'),

	)
PIECE_REVISION_MOTEUR = (
        ('BIELLE MOTEUR','BIELLE MOTEUR'),
		('BOURRAGE MOTEUR ','BOURRAGE MOTEUR '),
		('BOURRAGE MOTEUR BOUR04403','BOURRAGE MOTEUR BOUR04403'),
        ('BOURRAGE MOTEUR','BOURRAGE MOTEUR'),
        ('CHEMISE (JEU DE 4 PIECES)','CHEMISE (JEU DE 4 PIECES)'),
		('CHEMISE(JEU DE 4 PCES)','CHEMISE(JEU DE 4 PCES)'),
		('COUSSINET BIELLE','COUSSINET BIELLE'),
        ('COUSSINET LATERAL','COUSSINET LATERAL'),
		('COUSSINET PALIER','COUSSINET PALIER'),
        ('CROISILLON 1','CROISILLON 1'),
        ('CROISILLON 2','CROISILLON 2'),
        ('GOUJON DE ROUE ARRIERE','GOUJON DE ROUE ARRIERE'),
		('JOINT DE CULASSE','JOINT DE CULASSE'),
        ('PISTON (SANS SEGMENT)','PISTON (SANS SEGMENT)'),
        ('PISTON(SANS SEGMENT)','PISTON(SANS SEGMENT)'),
		('POCHETTE DE JOINT','POCHETTE DE JOINT'),
		('RETIENT HUILE','RETIENT HUILE'),
        ('ROULEMENT MOYEU ARRIERE','ROULEMENT MOYEU ARRIERE'),
		('SEGMENTS','SEGMENTS'),


	)

ANNEE_DEBUT_FABRICATION_VEHICULE = (
		('2002','2002'),
		('2003','2003'),
		('2004','2004'),
		('2005','2005'),
		('2006','2006'),
		('2007','2007'),
		('2008','2008'),
		('2009','2009'),
		('2010','2010'),
		('2011','2011'),
		('2012','2012'),
		('2013','2013'),
		('2014','2014'),
		('2015','2015'),
		('2016','2016'),
		('2017','2017'),
	)

ANNEE_FIN_FABRICATION_VEHICULE = (
		('2002','2002'),
		('2003','2003'),
		('2004','2004'),
		('2005','2005'),
		('2006','2006'),
		('2007','2007'),
		('2008','2008'),
		('2009','2009'),
		('2010','2010'),
		('2011','2011'),
		('2012','2012'),
		('2013','2013'),
		('2014','2014'),
		('2015','2015'),
		('2016','2016'),
		('2017','2017'),

	)

TYPE_VEHICULE = (
		('VOITURE','VOITURE'),
		('JEEP','JEEP'),
		('MINIBUS','MINIBUS'),

	)

TYPE_VOITURE = (
		('VOITURE','VOITURE'),
		('JEEP','JEEP'),
		('MINIBUS','MINIBUS'),
		('BUS', 'BUS'),

	)

TYPE_CAMION = (
		('4X4','4X4'),
		('6X6','6X6'),

	)

MODELE_VEHICULE = (
		('ALLEX','ALLEX'),
		('CAMRY','CAMRY'),
		('COROLLA','COROLLA'),
		('HIACE','HIACE'),
		('HILUX DOUBLE CABINE','HILUX DOUBLE CABINE'),
		('LAND CRUISER','LAND CRUISER'),
		('LAND CRUISER RUNNER','LAND CRUISER RUNNER'),
		('NOAH','NOAH'),
		('PRADO','PRADO'),
		('RAV4','RAV4'),
		('YARIS','YARIS'),
	)

MODELE_MOTEUR = (
		('26-28','26-28'),
		('26-36','26-36'),
		('33-330','33-330'),
		('ACTROS','ACTROS'),
	)

MODELE = (


		('ALLEX','ALLEX'),
		('ALMERA','ALMERA'),
		('CAMRY','CAMRY'),
		('CIVILIAN','CIVILIAN'),
		('COROLLA','COROLLA'),
		('GRAND TIGER SUV','GRAND TIGER SUV'),
		('GRANDTIGER PICK UP','GRANDTIGER PICK UP'),
		('HARDBODY','HARDBODY'),
		('HIACE','HIACE'),
		('HILUX DOUBLE CABINE','HILUX DOUBLE CABINE'),
		('JUKE','JUKE'),
		('LAND CRUISER','LAND CRUISER'),
		('NAVARA PICK UP ','NAVARA PICK UP '),
		('PATHFINDER','PATHFINDER'),
		('PATROL 10 PLACE ','PATROL 10 PLACE '),
		('PATROL PICK UP SIMPLE CABINE','PATROL PICK UP SIMPLE CABINE'),
		('PATROL V8-SE','PATROL V8-SE'),
		('PRADO','PRADO'),
		('QUASHKA','QUASHKA'),
		('RAV4','RAV4'),
		('SENTRA','SENTRA'),
		('SUNNY','SUNNY'),
		('TERRALORD LUXURY','TERRALORD LUXURY'),
		('URVAN','URVAN'),
		('X TRAIL 2X4','X TRAIL 2X4'),
		('X TRAIL 4X4','X TRAIL 4X4'),
		('Z100','Z100'),

	)


NOMBRE_PIED = (
		('20','20'),
		('40','40'),
		('2X20','2X20'),

	)
MARQUE_VOITURE = (

        ('IVECO', 'IVECO'),
        ('MAN', 'MAN'),
		('MERCEDES', 'MERCEDES'),
        ('NISSAN', 'NISSAN'),
        ('TOYOTA', 'TOYOTA'),
        ('ZOTYE', 'ZOTYE'),
        ('ZX AUTO', 'ZX AUTO'),

	)

MODELE_VOITURE = (

        ('ALMERA', 'ALMERA'),
        ('CIVILIAN', 'CIVILIAN'),
        ('GRAND TIGER SUV', 'GRAND TIGER SUV'),
        ('GRANDTIGER  PICK UP', 'GRANDTIGER  PICK UP'),
        ('HARDBODY', 'HARDBODY'),
        ('JUKE', 'JUKE'),
        ('NAVARA PICK UP', 'NAVARA PICK UP'),
        ('PATHFINDER', 'PATHFINDER'),
        ('PATROL 10 PLACE', 'PATROL 10 PLACE'),
        ('PATROL PICK UP SIMPLE CABINE', 'PATROL PICK UP SIMPLE CABINE'),
		('PATROL V8-SE', 'PATROL V8-SE'),
        ('QUASHKAI', 'QUASHKAI'),
        ('SENTRA', 'SENTRA'),
		('SPRINTER 209','SPRINTER 209'),
        ('SPRINTER 313 CDI ','SPRINTER 313 CDI '),
        ('SUNNY', 'SUNNY'),
        ('TERRALORD LUXURY', 'TERRALORD LUXURY'),
        ('URVAN', 'URVAN'),
        ('X TRAIL 2X4', 'X TRAIL 2X4'),
        ('X TRAIL 4X4', 'X TRAIL 4X4'),
        ('Z100', 'Z100'),
	)
MARQUE_CAMION=(

	('MERCEDES', 'MERCEDES'),

	)
MODELE_CAMION=(

	('26-28', '26-28'),
	('26-36', '26-36'),

	)
ETAT_VOITURE = (

		('NEUF', 'NEUF'),
		('OCCASION', 'OCCASION'),

	)
TYPE_USAGE = (

		('USAGE COMMERCIAL', 'USAGE COMMERCIAL'),
        ('USAGE PERSONNEL', 'USAGE PERSONNEL'),

	)

MARQUE_MOTO_2ROUES = (

		('TVS', 'TVS'),

	)


MARQUE_MOTO_3ROUES = (

		('TVS', 'TVS'),

	)


MODELE_MOTO_2ROUES = (

        ('APACHE', 'APACHE'),
		('STAR HLX', 'STAR HLX'),
        ('ZT', 'ZT'),

	)

MODELE_MOTO_3ROUES = (

        ('KING DELUXE', 'KING DELUXE'),

	)

ETAT_MOTO = (

		('NEUF', 'NEUF'),
		('OCCASION', 'OCCASION'),

	)

PUISSANCE_MOTEUR = (

		('100CC', '100CC'),
		('125CC', '125CC'),
		('160CC', '160CC'),
		('180CC', '180CC'),
		('200CC', '200CC'),

	)

PUISSANCE_MOTEUR_2ROUES = (

		('100CC', '100CC'),
		('125CC', '125CC'),
		('160CC', '160CC'),
		('180CC', '180CC'),

	)

PUISSANCE_MOTEUR_3ROUES = (
		('200CC', '200CC'),

	)

TYPE_DEMARRAGE_2ROUES = (

		('DEMARRAGE AU KICK', 'DEMARRAGE AU KICK'),
		('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE'),

	)

TYPE_DEMARRAGE_3ROUES = (
		('DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE', 'DEMARRAGE AU KICK ET DEMARRAGE  ELECTRONIQUE'),
	)

NOMBRE_CYLINDRE = (

		('6', '6'),
		('8', '8'),
		('10', '10'),

	)


MARQUE_BOUGIE = (

		('BERU', 'BERU'),
		('BOSCH', 'BOSCH'),
		('NJK', 'NJK'),
		('TOYOTA', 'TOYOTA'),

	)

ORDINAIRE_PLATINE = (

		('ORDINAIRE', 'ORDINAIRE'),
		('PLATINE', 'PLATINE'),

	)

NOMBRE_ELECTRODE = (

		('1', '1'),
		('2', '2'),
		('3', '3'),

	)


MARQUE_PNEU = (

		('GT RADIAL', 'GT RADIAL'),

	)


DIMENSION_PNEU = (

    ('1100R20','1100R20'),
    ('1100R22.5','1100R22.5'),
    ('1200R20','1200R20'),
    ('1200R22.5','1200R22.5'),
    ('1400R20','1400R20'),
    ('1400R22.5','1400R22.5'),
    ('145R12','145R12'),
		('155/70R13','155/70R13'),
    ('165/65R14','165/65R14'),
    ('165/70R13','165/70R13'),
    ('175/70R13','175/70R13'),
    ('175/70R14','175/70R14'),
    ('175/70R15','175/70R15'),
    ('185/65R14','185/65R14'),
    ('185/65R15','185/65R15'),
    ('185/70R13','185/70R13'),
    ('185/70R14','185/70R14'),
    ('185R14C','185R14C'),
    ('195/65R15','195/65R15'),
    ('195/70R14','195/70R14'),
    ('195/70R15','195/70R15'),
    ('195/75R15C','195/75R15C'),
    ('195R14C','195R14C'),
    ('195R15C','195R15C'),
    ('205/55R16','205/55R16'),
    ('205/65R15','205/65R15'),
    ('205/70R15C','205/70R15C'),
    ('205/80R16','205/80R16'),
    ('205R14C','205R14C'),
    ('205R15','205R15'),
    ('205R16','205R16'),
    ('215/65R16','215/65R16'),
    ('215/70R16','215/70R16'),
    ('215/80R15','215/80R15'),
    ('215R14C','215R14C'),
    ('215R15','215R15'),
    ('225/60R17','225/60R17'),
    ('225/65R17','225/65R17'),
    ('225/70R14','225/70R14'),
    ('225/70R15','225/70R15'),
    ('225/70R15','225/70R15'),
    ('225/70R16','225/70R16'),
    ('225/70R17','225/70R17'),
    ('225/75R16','225/75R16'),
    ('235/60R16','235/60R16'),
    ('235/65R17','235/65R17'),
    ('235/70R15','235/70R15'),
    ('235/70R16','235/70R16'),
    ('235/70R17','235/70R17'),
    ('235/70R18','235/70R18'),
    ('235/75R15','235/75R15'),
    ('245/65R17','245/65R17'),
    ('245/70R16','245/70R16'),
    ('245/70R17','245/70R17'),
    ('245/70R18','245/70R18'),
    ('245/75R16','245/75R16'),
    ('255/55R17','255/55R17'),
    ('255/55R18','255/55R18'),
    ('255/70R16','255/70R16'),
    ('265/60R18','265/60R18'),
    ('265/70R15','265/70R15'),
    ('265/70R16','265/70R16'),
    ('265/70R17','265/70R17'),
    ('275/60R17','275/60R17'),
    ('275/65R17','275/65R17'),
    ('275/75R16','275/75R16'),
    ('295/80R22.5','295/80R22.5'),
    ('315/80R20','315/80R20'),
    ('315R20','315R20'),
    ('650R16','650R16'),
    ('750R16 LT','750R16 LT'),
    ('825R16','825R16'),
    ('900R20','900R20'),
    ('900R22.5','900R22.5'),


	)



MARQUE_BATTERIE = (

		('AK', 'AK'),
		('LARGESTAR', 'LARGESTAR'),
		('TUDOR', 'TUDOR'),
	)


CAPACITE_BATTERIE = (
        ('40AH ','40AH'),
        ('45AH ','45AH'),
        ('60AH ','60AH'),
        ('62AH ','62AH'),
        ('65AH ','65AH'),
        ('66AH ','66AH'),
        ('70AH ','70AH'),
        ('75AH ','75AH'),
        ('80AH ','80AH'),
        ('85AH ','85AH'),
        ('85AH ','85AH'),
        ('88AH ','88AH'),
        ('90AH ','90AH'),
        ('95AH ','95AH'),
        ('100AH','100AH'),
        ('105AH','105AH'),
        ('120AH','120AH'),
        ('150AH','150AH'),
        ('180AH','180AH'),
        ('200AH','200AH'),
        ('220AH','220AH'),

	)



GARANTIE_BATTERIE = (

		('3 MOIS', '3 MOIS'),

	)


ENTRETIEN_BATTERIE = (

		('AVEC ENTRETIEN', 'AVEC ENTRETIEN'),
		('SANS ENTRETIEN', 'SANS ENTRETIEN'),

	)



FORME_BATTERIE = (

		('DIN', 'DIN'),
		('N', 'N'),
		('NL', 'NL'),

	)



FORMAT_BATTERIE = (

		('STANDARD', 'STANDARD'),
		('PETIT FORMAT', 'PETIT FORMAT'),

	)