TYPE_PEINTURE = (
		('PEINTURE A EAU','PEINTURE A EAU'),
		('PEINTURE A HUILE','PEINTURE A HUILE'),

	)


COMPOSITION_PEINTURE = (
		('EMAIL CELLULOSIQUE','EMAIL CELLULOSIQUE'),
		('EMAIL','EMAIL'),
		('LATEX ACRYLIQUE','LATEX ACRYLIQUE'),
		('LATEX','LATEX'),


	)


TEINTE_PEINTURE= (
        ('AUCUNE TEINTE','AUCUNE TEINTE'),
		('CLAIR','CLAIR'),
		('MAT','MAT'),
		('PASTEL','PASTEL'),
		('SATIN','SATIN'),
		('VIF','VIF'),

	)

PEINTURE_SPECIALE= (
		('ANTIROUILLE FER','ANTIROUILLE FER'),
		('ANTIROUILLE PLOMB','ANTIROUILLE PLOMB'),
		('BOUCHE PORS','BOUCHE PORS'),
		('CHROMATE DE ZINC','CHROMATE DE ZINC'),
		('GALVA','GALVA'),
		('MASTIC','MASTIC'),
		('MENUICOL','MENUICOL'),
		('PEINTURE AU LARO','PEINTURE AU LARO'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('PRIMER SURFACER','PRIMER SURFACER'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),
		('SATIN','SATIN'),
		('VERNIS INT&EXT','VERNIS INT&EXT'),
		('VERNIS NOIR','VERNIS NOIR'),


	)

DOMAINE_APPLICATION= (
		('APPRET MUR','APPRET MUR'),
        ('BOUCHE TROIS','BOUCHE TROIS'),
		('MENUISERIE','MENUISERIE'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('PROTECTION BOIS','PROTECTION BOIS'),
		('PROTECTION METAL','PROTECTION METAL'),
		('PROTECTION METAL','PROTECTION METAL'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),

	)


CARACTERISTIQUE_PEINTURE = (
		('PRIMAIRE','PRIMAIRE'),


	)

TYPE_BRIQUE = (
		('ARGILE STABILISE AU CIMENT','ARGILE STABILISE AU CIMENT'),

	)

LARGEUR_BRIQUE= (
		('220MM','220MM'),
		('140MM','140MM'),

	)

TYPE_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

DIMENSION_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

TYPE_MOELLON= (
		('CAILLASSE','CAILLASSE'),
		('MOELLON','MOELLON'),


	)

ESPACE= (
		('6M2','6M2'),
		('9M2','9M2'),
		('12M2','12M2'),


	)

PLAGE_SURFACE = (

		('<50M²', '<50M2'),
        ('50M²-100M²', '50M2-100M2'),
        ('100M²-150M²', '100M2-150M2'),
        ('150M²-200M²', '150M2-200M2'),
        ('>200M²', '>200M2'),

	)

SURFACE_DEPOT = (

        ('180M2', '180M2'),
	)

AVENUE_DEPOT = (

		('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL'),
	)

COMMUNE_DEPOT = (

		('LIMETE', 'LIMETE'),

	)

SURFACE_STAND = (

		('6M2', '6M2'),
        ('9M2', '9M2'),
        ('12M2', '12M2'),

	)

DUREE_MAXIMUM = (

		('4 JOURS', '4 JOURS'),

	)

TYPE_MOELLON = (

		('CAILLASSE', 'CAILLASSE'),
        ('MOELLON', 'MOELLON'),

	)

TONNAGE_CAMION = (

		('20T', '20T'),

	)

ZONE_LOCATION = (

		('INTRA-URBAIN', 'INTRA-URBAIN'),

	)
NOMBRE_PIED = (

		('20', '20'),
        ('40', '40'),
        ('2x20', '2x20'),

	)
QUALITE_DU_TERRAIN= (

		('ALCALINO-TERREUX','ALCALINO-TERREUX'),
		('ARGILEUX','ARGILEUX'),
		('MARECAGEUX','MARECAGEUX'),
		('SABLONEUX','SABLONEUX'),


	)
USAGE_DU_BATIMENT= (

		('COMMERCIAL LUXUEUX','COMMERCIAL LUXUEUX'),
		('COMMERCIAL ORDINAIRE','COMMERCIAL ORDINAIRE'),
		('ENTREPOT','ENTREPOT'),
		('RESIDENTIEL LUXUEUX','RESIDENTIEL LUXUEUX'),
		('RESIDENTIEL ORDINAIRE','RESIDENTIEL ORDINAIRE'),

	)
NOMBRE_ETAGE= (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
		('7','7'),
		('8','8'),
		('9','9'),
		('10','10'),


	)
NOMBRE_DE_PIECES= (
		('1 -10','1 -10'),
		('11 - 20','11 - 20'),
		('21 - 30','21 - 30'),
		('31 - 40','31 - 40'),
		('41 - 50','41 - 50'),
		('51 - 60','51 - 60'),
		('61 - 70','61 - 70'),
		('71 - 80','71 - 80'),
		('81 - 90','81 - 90'),
		('91 -100','91 -100'),

	)
TYPE_DE_TERRAIN= (
		('TERRAIN INCLINÉ','TERRAIN INCLINÉ'),
		('TERRAIN PLAT','TERRAIN PLAT'),

    )
TYPE_DE_ROUTE= (
		('ROUTE ASPHALTEE','ROUTE ASPHALTEE'),
		('ROUTE DE DESSERTE AGRICOLE','ROUTE DE DESSERTE AGRICOLE'),
		('ROUTE STABILISEE','ROUTE STABILISEE'),

	)
LARGEUR_DE_ROUTE= (
		('4M','4M'),
		('6M','6M'),


	)
COUCHE_DE_TOUT_VENANT= (
		('NON APPLICABLE','NON APPLICABLE'),
		('15M³ DE 0/31 SUR 10 M','15M3 DE 0/31 SUR 10 M'),



	)
COUCHE_DE_BETON= (
		('NON APPLICABLE','NON APPLICABLE'),
		('9M³ DE BETON SUR 10M','9M3 DE BETON SUR 10M'),


	)
COUCHE_DE_TERRE_JAUNE= (
		('NON APPLICABLE','NON APPLICABLE'),
		('15M³ DE TERRE JAUNE SUR 10M','15M3 DE TERRE JAUNE SUR 10M'),


	)
MATIERE_ROUTE= (
		('NON APPLICABLE','NON APPLICABLE'),
		('ASPHALTE','ASPHALTE'),
		('CIMENT','CIMENT'),



	)
CANALISATION_EAU= (
		('OUI','OUI'),

	)
NOMBRE_ETOILE = (

		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),

	)

ACCES_WIFI_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),

		)

PETIT_DEJEUNE_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),
		)


TYPE_LIT = (
		('LIT DOUBLE','LIT DOUBLE'),
		('LIT SIMPLE','LIT SIMPLE'),
		)





AVENUE_CHAMBRE = (
		('COLONEL EBEYA','COLONEL EBEYA'),
		('KASAI','KASAI'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('SENEGALAIS','SENEGALAIS'),
		('OUGANDA','OUGANDA'),

		)


COMMUNE_CHAMBRE = (
		('BANDALUNGWA','BANDALUNGWA'),
		('GOMBE','GOMBE'),
		('KASAVUBU','KASAVUBU'),
		('LIMETE','LIMETE'),
		)

DIMENSION_TRIPLEX= (

		('1220x2440MM','1220x2440MM'),


	)
TYPE_TRIPLEX= (

		('DOUBLE PRESS','DOUBLE PRESS'),

	)
EPAISSEUR_TRIPLEX= (

		('5MM','5MM'),
		('8MM','8MM'),
		('10MM','10MM'),

	)

