TYPE_PEINTURE = (
		('PEINTURE A EAU','PEINTURE A EAU'),
		('PEINTURE A HUILE','PEINTURE A HUILE'),

	)


COMPOSITION = (
		('LATEX ACRYLIQUE','LATEX ACRYLIQUE'),
		('LATEX','LATEX'),
		('EMAIL','EMAIL'),
		('EMAIL CELLULOSIQUE','EMAIL CELLULOSIQUE'),


	)


TEINTE= (
		('CLAIR','CLAIR'),
		('VIF','VIF'),
		('PASTEL','PASTEL'),
		('SATIN','SATIN'),
		('MAT','MAT'),
        ('AUCUNE TEINTE','AUCUNE TEINTE'),

	)

PEINTURE_SPECIALE= (
		('MASTIC','MASTIC'),
		('GALVA','GALVA'),
		('ANTIROUILLE FER','ANTIROUILLE FER'),
		('SATIN','SATIN'),
		('ANTIROUILLE PLOMB','ANTIROUILLE PLOMB'),
		('CHROMATE DE ZINC','CHROMATE DE ZINC'),
		('VERNIS INT&EXT','VERNIS INT&EXT'),
		('BOUCHE PORS','BOUCHE PORS'),
		('VERNIS NOIR','VERNIS NOIR'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),
		('PRIMER SURFACER','PRIMER SURFACER'),
		('MENUICOL','MENUICOL'),
		('PEINTURE AU LARO','PEINTURE AU LARO'),


	)

DOMAINE_APPLICATION= (
		('APPRET MUR','APPRET MUR'),
		('PROTECTION METAL','PROTECTION METAL'),
		('PROTECTION BOIS','PROTECTION BOIS'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),
		('MENUISERIE','MENUISERIE'),
		('PROTECTION METAL','PROTECTION METAL'),
        ('BOUCHE TROIS','BOUCHE TROIS'),
	)


CARACTERISTIQUE = (
		('PRIMAIRE','PRIMAIRE'),


	)

TYPE_BRIQUE = (
		('ARGILE STABILISE AU CIMENT','ARGILE STABILISE AU CIMENT'),

	)

LARGEUR_BRIQUE= (
		('220mm','220mm'),
		('140mm','140mm'),

	)

TYPE_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

DIMENSION_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

TYPE_MOELLON= (
		('CAILLASSE','CAILLASSE'),
		('MOELLON','MOELLON'),


	)

ESPACE= (
		('6m²','6m²'),
		('9m²','9m²'),
		('12m²','12m²'),


	)

PLAGE_SURFACE = (

		('<50M²', '<50M²'),
        ('50M²-100M²', '50M²-100M²'),
        ('100M²-150M²', '100M²-150M²'),
        ('150M²-200M²', '150M²-200M²'),
        ('>200M²', '>200M²'),

	)

AVENUE = (

		('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL'),
        ('7EME RUE', '7EME RUE'),
	)

COMMUNE = (

		('LIMETE', 'LIMETE'),

	)

SURFACE_STAND = (

		('6M2', '6M2'),
        ('9M2', '9M2'),
        ('12M2', '12M2'),

	)

DUREE_MAXIMUM = (

		('4 JOURS', '4 JOURS'),

	)

TYPE_MOELLON = (

		('CAILLASSE', 'CAILLASSE'),
        ('MOELLON', 'MOELLON'),

	)

TONNAGE = (

		('20T', '20T'),

	)

ZONE = (

		('INTRA-URBAIN', 'INTRA-URBAIN'),

	)
NOMBRE_PIED = (

		('20', '20'),
        ('40', '40'),
        ('2x20', '2x20'),

	)
QUALITE_DU_TERRAIN= (

		('SABLONEUX','SABLONEUX'),
		('ARGILEUX','ARGILEUX'),
		('MARECAGEUX','MARECAGEUX'),
		('ALCALINO-TERREUX','ALCALINO-TERREUX'),


	)
USAGE_DU_BATIMENT= (

		('ENTREPOT','ENTREPOT'),
		('COMMERCIAL ORDINAIRE','COMMERCIAL ORDINAIRE'),
		('COMMERCIAL LUXUEUX','COMMERCIAL LUXUEUX'),
		('RESIDENTIEL ORDINAIRE','RESIDENTIEL ORDINAIRE'),
		('RESIDENTIEL LUXUEUX','RESIDENTIEL LUXUEUX'),

	)
NOMBRE_ETAGE= (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
		('7','7'),
		('8','8'),
		('9','9'),
		('10','10'),


	)
NOMBRE_DE_PIECES= (
		('1 -10','1 -10'),
		('11 - 20','11 - 20'),
		('21 - 30','21 - 30'),
		('31 - 40','31 - 40'),
		('41 - 50','41 - 50'),
		('51 - 60','51 - 60'),
		('61 - 70','61 - 70'),
		('71 - 80','71 - 80'),
		('81 - 90','81 - 90'),
		('91 -100','91 -100'),
		('1 -10','1 -10'),


	)
TYPE_DE_TERRAIN= (
		('TERRAIN INCLINÉ','TERRAIN INCLINÉ'),
		('TERRAIN PLAT','TERRAIN PLAT'),

    )
TYPE_DE_ROUTE= (
		('ROUTE DE DESSERTE AGRICOLE','ROUTE DE DESSERTE AGRICOLE'),
		('ROUTE ASPHALTEE','ROUTE ASPHALTEE'),
		('ROUTE STABILISEE','ROUTE STABILISEE'),

	)
LARGEUR_DE_ROUTE= (
		('4M','4M'),
		('6M','6M'),


	)
COUCHE_DE_TOUT_VENANT= (
		('NON APPLICABLE','NON APPLICABLE'),
		('15M³ DE 0/31 SUR 10 M','15M³ DE 0/31 SUR 10 M'),



	)
COUCHE_DE_BETON= (
		('NON APPLICABLE','NON APPLICABLE'),
		('9M³ DE BETON SUR 10M','9M³ DE BETON SUR 10M'),


	)
COUCHE_DE_TERRE_JAUNE= (
		('NON APPLICABLE','NON APPLICABLE'),
		('15M³ DE TERRE JAUNE SUR 10M','15M³ DE TERRE JAUNE SUR 10M'),


	)
MATIERE= (
		('NON APPLICABLE','NON APPLICABLE'),
		('ASPHALTE','ASPHALTE'),
		('CIMENT','CIMENT'),



	)
CANALISATION_EAU= (
		('OUI','OUI'),

	)
NOMBRE_ETOILE = (

		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),

	)

ACCES_WIFI_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),

		)

PETIT_DEJEUNE_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),
		)


TYPE_LIT = (
		('LIT SIMPLE','LIT SIMPLE'),
		('LIT DOUBLE','LIT DOUBLE'),
		)





AVENUE_1 = (
		('SENEGALAIS','SENEGALAIS'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('KASAI','KASAI'),
		('COLONEL EBEYA','COLONEL EBEYA'),

		)


COMMUNE = (
		('GOMBE','GOMBE'),
		('KASAVUBU','KASAVUBU'),
		('LIMETE','LIMETE'),
		('BANDALUNGWA','BANDALUNGWA'),
		)
DIMENSION_TRIPLEX= (

		('1220x2440MM','1220x2440MM'),


	)
TYPE_TRIPLEX= (

		('DOUBLE PRESS','DOUBLE PRESS'),

	)
EPAISSEUR_TRIPLEX= (

		('10MM','10MM'),
		('5MM','5MM'),
		('8MM','8MM'),
		('10MM','10MM'),

	)