TYPE_PEINTURE = (
		('PEINTURE A EAU','PEINTURE A EAU'),
		('PEINTURE A HUILE','PEINTURE A HUILE'),

	)


COMPOSITION = (
		('LATEX ACRYLIQUE','LATEX ACRYLIQUE'),
		('LATEX','LATEX'),
		('EMAIL','EMAIL'),
		('EMAIL CELLULOSIQUE','EMAIL CELLULOSIQUE'),


	)


TEINTE= (
		('CLAIR','CLAIR'),
		('VIF','VIF'),
		('PASTEL','PASTEL'),
		('SATIN','SATIN'),
		('MAT','MAT'),
        ('AUCUNE TEINTE','AUCUNE TEINTE'),

	)

PEINTURE_SPECIALE= (
		('MASTIC','MASTIC'),
		('GALVA','GALVA'),
		('ANTIROUILLE FER','ANTIROUILLE FER'),
		('SATIN','SATIN'),
		('ANTIROUILLE PLOMB','ANTIROUILLE PLOMB'),
		('CHROMATE DE ZINC','CHROMATE DE ZINC'),
		('VERNIS INT&EXT','VERNIS INT&EXT'),
		('BOUCHE PORS','BOUCHE PORS'),
		('VERNIS NOIR','VERNIS NOIR'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),
		('PRIMER SURFACER','PRIMER SURFACER'),
		('MENUICOL','MENUICOL'),
		('PEINTURE AU LARO','PEINTURE AU LARO'),


	)

DOMAINE_APPLICATION= (
		('APPRET MUR','APPRET MUR'),
		('PROTECTION METAL','PROTECTION METAL'),
		('PROTECTION BOIS','PROTECTION BOIS'),
		('PEINTURE PISCINE','PEINTURE PISCINE'),
		('RUSTINE D’ALUMINIUM','RUSTINE D’ALUMINIUM'),
		('MENUISERIE','MENUISERIE'),
		('PROTECTION METAL','PROTECTION METAL'),
        ('BOUCHE TROIS','BOUCHE TROIS'),
	)


CARACTERISTIQUE = (
		('PRIMAIRE','PRIMAIRE'),


	)

TYPE_BRIQUE = (
		('ARGILE STABILISE AU CIMENT','ARGILE STABILISE AU CIMENT'),

	)

LARGEUR_BRIQUE= (
		('220mm','220mm'),
		('140mm','140mm'),

	)

TYPE_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

DIMENSION_CARREAU = (
		('CARREAU SOL','CARREAU SOL'),
		('FAIENCE','FAIENCE'),
		('PLACAGE SOL','PLACAGE SOL'),

	)

TYPE_MOELLON= (
		('CAILLASSE','CAILLASSE'),
		('MOELLON','MOELLON'),


	)

ESPACE= (
		('6m²','6m²'),
		('9m²','9m²'),
		('12m²','12m²'),


	)

PLAGE_SURFACE = (

		('<50M²', '<50M²'),
        ('50M²-100M²', '50M²-100M²'),
        ('100M²-150M²', '100M²-150M²'),
        ('150M²-200M²', '150M²-200M²'),
        ('>200M²', '>200M²'),

	)

AVENUE = (

		('7EME RUE INDUSTRIEL', '7EME RUE INDUSTRIEL'),

	)

COMMUNE = (

		('LIMETE', 'LIMETE'),

	)

SURFACE_STAND = (

		('6M²', '6M²'),
        ('9M²', '9M²'),
        ('12M²', '12M²'),

	)

DUREE_MAXIMUM = (

		('4 JOURS', '4 JOURS'),

	)

TYPE_MOELLON = (

		('CAILLASSE', 'CAILLASSE'),
        ('MOELLON', 'MOELLON'),

	)

TONNAGE = (

		('20T', '20T'),

	)

ZONE = (

		('INTRA-URBAIN', 'INTRA-URBAIN'),

	)
NOMBRE_PIED = (

		('20', '20'),
        ('40', '40'),
        ('2x20', '2x20'),

	)

