

SECTEUR = (

		('AUTRES SERVICES','AUTRES SERVICES'),
		('BATIMENTS ET TRAVAUX PUBLIC','BATIMENTS ET TRAVAUX PUBLIC'),
		('BRASSERIES ET AGROALIMENTAIRE','BRASSERIES ET AGROALIMENTAIRE'),
		('DISTRIBUTION ET COMMERCE','DISTRIBUTION ET COMMERCE'),
		('ENERGIE ET HYDROCARBURES','ENERGIE ET HYDROCARBURES'),
		('ETABLISSEMENT PUBLIC','ETABLISSEMENT PUBLIC'),
		('FINANCE ET BANQUES','FINANCE ET BANQUES'),
		('INDUSTRIES','INDUSTRIES'),
		('MINES','MINES'),
		('ORGANISME INTERNATIONAL','ORGANISME INTERNATIONAL'),
		('REPRESENTATION DIPLOMATIQUE','REPRESENTATION DIPLOMATIQUE'),
		('TELECOMMUNICATIONS ET TIC','TELECOMMUNICATIONS ET TIC'),
		('TRANSPORTS ET LOGISTIQUE','TRANSPORTS ET LOGISTIQUE'),
	)

TYPE_INTERVENTION = (
		('CONTINUE','CONTINUE'),
		('PONCTUELLE','PONCTUELLE'),

	)


NOMBRE_EMPLOYES = (
		('0-6','0-6'),
		('6-10','6-10'),
		('10–20','10–20'),
		('20–50','20–50'),
		('50–100','50–100'),
		('100 OU PLUS','100 OU PLUS'),

	)
TITRE= (
		('LES PRINCIPALES PREOCCUPATIOS DES CONGOLAIS','LES PRINCIPALES PREOCCUPATIONS DES CONGOLAIS'),
		('STATISTIQUES SUR LES MEDIAS A KINSHASA','STATISTIQUES SUR LES MEDIAS A KINSHASA'),

	)