NIVEAU_COURS = (
		('AVANCÉ','AVANCÉ'),
		('SEMI-INTERMEDIAIRE','SEMI-INTERMEDIAIRE'),
		('INTERMEDIAIRE','INTERMEDIAIRE'),
		('DEBUTANT','DEBUTANT'),
	)

LANGUE_COURS = (
		('ANGLAIS','ANGLAIS'),

	)

LANGUE_NATIONALE = (
		('LINGALA','LINGALA'),
		('KIKONGO','KIKONGO'),
		('SWAHILI','SWAHILI'),
		('TSHILUBA','TSHILUBA'),

	)

LANGUES = (
		('ANGLAIS-FRANCAIS','ANGLAIS-FRANCAIS'),
		('ANGLAIS-LINGALA','ANGLAIS-LINGALA'),
		('ALLEMAND-FRANCAIS','ALLEMAND-FRANCAIS'),
		('PORTUGAIS-FRANCAIS','PORTUGAIS-FRANCAIS'),
		('ESPAGNOL-FRANCAIS','ESPAGNOL-FRANCAIS'),
        ('SWAHILI-FRANCAIS','SWAHILI-FRANCAIS'),
        ('LINGALA-FRANCAIS','LINGALA-FRANCAIS'),
        ('LINGALA-ANGLAIS','LINGALA-ANGLAIS'),
        ('KIKONGO-FRANCAIS','KIKONGO-FRANCAIS'),
        ('TSHILUBA-FRANCAIS','TSHILUBA-FRANCAIS'),
        ('TSHILUBA-ANGLAIS','TSHILUBA-ANGLAIS'),
        ('KIKONGO-ANGLAIS','KIKONGO-ANGLAIS'),
 		('SWAHILI-ANGLAIS','SWAHILI-ANGLAIS'),

	)

LANGUES_INTERPRETARIAT = (
		('ANGLAIS-FRANCAIS','ANGLAIS-FRANCAIS'),
		('PORTUGAIS-FRANCAIS','PORTUGAIS-FRANCAIS'),
		('ALLEMAND-FRANCAIS','ALLEMAND-FRANCAIS'),
		('ESPAGNOL-FRANCAIS','ESPAGNOL-FRANCAIS'),
		('SWAHILI-FRANCAIS','SWAHILI-FRANCAIS'),
 		('SWAHILI-ANGLAIS','SWAHILI-ANGLAIS'),
        ('LINGALA-FRANCAIS','LINGALA-FRANCAIS'),
        ('LINGALA-ANGLAIS','LINGALA-ANGLAIS'),
        ('KIKONGO-FRANCAIS','KIKONGO-FRANCAIS'),
        ('KIKONGO-ANGLAIS','KIKONGO-ANGLAIS'),
        ('TSHILUBA-FRANCAIS','TSHILUBA-FRANCAIS'),
        ('TSHILUBA-ANGLAIS','TSHILUBA-ANGLAIS'),

	)
TYPE_DOCUMENT = (
		('GENERAL','GENERAL'),
		('TECHNIQUE','TECHNIQUE'),
	)

TYPE_NETTOYAGE = (
		('APPARTEMENT','APPARTEMENT'),
		('BUREAUX','BUREAUX'),
		('BUREAUX + SANITAIRES','BUREAUX + SANITAIRES'),
		('HOTEL','HOTEL'),
		('NETTOYAGE APRES CHANTIER','NETTOYAGE APRES CHANTIER'),
		('SANITAIRES','SANITAIRES'),
	)

TYPE_SERVICE_TRAITEUR = (
		('BUFFET','BUFFET'),
		('COCKTAIL','COCKTAIL'),

		('PAUSE CAFÉ','PAUSE CAFÉ'),
	)


TYPE_ABONNEMENT = (
		('JOURNAL','JOURNAL'),

	)

TYPE_INSERTION = (
		('JOURNAL','JOURNAL'),

	)

PERIODICITE_PARUTION = (
		('HEBDOMADAIRE','HEBDOMADAIRE'),

	)

DUREE_ABONNEMENT = (
		('3 MOIS','3 MOIS'),
		('6 MOIS','6 MOIS'),
		('12 MOIS','12 MOIS'),

	)


TIRAGE = (
		('1500','1500'),


	)

DIMENSION = (
		('1 PAGE COULEUR','1 PAGE COULEUR'),
		('1 PAGE NB','1 PAGE NB'),
		('1/2 PAGE COULEUR','1/2 PAGE COULEUR'),
		('1/2 PAGE NB','1/2 PAGE NB'),
		('1/4 PAGE NB','1/4 PAGE NB'),
		('LA UNE','LA UNE'),
		('PUBLI REPORTAGE','PUBLI REPORTAGE'),
		('PUBLICATION DOCUMENT','PUBLICATION DOCUMENT'),

	)


CHOIX_ENTREE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('7','7'),

	)

CHOIX_PLATS = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('8','8'),

	)

CHOIX_DE_LEGUMES = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),

	)

CHOIX_ACCOMPAGNEMENT = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)

CHOIX_DESSERT = (
		('0','0'),
		('1','1'),
		('2','2')
	)

CHOIX_AMUSE_GUEULE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
		('7','7'),
		('8','8'),
		('9','9'),
		('10','10'),
		('11','11'),
		('12','12'),
		('13','13'),
		('14','14'),
		('15','15'),

	)

CHOIX_BOISSON_FROIDE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)
CHOIX_BOISSON_CHAUDE= (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)

CHOIX_BOISSON_ALCOOLISEE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)


CHOIX_VIENNOISERIE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),

	)


TYPE_GARDIENNAGE = (
		('BATIMENTS ET TRAVAUX PUBLIC','BATIMENTS ET TRAVAUX PUBLIC'),
		('BRASSERIES ET AGROALIMENTAIRE','BRASSERIES ET AGROALIMENTAIRE'),
		('DISTRIBUTION ET COMMERCE','DISTRIBUTION ET COMMERCE'),
		('FINANCE ET BANQUES','FINANCE ET BANQUES'),
		('INDUSTRIES ','INDUSTRIES '),
		('MINES','MINES'),
		('ENERGIE ET HYDROCARBURES','ENERGIE ET HYDROCARBURES'),
		('TELECOMMUNICATIONS ET TIC','TELECOMMUNICATIONS ET TIC'),
		('TRANSPORTS ET LOGISTIQUE','TRANSPORTS ET LOGISTIQUE'),
		('AUTRES SERVICES','AUTRES SERVICES'),
		('ETABLISSEMENT PUBLIC','ETABLISSEMENT PUBLIC'),
		('REPRESENTATION DIPLOMATIQUE','REPRESENTATION DIPLOMATIQUE'),
		('ORGANISME INTERNATIONAL','ORGANISME INTERNATIONAL'),
		('SECURITE RAPPROCHEE','SECURITE RAPPROCHEE'),


	)

TYPE_SERVICE_ASSAINISSEMENT=(
		('NETTOYAGE BUREAUX','NETTOYAGE BUREAUX'),


	)

PERIODE_SERVICE=(
		('JOURNEE','JOURNEE'),
		('NUIT','NUIT'),

	)

FREQUENCE=(
		('1 FOIS/SEMAINE','1 FOIS/SEMAINE'),
		('2 FOIS/SEMAINE','2 FOIS/SEMAINE'),
		('3 FOIS/SEMAINE','3 FOIS/SEMAINE'),

	)

PAIEMENT=(
		('MENSUEL','MENSUEL'),

	)

TYPE_PRODUIT=(
		('EAU DE JAVEL','EAU DE JAVEL'),
		('BACTEROL','BACTEROL'),
		('CREOLINE','CREOLINE'),
		('ESPRIT DE SEL','ESPRIT DE SEL'),
		('INSECTICIDE','INSECTICIDE'),
		('RATICIDE','RATICIDE'),

	)
TYPE_ASSAINISSEMENT=(
		('DESINSECTISATION','DESINSECTISATION'),
		('DERATISATION','DERATISATION'),
		('NETTOYAGE','NETTOYAGE'),
		('NETTOYAGE APRES CHANTIER','NETTOYAGE APRES CHANTIER'),
		('DESINFECTION','DESINFECTION'),
	)


TYPE_SERVICE_SPLIT=(
		('INSTALLATION SPLIT','INSTALLATION SPLIT'),
		('ENTRETIEN SPLIT','ENTRETIEN SPLIT'),

			)

NOMBRE_JOUR = (
		('1-7 JOURS','1-7 JOURS'),
		('8-15 JOURS','8-15 JOURS'),
		('16-21 JOURS','16-21 JOURS'),
		('22-30 JOURS','22-30 JOURS'),
		('31-45 JOURS','31-45 JOURS'),
		('46-60 JOURS','46-60 JOURS'),
		('61-90 JOURS','61-90 JOURS'),
		('91-180 JOURS','91-180 JOURS'),
	)

TRANCHE_AGE = (
		('0-55 ANS','0-55 ANS'),
		('55-65 ANS','55-65 ANS'),
		('65 ANS ET PLUS','65 ANS ET PLUS'),
	)



NOMBRE_ETOILE = (

		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),

	)

ACCES_WIFI_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),

		)

PETIT_DEJEUNE_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),
		)


TYPE_LIT = (
		('SIMPLE','SIMPLE'),
		('DOUBLE','DOUBLE'),
		)





AVENUE = (
		('SENEGALAIS','SENEGALAIS'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('COLONNEL EBEYA','COLONNEL EBEYA'),

		)


COMMUNE = (
		('GOMBE','GOMBE'),
		('KASAVUBU','KASAVUBU'),
		('LIMETE','LIMETE'),
		('BANDALUNGWA','BANDALUNGWA'),
		)





SUPERFICIE	= (
		('140 M2','140 M2'),
		('71,5 M2','71,5 M2'),
		('72 M2','72 M2'),


		)
MICRO_GRATUIT= (
		('OUI','OUI'),
		('NON','NOM'),


		)
RETRO_PROJECTEUR = (
		('OUI','OUI'),
		('NON','NON'),

		)
BAFFLE_GRATUIT= (
		('OUI','OUI'),
		('NON','NON'),

		)

NOMBRE_PERSONNES= (
		('1','1'),
		('1<','1<'),

		)


PERIODE_SERVICE= (
		('JOUR','JOUR'),
		('NUIT','NUIT'),

		)

PAYS_SOURCE = (
		('FRANCE','FRANCE'),

		)

VILLE_DESTINATION = (
		('KINSHASA','KINSHASA'),

		)


SUR_PLACE=(
		('SUR PLACE','SUR PLACE'),
		('A CONVENIR','A CONVENIR'),

		)

FREQUENCE_EVACUATION=(
		('1 FOIS/SEMAINE','1 FOIS/SEMAINE'),
		('2 FOIS/SEMAINE','2 FOIS/SEMAINE'),
		('3 FOIS/SEMAINE','3 FOIS/SEMAINE'),

		)
TYPE_REPRODUCTION=(
		('DOUBLURE CLE SIMPLE','DOUBLURE CLE SIMPLE'),
		('DOUBLURE CONTACT VEHICULE','DOUBLURE CONTACT VEHICULE'),
		('REPRODUCTION CLE MEMOIRE VEHICULE','REPRODUCTION CLE MEMOIRE VEHICULE'),

		)
