NIVEAU_COURS = (
		('AVANCÉ','AVANCÉ'),
		('SEMI-INTERMEDIAIRE','SEMI-INTERMEDIAIRE'),
		('INTERMEDIAIRE','INTERMEDIAIRE'),
		('DEBUTANT','DEBUTANT'),
	)

LANGUE_COURS = (
		('ANGLAIS','ANGLAIS'),

	)

LANGUE_NATIONALE = (
		('KIKONGO','KIKONGO'),
		('LINGALA','LINGALA'),
		('SWAHILI','SWAHILI'),
		('TSHILUBA','TSHILUBA'),

	)

LANGUES = (
		('ALLEMAND-FRANCAIS','ALLEMAND-FRANCAIS'),
		('ANGLAIS-FRANCAIS','ANGLAIS-FRANCAIS'),
		('ANGLAIS-LINGALA','ANGLAIS-LINGALA'),
		('ESPAGNOL-FRANCAIS','ESPAGNOL-FRANCAIS'),
        ('KIKONGO-ANGLAIS','KIKONGO-ANGLAIS'),
        ('KIKONGO-FRANCAIS','KIKONGO-FRANCAIS'),
        ('LINGALA-ANGLAIS','LINGALA-ANGLAIS'),
        ('LINGALA-FRANCAIS','LINGALA-FRANCAIS'),
		('PORTUGAIS-FRANCAIS','PORTUGAIS-FRANCAIS'),
 		('SWAHILI-ANGLAIS','SWAHILI-ANGLAIS'),
        ('SWAHILI-FRANCAIS','SWAHILI-FRANCAIS'),
        ('TSHILUBA-ANGLAIS','TSHILUBA-ANGLAIS'),
        ('TSHILUBA-FRANCAIS','TSHILUBA-FRANCAIS'),

	)

LANGUES_INTERPRETARIAT = (
		('ALLEMAND-FRANCAIS','ALLEMAND-FRANCAIS'),
		('ANGLAIS-FRANCAIS','ANGLAIS-FRANCAIS'),
		('ESPAGNOL-FRANCAIS','ESPAGNOL-FRANCAIS'),
        ('KIKONGO-ANGLAIS','KIKONGO-ANGLAIS'),
        ('KIKONGO-FRANCAIS','KIKONGO-FRANCAIS'),
        ('LINGALA-ANGLAIS','LINGALA-ANGLAIS'),
        ('LINGALA-FRANCAIS','LINGALA-FRANCAIS'),
		('PORTUGAIS-FRANCAIS','PORTUGAIS-FRANCAIS'),
 		('SWAHILI-ANGLAIS','SWAHILI-ANGLAIS'),
		('SWAHILI-FRANCAIS','SWAHILI-FRANCAIS'),
        ('TSHILUBA-ANGLAIS','TSHILUBA-ANGLAIS'),
        ('TSHILUBA-FRANCAIS','TSHILUBA-FRANCAIS'),

	)
TYPE_DOCUMENT = (
		('GENERAL','GENERAL'),
		('TECHNIQUE','TECHNIQUE'),
	)

TYPE_NETTOYAGE = (
		('APPARTEMENT','APPARTEMENT'),
		('BUREAUX','BUREAUX'),
		('BUREAUX + SANITAIRES','BUREAUX + SANITAIRES'),
		('HOTEL','HOTEL'),
		('NETTOYAGE APRES CHANTIER','NETTOYAGE APRES CHANTIER'),
		('SANITAIRES','SANITAIRES'),
	)

TYPE_SERVICE_TRAITEUR = (
		('BUFFET','BUFFET'),
		('COCKTAIL','COCKTAIL'),
		('PAUSE CAFÉ','PAUSE CAFÉ'),
	)


TYPE_ABONNEMENT = (
		('JOURNAL','JOURNAL'),

	)

TYPE_INSERTION = (
		('JOURNAL','JOURNAL'),

	)

PERIODICITE_PARUTION = (
		('HEBDOMADAIRE','HEBDOMADAIRE'),

	)

DUREE_ABONNEMENT = (
		('3 MOIS','3 MOIS'),
		('6 MOIS','6 MOIS'),
		('12 MOIS','12 MOIS'),

	)


TIRAGE = (
		('1500','1500'),


	)


#/
DIMENSION = (
		('1 PAGE COULEUR','1 PAGE COULEUR'),
		('1 PAGE NB','1 PAGE NB'),
		('1/2 PAGE COULEUR','1/2 PAGE COULEUR'),
		('1/2 PAGE NB','1/2 PAGE NB'),
		('1/4 PAGE NB','1/4 PAGE NB'),
		('LA UNE','LA UNE'),
		('PUBLI REPORTAGE','PUBLI REPORTAGE'),
		('PUBLICATION DOCUMENT','PUBLICATION DOCUMENT'),

	)
#\

CHOIX_ENTREE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('7','7'),

	)

CHOIX_PLATS = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('8','8'),

	)

CHOIX_DE_LEGUMES = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),

	)

CHOIX_ACCOMPAGNEMENT = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)

CHOIX_DESSERT = (
		('0','0'),
		('1','1'),
		('2','2')
	)

CHOIX_AMUSE_GUEULE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
		('7','7'),
		('8','8'),
		('9','9'),
		('10','10'),
		('11','11'),
		('12','12'),
		('13','13'),
		('14','14'),
		('15','15'),

	)

CHOIX_BOISSON_FROIDE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)
CHOIX_BOISSON_CHAUDE= (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)

CHOIX_BOISSON_ALCOOLISEE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)


CHOIX_VIENNOISERIE = (
		('0','0'),
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),

	)


TYPE_GARDIENNAGE = (
		('AUTRES SERVICES','AUTRES SERVICES'),
		('BATIMENTS ET TRAVAUX PUBLIC','BATIMENTS ET TRAVAUX PUBLIC'),
		('BRASSERIES ET AGROALIMENTAIRE','BRASSERIES ET AGROALIMENTAIRE'),
		('DISTRIBUTION ET COMMERCE','DISTRIBUTION ET COMMERCE'),
		('ENERGIE ET HYDROCARBURES','ENERGIE ET HYDROCARBURES'),
		('ETABLISSEMENT PUBLIC','ETABLISSEMENT PUBLIC'),
		('FINANCE ET BANQUES','FINANCE ET BANQUES'),
		('INDUSTRIES ','INDUSTRIES '),
		('MINES','MINES'),
		('ORGANISME INTERNATIONAL','ORGANISME INTERNATIONAL'),
		('REPRESENTATION DIPLOMATIQUE','REPRESENTATION DIPLOMATIQUE'),
		('SECURITE RAPPROCHEE','SECURITE RAPPROCHEE'),
		('TELECOMMUNICATIONS ET TIC','TELECOMMUNICATIONS ET TIC'),
		('TRANSPORTS ET LOGISTIQUE','TRANSPORTS ET LOGISTIQUE'),


	)
REVETEMENT_CHAISE=(
		('TISSUS','TISSUS'),
		('CUIR','CUIR'),
	)



TYPE_SERVICE_ASSAINISSEMENT=(
		('NETTOYAGE BUREAUX','NETTOYAGE DE BUREAUX'),
		('BUREAU ORDINAIRE','BUREAU ORDINAIRE'),
		('APRES CHANTIER','APRES CHANTIER'),
		('FAÇADE IMMEUBLE','FAÇADE IMMEUBLE'),
		('PARQUET EN BOIS','PARQUET EN BOIS'),
		('GRANITO','GRANITO'),
		('TAPIS','TAPIS'),

	)

SPECIFICATION_ASSAINISSEMENT=(
		('NON APPLICABLE','NON APPLICABLE'),
		('VITRE','VITRE'),
		('ALUCOBONDE','ALUCOBONDE'),
		('PEINTURE','PEINTURE'),
		('CARRELAGE','CARRELAGE'),
		('GRANITO QUARTZ','GRANITO QUARTZ'),
		('GRATTAGE','GRATTAGE'),
		('VITRE','VITRE'),
)

PERIODE_SERVICE=(
		('JOURNEE','JOURNEE'),
		('NUIT','NUIT'),

	)

FREQUENCE=(
		('1 FOIS/SEMAINE','1 FOIS/SEMAINE'),
		('2 FOIS/SEMAINE','2 FOIS/SEMAINE'),
		('3 FOIS/SEMAINE','3 FOIS/SEMAINE'),

	)

PAIEMENT=(
		('MENSUEL','MENSUEL'),

	)

TYPE_PRODUIT=(
		('EAU DE JAVEL','EAU DE JAVEL'),
		('BACTEROL','BACTEROL'),
		('CREOLINE','CREOLINE'),
		('ESPRIT DE SEL','ESPRIT DE SEL'),
		('INSECTICIDE','INSECTICIDE'),
		('RATICIDE','RATICIDE'),

	)
TYPE_ASSAINISSEMENT=(
		('DESINSECTISATION','DESINSECTISATION'),
		('DERATISATION','DERATISATION'),
		('NETTOYAGE','NETTOYAGE'),
		('NETTOYAGE APRES CHANTIER','NETTOYAGE APRES CHANTIER'),
		('DESINFECTION','DESINFECTION'),
        ('NETTOYAGE BUREAUX','NETTOYAGE DE BUREAUX'),
		('FAÇADE IMMEUBLE','FAÇADE IMMEUBLE'),
		('PARQUET EN BOIS','PARQUET EN BOIS'),
		('GRANITO','GRANITO'),
		('TAPIS','TAPIS'),
	)


TYPE_SERVICE_SPLIT=(
		('INSTALLATION SPLIT','INSTALLATION DES SPLIT'),
		('ENTRETIEN SPLIT','ENTRETIEN DES SPLIT'),

			)

NOMBRE_JOUR = (
		('1-5 JOURS','1-5 JOURS'),
		('1-7 JOURS','1-7 JOURS'),
		('6-7 JOURS','6-7 JOURS'),
		('8-10 JOURS','8-10 JOURS'),
		('8-15 JOURS','8-15 JOURS'),
		('11-15 JOURS','11-15 JOURS'),
		('16-21 JOURS','16-21 JOURS'),
		('22-30 JOURS','22-30 JOURS'),
		('31-45 JOURS','31-45 JOURS'),
		('46-60 JOURS','46-60 JOURS'),
		('61-90 JOURS','61-90 JOURS'),
		('91-180 JOURS','91-180 JOURS'),

	)

TRANCHE_AGE = (
		('0-54 ANS','0-54 ANS'),
		('55-64 ANS','55-64 ANS'),
		('65-69 ANS','65-69 ANS'),
	)



NOMBRE_ETOILE = (

		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),

	)

ACCES_WIFI_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),

		)

PETIT_DEJEUNE_GRATUIT = (
		('OUI','OUI'),
		('NON','NON'),
		)


TYPE_LIT = (
		('SIMPLE','SIMPLE'),
		('DOUBLE','DOUBLE'),
		)

AVENUE_GYM= (
		('COLONNEL EBEYA','COLONNEL EBEYA'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('SENEGALAIS','SENEGALAIS'),
		('OUGANDA','OUGANDA'),

		)




AVENUE = (
		('COLONNEL EBEYA','COLONNEL EBEYA'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('SENEGALAIS','SENEGALAIS'),

		)

AVENUE_SALLE_CONF = (
		('COLONNEL EBEYA','COLONNEL EBEYA'),
		('KASAVUBU','KASAVUBU'),
		('LUAMBO MAKIADI','LUAMBO MAKIADI'),
		('SENEGALAIS','SENEGALAIS'),
		('OUGANDA','OUGANDA'),

		)

COMMUNE = (
		('BANDALUNGWA','BANDALUNGWA'),
		('GOMBE','GOMBE'),
		('KASAVUBU','KASAVUBU'),
		('LIMETE','LIMETE'),
		)





SUPERFICIE	= (
		('71,5 M2','71,5 M2'),
		('72 M2','72 M2'),
		('140 M2','140 M2'),


		)


SUPERFICIE_SALLE_CONF=	(
		('28 M2','28 M2'),
		('50 M2','50 M2'),
		('65 M2','65 M2'),
		('66 M2','66 M2'),
		('71,5 M2','71,5 M2'),
		('72 M2','72 M2'),
		('140 M2','140 M2'),
		('146 M2','146 M2'),
		('435 M2','435 M2'),

		)

MICRO_GRATUIT= (
		('OUI','OUI'),
		('NON','NOM'),


		)
RETRO_PROJECTEUR = (
		('OUI','OUI'),
		('NON','NON'),

		)
BAFFLE_GRATUIT= (
		('OUI','OUI'),
		('NON','NON'),

		)

NOMBRE_PERSONNES= (
		('1','1'),
		('1<','1<'),

		)


PERIODE_SERVICE= (
		('JOUR','JOUR'),
		('NUIT','NUIT'),

		)

PAYS_SOURCE = (
		('FRANCE','FRANCE'),

		)

VILLE_DESTINATION = (
		('KINSHASA','KINSHASA'),

		)


SUR_PLACE=(
		('A CONVENIR','A CONVENIR'),
		('SUR PLACE','SUR PLACE'),

		)

FREQUENCE_EVACUATION=(
		('1 FOIS/SEMAINE','1 FOIS/SEMAINE'),
		('2 FOIS/SEMAINE','2 FOIS/SEMAINE'),
		('3 FOIS/SEMAINE','3 FOIS/SEMAINE'),

		)
TYPE_REPRODUCTION=(
		('DOUBLURE CLE SIMPLE','DOUBLURE POUR CLE SIMPLE'),
		('DOUBLURE CONTACT VEHICULE','DOUBLURE POUR CONTACT VEHICULE'),
		('REPRODUCTION CLE MEMOIRE VEHICULE','REPRODUCTION DE CLE MEMOIRE VEHICULE'),

		)
