
PAYS_SOURCE = (

		('FRANCE','FRANCE'),

	)

VILLE_DE_DESTINATION = (
		('KINSHASA','KINSHASA'),

		)

TONNAGE = (
		('20T','20T'),


	)

CAPACITE_MAX = (
		('20T','20T'),


	)

LIEU_DEPART=(
		('KINSHASA','KINSHASA'),



	)

LIEU_DESTINATION = (
		('KANANGA','KANANGA'),
		('MBUJI MAYI ','MBUJI MAYI '),
		('KIKWIT','KIKWIT'),
		('TSHIKAPA','TSHIKAPA'),


	)
POIDS_BIEN = (

		('0 - 300 KG', '0 - 300 KG'),
        ('300 KG <', '300 KG <'),

	)

ASSURANCE = (

		('OUI', 'OUI'),
        ('NON', 'NON'),

	)

DUREE_LOCATION = (

		('DEMI-JOURNEE(4H)', 'DEMI-JOURNEE(4H)'),
        ('JOURNEE(8H)', 'JOURNEE(8H)'),

	)
ZONEDUREE_LOCATION = (

		('INTRA-URBAIN', 'INTRA-URBAIN'),


	)

VILLE_DEPART= (
		('KINSHASA','KINSHASA'),



	)
VILLE_DESTINATION= (
		('KISANGANI','KISANGANI'),
		('GOMA','GOMA'),
		('BUNIA','BUNIA'),
		('ISIRO','ISIRO'),
		('BUKAVU','BUKAVU'),
		('LODJA','LODJA'),
		('LUBUMBASHI','LUBUMBASHI'),
		('MBUJI MAYI','MBUJI MAYI'),
		('KANANGA','KANANGA'),
		('MBANDAKA','MBANDAKA'),
		('GEMENA','GEMENA'),
		('KINDU','KINDU'),
		('TSHIKAPA','TSHIKAPA'),
		('MATADI','MATADI'),
		('BOMA','BOMA'),
		('MOANDA','MOANDA'),
		('KIKWIT','KIKWIT'),
		('BANDUNDU','BANDUNDU'),
		('BENI','BENI'),
		('BUTEMBO','BUTEMBO'),
		('KALEMIE','KALEMIE'),
		('LIKASI','LIKASI'),
		('KOLWEZI','KOLWEZI'),
		('BOENDE','BOENDE'),
		('DUNGU','DUNGU'),
		('UVIRA','UVIRA'),
		('GBADOLITE','GBADOLITE'),
		('KAMINA','KAMINA'),
        ('BUTA','BUTA'),
        ('FUNGURUME','FUNGURUME'),
        ('INONGO','INONGO'),
        ('KABINDA','KABINDA'),
        ('KASUMBALESA','KASUMBALESA'),
        ('KENGE','KENGE'),
        ('KILWA','KILWA'),
        ('KIMPESE','KIMPESE'),
        ('LISALA','LISALA'),
        ('LUKALA','LUKALA'),
        ('MAHAGI','MAHAGI'),
        ('MATADI','MATADI'),
        ('MBANZA-NGUNGU','MBANZA-NGUNGU'),
        ('MWENE-DITU','MWENE-DITU'),

    )
ZONE= (
		('ZONE 1','ZONE 1'),
		('ZONE 2 ','ZONE 2 '),
		('ZONE 3','ZONE 3'),
		('ZONE 4','ZONE 4'),
		('ZONE 5 ','ZONE 5'),
		('ZONE 6 ','ZONE 6'),

	)

POIDS= (

        ('0 à 0,5kgs','0 à 0,5kgs'),
        ('0,51 à 1kgs','0,51 à 1kgs'),
        ('0 à 1kgs','0 à 1kgs'),
        ('1,01 à 2kgs','1,01 à 2kgs'),
        ('2,01 à 3kgs','2,01 à 3kgs'),
        ('3,01 à 4kgs','3,01 à 4kgs'),
        ('4,01 à 5kgs','4,01 à 5kgs'),
        ('5,01 à 6kgs','5,01 à 6kgs'),
        ('6,01 à 7kgs','6,01 à 7kgs'),
        ('7,01 à 8 kgs','7,01 à 8 kgs'),
        ('8,01 à 9kgs','8,01 à 9kgs'),
        ('9,01 à 10kgs','9,01 à 10kgs'),
        ('10,01 à 11kgs','10,01 à 11kgs'),
        ('11,01 à 12kgs','11,01 à 12kgs'),
        ('12,01 à 13kgs','12,01 à 13kgs'),
        ('13,01 à 14kgs','13,01 à 14kgs'),
        ('14,01 à 15kgs','14,01 à 15kgs'),
        ('15,01 à 16kgs','15,01 à 16kgs'),
        ('16,01 à 17kgs','16,01 à 17kgs'),
        ('17,01 à 18kgs','17,01 à 18kgs'),
        ('18,01 à 19kgs','18,01 à 19kgs'),
        ('19,01 à 20kgs','19,01 à 20kgs'),
        ('0 à 0,5kgs','0 à 0,5kgs'),
        ('0,51 à 1kgs','0,51 à 1kgs'),
        ('1,01 à 1,5kgs','1,01 à 1,5kgs'),
        ('1,51 à 2kgs','1,51 à 2kgs'),
        ('2,01 à 2,5kgs','2,01 à 2,5kgs'),
        ('2,51 à 3kgs','2,51 à 3kgs'),
        ('3,01 à 3,5kgs','3,01 à 3,5kgs'),
        ('3,51 à 4kgs','3,51 à 4kgs'),
        ('4,01 à 4,5kgs','4,01 à 4,5kgs'),
        ('4,51 à 5kgs','4,51 à 5kgs'),
        ('5,01 à 5,5kgs','5,01 à 5,5kgs'),
        ('5,51 à 6kgs','5,51 à 6kgs'),
        ('6,01 à 6,5kgs','6,01 à 6,5kgs'),
        ('6,51 à 7kgs','6,51 à 7kgs'),
        ('7,01 à 7,5kgs','7,01 à 7,5kgs'),
        ('7,51 à 8kgs','7,51 à 8kgs'),
        ('8,01 à 8,5kgs','8,01 à 8,5kgs'),
        ('8,51 à 9kgs','8,51 à 9kgs'),
        ('9,01, à 9,5kgs','9,01, à 9,5kgs'),
        ('9,51 à 10kgs','9,51 à 10kgs'),
        ('10,01 à 11kgs','10,01 à 11kgs'),
        ('11,01 à 12kgs','11,01 à 12kgs'),
        ('12,01 à 13kgs','12,01 à 13kgs'),
        ('13,01 à 14kgs','13,01 à 14kgs'),
        ('14,01 à 15kgs','14,01 à 15kgs'),
        ('15,01 à 16kgs','15,01 à 16kgs'),
        ('16,01 à 17kgs','16,01 à 17kgs'),
        ('17,01 à 18kgs','17,01 à 18kgs'),
        ('18,01 à 19kgs','18,01 à 19kgs'),
        ('19,01 à 20kgs','19,01 à 20kgs'),
        ('20,01 à 21kgs','20,01 à 21kgs'),
        ('21,01 à 22kgs','21,01 à 22kgs'),
        ('22,01 à 23kgs','22,01 à 23kgs'),
        ('23,01 à 24kgs','23,01 à 24kgs'),
        ('24,01 à 25kgs','24,01 à 25kgs'),
        ('25,01 à 26kgs','25,01 à 26kgs'),
        ('26,01 à 27kgs','26,01 à 27kgs'),
        ('27,01 à 28kgs','27,01 à 28kgs'),
        ('28,01 à 29kgs','28,01 à 29kgs'),
        ('29,01 à 30kgs','29,01 à 30kgs'),
        ('30,01 à 31kgs','30,01 à 31kgs'),
        ('31,01 à 32kgs','31,01 à 32kgs'),
        ('32,01 à 33kgs','32,01 à 33kgs'),
        ('33,01 à 34kgs','33,01 à 34kgs'),
        ('34,01 à 35kgs','34,01 à 35kgs'),
        ('35,01 à 36kgs','35,01 à 36kgs'),
        ('36,01 à 37kgs','36,01 à 37kgs'),
        ('37,01 à 38kgs','37,01 à 38kgs'),
        ('38,01 à 39kgs','38,01 à 39kgs'),
        ('39,01 à 40kgs','39,01 à 40kgs'),
        ('40,01 à 41kgs','40,01 à 41kgs'),
        ('41,01 à 42kgs','41,01 à 42kgs'),
        ('42,01 à 43kgs','42,01 à 43kgs'),
        ('43,01 à 44kgs','43,01 à 44kgs'),
        ('44,01 à 45kgs','44,01 à 45kgs'),
        ('45,01 à 46kgs','45,01 à 46kgs'),
        ('46,01 à 47kgs','46,01 à 47kgs'),
        ('47,01 à 48kgs','47,01 à 48kgs'),
        ('48,01 à 49kgs','48,01 à 49kgs'),
        ('49,01 à 50kgs','49,01 à 50kgs'),
        ('50,01 à 51kgs','50,01 à 51kgs'),
        ('51,01 à 52kgs','51,01 à 52kgs'),
        ('52,01 à 53kgs','52,01 à 53kgs'),
        ('53,01 à 54kgs','53,01 à 54kgs'),
        ('54,01 à 55kgs','54,01 à 55kgs'),
        ('55,01 à 56kgs','55,01 à 56kgs'),
        ('56,01 à 57kgs','56,01 à 57kgs'),
        ('57,01 à 58kgs','57,01 à 58kgs'),
        ('58,01 à 59kgs','58,01 à 59kgs'),
        ('59,01 à 60kgs','59,01 à 60kgs'),
        ('60,01 à 61kgs','60,01 à 61kgs'),
        ('61,01 à 62kgs','61,01 à 62kgs'),
        ('62,01 à 63kgs','62,01 à 63kgs'),
        ('63,01 à 64kgs','63,01 à 64kgs'),
        ('64,01 à 65kgs','64,01 à 65kgs'),
        ('65,01 à 66kgs','65,01 à 66kgs'),
        ('66,01 à 67kgs','66,01 à 67kgs'),
        ('67,01 à 68kgs','67,01 à 68kgs'),
        ('68,01 à 69kgs','68,01 à 69kgs'),
        ('69,01 à 70kgs','69,01 à 70kgs'),
        ('1,01 à 1,5kgs1','01-1,5kgs'),
        ('1,51 à 2kgs','1,51-2kgs'),
        ('2,01 à 2,5kgs','2,01-2,5kgs'),
        ('2,51 à 3kgs','2,51-3kgs'),
        ('3,01 à 3,5kgs','3,01-3,5kgs'),
        ('3,51 à 4kgs','3,51-4kgs'),
        ('4,01 à 4,5kgs','4,01-4,5kgs'),
        ('4,51 à 5kgs','4,51-5kgs'),
        ('5,01 à 5,5kgs','5,01-5,5kgs'),
        ('5,51 à 6,0kgs','5,51-6,0kgs'),
        ('6,01 à 6,5 kgs','6,01-6,5 kgs'),
        ('6,51 à 7,0 kgs','6,51-7,0 kgs'),
        ('7,01 à 7,5 kgs','7,01-7,5 kgs'),
        ('7,51 à 8,0 kgs','7,51- 8,0 kgs'),
        ('8,01 à 8,5 kgs','8,01-8,5 kgs'),
        ('8,51 à 9,0 kgs','8,51-9,0 kgs'),
        ('9,01 à 9,5 kgs','9,01-9,5 kgs'),
        ('9,51 à 10 kgs','9,51-10 kgs'),



	)

DELAI_LIVRAISON= (
		('1 JOUR','1 JOUR'),
		('2 JOURS','2 JOURS'),
		('3 JOURS','3 JOURS'),
		('4 JOURS','4 JOURS'),
		('5 JOURS','5 JOURS'),
		('6 JOURS','6 JOURS'),
		('7 JOURS','7 JOURS'),
		('8 JOURS','8 JOURS'),
		('9 JOURS','9 JOURS'),
		('10 JOURS','10 JOURS'),
		('11 JOURS','11 JOURS'),
		('14 JOURS','14 JOURS'),
		('A CONFIRMER','A CONFIRMER'),
        ('3 A 4 JOURS','3 A 4 JOURS'),
        ('2 A 3 JOURS','2 A 3 JOURS'),
        ('5 A 6 JOURS','5 A 6 JOURS'),
        ('4 A 5 JOURS','4 A 5 JOURS'),
        ('3 A 5 JOURS','3 A 5 JOURS'),
        ('6 A 8 JOURS','6 A 8 JOURS'),
        ('1 A 2 JOURS','1 A 2 JOURS'),
        ('1 A 3 JOURS','1 A 3 JOURS'),
        ('2 A 4 JOURS','2 A 4 JOURS'),
        ('4 JOURS','4 JOURS'),
        ('2 JOURS','2 JOURS'),
        ('6 à 8 JOURS','6 à 8 JOURS'),
        ('3 à 4 JOURS','3 à 4 JOURS'),
        ('1 à 2 JOURS','1 à 2 JOURS'),
        ('3 JOURS','3 JOURS'),
        ('2 à 3 JOURS','2 à 3 JOURS'),
        ('5 JOURS','5 JOURS'),
        ('6 JOURS','6 JOURS'),
        ('A CONFIRMER','A CONFIRMER'),
        ('4 à 5 JOURS','4 à 5 JOURS'),
        ('1 à 3 JOURS','1 à 3 JOURS'),
        ('2 à 4 JOURS','2 à 4 JOURS'),
        ('8 JOURS','8 JOURS'),
        ('2à3 JOURS','2à3 JOURS'),
        ('4à5 JOURS','4à5 JOURS'),
        ('3à4 JOURS','3à4 JOURS'),
        ('7 JOURS','7 JOURS'),
        ('14 JOURS ','14 JOURS '),
        ('3 A 4 JOURS ','3 A 4 JOURS '),
        ('1 JOURS','1 JOURS'),


	)
PRODUIT_EXONERES=(
		('OUI','OUI'),
		('NON','NON'),

	)
TYPE_ENTREPOSAGE=(

		('ENTREPOSAGE SIMPLE','ENTREPOSAGE SIMPLE'),
		('GESTION ENTREPOSAGE','GESTION ENTREPOSAGE'),




)
PAYS_DESTINATION=(
		('ACORES','ACORES'),
		('AFGHANISTAN','AFGHANISTAN'),
		('AFRIQUE DU SUD','AFRIQUE DU SUD'),
		('ALBANIE','ALBANIE'),
		('ALLEMAGNE','ALLEMAGNE'),
		('ALGERIE','ALGERIE'),
		('BARBADES','BARBADES'),
		('ANDORRE','ANDORRE'),
		('ANGLETERRE','ANGLETERRE'),
		('ANGOLA','ANGOLA'),
		('ANTIGUA','ANTIGUA'),
		('ANGUILLA','ANGUILLA'),
		('ANTIGUA-ET-BARBUDA','ANTIGUA-ET-BARBUDA'),
		('ANTILLES NEERLANDAISES','ANTILLES NEERLANDAISES'),
		('ARABIE SAOUDITE','ARABIE SAOUDITE'),
		('ARGENTINE','ARGENTINE'),
		('ARMENIE','ARMENIE'),
		('ARUBA','ARUBA'),
		('AUSTRALIE','AUSTRALIE'),
		('AUTRICHE','AUTRICHE'),
		('AZERBAIDJAN','AZERBAIDJAN'),
		('BAHAMAS','BAHAMAS'),
		('BAHREIN','BAHREIN'),
		('BANGLADESH','BANGLADESH'),
		('BARBADE','BARBADE'),
		('BARBUDA(ANTIGUA)','BARBUDA(ANTIGUA)'),
		('BIELORUSSIE','BIELORUSSIE'),
		('BELGIQUE','BELGIQUE'),
		('BELGIQUE ','BELGIQUE '),
		('BELIZE','BELIZE'),
		('BENIN','BENIN'),
		('CAIMAN ILES','CAIMAN ILES'),
		('BERMUDES','BERMUDES'),
		('BHOUTAN','BHOUTAN'),
		('BOLIVIE','BOLIVIE'),
		('BONAIRE','BONAIRE'),
		('BOSNIE-HERZEGOVINE','BOSNIE-HERZEGOVINE'),
		('BOSNIE','BOSNIE'),
		('BOTSWANA','BOTSWANA'),
		('BRESIL','BRESIL'),
		('BRUNEI','BRUNEI'),
		('BULGARIE','BULGARIE'),
		('BURKINA FASO','BURKINA FASO'),
		('BURUNDI','BURUNDI'),
		('CAÏMANS(ILES)','CAÏMANS(ILES)'),
		('CAMBODGE','CAMBODGE'),
		('CAMEROUN','CAMEROUN'),
		('CANADA','CANADA'),
		('CANARIES(ILES)','CANARIES(ILES)'),
		('CAP VERT','CAP VERT'),
		('CENTRAFRIQUE','CENTRAFRIQUE'),
		('CEUTA','CEUTA'),
		('CHANNELLE(ILES) - GUERNSEY','CHANNELLE(ILES) - GUERNSEY'),
		('CHANNELLE(ILES) - JERSEY','CHANNELLE(ILES) - JERSEY'),
		('CHILI','CHILI'),
		('LYBIE','LYBIE'),
		('MADEIRE','MADEIRE'),
		('MALDIVES','MALDIVES'),
		('MALI','MALI'),
		('NAURU','NAURU'),
		('MONTSERRAT','MONTSERRAT'),
		('MYANMAR','MYANMAR'),
		('MEXIQUE','MEXIQUE'),
		('KYRGYZSTAN','KYRGYZSTAN'),
		('JERSEY','JERSEY'),
		('CHINE','CHINE'),
		('CHYPRE','CHYPRE'),
		('CUBA','CUBA'),
		('EGYPTE','EGYPTE'),
		('ERYTRHEE','ERYTRHEE'),
		('ESPAGNE ','ESPAGNE '),
		('EMIRATS ARABE UNIS','EMIRATS ARABE UNIS'),
		('EL SALVADOR','EL SALVADOR'),
		('COREE DU SUD','COREE DU SUD'),
		('COREE DU NORD','COREE DU NORD'),
		('COOK ILES','COOK ILES'),
		('COLOMBIE','COLOMBIE'),
		('COMORES','COMORES'),
		('CONGO(BRAZZAVILLE)','CONGO(BRAZZAVILLE)'),
		('CONGO','CONGO'),
		('COOK(ILES)','COOK(ILES)'),
		('CORÉE DU SUD','CORÉE DU SUD'),
		('COSTA RICA','COSTA RICA'),
		('COTE D IVOIRE','COTE D IVOIRE'),
		('CROATIE','CROATIE'),
		('CURACAO','CURACAO'),
		('DANEMARK','DANEMARK'),
		('DJIBOUTI','DJIBOUTI'),
		('DOMINIQUE','DOMINIQUE'),
		('ECOSSE','ECOSSE'),
		('EMIRATS ARABES UNIS','EMIRATS ARABES UNIS'),
		('EQUATEUR','EQUATEUR'),
		('ERITHRÉE','ERITHRÉE'),
		('ESPAGNE','ESPAGNE'),
		('ESTONIE','ESTONIE'),
		('FRANCE ','FRANCE '),
		('FALKSLANDS','FALKSLANDS'),
		('ETATS-UNIS','ETATS-UNIS'),
		('ETATS UNIS','ETATS UNIS'),
		('ETHIOPIE','ETHIOPIE'),
		('FÉROÉ(ILES)','FÉROÉ(ILES)'),
		('FIDJI','FIDJI'),
		('FINLANDE','FINLANDE'),
		('FRANCE','FRANCE'),
		('GABON','GABON'),
		('GAMBIE','GAMBIE'),
		('GAZA (WEST BANK)','GAZA (WEST BANK)'),
		('GÉORGIE','GÉORGIE'),
		('GHANA','GHANA'),
		('GIBRALTAR','GIBRALTAR'),
		('GRECE','GRECE'),
		('GROENLAND','GROENLAND'),
		('GRENADE','GRENADE'),
		('GUADELOUPE','GUADELOUPE'),
		('GUAM (ILE)','GUAM (ILE)'),
		('GUATEMALA','GUATEMALA'),
		('GUAM','GUAM'),
		('GUERNESEY','GUERNESEY'),
		('GUIANA','GUIANA'),
		('GUINÉE','GUINÉE'),
		('GUINEE','GUINEE'),
		('GUINÉE BISSAU','GUINÉE BISSAU'),
		('GUINEE BISSAU','GUINEE BISSAU'),
		('GUINÉE EQUATORIALE','GUINÉE EQUATORIALE'),
		('GUINEE EQUATORIALE','GUINEE EQUATORIALE'),
		('GUYANE','GUYANE'),
		('GUINEE FRANCAISE','GUINEE FRANCAISE'),
		('GUYANE FRANÇAISE','GUYANE FRANÇAISE'),
		('HAITI','HAITI'),
		('HAWAI','HAWAI'),
		('HONDURAS','HONDURAS'),
		('HONG KONG','HONG KONG'),
		('HONGRIE','HONGRIE'),
		('ILLE MAURICE','ILLE MAURICE'),
		('ILES VIERGES-USA','ILES VIERGES-USA'),
		('ILES VIERGES-GB','ILES VIERGES-GB'),
		('ILE DE MAN','ILE DE MAN'),
		('ILES CANARIES','ILES CANARIES'),
		('ILES FEROE','ILES FEROE'),
		('ILES MARSHALL','ILES MARSHALL'),
		('ILE MAURICE','ILE MAURICE'),
		('ILES TURQUES ET CAICOS','ILES TURQUES ET CAICOS'),
		('ILES VIERGES - USA','ILES VIERGES - USA'),
		('ILES VIERGES - GB','ILES VIERGES - GB'),
		('INDE','INDE'),
		('INDONESIE','INDONESIE'),
		('IRAK','IRAK'),
		('IRAN','IRAN'),
		('ITALIE ','ITALIE '),
		('IRLANDE','IRLANDE'),
		('IRLANDE ','IRLANDE '),
		('IRLANDE DU NORD','IRLANDE DU NORD'),
		('ISLANDE','ISLANDE'),
		('ISRAEL','ISRAEL'),
		('ITALIE','ITALIE'),
		('JAMAIQUE','JAMAIQUE'),
		('JAPON','JAPON'),
		('JORDANIE','JORDANIE'),
		('KAZAKHSTAN','KAZAKHSTAN'),
		('KENYA','KENYA'),
		('KIRIBATI','KIRIBATI'),
		('KOSOVO','KOSOVO'),
		('KOSRAE(MICRONÉSIE)','KOSRAE(MICRONÉSIE)'),
		('KOWEIT','KOWEIT'),
		('KIRGHIZISTAN','KIRGHIZISTAN'),
		('LAOS','LAOS'),
		('LETTONIE','LETTONIE'),
		('LESOTHO','LESOTHO'),
		('LIBAN','LIBAN'),
		('LIBERIA','LIBERIA'),
		('LIBYE','LIBYE'),
		('LIECHTENSTEIN','LIECHTENSTEIN'),
		('LITUANIE','LITUANIE'),
		('LUXEMBOURG','LUXEMBOURG'),
		('MACAO','MACAO'),
		('MACEDOINE','MACEDOINE'),
		('MADAGASCAR','MADAGASCAR'),
		('MADERE','MADERE'),
		('MALAWI','MALAWI'),
		('MALAISIE','MALAISIE'),
		('MALTE','MALTE'),
		('MARIANNE DU NORD(ILES)','MARIANNE DU NORD(ILES)'),
		('MAROC','MAROC'),
		('MARTINIQUE','MARTINIQUE'),
		('MAURITANIE','MAURITANIE'),
		('MAYOTTE','MAYOTTE'),
		('MELILLA','MELILLA'),
		('MICRONESIE','MICRONESIE'),
		('MOLDAVIE','MOLDAVIE'),
		('MONACO','MONACO'),
		('MONGOLIE','MONGOLIE'),
		('MONTENEGRO','MONTENEGRO'),
		('MONSERRAT','MONSERRAT'),
		('MOZAMBIQUE','MOZAMBIQUE'),
		('NAMIBIE','NAMIBIE'),
		('NEPAL','NEPAL'),
		('NEVIS(ST KITTS)','NEVIS(ST KITTS)'),
		('NEVIS','NEVIS'),
		('NIUE ILE','NIUE ILE'),
		('NICARAGUA','NICARAGUA'),
		('NIGER','NIGER'),
		('NIGERIA','NIGERIA'),
		('NOUVELLE CALÉDONIE','NOUVELLE CALÉDONIE'),
		('NOUVELLE ZELANDE','NOUVELLE ZELANDE'),
		('NORVEGE','NORVEGE'),
		('OMAN','OMAN'),
		('OUGANDA','OUGANDA'),
		('OUZBEKISTAN','OUZBEKISTAN'),
		('PAKISTAN','PAKISTAN'),
		('PALAOS','PALAOS'),
		('PANAMA','PANAMA'),
		('PAPOUASIE NOUVELLE GUINÉE','PAPOUASIE NOUVELLE GUINÉE'),
		('PARAGUAY','PARAGUAY'),
		('PAYS DE GALLES','PAYS DE GALLES'),
		('PEROU','PEROU'),
		('PHILIPPINES','PHILIPPINES'),
		('POLOGNE','POLOGNE'),
		('PONAPE','PONAPE'),
		('PORTUGAL','PORTUGAL'),
		('PORTO RICO','PORTO RICO'),
		('POLYNÉSIE FRANÇAISE','POLYNÉSIE FRANÇAISE'),
		('QATAR','QATAR'),
		('RÉPUBLIQUE DOMINICAINE','RÉPUBLIQUE DOMINICAINE'),
		('RÉPUBLIQUE TCHÈQUE','RÉPUBLIQUE TCHÈQUE'),
		('RÉUNION','RÉUNION'),
		('ROTA','ROTA'),
		('ROUMANIE','ROUMANIE'),
		('RUSSIE','RUSSIE'),
		('RWANDA','RWANDA'),
		('SABA','SABA'),
		('SAIPAN','SAIPAN'),
		('SAMOA ILES','SAMOA ILES'),
		('SAMOA - USA','SAMOA - USA'),
		('SAINT MARIN','SAINT MARIN'),
		('SENEGAL','SENEGAL'),
		('SERBIE','SERBIE'),
		('SEYCHELLES','SEYCHELLES'),
		('SIERRA LEONE','SIERRA LEONE'),
		('SINGAPOUR','SINGAPOUR'),
		('SLOVAQUIE','SLOVAQUIE'),
		('SLOVENIE','SLOVENIE'),
		('SRI LANKA','SRI LANKA'),
		('SAINT BARTH','SAINT BARTH'),
		('SAINT CHRISTOPHE(ST. KITTS)','SAINT CHRISTOPHE(ST. KITTS)'),
		('SAINT JEAN','SAINT JEAN'),
		('SAINT MAARTEN','SAINT MAARTEN'),
		('SAINT MARTIN','SAINT MARTIN'),
		('SAINT THOMAS','SAINT THOMAS'),
		('SAINT VINCENT ET LES GRENADES','SAINT VINCENT ET LES GRENADES'),
		('SURINAME','SURINAME'),
		('SAINTE LUCIE','SAINTE LUCIE'),
		('SAINT KITTS','SAINT KITTS'),
		('SUEDE','SUEDE'),
		('SUISSE','SUISSE'),
		('SWAZILAND','SWAZILAND'),
		('SYRIE','SYRIE'),
		('TAHITI','TAHITI'),
		('TAIWAN','TAIWAN'),
		('TADJIKISTAN','TADJIKISTAN'),
		('TANZANIE','TANZANIE'),
		('TCHAD','TCHAD'),
		('THAILANDE','THAILANDE'),
		('TIMOR ORIENTAL','TIMOR ORIENTAL'),
		('TINIAN','TINIAN'),
		('TOGO','TOGO'),
		('TONGA','TONGA'),
		('TORTOLA','TORTOLA'),
		('TRINITÉ ET TOBAGO','TRINITÉ ET TOBAGO'),
		('TRUK','TRUK'),
		('TUNISIE','TUNISIE'),
		('TURQUIE','TURQUIE'),
		('TURKMENISTAN','TURKMENISTAN'),
		('TUVALU','TUVALU'),
		('UKRAINE','UKRAINE'),
		('UNION(ILE)','UNION(ILE)'),
		('URUGUAY','URUGUAY'),
		('VANUATU','VANUATU'),
		('VENEZUELA','VENEZUELA'),
		('VIETNAM','VIETNAM'),
		('VIERGE GORDA(ILES VIERGES BRITANNIQUES)','VIERGE GORDA(ILES VIERGES BRITANNIQUES)'),
		('WALLIS ET FUTUNA','WALLIS ET FUTUNA'),
		('YAP','YAP'),
		('YEMEN','YEMEN'),
		('ZAMBIE','ZAMBIE'),
		('ZIMBABWE','ZIMBABWE'),
		('CHANNELLE(ILES)  à  GUERNSEY','CHANNELLE(ILES)  à  GUERNSEY'),
        ('CHANNELLE(ILES)  à  JERSEY','CHANNELLE(ILES)  à  JERSEY'),
        ('CHYPRE ','CHYPRE '),
        ('PAYS-BAS','PAYS-BAS'),
	    ('SAMOA  à  USA','SAMOA  à  USA'),
        ('ILES VIERGES-USA','ILES VIERGES-USA'),
        ('ILES VIERGES-GB','ILES VIERGES-GB'),
        ('VATICAN CITE','VATICAN CITE'),
        ('ROYAUME-UNI','ROYAUME-UNI'),
        ('REUNION','REUNION'),
        ('PAPOUASIE','PAPOUASIE'),
        ('GEORGIE','GEORGIE'),
        ('THAILAND','THAILAND'),
        ('SAN MARIN','SAN MARIN'),
        ('SAINT BARTHELEMY','SAINT BARTHELEMY'),
        ('POLYNESIE','POLYNESIE'),
        ('NOUVELLE CALEDONIE','NOUVELLE CALEDONIE'),
        ('TRINITE ET TOBAGO','TRINITE ET TOBAGO'),
        ('SURINAM','SURINAM'),
        ('SAINT VINCENT','SAINT VINCENT'),
        ('SAINT PIERRE','SAINT PIERRE'),
        ('REPUBLIQUE DIMINICAINE','REPUBLIQUE DIMINICAINE'),
        ('QUATAR','QUATAR'),
        ('PORTORICO','PORTORICO'),
        ('ILES VIERGES  à  GB','ILES VIERGES  à  GB'),
        ('ILES VIERGES  à  USA','ILES VIERGES  à  USA'),
        ('BOSNIE à HERZEGOVINE','BOSNIE à HERZEGOVINE'),



	)
TYPE_ENVOIE=(
		('COLIS','COLIS'),
		('COURRIER','COURRIER'),


	)